packages/s2-core/src/cell/data-cell.ts

✨ Feature
🎨 Enhance
🐛 Bug fix
🔧 Chore
|----|----|
|  ❌  |  ✅  |

fix(data-cell): cycle dependence bugs

---

packages/s2-core/src/cell/base-cell.ts

✨ Feature
🎨 Enhance
🐛 Bug fix
🔧 Chore
add pointer cursor for linked text, close #266 
|----|----|
|  ❌  |  ✅  |

feat: add pointer cursor for link field text

---

packages/s2-core/src/cell/header-cell.ts
packages/s2-core/src/components/sheets/base-sheet/index.tsx
packages/s2-core/src/facet/header/corner.ts
packages/s2-core/src/facet/pivot-facet.ts
packages/s2-core/src/facet/table-facet.ts
packages/s2-core/src/interaction/root.ts
packages/s2-core/src/utils/interaction/multi-click.ts

✨ Feature
🎨 Enhance
🐛 Bug fix
🔧 Chore
fix circular deps.
|----|----|
|  ❌  |  ✅  |

fix: replace circular deps

---

.github/workflows/ci.yml
README.en-US.md
README.md

✨ Feature
🎨 Enhance
🐛 Bug fix
🔧 Chore
|----|----|
|  ❌  |  ✅  |

docs: update badge

---

packages/s2-core/src/facet/base-facet.ts
packages/s2-core/src/facet/layout/interface.ts
packages/s2-core/src/facet/pivot-facet.ts
packages/s2-core/src/facet/table-facet.ts

🐛 Bug fix
修复明细表分页失效的问题。并把 getCellHeight 方法改名为 getCellOffsetY，更符合函数的作用，避免歧义。

fix: table mode pagination issue

---

packages/s2-core/src/data-set/table-data-set.ts

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore
fix table-dataset-spec test
|----|----|
|  ❌  |  ✅  |

fix: table dataset spec

---

.github/workflows/emoji-helper.yml
.github/workflows/issue-labeled.yml
.github/workflows/pr-auto-assign-reviewer.yml

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore
- 新增 emoji helper
- 优化其他 Action 显示
混PR ~
|----|----|
|  ❌  |  ✅  |

ci: create emoji-helper 

---

packages/s2-core/package.json

fix(build): update d.ts path

---

packages/s2-core/__tests__/spreadsheet/spread-sheet-spec.tsx
packages/s2-core/src/cell/corner-cell.ts
packages/s2-core/src/common/icons/gui-icon.ts
packages/s2-core/src/facet/header/corner.ts
packages/s2-core/src/theme/index.ts

✨ Feature
🐛 Bugfix
|----|----|
| ![image](https://user-images.githubusercontent.com/10885578/134140484-f0bc4016-4e48-4452-9abf-d7b9643be32b.png) |  ![image](https://user-images.githubusercontent.com/10885578/134139974-882b4e9e-fd5d-42fc-9c35-d93fdcfd2f5b.png)|
|![image](https://user-images.githubusercontent.com/10885578/134140455-4d97febb-5e63-4cbc-a2cb-08af61a8a48d.png)| ![image](https://user-images.githubusercontent.com/10885578/134140184-4275e3b4-b705-4304-aa6c-77d16be2598f.png)|
|![image](https://user-images.githubusercontent.com/10885578/134176745-67321a71-8c61-4e85-a25d-ed30f67c64ec.png)|![image](https://user-images.githubusercontent.com/10885578/134176708-7eb386ed-5510-4248-bba8-6bb4ad391ad4.png)|
| ![image](https://user-images.githubusercontent.com/10885578/1 …

feat: :sparkles: add column header labels for the corner header

---

packages/s2-core/src/facet/table-facet.ts

fix(table): revert table fact clip code

---

packages/s2-core/__tests__/spreadsheet/table-sheet-spec.tsx
packages/s2-core/src/cell/header-cell.ts
packages/s2-core/src/interaction/base-interaction/click/data-cell-click.ts
packages/s2-core/src/interaction/base-interaction/click/row-column-click.ts
packages/s2-core/src/interaction/base-interaction/hover.ts
packages/s2-core/src/ui/tooltip/components/operator/index.less
packages/s2-core/src/ui/tooltip/components/operator/index.tsx
packages/s2-core/src/utils/tooltip.ts

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore
|----|----|
|  ❌  |  ✅  |

fix: row-col-click's show about pivot and table, formatter when showSingleTips

---

packages/s2-core/__tests__/spreadsheet/table-sheet-spec.tsx
packages/s2-core/src/common/constant/events/basic.ts
packages/s2-core/src/common/constant/events/origin.ts
packages/s2-core/src/common/interface/emitter.ts
packages/s2-core/src/components/sheets/base-sheet/index.tsx
packages/s2-core/src/components/sheets/interface.ts
packages/s2-core/src/components/sheets/table-sheet/index.tsx
packages/s2-core/src/components/sheets/tabular-sheet/index.tsx
packages/s2-core/src/interaction/event-controller.ts

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore
add Event:
1. doubleClick
2. contextMenu
|----|----|
|  ❌  |  ✅  |

Feat: add Event doubleClick and contextMenu

---

packages/s2-core/__tests__/unit/utils/hide-columns.spec.ts
packages/s2-core/src/cell/table-col-cell.ts
packages/s2-core/src/utils/hide-columns.ts

test(interaction): add hidden columns tests

---

.husky/prepare-commit-msg
packages/s2-core/__tests__/spreadsheet/data-accuracy-one-measure-spec.tsx
packages/s2-core/__tests__/spreadsheet/data-accuracy-two-measures-spec.tsx
packages/s2-core/__tests__/spreadsheet/sort-sheet-spec.tsx
packages/s2-core/__tests__/unit/data-process/pivot-spec.tsx
packages/s2-core/__tests__/unit/data-process/table-spec.tsx
packages/s2-core/src/cell/data-cell.ts
packages/s2-core/src/cell/row-cell.ts
packages/s2-core/src/common/interface/basic.ts
packages/s2-core/src/components/dimension-switch/index.less
packages/s2-core/src/components/dimension-switch/index.tsx
packages/s2-core/src/components/drill-down/index.less
packages/s2-core/src/components/drill-down/index.tsx
packages/s2-core/src/components/icons/index.less
packages/s2-core/src/facet/header/corner.ts
packages/s2-core/src/utils/interaction/select-event.ts
s2-site/gatsby-browser.js

🐛 Bugfix
🎨 Enhance
* Add the `spreadsheet` for the meta of the corner cell in tree mode.
* Tweak the position of the row cell border.
|----|----|
|  ❌ ![](https://gw.alipayobjects.com/zos/antfincdn/2DCfC4Ka1I/3827f97d-b3e4-43dd-bc27-7229d9bc8df9.png) |  ✅ ![](https://gw.alipayobjects.com/zos/antfincdn/3taRbwDjUY/5663a179-bbfa-43ce-a9dd-58ff342f5923.png) |

fix: 🐛 add the `spreadsheet` for the meta of the corner cell in tree mode and tweak the style of cell borders 

---

.github/workflows/preview-build.yml
.github/workflows/preview-deploy.yml
package.json

chore: :wrench: fix the site preview

---

packages/s2-core/__tests__/spreadsheet/spread-sheet-spec.tsx
packages/s2-core/__tests__/util/sheet-entry.tsx
packages/s2-core/src/cell/header-cell.ts

feat: :sparkles: allow users to set different display condition for headerActionIcons

---

packages/s2-core/__tests__/spreadsheet/spread-sheet-spec.tsx
packages/s2-core/src/interaction/base-interaction/click/row-column-click.ts
packages/s2-core/src/interaction/event-controller.ts
packages/s2-core/src/ui/tooltip/index.tsx

修复自定义 tooltip 的场景下, 需要点击两次列头才会显示自定义tooltip, 并且鼠标移动后 tooltip 会消失的问题
|----|----|
|  ❌  |  ✅  |
#340

fix(tooltip): fix cannot render tooltip element when first show

---

.github/workflows/site-deploy.yml
s2-site/docs/manual/interaction/custom.zh.md
s2-site/docs/manual/interaction/hide-columns.zh.md
s2-site/docs/manual/interaction/link-jump.zh.md
s2-site/examples/interaction/demo/basic.ts
s2-site/examples/interaction/demo/custom.ts
s2-site/examples/interaction/demo/hide-columns.ts
s2-site/examples/interaction/demo/meta.json
s2-site/examples/interaction/demo/pivot-link-jump.ts

🔧 Chore
1. 文档里面嵌入一些 example
2. 新增手动隐藏列 example
3. 增加自动部署文档 CI

docs(interaction): add hide column example

---

packages/s2-core/__tests__/spreadsheet/spread-sheet-spec.tsx
packages/s2-core/src/common/interface/s2Options.ts
packages/s2-core/src/interaction/event-controller.ts
packages/s2-core/src/sheet-type/spread-sheet.ts
s2-site/docs/api/general/options.zh.md

🐛 Bugfix
1. 修复 showTooltip 配置 无效的问题
2. 修复 点击 tooltip 会隐藏的问题
close #363

fix(tooltip): tooltip will hide if clicked

---

packages/s2-core/__tests__/spreadsheet/sort-sheet-spec.tsx
packages/s2-core/src/utils/index.ts

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore
|----|----|
|  ❌  |  ✅  |

chore: 🎡 export g-render methods for cell customization

---

.github/workflows/lint.yml
.github/workflows/test.yml

🔧 Chore
修复通过 fork 仓库的方式 提交 pr 不会触发 action 的问题

chore(ci): fix cannot trigger action

---

README.en-US.md
README.md

添加 issues-helper 徽章 ~
<a href="https://github.com/actions-cool/issues-helper" target="_blank">
</a>

docs: add issues-helper badge

---

.markdownlint.json
s2-site/docs/api/basic-class/interaction.zh.md
s2-site/docs/api/basic-class/spreadsheet.zh.md
s2-site/docs/api/components/drill-down.zh.md
s2-site/docs/api/components/switcher.zh.md
s2-site/docs/api/general/S2DataConfig.zh.md
s2-site/docs/api/general/S2Options.zh.md
s2-site/docs/api/general/S2Theme.zh.md
s2-site/docs/api/graphic.en.md
s2-site/docs/api/graphic.zh.md
s2-site/docs/common/conditions.zh.md
s2-site/docs/common/tooltip.zh.md
s2-site/docs/common/totals.zh.md
s2-site/docs/common/view-meta.zh.md

docs: add graphic style docs

---

packages/s2-core/src/utils/export/index.ts

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore
修复导出功能，兼容新数据流。
|----|----|
|  ❌  |  ✅  |

fix(export): export feature

---

packages/s2-core/__tests__/spreadsheet/hidden-columns-spec.tsx
packages/s2-core/__tests__/spreadsheet/table-sheet-spec.tsx
packages/s2-core/__tests__/unit/utils/hide-columns.spec.ts
packages/s2-core/src/common/constant/events/basic.ts
packages/s2-core/src/common/interface/emitter.ts
packages/s2-core/src/sheet-type/spread-sheet.ts
packages/s2-core/src/utils/hide-columns.ts
s2-site/docs/manual/advanced/interaction/basic.zh.md
s2-site/docs/manual/advanced/interaction/hide-columns.zh.md
s2-site/examples/interaction/demo/custom.ts
s2-site/examples/interaction/demo/hide-columns.ts

🐛 Bugfix
🔧 Chore
1. 修复 core 层 配置了 hiddenColumnFields, 初始化未隐藏, 并且手动点击隐藏无效
2. S2Event.LAYOUT_TABLE_COL_HIDE => S2Event.LAYOUT_TABLE_COL_HIDDEN
3. 增加测试
|----|----|
|  ![image](https://user-images.githubusercontent.com/21015895/136784953-98264896-05a9-4b70-a266-3fe1e659ef79.png) |  ![image](https://user-images.githubusercontent.com/21015895/136785208-088756b7-89c7-45b7-a2be-aafcd5a524b9.png) |
close #417

fix(interaction): invalid "hiddenColumnFields" config close #417

---

packages/s2-core/__tests__/spreadsheet/spread-sheet-spec.tsx
packages/s2-core/src/components/drill-down/index.tsx
packages/s2-core/src/components/export/index.tsx
packages/s2-core/src/components/pagination/index.tsx
packages/s2-core/src/components/sheets/base-sheet/index.tsx
packages/s2-core/src/components/sheets/hooks.ts
packages/s2-core/src/components/sheets/interface.ts
packages/s2-core/src/components/sheets/table-sheet/index.tsx

🎨 Enhance
- Refactor the logic of the pagination component.

refactor: ♻️optimize the logic of the pagination component close #382

---

packages/s2-core/rollup.config.js
packages/s2-core/src/facet/pivot-facet.ts

fix: :bug: correct the condition of the function adustTotalNodesCoordinate and close #448

---

packages/s2-core/src/utils/cell/data-cell.ts

🔧 Chore
- Remove redundant characters for the  for the id of dataCell.

chore: :pencil2: fix typos for the id of dataCell

---

packages/s2-core/__tests__/bugs/issue-446-spec.tsx
packages/s2-core/__tests__/data/data-issue-446.json
packages/s2-core/src/utils/export/index.ts

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore
修复table mode下的copyData函数报错

fix(export): 🐛  solve the  table sheet export problem and close #446

---

.github/PULL_REQUEST_TEMPLATE.md
packages/s2-core/package.json

 chore: update the PULL_REQUEST_TEMPLATE

---

packages/s2-core/src/utils/index.ts
packages/s2-core/src/utils/layout/index.ts

🎨 Enhance
新增 export generateId

feat(util): add generateId export function

---

packages/s2-core/src/data-set/table-data-set.ts
packages/s2-core/src/facet/table-facet.ts

🐛 Bugfix
tableFacet销毁时没有注销filter的事件

fix: 🐛 event disposal on facet destroy

---

packages/s2-core/src/components/pagination/index.tsx

fix: :bug: set the default page and close #473

---

packages/s2-core/__tests__/bugs/issue-446-spec.tsx
packages/s2-core/__tests__/bugs/issue-565-spec.tsx
packages/s2-core/src/utils/export/export-worker.ts

* Refactor the function of getCsvString and remove unused spaces.

fix: :bug: refactor the csvString

---

packages/s2-core/package.json

chore(release): 🔖 publish the version 1.0.0-beta.5

---

packages/s2-core/package.json

chore(release): 1.0.0-beta.6

---

s2-site/examples/custom/header-action-icon/demo/basic.ts
s2-site/examples/custom/layout-arrange/demo/basic.ts
s2-site/examples/custom/layout-coordinate/demo/basic.ts
s2-site/examples/custom/layout-data-position/demo/basic.ts
s2-site/examples/custom/layout-hierarchy/demo/basic.ts

docs(demo): remove ts interface in custom demo

---

s2-site/docs/api/components/sheet-component.zh.md
s2-site/docs/manual/advanced/get-instance.en.md
s2-site/docs/manual/advanced/get-instance.zh.md

docs: add get sheet instance doc

---

packages/s2-core/__tests__/bugs/issue-368-spec.tsx
packages/s2-core/__tests__/bugs/issue-372-spec.tsx
packages/s2-core/__tests__/unit/interaction/row-column-resize-spec.ts
packages/s2-core/src/cell/data-cell.ts
packages/s2-core/src/common/constant/options.ts
packages/s2-core/src/theme/index.ts

🎨 Enhance
* Tweak the default height of column cells.
* Add the border highlight for the hover state.

style: 💄 tweak the default height of column cells and add the border highlight for the hover state

---

packages/s2-core/src/common/constant/scroll.ts
packages/s2-core/src/facet/base-facet.ts
packages/s2-core/src/theme/index.ts
packages/s2-core/src/ui/scrollbar/index.ts

🎨 Enhance
|![image](https://user-images.githubusercontent.com/10885578/140597916-b5e031a3-7a5d-4b03-88cc-241b90b99a82.png)|   ![3](https://user-images.githubusercontent.com/10885578/140597895-13c89873-2847-4d00-ad21-de3c6498af92.gif)|

style: :lipstick: optimize the style of scrollBar

---

packages/s2-core/__tests__/spreadsheet/condition-usage-spec.tsx
s2-site/docs/manual/basic/conditions.zh.md
s2-site/examples/analysis/conditions/demo/background.ts
s2-site/examples/analysis/conditions/demo/meta.json
s2-site/examples/analysis/conditions/demo/multi-conditions.ts

docs: :memo: add the multi-condition demo 

---

packages/s2-core/__tests__/unit/interaction/base-interaction/hover-spec.ts
packages/s2-core/src/cell/base-cell.ts
packages/s2-core/src/cell/corner-cell.ts
packages/s2-core/src/interaction/base-interaction/hover.ts

feat: :art: only show the header cell tooltip when the text is omitted

---

.github/PULL_REQUEST_TEMPLATE.md
packages/s2-core/src/utils/export/index.ts

refactor: :fire: remove the derivedValues in the  export process

---

packages/s2-core/package.json

chore(release): 1.0.0-beta.7

---

packages/s2-core/package.json

Revert "chore(release): 1.0.0-beta.7"

---

s2-site/gatsby-config.js

chore: :wrench: add the GATrackingId for the s2-site

---

packages/s2-core/__tests__/unit/facet/table-facet-spec.ts
packages/s2-core/src/facet/table-facet.ts

修复 frozenTrailingColCount > 1 时渲染不正确的问题。增加了这部分的测试。

fix(table): frozen trailing col render issue

---

packages/s2-core/__tests__/spreadsheet/link-fields-spec.tsx
packages/s2-core/__tests__/spreadsheet/table-sheet-spec.tsx
packages/s2-core/src/facet/base-facet.ts

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore

fix: fix linkField config path

---

packages/s2-core/src/cell/corner-cell.ts
packages/s2-core/src/cell/row-cell.ts
packages/s2-core/src/common/icons/svg/index.ts
packages/s2-core/src/common/icons/svg/svgs.ts

refactor: tweak alignment

---

packages/s2-core/src/common/icons/factory.ts
packages/s2-core/src/common/icons/gui-icon.ts
packages/s2-core/src/common/icons/index.ts
packages/s2-core/src/common/icons/svg/index.ts

✨ Feature
🐛 Bugfix
| ![image](https://user-images.githubusercontent.com/17964556/140893504-bfc8803d-28f5-4a22-be3d-849ea202450c.png)                          | ![image](https://user-images.githubusercontent.com/17964556/140892630-0d263889-0b66-4c58-b985-0cdeabb71f46.png)|

fix: fix internal svg icon disappear issue in official website

---

.github/workflows/auto-release.yml
.github/workflows/test.yml
s2-site/examples/analysis/conditions/demo/background.ts
s2-site/examples/analysis/conditions/demo/gradient-interval.ts
s2-site/examples/analysis/conditions/demo/icon.ts
s2-site/examples/analysis/conditions/demo/interval.ts
s2-site/examples/analysis/conditions/demo/multi-background.ts
s2-site/examples/analysis/conditions/demo/multi-conditions.ts
s2-site/examples/analysis/conditions/demo/table-text.ts
s2-site/examples/analysis/conditions/demo/text.ts
s2-site/examples/case/group-drill-down/demo/basic.tsx
s2-site/examples/case/kpi-strategy/API.en.md
s2-site/examples/case/kpi-strategy/API.zh.md
s2-site/examples/case/kpi-strategy/demo/basic.tsx
s2-site/examples/case/kpi-strategy/demo/meta.json
s2-site/examples/case/kpi-strategy/design.en.md
s2-site/examples/case/kpi-strategy/design.zh.md
s2-site/examples/case/kpi-strategy/index.en.md
s2-site/examples/case/kpi-strategy/index.zh.md
s2-site/examples/case/measure-comparison/demo/basic.tsx
s2-site/examples/case/performance-compare/demo/basic.tsx
s2-site/examples/case/performance-compare/index.en.md
s2-site/examples/case/performance-compare/index.zh.md
s2-site/examples/data/kpi-strategy.json
s2-site/package.json
s2-site/yarn.lock

🔧 Chore
1. 增加 KPI 趋势表 场景 demo
2. 修复 指标对比 demo 配置不生效
3. 修改 是否使用 prerelease 分支判断规则

docs(case): add kpi strategy sheet demo

---

packages/s2-core/src/theme/index.ts
s2-site/docs/api/general/S2Theme.zh.md

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore

docs: update resize area docs

---

packages/s2-core/src/cell/header-cell.ts

🐛 Bugfix
fix: pivot sheet sort icon's show

fix: pivot sheet sort icon's show

---

packages/s2-core/__tests__/spreadsheet/table-sheet-spec.tsx
packages/s2-core/src/cell/base-cell.ts
packages/s2-core/src/cell/corner-cell.ts
packages/s2-core/src/cell/table-col-cell.ts
packages/s2-core/src/common/interface/s2Options.ts
packages/s2-core/src/utils/text.ts
s2-site/docs/api/general/S2Options.zh.md

✨ Feature
🎨 Enhance
空数据时，可自定义空cell的填充内容，之前是'-'

feat(options): add empty cell placeholder options

---

packages/s2-core/package.json

chore(release): 🔖 publish the version 1.0.0-beta.8

---

.github/workflows/pr-labeled.yml
.github/workflows/test.yml

🔧 Chore
1. 修复 pr 添加 label 获取不到用户名的问题
2. 去除 test 通过 的 label (有点冗余了...)

chore(ci): fix cannot get user name

---

packages/s2-core/__tests__/unit/utils/export/copy-spec.ts
packages/s2-core/src/common/interface/s2Options.ts
packages/s2-core/src/utils/export/copy.ts
s2-site/docs/common/interaction.zh.md

🐛 Bugfix
1. 复制format过后的data
2. 处理最后的复制内容，去掉最后一行的\t\n

fix(copy): copy with format data

---

packages/s2-core/package.json

chore(release): 🔖 publish the version 1.0.0-beta.9

---

packages/s2-core/package.json

Revert "chore(release): 🔖 publish the version 1.0.0-beta.9"

---

packages/s2-core/src/facet/base-facet.ts
s2-site/examples/case/performance-compare/demo/pivot.tsx
s2-site/examples/case/performance-compare/demo/table.tsx

docs: :memo: update the performance demos

---

packages/s2-core/__tests__/unit/interaction/row-column-resize-spec.ts
packages/s2-core/src/theme/palette/default.ts

style: fix the color of the resize guideline

---

packages/s2-core/package.json

chore(release): 1.0.0-beta.9

---

s2-site/examples/case/group-drill-down/demo/meta.json
s2-site/package.json
s2-site/yarn.lock

chore: upgrage the s2 version for the site

---

.gitignore
packages/s2-core/__tests__/unit/interaction/data-cell-multi-selection-spec.ts
packages/s2-core/__tests__/unit/interaction/row-column-resize-spec.ts
packages/s2-core/src/interaction/data-cell-multi-selection.ts
s2-site/docs/manual/getting-started.zh.md

test(interaction): add data cell multi selection test

---

packages/s2-core/__tests__/util/sheet-entry.tsx
packages/s2-core/src/components/header/index.less
packages/s2-core/src/components/header/index.tsx
packages/s2-core/src/components/sheets/base-sheet/index.tsx

feat: :sparkles: make the head width change with the width of the sheet

---

packages/s2-core/__tests__/spreadsheet/table-sheet-spec.tsx
packages/s2-core/__tests__/unit/utils/export/copy-spec.ts
packages/s2-core/src/utils/export/copy.ts

🐛 Bugfix
修复当内容包含\n时，内容换行出错的问题
| ![image](https://user-images.githubusercontent.com/16497201/141731857-e3bd7fac-277f-415b-8109-fdbdd8946397.png)| ![image](https://user-images.githubusercontent.com/16497201/141731988-4967d131-5e23-45fd-b4fd-d9237482f506.png)|

fix(copy): fix copy data format problem

---

packages/s2-core/src/facet/base-facet.ts
packages/s2-core/src/ui/scrollbar/index.ts
packages/s2-core/src/ui/scrollbar/interface.ts

相关背景参考 https://github.com/antvis/S2/issues/590
修复滚动速率问题。滚动条的渲染按实际滚动的 offset 换算。页面滚动的速度只和用户滚动的事件的 offset 有关，和滚动条本身的长度无关。
Fix https://github.com/antvis/S2/issues/590 https://github.com/antvis/S2/issues/696

fix(facet): scrollbar offset

---

packages/s2-core/__tests__/unit/ui/hd-adapter/index-spec.ts
packages/s2-core/src/ui/hd-adapter/index.ts

test: fix hd tests

---

s2-site/docs/api/components/header.zh.md
s2-site/examples/react-component/header/demo/default.tsx
s2-site/site/pages/index.less
s2-site/site/pages/index.zh.tsx

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore
1. 官网首页UI调整
2. 官网header组件的UI调整
| ![image](https://user-images.githubusercontent.com/20497176/141883151-e64c9634-7d20-452e-bc39-c4f88be80449.png) | ![image](https://user-images.githubusercontent.com/20497176/141883200-5c86acc7-38b1-4b5c-93c2-d9a07dbbfbc2.png) |
|![image](https://user-images.githubusercontent.com/20497176/141883400-1b9e505b-ef64-46ee-a352-ec6e36a58e10.png) |![image](https://user-images.githubusercontent.com/20497176/141883476-e88421ba-3c87-4ad4-9694-0ae0b6349b92.png)|
|![image](https://user-images.githubusercontent.com/20497176/141883606-b1 …

docs: homepage and header UI

---

.github/workflows/codeql-analysis.yml
README.en-US.md
README.md

🔧 Chore
1. 去除 deps 和 devDeps 的 badge (服务挂了, 显示不出来)
2. 增加 gzip 和 discussions badge
3. 增加 Contributors
4. 增加 CodeQL

chore: add codeql and update README

---

packages/s2-core/__tests__/bugs/issue-565-spec.tsx
packages/s2-core/__tests__/spreadsheet/scroll-spec.tsx

test: add scroll group test

---

package.json
packages/s2-core/__tests__/bugs/issue-720-spec.tsx
packages/s2-core/__tests__/spreadsheet/scroll-spec.tsx
packages/s2-core/scripts/test-live.mjs

🔧 Chore
玄学时间, scroll 的测试 本地是通过的, CI 不稳定

test: fix scroll test case

---

.github/workflows/mirror.yml

chore: add the mirror.yml

---

packages/s2-core/package.json

chore(release): 1.0.0-beta.10

---

s2-site/examples/custom/custom-tree/demo/custom-tree.ts

🐛 Bugfix
🔧 Chore
替换demo中的工具方法
close #680

docs(custom-tree): use transformCustomTreeItems of antv/s2

---

packages/s2-core/__tests__/spreadsheet/table-sheet-spec.tsx
packages/s2-core/__tests__/unit/utils/text.spec.ts
packages/s2-core/src/utils/text.ts

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore

fix(placeholder): placeholder issue

---

packages/s2-core/package.json

chore(release): 1.0.0-beta.11

---

s2-site/examples/case/data-preview/demo/index.tsx

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore

feat: 🎸 demo添加筛选排序

---

packages/s2-core/__tests__/unit/utils/export/copy-spec.ts
packages/s2-core/src/interaction/event-controller.ts
packages/s2-core/src/utils/export/copy.ts

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore
没有选中的cell的时候 不执行复制功能

fix(copy): do not copy when no cell selected

---

.github/workflows/test.yml

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore

ci: perf text

---

package.json

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore
由于 现在存在 s2-core 和 s2-react, 且后者依赖前者
在打包时需要配置 --concurrency 1 保证打包顺序，后者能正常引用到前者的构建产物

chore: fix build deps

---

.github/workflows/lint.yml

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore

chore: test lint

---

.eslintrc
.github/workflows/auto-release.yml
.github/workflows/lint.yml
.github/workflows/test.yml
lerna.json
packages/s2-core/__tests__/unit/ui/hd-adapter-spec.ts
packages/s2-react/package.json
packages/s2-react/src/components/tooltip/components/divider.tsx
packages/s2-react/src/components/tooltip/components/head-info.tsx
packages/s2-react/src/components/tooltip/components/interpretation.tsx
packages/s2-react/src/components/tooltip/components/simple-tips.tsx
packages/s2-react/vite.config.ts
yarn.lock

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore
1. 修复本地 build 和 CI build 行为不一致
2. lerna 加上 s2-react 包声明
3. 去除 s2-react 下的 s2-core devDeps 声明 （统一走的 yarn workspace 软链接，不应该设置为 devDeps）
4. 修改 react 的 preDeps 为 16.x

chore: fix bundle faild

---

README.en-US.md
README.md
packages/s2-core/README.md
packages/s2-react/README.md

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore
1. 去掉 WIP 标识
2. 增加 packages 说明

docs: update packages

---

packages/s2-react/package.json
packages/s2-react/vite.config.ts

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore
将antd作为s2-react纯依赖，不再打包到构建文件中

chore: external antd

---

s2-site/yarn.lock

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore

docs: update site lock

---

README.md

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore

chore: add the contact info and update the README

---

.github/workflows/auto-release.yml
.github/workflows/lint.yml
.releaserc.js
README.en-US.md
README.md
package.json
packages/s2-core/README.md
packages/s2-react/README.md

🔧 Chore
1. 支持正式版的自动发布
2. prepare 增加 自动 build core 层 esm, 解决 s2-react 找不到 s2 类型的问题

chore: support auto release latest

---

packages/s2-core/__tests__/spreadsheet/table-sheet-spec.tsx
packages/s2-core/__tests__/unit/utils/export/copy-spec.ts
packages/s2-core/src/utils/export/copy.ts

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore
原来行选择复制的时候使用的是原数据，改成dispalyData
修复sort和filter之后获取到的数据和看到的数据不一致的问题

fix(copy): copy data with data sorted or filtered

---

packages/s2-core/__tests__/unit/ui/hd-adapter/index-spec.ts
packages/s2-core/__tests__/unit/ui/tooltip/index-spec.ts
packages/s2-core/__tests__/util/helpers.ts

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore
增加 core 层 tooltip 测试

test: add tooltip tests

---

packages/s2-core/README.md
s2-site/docs/manual/getting-started.zh.md

🔧 Chore
添加对`@antv/s2` tooltip使用变化的说明

docs: add tooltip note for s2-core

---

s2-site/examples/interaction/custom/demo/double-click-hide-columns.ts
s2-site/examples/react-component/tooltip/demo/custom-interaction-tooltip.tsx
s2-site/examples/react-component/tooltip/demo/meta.json
s2-site/package.json
s2-site/yarn.lock

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore

docs: add the demo of Custom Click Tooltip and upgrade the gatsby-theme

---

packages/s2-core/package.json
packages/s2-react/package.json

release s2-core@1.0.3-beta.1 s2-react@1.0.3-beta.1

chore(release): s2-core@1.0.3-beta.1 s2-react@1.0.3-beta.1

---

packages/s2-core/__tests__/unit/common/store/index.spec.ts
packages/s2-core/__tests__/unit/sheet-type/pivot-sheet-spec.ts
packages/s2-core/src/common/store/index.ts
packages/s2-core/src/sheet-type/pivot-sheet.ts

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore
1. 将 handleGroupSort 方法提取出来，方便测试
2. 增加 真正的 pivot sheet 测试, 90% 覆盖 ...

fix: optimize handleGroupSort and add pivot sheet basic class tests

---

package.json
packages/s2-react/__tests__/spreadsheet/part-drill-down-spec.tsx
packages/s2-react/__tests__/unit/utils/drill-down-spec.ts
packages/s2-react/src/components/sheets/base-sheet/index.tsx
packages/s2-react/src/utils/drill-down.ts

chore: fix typos and update the main script

---

packages/s2-react/package.json

chore(release): s2-react@1.0.0-beta.2

---

packages/s2-react/package.json

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore

chore(release): s2-react@1.0.0-beta.1

---

package.json
packages/s2-core/package.json
packages/s2-core/src/facet/layout/build-row-tree-hierarchy.ts
packages/s2-core/src/theme/index.ts

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore

fix: solve the wrong collapse status and tweak the default icon size for the corner cell and close #791

---

s2-site/docs/manual/advanced/adaptive.en.md
s2-site/docs/manual/advanced/adaptive.zh.md
s2-site/docs/manual/advanced/get-instance.en.md
s2-site/docs/manual/advanced/hd-adapter.en.md

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore
新增表格自适应文档

docs: add adaptive docs

---

packages/s2-core/package.json
packages/s2-react/package.json

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore

chore(release): s2-core@1.0.3 s2-react@1.0.3

---

.github/workflows/auto-release.yml
README.en-US.md
README.md

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore
增加官方群发布通知

chore: add public ding talk group notify

---

package.json
packages/s2-core/package.json
packages/s2-react/package.json

chore: update the scripts

---

package.json
packages/s2-core/package.json
packages/s2-react/package.json

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore

chore(release): 🔖 publish the new version [ci skip]

---

s2-site/package.json
s2-site/yarn.lock

chore: update the lock for the site

---

packages/s2-core/__tests__/unit/utils/export/copy-spec.ts
packages/s2-core/src/utils/export/copy.ts

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore
复制的时候 用户不希望有“”

fix(copy): remove '' on copied data

---

packages/s2-core/package.json

chore(release): s2-core@1.0.0-beta.16

---

s2-site/docs/manual/basic/analysis/export.zh.md
s2-site/docs/manual/basic/analysis/switcher.zh.md
s2-site/examples/react-component/switcher/demo/table.tsx

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore
1. 修复 行列维度切换组件 错误的文档
2. 修复 行列维度切换组件 明细表 demo 展示异常
| ![image](https://user-images.githubusercontent.com/21015895/143452297-bd418a16-cbe5-48b1-ad8c-22ea1ebdbbfd.png) | ![image](https://user-images.githubusercontent.com/21015895/143452117-66c4c7ba-679d-47f4-ae6d-591fbf21862f.png) |

docs(switcher): fix switcher docs example

---

.github/workflows/sync-site-lock-with-pr.yml
README.en-US.md
README.md
packages/s2-core/README.en-US.md
packages/s2-core/README.md
packages/s2-core/src/common/interface/basic.ts
packages/s2-core/src/common/interface/s2DataConfig.ts
s2-site/docs/api/basic-class/spreadsheet.zh.md
s2-site/docs/api/components/sheet-component.zh.md
s2-site/docs/api/general/S2DataConfig.zh.md
s2-site/docs/common/sort-params.zh.md
s2-site/docs/manual/basic/analysis/switcher.zh.md
s2-site/docs/manual/getting-started.zh.md
s2-site/docs/manual/introduction.zh.md

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore
1. 修改错误的贡献指南步骤, 应该是大写的 S2
2. 优化部分文档细节

docs: fix invalid contributing step

---

packages/s2-core/__tests__/unit/utils/merge-cells.spec.ts
packages/s2-core/src/common/interface/basic.ts
packages/s2-core/src/utils/interaction/merge-cells.ts

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore
为 merge-cells.ts 添加单测

test: add merge-cells.ts test

---

packages/s2-core/__tests__/spreadsheet/table-sheet-spec.ts
packages/s2-core/__tests__/unit/utils/export/copy-spec.ts
packages/s2-core/src/utils/export/copy.ts

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore
重构copy代码
修复不可视区域复制没有内容的问题
改成用meta来取值

fix: copy refactor

---

packages/s2-core/package.json

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore

chore(release): s2-core@1.1.1-beta.1

---

.github/workflows/issue-labeled.yml
.github/workflows/sync-site-lock-changelog-with-pr.yml

🔧 Chore
支持自动发布后, 创建 同步lock 和 changelog 的脚本, 修复push 代码报错的问题

ci: auto create pr for merge lock and chagnelog into master

---

packages/s2-core/__tests__/unit/utils/export/copy-spec.ts
packages/s2-core/src/utils/export/copy.ts

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore
修复\r\n导致的单元格内换行问题

fix(copy): copy \r\n problem

---

packages/s2-core/package.json

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore

chore(release): s2-core@1.1.1-beta.2

---

s2-site/docs/api/general/S2Options.zh.md
s2-site/docs/manual/basic/sort/custom.zh.md
s2-site/examples/analysis/sort/demo/custom-sort-func.ts

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore
1. 修复自定义排序 demo 无法生效
2. 添加 hideMeasureColumn 文档说明
|![image](https://user-images.githubusercontent.com/20497176/144021283-c873a3a2-0548-46af-bc06-736503077f8e.png)|![image](https://user-images.githubusercontent.com/20497176/144021365-3705cb45-109b-4b67-a56a-82e56d02bde1.png)|

 docs: custom sort demo not work

---

.github/workflows/sync-site-lock-changelog-with-pr.yml

ci: fix cannot checkout branch

---

s2-site/docs/manual/advanced/interaction/custom.zh.md
s2-site/docs/manual/basic/sheet-type/pivot-mode.zh.md
s2-site/docs/manual/basic/tooltip.zh.md

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore
1. 修复链接跳转错误
2. 修改 tooltip 文档

docs: optimize tooltip docs

---

packages/s2-core/src/cell/corner-cell.ts
packages/s2-core/src/common/interface/node.ts
packages/s2-core/src/facet/header/corner.ts
packages/s2-core/src/interaction/row-column-resize.ts

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore
| ![image](https://user-images.githubusercontent.com/17964556/144427337-529202b7-6cd7-4dd1-b1b1-7975619879b1.png)   | ![image](https://user-images.githubusercontent.com/17964556/144427384-c6765244-a7b9-4893-99dd-ec5c2093ea64.png)    |
| ![2021-12-03 11 14 40](https://user-images.githubusercontent.com/17964556/144539002-1058713f-44bd-4aa4-98a6-94f99b721adc.gif) |![2021-12-03 11 12 20](https://user-images.githubusercontent.com/17964556/144539074-c61acfd3-64fe-465f-ac12-bef5421ed40f.gif)|

fix: fix series resize area

---

s2-site/docs/api/components/export.zh.md
s2-site/docs/manual/basic/analysis/export.zh.md

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore
add export func docs

docs(export): add export func docs

---

s2-site/docs/api/general/S2DataConfig.zh.md
s2-site/docs/common/custom/customTreeItem.zh.md

🔧 Chore
- [ x Add or update relevant TypeScript definitions.

docs: :memo: update the doc of S2DataConfig

---

packages/s2-core/__tests__/bugs/issue-868-spec.ts
packages/s2-core/__tests__/data/data-issue-868.json
packages/s2-core/__tests__/unit/utils/dataset/pivot-dataset-spec.ts
packages/s2-core/src/utils/dataset/pivot-data-set.ts

🐛 Bugfix
| ❌  ![image](https://user-images.githubusercontent.com/10885578/145175419-b0b7d360-f59f-4b16-8dd7-4aa1e74d7783.png) | ✅ ![image](https://user-images.githubusercontent.com/10885578/145175322-3f5cf025-f255-406b-a45a-d0a7dc58d96a.png) |

fix: 🐛 solve the issue that the measure does not shown when the type of dimensions are number

---

packages/s2-core/src/cell/col-cell.ts
s2-site/examples/analysis/sort/demo/meta.json
s2-site/examples/custom/custom-icon/demo/custom-header-action-icon.tsx
s2-site/examples/react-component/sheet/demo/table.tsx
s2-site/examples/theme/custom/demo/custom-schema.ts

🔧 Chore
* Fix the wrong date path of table demos.
* Optimize the demo of custom-header-action-icon.

docs: :memo: fix crashed demos

---

packages/s2-react/__tests__/spreadsheet/tooltip-spec.tsx
packages/s2-react/__tests__/unit/components/header/index.spec.tsx
packages/s2-react/__tests__/util/helpers.ts
packages/s2-react/src/components/tooltip/components/operator/index.tsx

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore
修复 hover 趋势图icon 时 报错的问题 close #873 

fix(components): add empty fragment close #873

---

s2-site/docs/manual/advanced/performance.zh.md

docs(performance): table compare size

---

packages/s2-react/src/components/export/index.tsx

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore
去掉组件内的a标签

fix(export): export link problem

---

packages/s2-core/__tests__/unit/sheet-type/pivot-sheet-spec.ts
packages/s2-core/src/cell/header-cell.ts
packages/s2-core/src/cell/table-col-cell.ts
packages/s2-core/src/sheet-type/pivot-sheet.ts
packages/s2-core/src/utils/sort-action.ts
packages/s2-react/playground/index.tsx

✨ Feature
🎨 Enhance
🔧 Chore
close #882

feat: ✨ show the sortIcon when the hideMeasureColumn is set

---

packages/s2-core/package.json
packages/s2-react/package.json

🔖@antv/s2@1.3.0 @antv/s2-react@1.3.0

---

.github/workflows/auto-release.yml

chore: rename the release branch [skip ci]

---

.github/workflows/sync-site-lock-changelog-with-pr.yml
.releaserc.js
packages/s2-core/CHANGELOG.md
packages/s2-core/package.json
packages/s2-react/CHANGELOG.md
packages/s2-react/package.json
s2-site/package.json
s2-site/yarn.lock

chore: 同步 lock 和 changelog

---

packages/s2-react/src/components/sheets/table-sheet/index.tsx
s2-site/docs/api/components/sheet-component.zh.md

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore
close #895

fix(table): 修复明细表 onDataCellHover 无法触发

---

packages/s2-core/__tests__/unit/interaction/data-cell-multi-selection-spec.ts
packages/s2-core/__tests__/unit/interaction/shift-multi-selection-spec.ts
packages/s2-core/src/interaction/data-cell-multi-selection.ts
packages/s2-core/src/interaction/shift-multi-selection.ts

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore

fix(interactive): global selected event emit

---

.github/workflows/issue-close-require.yml
.github/workflows/issue-labeled.yml
.github/workflows/lint.yml
.github/workflows/pr-labeled.yml
.github/workflows/test.yml

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore

chore: 更新CI中英文翻译

---

packages/s2-core/__tests__/unit/utils/merge.spec.ts
packages/s2-core/src/sheet-type/spread-sheet.ts
packages/s2-core/src/utils/merge.ts
packages/s2-core/src/utils/text.ts
packages/s2-core/src/utils/tooltip.ts
packages/s2-react/src/hooks/usePaginationEffect.ts

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore
在进行merge时，没有赋值到一个新对象上，导致最终merge到了default options。统一在`customMerge`兜底，保证上层不管有没有传递新对象作为第一个参数，都能正确处理数据
close #886

fix: 修复错误修改DefaultOptions问题 close #886

---

packages/s2-core/__tests__/unit/interaction/base-interaction/click/row-text-click-spec.ts
packages/s2-core/__tests__/unit/interaction/root-spec.ts
packages/s2-core/__tests__/unit/interaction/shift-multi-selection-spec.ts
packages/s2-core/__tests__/unit/utils/merge-spec.ts
packages/s2-core/src/common/constant/interaction.ts
packages/s2-core/src/common/constant/options.ts
packages/s2-core/src/common/interface/basic.ts
packages/s2-core/src/common/interface/interaction.ts
packages/s2-core/src/common/interface/s2DataConfig.ts
packages/s2-core/src/common/interface/s2Options.ts
packages/s2-core/src/facet/utils.ts
packages/s2-core/src/interaction/index.ts
packages/s2-core/src/interaction/range-selection.ts
packages/s2-core/src/interaction/root.ts
packages/s2-core/src/interaction/shift-multi-selection.ts
packages/s2-react/__tests__/unit/utils/options-spec.ts
packages/s2-react/__tests__/util/helpers.ts
packages/s2-react/playground/index.tsx
packages/s2-react/src/components/sheets/strategy-sheet/custom-tooltip/custom-data-tooltip.tsx
packages/s2-react/src/components/sheets/strategy-sheet/index.tsx
s2-site/docs/common/interaction.zh.md
s2-site/docs/manual/advanced/interaction/basic.zh.md
s2-site/examples/case/kpi-strategy/demo/basic.tsx

✨ Feature
1. 交互 多选 和 区间多选 支持配置是否开启
2. 趋势分析表 禁用 多选 和 区间多选
3. `shiftMultiSelection` 重名为 `rangeMultiSelection` 更表意 @YardWill 
3. 增加测试, 和文档

feat(strategy-sheet): 趋势分析表禁用多选和快捷多选

---

.github/workflows/release-notify.yml
.github/workflows/sync-site-lock-changelog-with-pr.yml
README.en-US.md
README.md
s2-site/docs/manual/introduction.zh.md

🔧 Chore
1. 只在正式版发布时才同步changelog
2. 文档增加 alpha 版本

ci: 只在正式版发布时才同步changelog

---

s2-site/examples/analysis/conditions/demo/table-text.ts

docs: 修复字段标记明细表demo错误的数据地址

---

packages/s2-core/__tests__/unit/interaction/event-controller-spec.ts
packages/s2-core/__tests__/unit/interaction/root-spec.ts
packages/s2-core/__tests__/unit/sheet-type/pivot-sheet-spec.ts
packages/s2-core/src/interaction/event-controller.ts

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore

fix: event-controller 重复注册事件

---

packages/s2-core/src/common/interface/condition.ts
packages/s2-core/src/utils/index.ts
packages/s2-core/src/utils/text.ts
packages/s2-react/playground/config.ts
packages/s2-react/playground/index.tsx
packages/s2-react/src/components/sheets/grid-analysis-sheet/index.tsx
packages/s2-react/src/components/sheets/strategy-sheet/index.tsx

🐛 Bugfix
* fix: 修复趋势分析表和网格分析表无法自定义主题
* fix: 完善条件格式定义
* chore: 增加趋势分析表自定义主题示例

fix: 🐛 修复趋势分析表和网格分析表无法自定义主题

---

s2-site/docs/api/general/S2Theme.zh.md
s2-site/docs/manual/basic/theme.en.md
s2-site/docs/manual/basic/theme.zh.md

docs: 新增theme主题配置文档 close #872

---

packages/s2-core/__tests__/unit/data-process/table-spec.tsx
packages/s2-core/__tests__/unit/facet/table-facet-spec.ts
packages/s2-core/src/facet/base-facet.ts
packages/s2-core/src/facet/layout/build-table-hierarchy.ts
packages/s2-core/src/facet/table-facet.ts

修复明细表 layoutWidthType 为 adaptive 时不生效的问题。
https://github.com/antvis/S2/issues/870

fix(facet): table adaptive layout 

---

s2-site/examples/react-component/switcher/demo/pivot-header.tsx
s2-site/examples/react-component/switcher/demo/pivot.tsx

docs: 修复维度切换组件 demo 的错误数据链接

---

s2-site/docs/manual/advanced/adaptive.zh.md
s2-site/docs/manual/advanced/interaction/custom-header-action-icon.zh.md
s2-site/docs/manual/faq.zh.md
s2-site/examples/custom/custom-cell/demo/data-cell.ts

🔧 Chore
1. 修改部分错别字
2. 增加部分常见问题
3. 修复自定义icon 示例打不开

docs: 增加常见问题, 修复部分文档错误链接

---

s2-site/docs/api/components/drill-down.zh.md
s2-site/docs/manual/introduction.zh.md

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore
更新 intro 中的调试命令
更新下钻文档

docs: 完善文档

---

packages/s2-core/__tests__/bugs/issue-368-spec.ts
packages/s2-core/__tests__/bugs/issue-836-spec.ts
packages/s2-core/__tests__/data/data-issue-836.json
packages/s2-core/src/cell/header-cell.ts
packages/s2-core/src/facet/pivot-facet.ts

🐛 Bugfix
| ❌ ![image](https://user-images.githubusercontent.com/10885578/147156335-8ecca2d6-dad4-4cea-aea0-8cc30bda0827.png) | ✅  ![image](https://user-images.githubusercontent.com/10885578/147156365-29744397-aebf-4d88-8c03-66c4ac4cf529.png)|

fix: :bug: 修复列头小计总计位置漂移问题， close #836

---

packages/s2-core/__tests__/unit/dataset/table-dataset-spec.ts
packages/s2-core/src/common/interface/basic.ts
packages/s2-core/src/data-set/table-data-set.ts
s2-site/docs/manual/advanced/data-process/table.zh.md

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore
add custom filter function feat

feat(table filter): add custom filter function

---

packages/s2-core/__tests__/unit/facet/table-facet-spec.ts
packages/s2-core/__tests__/unit/interaction/base-interaction/click/data-cell-click-spec.ts
packages/s2-core/__tests__/unit/interaction/base-interaction/hover-spec.ts
packages/s2-core/__tests__/unit/interaction/root-spec.ts
packages/s2-core/__tests__/unit/utils/export/copy-spec.ts
packages/s2-core/__tests__/unit/utils/merge-spec.ts
packages/s2-core/src/cell/base-cell.ts
packages/s2-core/src/cell/header-cell.ts
packages/s2-core/src/common/constant/options.ts
packages/s2-core/src/common/interface/interaction.ts
packages/s2-core/src/facet/layout/build-table-hierarchy.ts
packages/s2-core/src/interaction/base-interaction/hover.ts
packages/s2-core/src/interaction/root.ts
packages/s2-react/__tests__/unit/utils/options-spec.ts
packages/s2-react/playground/index.tsx
s2-site/docs/api/basic-class/interaction.zh.md
s2-site/docs/common/interaction.zh.md
s2-site/docs/manual/advanced/interaction/basic.zh.md

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore
1. 新增 `hoverFocus` 配置项, 和 `hoverHighlight` 独立开
2. 优化文档

feat(interaction): 新增 hoverFocus 配置项

---

README.en-US.md
README.md
packages/s2-core/README.en-US.md
packages/s2-core/README.md
s2-site/docs/manual/introduction.zh.md

docs: :memo: 更新 README 和官网文档首页头图

---

s2-site/gatsby-config.js

chore: 官网增加 docs search 配置

---

packages/s2-react/src/components/sheets/interface.ts
packages/s2-react/src/hooks/useResizeEffect.ts
s2-site/docs/api/components/sheet-component.zh.md
s2-site/docs/manual/advanced/adaptive.zh.md
s2-site/docs/manual/basic/sheet-type/pivot-mode.zh.md
s2-site/docs/manual/basic/sheet-type/table-mode.zh.md

🎨 Enhance
1. adaptive getContainer 类型修改为可选, 否则如果是这种只想开启宽或高自适应, 还是提示必须要传 getContainer
```tsx
<SheetComponent adaptive={{ width: true, height: false }} />
```
2. 优化文档

fix(components): adaptive getContainer 类型修改为可选, 并优化相关文档

---

packages/s2-core/__tests__/spreadsheet/spread-sheet-spec.ts
packages/s2-core/src/facet/base-facet.ts
packages/s2-react/playground/index.tsx

🐛 Bugfix
| ❌  ![error](https://user-images.githubusercontent.com/10885578/147534928-4c595a31-2d9d-4522-a288-40669d464e2d.gif)  | ✅ ![scroll](https://user-images.githubusercontent.com/10885578/147534947-67c276de-2608-4cea-ac57-db41ae59873a.gif) |

fix: bug: 修复交叉表手动设置滚动不生效问题

---

packages/s2-core/__tests__/unit/facet/table-facet-spec.ts

fix(test): table facet 测试小数取整

---

packages/s2-core/__tests__/unit/utils/merge-cell.spec.ts
packages/s2-core/src/cell/merged-cell.ts
packages/s2-core/src/common/interface/basic.ts
packages/s2-core/src/utils/interaction/merge-cell.ts

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore
refactor: 合并单元格在绘制时使用增量更新 替换之前的全量更新。
test: 添加增量更新方法单测。
| 增量更新 | 全量更新 |
|![image](https://user-images.githubusercontent.com/20497176/147807452-a5cfd57e-3441-4952-81f8-5df0fc970933.png)|![image](https://user-images.githubusercontent.com/20497176/147807334-8b67e11c-44d0-4fc5-a859-eba2be3bcdfb.png)|
https://github.com/antvis/S2/issues/616

refactor: 合并单元格在绘制时使用增量更新。

---

packages/s2-react/package.json

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore
如题
close #963

fix: 修改 s2-react 错误的 peerDependencies close #963

---

packages/s2-react/src/components/export/index.tsx

chore(react): fix lint

---

packages/s2-core/src/facet/layout/build-row-custom-tree-hierarchy.ts
packages/s2-core/src/interaction/event-controller.ts

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore

fix: 修复点击非表格区域报错

---

packages/s2-core/src/utils/export/index.ts
packages/s2-react/src/components/export/index.tsx
s2-site/docs/api/components/export.zh.md
s2-site/docs/common/conditions.en.md
s2-site/docs/common/export.en.md
s2-site/docs/common/export.zh.md
s2-site/docs/manual/basic/analysis/export.zh.md

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore
1. 优化复制数据的处理逻辑
2. 优化相关文档
3. 修复类型错误
cc @YardWill @zxc0328

fix(export): 优化复制数据到剪贴板的逻辑

---

s2-site/docs/manual/advanced/interaction/basic.zh.md

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore
correct brush event constant

docs: correct brush event

---

packages/s2-react/package.json

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore

fix(react): 修复 s2-react 无法安装到 alpha 版本 s2 的问题

---

packages/s2-core/src/facet/layout/build-row-tree-hierarchy.ts
packages/s2-react/src/components/sheets/interface.ts
packages/s2-react/src/components/sheets/strategy-sheet/index.tsx
packages/s2-react/src/hooks/useEvents.ts
packages/s2-react/src/hooks/useSpreadSheet.ts

fix(s2-react): 修复 hierarchyType 切换导致的渲染问题

---

packages/s2-core/src/data-set/custom-tree-pivot-data-set.ts
packages/s2-react/src/hooks/useEvents.ts

fix: 修复多指标情况下自定义树展示不全的问题

---

packages/s2-core/__tests__/unit/utils/merge.spec.ts
packages/s2-core/src/common/constant/options.ts
packages/s2-core/src/common/interface/s2Options.ts
packages/s2-core/src/sheet-type/spread-sheet.ts
packages/s2-react/__tests__/unit/utils/options-spec.ts
s2-site/docs/api/general/S2Options.zh.md

feat: 增加supportCSSTransform设置

---

.github/workflows/issue-labeled.yml
.github/workflows/release-notify.yml
s2-site/docs/api/basic-class/base-cell.zh.md
s2-site/docs/api/general/S2Options.zh.md
s2-site/docs/manual/contribution.zh.md
s2-site/docs/manual/faq.zh.md

🔧 Chore
1. 修复部分文档错误描述
2. 增加如何更新数据的 faq
3. 调整版本发布推送方式

docs: 优化部分文档, 增加部分 faq

---

packages/s2-core/src/utils/text.ts

fix: :bug: 修复多指标渲染空值问题

---

packages/s2-core/__tests__/unit/interaction/row-column-resize-spec.ts
packages/s2-core/__tests__/unit/utils/text-spec.ts
packages/s2-core/src/common/constant/options.ts
packages/s2-core/src/common/interface/basic.ts
packages/s2-core/src/facet/pivot-facet.ts
packages/s2-core/src/facet/table-facet.ts
packages/s2-core/src/utils/text.ts
packages/s2-react/__tests__/data/grid-analysis-data.ts

🎨 Enhance
🐛 Bugfix
🔧 Chore
* 列宽计算适配多指标情况
* 去掉无效列宽采样配置项
* 补充文本工具函数单测

fix: 列宽计算适配多指标情况

---

packages/s2-core/__tests__/spreadsheet/scroll-spec.ts
packages/s2-core/src/common/constant/interaction.ts
packages/s2-core/src/common/constant/options.ts
packages/s2-core/src/common/interface/basic.ts
packages/s2-core/src/common/interface/s2Options.ts
packages/s2-core/src/facet/base-facet.ts

修复 ScrollbarPositionType 枚举的文件和大小写问题。

fix(facet): 移动 ScrollbarPositionType 枚举位置

---

packages/s2-core/__tests__/spreadsheet/scroll-spec.ts

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore

test(scroll): 修复 layout变化后导致的断言错误

---

packages/s2-core/package.json
packages/s2-react/package.json

release @antv/s2@1.6.0 @antv/s2-react@1.6.0

chore(release): @antv/s2@1.6.0 @antv/s2-react@1.6.0

---

packages/s2-react/src/hooks/useResize.ts

fix: 修复高度自适应死循环问题

---

packages/s2-core/src/facet/layout/build-row-custom-tree-hierarchy.ts
packages/s2-core/src/facet/layout/node.ts

feat: node增加节点信息参数便于透传额外业务信息

---

.github/workflows/auto-release.yml
.github/workflows/lint.yml
.github/workflows/pr-notify.yml
.github/workflows/prerelease-notify.yml
.github/workflows/release-notify.yml
.github/workflows/sync-site-lock-changelog-with-pr.yml
.github/workflows/test.yml

🔧 Chore
1. 自动同步 changelog 的 CI 去掉 [skip ci] 标识, 因为 lint 和 test 是 required, 即使跳过了也不能合并
2. 由于有 `prepare` 脚本, 导致会 build 两次, yarn install 一次, yarn build 一次, 保留一次提升 CI 速度 (后面可以考虑 pnpm)
3. 增加 prerelease 发布开发群推送

chore(ci): 新增 prerelease 推送 & CI 细节调整

---

packages/s2-core/src/facet/layout/build-row-custom-tree-hierarchy.ts
packages/s2-core/src/utils/text.ts

🐛 Bugfix
* 保持自定义目录树构建流程和普通流程统一，开放layoutHierarchy，保证 layout 层级结构和普通透视模式一致

fix: 自定义目录树增加layoutHierarchy的hook修复层级问题

---

s2-site/examples/case/comparison/demo/meta.json
s2-site/examples/case/comparison/demo/philosophers.tsx

docs: 增加小册子demo《哲学家的观点》

---

packages/s2-core/__tests__/unit/interaction/selected-cell-move-spec.ts
packages/s2-core/src/facet/base-facet.ts
packages/s2-core/src/facet/table-facet.ts
packages/s2-core/src/facet/utils.ts
packages/s2-core/src/interaction/selected-cell-move.ts

🎨 Enhance
重写scrollToActiveCell方法，滚动效果和excel保持一致
https://user-images.githubusercontent.com/16497201/150716986-aa68d719-0307-46c4-ba7d-a273828555f8.mov

fix(interactive): table move problem

---

s2-site/examples/case/comparison/demo/philosophers.tsx

docs: 优化demo《哲学家的观点》

---

package.json
packages/s2-core/src/cell/row-cell.ts
packages/s2-core/src/facet/base-facet.ts
packages/s2-core/src/facet/header/row.ts
packages/s2-core/src/facet/header/series-number.ts
packages/s2-core/src/facet/pivot-facet.ts
packages/s2-core/src/utils/facet.ts
packages/s2-react/package.json
packages/s2-react/src/components/sheets/base-sheet/index.tsx
yarn.lock

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore
主要修改点
- master 已存 BUG：
- 序号列未展示
- 组件初始化未设置 分页 total
- PanelBBox 引入 viewportHeight 后，角头等未使用正确的高度，导致多渲染或 clip 错误
| | Before | After |
| ------ | ------ | ----- |
| 视窗高度不足 |   ![CleanShot 2022-01-24 at 11 08 59](https://user-images.githubusercontent.com/6716092/150715864-0851e0f5-c39b-4a6c-a73d-b0a40695fee3.gif)     |  <img width="829" alt="CleanShot 2022-01-24 at 10 54 38@2x" src="https://user-images.githubusercontent.com/6716092/150714521-164b6206-0b5c-45cb-87f8-a1a900c5d89d.png"> |
| 视窗高度充足 |  ![CleanShot 2022-01-24 at 11 00 09](https://user-images.githubusercontent.com/6716092/150715126-e7c3d6c5-a4ff-4b5f-913c-b440568fc808.gif) | ![CleanShot 2022-01-24 at 10 56 19](https://user-images.githubusercontent.com/6716092/150714632-c7534a89-dd0d-4179-aeea-d8b3 …

feat: 完善交叉表分页功能

---

packages/s2-core/src/facet/base-facet.ts

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore
序号列后添加，遮住了角头
|     <img width="804" alt="CleanShot 2022-01-24 at 14 27 25@2x" src="https://user-images.githubusercontent.com/6716092/150732768-48fe849c-3af3-47a2-bfb4-a59d2c5ef78e.png">   |  <img width="807" alt="CleanShot 2022-01-24 at 14 26 36@2x" src="https://user-images.githubusercontent.com/6716092/150732695-d3a043f6-3580-4d29-9d73-2360455577fe.png">     |

fix(facet): 序号列应早于列头添加到group

---

packages/s2-core/package.json
packages/s2-react/package.json

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore

chore(release): @antv/s2@1.7.0 @antv/s2-react@1.7.0

---

packages/s2-core/package.json
packages/s2-react/package.json

This reverts commit 0d538f2de3f98ee2adbc4f024123a58a37f076d4.
✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore

chore: Revert release commit @antv/s2@1.7.0 @antv/s2-react@1.7.0 (#1039)

---

packages/s2-core/package.json
packages/s2-react/package.json

chore(release): @antv/s2@1.7.0 @antv/s2-react@1.6.1

---

packages/s2-core/src/interaction/selected-cell-move.ts

fix(interaction): table 模式下的序列号兼容

---

packages/s2-react/__tests__/data/strategy-data.ts
packages/s2-react/src/components/sheets/strategy-sheet/custom-tooltip/custom-col-tooltip.tsx
packages/s2-react/src/components/sheets/strategy-sheet/custom-tooltip/custom-row-tooltip.tsx
packages/s2-react/src/components/sheets/strategy-sheet/custom-tooltip/interface.ts
packages/s2-react/src/components/sheets/strategy-sheet/index.tsx

🐛 Bugfix
1. 修复单指标模式下列头tooltip 不显示日期文本
2. 修复自定义树模式下不显示字段描述
3. 修复一些类型错误

fix(strategy-sheet): 修复自定义树布局模式下, 获取不到字段描述

---

packages/s2-core/__tests__/setup.js
packages/s2-core/__tests__/spreadsheet/spread-sheet-spec.ts
packages/s2-core/__tests__/unit/ui/hd-adapter/index-spec.ts
packages/s2-core/__tests__/unit/utils/merge.spec.ts
packages/s2-core/src/common/constant/options.ts
packages/s2-core/src/common/interface/s2Options.ts
packages/s2-core/src/sheet-type/spread-sheet.ts
packages/s2-core/src/ui/hd-adapter/index.ts
packages/s2-react/__tests__/unit/utils/options-spec.ts
packages/s2-react/playground/index.tsx
s2-site/docs/api/general/S2Options.zh.md
s2-site/docs/manual/advanced/hd-adapter.zh.md

✨ Feature
🐛 Bugfix
1. 支持自定义 devicePixelRatio, 兼容高清场景
2. 修复缩放表格为原始大小后, canvas 宽高没有还原的问题
close #1050

feat: 支持自定义设备像素比

---

packages/s2-core/__tests__/unit/utils/export/copy-spec.ts
packages/s2-core/src/utils/export/copy.ts

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore
支持透视表网格模式复制功能

feat: copy with grid pivot sheet

---

packages/s2-react/__tests__/spreadsheet/filter-sheet-spec.tsx
s2-site/docs/api/general/S2Theme.zh.md
s2-site/examples/analysis/totals/demo/basic.ts
s2-site/examples/analysis/totals/demo/multiple-values.ts
s2-site/examples/analysis/totals/demo/tree.ts
s2-site/examples/case/data-preview/demo/index.tsx
s2-site/examples/react-component/export/demo/export.tsx
s2-site/examples/react-component/header/demo/default.tsx

docs: 修复部分错误文档和示例配置

---

packages/s2-core/package.json
packages/s2-core/src/cell/row-cell.ts
packages/s2-core/src/utils/g-renders.ts

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore

fix: 只在移动端绑定tap事件，防止多次触发 collapse 事件

---

packages/s2-core/src/common/interface/s2DataConfig.ts
packages/s2-core/src/facet/layout/build-row-custom-tree-hierarchy.ts
packages/s2-core/src/facet/layout/build-row-tree-hierarchy.ts
packages/s2-core/src/utils/export/index.ts
packages/s2-core/src/utils/text.ts
packages/s2-react/__tests__/data/strategy-data.ts
packages/s2-react/playground/config.ts
packages/s2-react/playground/index.tsx
packages/s2-react/src/components/sheets/strategy-sheet/custom-col-cell.ts

✨ Feature
🎨 Enhance
🐛 Bugfix
* feat:  数据导出适配自定义目录树
* fix: 修复树状 Hierarchy maxLevel 无取值问题
* refactor: 重构 copyData， 优化行列头补空逻辑
* TODO：导出下钻层级适配

feat:  数据导出适配自定义目录树

---

packages/s2-core/src/facet/base-facet.ts

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore
修复移动端画布内容滚动不流畅
| ----
修复之前
https://user-images.githubusercontent.com/85494491/153121919-70b3a57e-baaa-4aa1-afc1-7d64eae7bfe3.mp4
-- | ----- |
修复之后
https://user-images.githubusercontent.com/85494491/153121984-062b3cfd-1dc8-48b2-a06a-03c40566d018.mp4

fix(scroll): refactor mobile scrolling

---

packages/s2-core/src/utils/data-set-operate.ts
packages/s2-core/src/utils/layout/generate-header-nodes.ts

perf: lodash 使用优化

---

packages/s2-core/__tests__/unit/utils/merge-spec.ts
packages/s2-core/src/common/constant/options.ts
packages/s2-core/src/common/interface/s2Options.ts
packages/s2-core/src/data-set/pivot-data-set.ts
packages/s2-core/src/facet/layout/build-gird-hierarchy.ts
packages/s2-core/src/facet/layout/build-row-custom-tree-hierarchy.ts
packages/s2-core/src/facet/layout/build-row-tree-hierarchy.ts
packages/s2-core/src/utils/layout/generate-header-nodes.ts
packages/s2-core/src/utils/layout/generate-id.ts
packages/s2-react/__tests__/spreadsheet/layout-hooks-spec.tsx
packages/s2-react/__tests__/unit/utils/options-spec.ts
s2-site/examples/custom/custom-layout/demo/custom-layout-hierarchy.ts

refactor: 删除无用配置项customHeaderCells及相关逻辑

---

packages/s2-core/src/utils/export/index.ts
packages/s2-react/__tests__/data/strategy-data.ts

feat: 单元格内多指标支持分列导出

---

packages/s2-core/__tests__/unit/interaction/root-spec.ts
packages/s2-core/src/common/interface/interaction.ts
packages/s2-core/src/interaction/base-interaction/click/row-column-click.ts
packages/s2-core/src/interaction/root.ts
s2-site/docs/api/basic-class/interaction.zh.md

feat(interaction): interaction增加点击行列头方法供外部调用

---

packages/s2-core/__tests__/unit/sheet-type/pivot-sheet-spec.ts
packages/s2-core/src/facet/layout/build-row-custom-tree-hierarchy.ts
packages/s2-core/src/facet/layout/build-row-tree-hierarchy.ts
packages/s2-core/src/sheet-type/pivot-sheet.ts
packages/s2-react/playground/index.tsx

🐛 Bugfix
如题
| ![image](https://user-images.githubusercontent.com/21015895/153356124-31de45db-e025-4429-9d81-32d720803b4d.gif) | ![Kapture 2022-02-10 at 17 46 44](https://user-images.githubusercontent.com/21015895/153381157-a15259f2-cdf8-4ebd-884b-033dcf5373a5.gif) |

fix: 修复子节点收起后角头全部展开收起不生效 close #1072

---

packages/s2-core/__tests__/unit/utils/merge-spec.ts
packages/s2-core/src/common/constant/events/basic.ts
packages/s2-core/src/common/constant/options.ts
packages/s2-core/src/common/interface/emitter.ts
packages/s2-core/src/common/interface/events.ts
packages/s2-core/src/common/interface/s2Options.ts
packages/s2-core/src/common/interface/store.ts
packages/s2-core/src/facet/pivot-facet.ts
packages/s2-react/__tests__/unit/utils/options-spec.ts
packages/s2-react/src/components/sheets/interface.ts
packages/s2-react/src/hooks/useEvents.ts
s2-site/docs/api/basic-class/store.zh.md
s2-site/docs/api/general/S2Options.zh.md

🎨 Enhance
删除无用的 fireReachBorderEvent 方法及其所有相关参数定义

refactor: 删除无用代码及参数

---

packages/s2-react/__tests__/unit/hooks/useEvents-spec.ts
packages/s2-react/src/hooks/useEvents.ts
packages/s2-react/src/hooks/useSpreadSheet.ts

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore
s2-react 事件在 react hooks 使用中事件改变后未及时更新
[demo](https://stackblitz.com/edit/react-ts-v6pek2?file=index.tsx)
```jsx
const ButtonDemo = () => {
const [status, setStatus] = useState(false);
// status 改变不会更新 
const onDataCellClick = () => alert(status ? '开' : '关');
return (
<div>
<Switch checked={status} onChange={setStatus} />
<SheetComponent
sheetType={'pivot'}
adaptive={false}
dataCfg={{ data, fields }}
options={s2Options}
onDataCellClick={onDataCellClick}
/>
</div>
);
```
|<img width="1055" alt="image" src="https://user-images.githubusercontent.com/20497176/154000984-2a5f75e9-ef4e-4f79-a145-fc7f36a481cb.png"> | <img width="1055" alt="image" …

fix: s2-react 事件在 react hooks 使用中事件改变后未及时更新

---

packages/s2-core/__tests__/unit/utils/export/copy-spec.ts
packages/s2-core/src/common/constant/events/basic.ts
packages/s2-core/src/common/interface/emitter.ts
packages/s2-core/src/common/interface/resize.ts
packages/s2-core/src/facet/base-facet.ts
packages/s2-core/src/facet/header/col.ts
packages/s2-core/src/facet/table-facet.ts
packages/s2-core/src/interaction/brush-selection.ts
packages/s2-core/src/interaction/row-column-resize.ts
packages/s2-core/src/sheet-type/pivot-sheet.ts
packages/s2-react/__tests__/spreadsheet/filter-sheet-spec.tsx
packages/s2-react/__tests__/spreadsheet/table-sheet-spec.tsx
packages/s2-react/__tests__/unit/hooks/useEvents-spec.ts
packages/s2-react/playground/index.tsx
packages/s2-react/src/components/sheets/interface.ts
packages/s2-react/src/hooks/useEvents.ts
s2-site/docs/api/components/sheet-component.zh.md
s2-site/examples/case/data-preview/demo/index.tsx
s2-site/examples/interaction/custom/demo/double-click-hide-columns.ts

✨ Feature
🎨 Enhance
* s2-core 事件全量透出 s2-react 
* s2-core 事件重命名
* RANGE_SORT -> SORT_BEFORE_SORT
* RANGE_SORTED -> SORT_AFTER_SORT
* RANGE_FILTER -> FILTER_BEFORE_FILTER
* RANGE_FILTERED -> FILTER_AFTER_FILTER

feat: s2-react 全量透出事件回调函数

---

packages/s2-react/__tests__/unit/hooks/usePagination-spec.ts
packages/s2-react/src/components/pagination/index.tsx
packages/s2-react/src/hooks/usePagination.ts
packages/s2-react/src/hooks/useSpreadSheet.ts

🎨 Enhance
🔧 Chore
1. useSpreadSheet 保存 s2 实例时，除了 ref，增加 state 保存，让下游 hooks deps 依赖更新时更加精准
2. 结合 1 精简了 usePagination 内 hooks 的 dep 依赖
3. 补充 https://github.com/antvis/S2/pull/1090 的 test

refactor: 精简 usePagination hooks deps

---

packages/s2-react/src/components/header/index.tsx

🎨 Enhance
fix Header props types
Before:

fix(header): header props types

---

packages/s2-core/__tests__/unit/utils/export/copy-spec.ts
packages/s2-core/src/common/constant/events/basic.ts
packages/s2-core/src/common/interface/emitter.ts
packages/s2-core/src/common/interface/resize.ts
packages/s2-core/src/facet/table-facet.ts
packages/s2-core/src/sheet-type/pivot-sheet.ts
packages/s2-react/__tests__/spreadsheet/filter-sheet-spec.tsx
packages/s2-react/__tests__/unit/hooks/useEvents-spec.ts
packages/s2-react/src/components/sheets/interface.ts
packages/s2-react/src/hooks/useEvents.ts
s2-site/docs/api/components/sheet-component.zh.md
s2-site/examples/case/data-preview/demo/index.tsx

🐛 Bugfix
* s2-core: S2Event
* SORT_GROUP_SORT -> RANGE_SORT
* SORT_GROUP_SORTED -> RANGE_SORTED
* FILTER ->  RANGE_FILTER
* FILTERED -> RANGE_FILTERED
* s2-react
* onGroupSort ->  onRangeSort
* onGroupSorted -> onRangeSorted
* onFilter -> onRangeFilter 
* onFiltered ->  onRangeFiltered

fix: 回退排序筛选事件变量名

---

packages/s2-react/src/components/sheets/interface.ts
s2-site/docs/api/components/sheet-component.zh.md

docs: 完善表组件文档,添加事件回调接口说明

---

packages/s2-core/src/sheet-type/table-sheet.ts
s2-site/docs/api/components/sheet-component.zh.md

fix: 明细表增加排序事件回调 close#1087

---

packages/s2-core/__tests__/spreadsheet/spread-sheet-totals-spec.ts
packages/s2-core/src/utils/layout/add-totals.ts

🐛 Bugfix
未配置总计节点时，layout 错误地添加了小计节点
|   <img width="503" alt="CleanShot 2022-02-21 at 18 13 50@2x" src="https://user-images.githubusercontent.com/6716092/154934712-1d056101-7d31-4a8e-9491-482c09291785.png">      |  <img width="504" alt="CleanShot 2022-02-21 at 18 13 13@2x" src="https://user-images.githubusercontent.com/6716092/154934588-179d6cd5-dd05-440d-81c5-7c26dc21a526.png">     |

fix: 不添加总计时错误地添加了小计节点

---

s2-site/docs/manual/advanced/get-cell-data.en.md
s2-site/docs/manual/advanced/get-cell-data.zh.md
s2-site/docs/manual/advanced/performance.zh.md
s2-site/docs/manual/basic/analysis/export.zh.md
s2-site/docs/manual/basic/theme.zh.md
s2-site/examples/case/performance-compare/demo/meta.json

docs: 新增获取单元格数据文档

---

packages/s2-core/src/sheet-type/spread-sheet.ts
s2-site/docs/manual/advanced/custom/custom-icon.zh.md

✨ Feature
* 取消不能重复注册 icon 的限制，允许用户覆盖默认 icon 图标
* 修改文档不存在的 icon 说明
close #1126

feat: :sparkles: 支持覆盖默认icon

---

packages/s2-core/src/interaction/brush-selection.ts

🐛 Bugfix
| ❌   ![before](https://user-images.githubusercontent.com/10885578/155473177-1975fe43-a861-4f30-9689-58f3daf60279.gif)| ✅ ![after](https://user-images.githubusercontent.com/10885578/155473186-c18d5bb8-32a8-4aa6-8b14-ed27e22cac64.gif)|

fix: 修复对全局鼠标按下事件的污染

---

packages/s2-core/package.json
packages/s2-react/package.json

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore

chore(release): @antv/s2@1.10.0 @antv/s2-react@1.10.0

---

packages/s2-core/CHANGELOG.md
packages/s2-react/CHANGELOG.md
s2-site/package.json
s2-site/yarn.lock

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore

chore: 🤖 更新 lock 和 changelog 文件

---

packages/s2-core/src/theme/index.ts
packages/s2-core/src/utils/text.ts
packages/s2-react/src/components/sheets/strategy-sheet/strategy-theme.ts

✨ Feature
* 支持多指标单元格配置文本水对齐方式
* 修改趋势分析表指标默认为居右对齐
* TODO： 适配居中对齐

feat: :sparkles: 多指标单元格支持切换文本水对齐方式

---

packages/s2-react/src/components/pagination/index.tsx
packages/s2-react/src/components/sheets/base-sheet/index.tsx
packages/s2-react/src/components/sheets/interface.ts
s2-site/docs/api/components/sheet-component.zh.md

✨ Feature
透出 s2 自带翻页器的 current & pageSize 变化事件

feat: 透出s2自带翻页器change事件

---

packages/s2-react/src/components/sheets/base-sheet/index.less
packages/s2-react/src/components/sheets/base-sheet/index.tsx

fix: :bug: 修复s2-react组件污染全局样式问题 close#1144

---

packages/s2-core/__tests__/unit/interaction/event-controller-spec.ts
packages/s2-core/src/common/interface/s2Options.ts
packages/s2-react/src/hooks/useResize.ts
s2-site/docs/api/general/S2Options.zh.md
s2-site/docs/common/style.zh.md
s2-site/docs/manual/basic/totals.zh.md
s2-site/examples/basic/pivot/demo/tree.ts

✨ Feature
🎨 Enhance
🐛 Bugfix
-  [X] Solve the issue and close #1122 
🔧 Chore
| ![image](https://user-images.githubusercontent.com/20497176/157391411-1fb8414d-f3e2-4f54-b198-70975a54770c.png) | ![image](https://user-images.githubusercontent.com/20497176/157391389-485b9ea2-a0ce-49e9-9c94-99993b41bb15.png)|

docs: 文档校正，主要涉及属性：collapsedRows、calcTotals、calcSubTotals 和 width、height

---

.github/workflows/issue-labeled.yml

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore

chore: 增加 rejected label action

---

packages/s2-react/src/components/sheets/strategy-sheet/custom-data-set.ts
packages/s2-react/src/components/sheets/strategy-sheet/index.tsx

✨ Feature
🎨 Enhance
* 趋势分析表增加自定义 dataSet 
也就快了三百多倍吧 0x0
| ❌  优化前    | ✅  优化后   |
| ![image](https://user-images.githubusercontent.com/10885578/157801479-c15ece9d-bb1a-4f3e-8f5d-7bbdb6928a11.png)| ![image](https://user-images.githubusercontent.com/10885578/157801463-3399a1fd-493d-4f47-a0a5-3c7b71c29838.png)|

perf(strategysheet): :zap: 趋势分析表性能优化

---

packages/s2-core/package.json
packages/s2-react/package.json

chore(release): @antv/s2@1.12.0 @antv/s2-react@1.12.0

chore(release): @antv/s2@1.12.0 @antv/s2-react@1.12.0

---

s2-site/examples/analysis/conditions/demo/table-text.ts
s2-site/examples/basic/table/demo/table.ts
s2-site/examples/interaction/advanced/demo/table-hide-columns.ts
s2-site/examples/interaction/advanced/demo/table-link-jump.ts
s2-site/examples/interaction/basic/demo/auto-reset-sheet-style.ts
s2-site/examples/interaction/basic/demo/frozen.ts
s2-site/examples/react-component/sheet/demo/table.tsx

docs: update table data docs

---

packages/s2-core/src/interaction/brush-selection.ts

fix: 修复draggable事件失效问题 close#1172

---

packages/s2-core/src/cell/col-cell.ts

🎨 Enhance
| ❌  ![image](https://user-images.githubusercontent.com/10885578/158523795-d43efd6e-4d15-44e7-bb2f-b77a3a9f385f.png)| ✅  ![image](https://user-images.githubusercontent.com/10885578/158523813-9d70e36e-7368-4888-b0da-afd993d575c9.png)|

style: 恢复指标列头对齐方式和数据单元格保持一致

---

packages/s2-react/src/components/sheets/strategy-sheet/custom-data-set.ts
packages/s2-react/src/components/sheets/strategy-sheet/index.tsx

fix: 修复趋势分析表多指标丢失问题

---

packages/s2-core/__tests__/spreadsheet/interaction-brush-selection-scroll-spec.ts
packages/s2-core/__tests__/unit/interaction/event-controller-spec.ts

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore
ref #1172

test(interaction): 新增重复事件注册的测试

---

packages/s2-react/src/components/sheets/strategy-sheet/custom-data-set.ts

fix: 修复趋势分析表空数据不渲染问题

---

s2-site/package.json
s2-site/yarn.lock

docs: 修复Safari 15 无法访问官网的问题

---

.github/workflows/sync-site-lock-changelog-with-pr.yml

🔧 Chore
默认用的是机器人的 token, 无法触发 ci

chore: 修复自动同步changelog action 无法触发 ci 的问题

---

package.json
packages/s2-core/__tests__/unit/facet/pivot-facet-spec.ts
packages/s2-core/src/facet/pivot-facet.ts
packages/s2-core/src/utils/text.ts
packages/s2-react/src/components/sheets/strategy-sheet/index.tsx

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore
| label 为 数组 | label 不为数组，value为数组 |
| ![image](https://user-images.githubusercontent.com/17964556/158588692-d0b45702-9bcd-4f45-9fcb-e8d3dc2f341c.png)  | ![image](https://user-images.githubusercontent.com/17964556/158588418-b102b886-2de9-4a4f-a47c-94209fe64282.png) |

feat: 趋势分析表支持列展示不同数量的指标

---

packages/s2-core/package.json
packages/s2-react/package.json

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore

chore(release): @antv/s2@1.12.3 @antv/s2-react@1.12.3

---

packages/s2-core/src/utils/text.ts

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore
| ![image](https://user-images.githubusercontent.com/17964556/159650362-17446b78-a692-4894-90cc-4b5fc8e5295b.png)    | ![image](https://user-images.githubusercontent.com/17964556/159650264-dc0bf91c-9413-47cb-a8c9-3c5a2ef60c1f.png)    |

fix: 修复趋势分析表label文字对齐问题

---

packages/s2-core/__tests__/data/sort-advanced.ts
packages/s2-core/__tests__/unit/utils/sort-action-spec.tsx
packages/s2-core/src/data-set/interface.ts
packages/s2-core/src/utils/sort-action.ts
s2-site/docs/manual/basic/sort/custom.zh.md

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore
此次修复，主要修复  `sortByMeasure: TOTAL_VALUE`  的情况
修复：
1. 行列总计进行排序的问题 
2. 行总计排序问题。
|   <img width="767" alt="image" src="https://user-images.githubusercontent.com/20497176/159859589-b07acbbd-1533-485f-bc59-7ddef4a3a065.png">| <img width="717" alt="image" src="https://user-images.githubusercontent.com/20497176/159859420-fa1febc5-4197-481e-972b-5e57fc12f847.png">|
|<img width="700" alt="image" src="https://user-images.githubusercontent.com/20497176/159859852-c65a3767-df6a-41d4-a64a-53b5af09a002.png"> | <img width="762" alt="image" src="https://user-images.githubusercontent.com/20497176/159859700-8aae9002-e18f-4c79-8059-e0fdda677991.png">|

fix: 修复以行列总计依赖度量汇总排序失败问题。

---

s2-site/examples/custom/custom-cell/demo/corner-cell.ts
s2-site/examples/custom/custom-cell/demo/corner-header.ts

docs: 修复自定义角头单元格 demo

---

packages/s2-core/src/cell/corner-cell.ts
packages/s2-core/src/cell/header-cell.ts
s2-site/docs/api/general/S2DataConfig.zh.md

✨ Feature
feat: add col cell and row cell getFormattedFieldValue method
feat: 添加行头和列头的格式化功能 （单测下次加🐶
🎨 Enhance
🐛 Bugfix
🔧 Chore
|<img width="533" alt="image" src="https://user-images.githubusercontent.com/20497176/160584207-2ce38285-24ef-45e8-ad50-978bd6de1b2e.png">|<img width="494" alt="image" src="https://user-images.githubusercontent.com/20497176/160580306-64b87dee-bdec-4b80-9400-efe50a014461.png">|

feat: 添加行头和列头的格式化功能

---

s2-site/docs/api/basic-class/spreadsheet.zh.md
s2-site/docs/api/components/sheet-component.zh.md
s2-site/docs/common/custom/customTreeItem.zh.md
s2-site/docs/manual/advanced/custom/category-tree.zh.md
s2-site/docs/manual/advanced/interaction/basic.zh.md
s2-site/examples/custom/custom-cell/demo/col-cell.ts
s2-site/examples/custom/custom-cell/demo/corner-cell.ts
s2-site/examples/custom/custom-cell/demo/corner-header.ts
s2-site/examples/custom/custom-tree/demo/meta.json
s2-site/examples/react-component/tooltip/demo/custom-hover-show-tooltip.tsx

🔧 Chore
- 修复一些错误的文档
- 优化自定义目录文档
- 增加如何在组件层监听 S2Event 的说明

docs: 优化自定义目录和交互文档细节

---

.github/workflows/issue-close-require.yml
.github/workflows/issue-labeled.yml
.github/workflows/issue-remove-inactive.yml
.github/workflows/issues-similarity-analysis.yml
.github/workflows/pr-labeled.yml

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore
1. 修复标记为需要复现链接 15天后 issue 没有自动关闭的问题
2. 完善了 action 模板的文案, 增加参考issue 等描述
3. 参考 Antd, 使用 actions-cool/issues-similarity-analysis 新增了 自动回复相似 issue 的 action

chore: 新增相似issue提示action, 完善action模板

---

packages/s2-core/__tests__/bugs/issue-1201-spec.ts
packages/s2-core/__tests__/unit/facet/pivot-facet-spec.ts
packages/s2-core/src/cell/col-cell.ts
packages/s2-core/src/cell/corner-cell.ts
packages/s2-core/src/cell/data-cell.ts
packages/s2-core/src/cell/row-cell.ts
packages/s2-core/src/common/interface/theme.ts
packages/s2-core/src/facet/header/corner.ts

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore

fix: 修复 backgroundColorOpacity 不生效问题，close #1201

---

s2-site/package.json
s2-site/yarn.lock

fix: 修复官网在Safari环境下打不开的问题 

---

packages/s2-core/src/sheet-type/pivot-sheet.ts
packages/s2-core/src/sheet-type/table-sheet.ts

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore
防止获取facet config时，style中同名字段被options错误覆盖

fix: 更改remapping字段顺序

---

packages/s2-core/package.json
packages/s2-react/package.json

🔧 Chore
目前最新版本
- @antv/s2: `1.13.1`
- @antv/s2-react: `1.12.1`

chore(release): @antv/s2@1.14.0 @antv/s2-react@1.13.0

---

packages/s2-core/__tests__/unit/interaction/row-column-resize-spec.ts
packages/s2-core/src/interaction/row-column-resize.ts

fix(row-column-resize): 修复虚线宽度设置不生效问题

---

s2-site/gatsby-config.js
s2-site/package.json
s2-site/yarn.lock

fix: 修复官网搜索功能

---

packages/s2-core/__tests__/unit/utils/export/copy-spec.ts
packages/s2-core/src/common/constant/copy.ts
packages/s2-core/src/common/constant/index.ts
packages/s2-core/src/utils/export/copy.ts

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore
添加复制全部 复制行 复制列功能 暂时仅透出方法

feat(copy): 添加复制全部 复制行 复制列功能

---

.github/workflows/auto-add-to-project.yml
packages/s2-react/playground/resize.tsx

✨ Feature
之前建立Project，只会对于已经添加到其中的issue和PR进行自动状态更新，新建的却不会，类似于 git 的跟踪与未跟踪文件的区别，该PR就是在新建issue和PR时，自动加到project中，后续就能跟踪状态更改了
🎨 Enhance
🐛 Bugfix
🔧 Chore

chore: 增加自动添加 issue&PR 到 project 的 action

---

.github/workflows/auto-add-to-project.yml

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore

fix: 修复auto add to project action 语法错误

---

packages/s2-core/__tests__/unit/interaction/event-controller-spec.ts
packages/s2-core/__tests__/unit/utils/merge-spec.ts
packages/s2-core/src/common/constant/options.ts
packages/s2-core/src/common/interface/interaction.ts
packages/s2-core/src/interaction/event-controller.ts
packages/s2-react/__tests__/unit/utils/options-spec.ts
s2-site/docs/common/interaction.zh.md
s2-site/docs/manual/advanced/interaction/basic.zh.md

✨ Feature
透传 addEventListener 第三个参数, 可自由控制事件触发阶段, 避免和项目的其他事件冲突

feat(interaction): 支持透传 addEventListener 的可选参数

---

.github/workflows/auto-add-to-project.yml

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore

chore: 修复github event_name 判断问题

---

packages/s2-core/__tests__/unit/cell/header-cell-spec.ts
packages/s2-core/src/cell/corner-cell.ts
packages/s2-core/src/cell/header-cell.ts
packages/s2-core/src/cell/table-col-cell.ts
packages/s2-core/src/utils/cell/header-cell.ts

#1249 
🐛 Bugfix
🔧 Chore
| <img width="906" alt="image" src="https://user-images.githubusercontent.com/20497176/162740541-e5a9781b-db13-4621-9af0-7fe7802da085.png"> |<img width="880" alt="image" src="https://user-images.githubusercontent.com/20497176/162740239-02d5e0eb-ef7f-4948-8200-ccae149239cf.png">|

fix: 解决明细表表头被格式化的问题

---

packages/s2-react/src/components/header/index.less
packages/s2-react/src/components/switcher/header.tsx
packages/s2-react/src/components/switcher/index.tsx
s2-site/docs/api/components/switcher.zh.md

✨ Feature
- add disabled property
- add css to center disabled popover Button

feat(switcher): add disabled property

---

packages/s2-core/__tests__/unit/sheet-type/pivot-sheet-spec.ts
packages/s2-core/__tests__/unit/utils/merge-spec.ts
packages/s2-core/src/sheet-type/spread-sheet.ts
packages/s2-core/src/utils/merge.ts
packages/s2-react/__tests__/unit/components/switcher/headerUtil-spec.ts
packages/s2-react/__tests__/unit/components/switcher/util-spec.ts
packages/s2-react/src/components/switcher/constant.ts
packages/s2-react/src/components/switcher/content/index.less
packages/s2-react/src/components/switcher/content/index.tsx
packages/s2-react/src/components/switcher/header.tsx
packages/s2-react/src/components/switcher/headerUtil.ts
packages/s2-react/src/components/switcher/util.ts
s2-site/docs/api/components/switcher.zh.md
s2-site/docs/manual/basic/analysis/switcher.zh.md
s2-site/examples/react-component/switcher/demo/table.tsx

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore
|      |     |

fix: 修复switcher组件布局问题

---

.github/workflows/auto-add-to-project.yml

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore

chore: 修复自动添加到project action 触发类型

---

packages/s2-core/src/facet/layout/build-row-tree-hierarchy.ts

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore

fix: 树状结构第一个子层级无法排序的问题

---

s2-site/examples/case/proportion/demo/group-drill-down.tsx

🔧 Chore
| ❌  ![image](https://user-images.githubusercontent.com/10885578/164257670-1d0928b4-bc30-4ae9-8648-eae46b576480.png) | ✅   ![image](https://user-images.githubusercontent.com/10885578/164257443-9f8eaf20-1f34-43d8-8557-ef0a850809bd.png) |

docs: 修复官网demo分群下钻表颜色丢失问题

---

s2-site/docs/api/general/S2Theme.zh.md
s2-site/docs/manual/basic/theme.zh.md
s2-site/package.json
s2-site/yarn.lock

docs: 完善主题章节

---

packages/s2-core/__tests__/spreadsheet/scroll-spec.ts
packages/s2-core/src/cell/corner-cell.ts
packages/s2-core/src/theme/index.ts

🎨 Enhance
| ❌ ![image](https://user-images.githubusercontent.com/10885578/164645473-33641996-877c-4c52-8e99-046026877f06.png)  | ✅   ![image](https://user-images.githubusercontent.com/10885578/164645657-cd5bb031-4e08-4c78-a825-7fe187b06e30.png)  |

fix(corner-cell): 微调角头icon位置保持和行头对齐

---

s2-site/package.json
s2-site/yarn.lock

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore

chore: 🤖 更新 version 以及 lock 文件

---

packages/s2-core/src/cell/header-cell.ts
packages/s2-core/src/cell/row-cell.ts
packages/s2-core/src/common/constant/options.ts
packages/s2-core/src/common/interface/basic.ts
packages/s2-core/src/utils/g-renders.ts
s2-site/docs/common/style.zh.md

✨ Feature
🎨 Enhance
* 增加树状层级缩进配置项
* 加粗字体调整为仅第一层和小计总计为粗体
| ❌ ![image](https://user-images.githubusercontent.com/10885578/165220192-329e3a0f-4c9b-4c69-afa0-567d07d6fff8.png)| ✅  ![image](https://user-images.githubusercontent.com/10885578/165220120-60f304fb-9730-4cc5-a2e8-3797b28f1e34.png)|

feat: 树状层级样式优化

---

packages/s2-core/__tests__/unit/utils/export/export-spec.ts
packages/s2-core/src/utils/export/index.ts
s2-site/docs/common/export.zh.md
s2-site/docs/manual/advanced/adaptive.zh.md

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore
|<img width="1391" alt="image" src="https://user-images.githubusercontent.com/20497176/167407783-d3e1d548-9d0e-4030-b283-dae74d73c771.png">|<img width="1521" alt="image" src="https://user-images.githubusercontent.com/20497176/167407089-1f7a0d50-393b-4b97-9193-0a349ce0795f.png">|

fix: 在复制或者表格数据时，可对行列头进行格式化导出

---

.github/workflows/prerelease-notify.yml
.github/workflows/release-notify.yml
.github/workflows/sync-site-lock-changelog-with-pr.yml

🔧 Chore
对发布通知 和 同步 s2 lock 增加延时操作, 避免时序问题拿不到最新数据

chore: 延时同步 s2 lock

---

s2-site/docs/manual/basic/tooltip.zh.md
s2-site/docs/manual/faq.zh.md

🔧 Chore
增加两种方式的介绍, 完善文档, 修改错别字

docs: 更新 Vue3 自定义 Tooltip 文档

---

.github/workflows/auto-release.yml
.github/workflows/codeql-analysis.yml
.github/workflows/compressed-size.yml
.github/workflows/lint.yml
.github/workflows/preview-build.yml
.github/workflows/sync-notify.yml
.github/workflows/sync-site-lock-changelog-with-pr.yml
.github/workflows/test.yml

🔧 Chore
- 增加 sync action 同步成功 & 失败的钉钉通知
- actions/checkout 更新到V3

chore(ci): 增加 sync changelog 成功&失败的通知

---

.github/workflows/issue-labeled.yml

chore: 增加 pengding 标签 action

---

packages/s2-react/__tests__/unit/hooks/usePivotSheetUpdate-spec.ts
packages/s2-react/__tests__/unit/utils/drill-down-spec.ts
packages/s2-react/src/components/sheets/interface.ts
packages/s2-react/src/components/sheets/pivot-sheet/index.tsx
packages/s2-react/src/hooks/index.ts
packages/s2-react/src/hooks/usePivotSheetUpdate.ts
packages/s2-react/src/hooks/useSpreadSheet.ts
packages/s2-react/src/utils/drill-down.ts

🎨 Enhance
🐛 Bugfix
- 以 mutable 方式修改 options.headerActionIcons
- 减少 hooks 中以 useLatest 方式引用变量
- 减少 pivot-sheet 重复 render（收拢到 base-sheet/useSpreadsheet）

fix: 不应以mutable的方式修改headerActionIcons

---

.github/workflows/issue-labeled.yml

🔧 Chore
Pending action 缩进有问题 @xingwanying

chore(ci): 修复 action 格式错误

---

packages/s2-core/__tests__/spreadsheet/tooltip-spec.ts
packages/s2-core/src/common/interface/tooltip.ts
packages/s2-core/src/ui/tooltip/index.ts
packages/s2-core/src/utils/tooltip.ts
s2-site/docs/common/tooltip.zh.md

✨ Feature
* 解决想要各种微调 tooltip 显示位置的场景

feat: 支持回调函数调整 Tooltip 位置

---

packages/s2-core/__tests__/spreadsheet/tooltip-spec.ts
packages/s2-core/src/common/interface/tooltip.ts
packages/s2-core/src/sheet-type/spread-sheet.ts
packages/s2-core/src/ui/tooltip/index.ts
packages/s2-react/playground/index.tsx
s2-site/docs/common/tooltip.zh.md

🎨 Enhance
* 将鼠标点击事件透出给 adjustPosition 参数
* 更新对应文档

refactor(tooltip): 增加 adjustPosition 回调参数

---

s2-site/examples/custom/custom-cell/demo/col-cell.ts
s2-site/examples/custom/custom-cell/demo/corner-cell.ts
s2-site/examples/custom/custom-cell/demo/corner-header.ts
s2-site/examples/custom/custom-cell/demo/data-cell.ts
s2-site/examples/custom/custom-cell/demo/meta.json
s2-site/examples/custom/custom-cell/demo/row-cell.ts
s2-site/examples/custom/custom-cell/demo/totals-cell.ts

docs: 增加自定义小计/总计单元格的例子

---

s2-site/docs/api/general/S2DataConfig.zh.md

docs: 修改 S2DataConfig 文案

---

packages/s2-core/src/cell/data-cell.ts

fix: 增加文本条件格式默认值

---

packages/s2-react/src/components/advanced-sort/index.tsx
s2-site/examples/analysis/sort/demo/advanced.tsx
s2-site/examples/case/data-preview/demo/house.tsx
s2-site/examples/case/data-preview/demo/meta.json
s2-site/examples/react-component/header/demo/default.tsx
s2-site/gatsby-browser.js

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore
[feat: 新增 "如何用 S2 买房" demo](https://github.com/antvis/S2/commit/5f9a935a145475a92e15394cf6d0f32c832b474d)

feat: 新增 "如何用 S2 买房" demo

---

s2-site/examples/case/art/demo/meta.json
s2-site/examples/case/art/demo/mosaic.tsx
s2-site/examples/case/art/demo/time-spend-abstract.tsx
s2-site/examples/case/comparison/demo/time-spend.tsx

docs: 新增demo「想如何度过一天（抽象版）」

---

packages/s2-core/src/facet/base-facet.ts
packages/s2-react/playground/config.ts
packages/s2-react/playground/index.tsx
s2-site/docs/api/basic-class/base-facet.zh.md
s2-site/docs/api/basic-class/spreadsheet.zh.md
s2-site/docs/common/browser.zh.md
s2-site/docs/manual/advanced/get-cell-data.zh.md
s2-site/docs/manual/basic/tooltip.zh.md
s2-site/examples/interaction/advanced/demo/meta.json
s2-site/examples/interaction/advanced/demo/scroll-loop.ts
s2-site/examples/interaction/advanced/demo/scroll-to-cell.ts

🔧 Chore
1. 补充了一直缺失的 facet API 文档
2. 增加两个滚动 demo
循环滚动
指定滚动

docs: 新增 facet 相关 API 和 循环滚动 demo

---

README.en-US.md
README.md
s2-site/docs/manual/basic/analysis/vue.en.md
s2-site/docs/manual/basic/analysis/vue.zh.md
s2-site/docs/manual/getting-started.zh.md

docs(vue):  添加 vue 3.0 组件demo

---

packages/s2-core/src/utils/export/copy.ts

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore
用户传入的数据可能是null，所以这里做一下兼容

fix(copy): 修复rowdata可能为null的情况

---

packages/s2-core/src/cell/base-cell.ts
packages/s2-core/src/cell/header-cell.ts
packages/s2-core/src/common/interface/basic.ts
packages/s2-core/src/common/interface/s2DataConfig.ts
packages/s2-core/src/common/interface/theme.ts
packages/s2-core/src/theme/index.ts
packages/s2-core/src/theme/palette/colorful.ts
packages/s2-core/src/theme/palette/default.ts
packages/s2-core/src/theme/palette/gray.ts
packages/s2-core/src/utils/export/index.ts
packages/s2-core/src/utils/text.ts
packages/s2-react/__tests__/data/strategy-data.ts
packages/s2-react/playground/config.ts
packages/s2-react/src/components/sheets/strategy-sheet/custom-tooltip/custom-data-tooltip.tsx
packages/s2-react/src/components/sheets/strategy-sheet/index.tsx
s2-site/examples/case/proportion/demo/group-drill-down.tsx

✨ Feature
TODO
* 单测
* 子弹图Tooltip
* 子弹图对齐方式配置？
* 文档
* demo
* 官网场景案例的 KPI 表是否直接替换掉？

feat: 趋势分析表支持子弹图配置

---

packages/s2-react/README.md
packages/s2-react/playground/index.tsx
packages/s2-vue/README.md
s2-site/docs/manual/getting-started.zh.md

docs: 优化快速上手文档

---

s2-site/docs/api/components/advanced-sort.zh.md
s2-site/docs/api/components/drill-down.zh.md
s2-site/docs/api/components/export.zh.md
s2-site/docs/api/components/header.zh.md
s2-site/docs/api/components/sheet-component.zh.md
s2-site/docs/api/components/switcher.zh.md

🔧 Chore
- 补充 vue 表组件文档
- 其他分析组件区分 react/vue 章节

docs: 补充表组件部分文档

---

packages/s2-core/src/facet/base-facet.ts

refactor: 删除无用的 debounceRenderCell 方法

---

packages/s2-vue/package.json

chore(release): 🔖@antv/s2@1.18.1  @antv/s2-vue@1.0.1

---

packages/s2-react/src/components/tooltip/index.less
packages/s2-react/src/components/tooltip/index.tsx
packages/s2-vue/src/components/tooltip/index.vue

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore

fix: 修复打包core层源码中样式文件错误问题

---

s2-site/docs/manual/basic/analysis/vue.zh.md

🔧 Chore
统一 codesandbox 为展示主要源码的预览视图

docs: 更新vue组件demo

---

packages/s2-core/src/common/interface/basic.ts
packages/s2-react/src/hooks/useSpreadSheet.ts
packages/s2-shared/src/interface.ts
packages/s2-vue/src/hooks/useSpreadSheet.ts
s2-site/docs/api/basic-class/spreadsheet.zh.md
s2-site/docs/api/components/sheet-component.zh.md
s2-site/docs/api/general/S2DataConfig.zh.md
s2-site/docs/common/style.zh.md
s2-site/docs/common/totals.zh.md

🔧 Chore
- 去除冗余的 S2Constructor 类型
- 修复一些文档参数格式 和 Typo

docs: 修正一些错误文档

---

packages/s2-core/__tests__/spreadsheet/theme-spec.ts
packages/s2-core/src/cell/row-cell.ts
packages/s2-core/src/cell/table-series-cell.ts
packages/s2-core/src/common/interface/theme.ts
packages/s2-core/src/facet/header/series-number.ts
packages/s2-core/src/theme/index.ts
s2-site/docs/api/general/S2Theme.zh.md

✨ Feature
🎨 Enhance
🐛 Bugfix
关联PR: #1364 
🔧 Chore
| ![image](https://user-images.githubusercontent.com/17964556/173305179-f2fce1ea-fc1a-4ce1-a4b1-d22e77d75bcf.png)![image](https://user-images.githubusercontent.com/17964556/173305210-86fe0503-d3c6-4798-ae5b-24b091e6fdb7.png)    |  ![image](https://user-images.githubusercontent.com/17964556/173304881-79efc27b-6952-49ed-9433-ba1f92fdee9b.png)![image](https://user-images.githubusercontent.com/17964556/173304927-b7efc651-d579-480d-916a-fee1ca57c9d8.png)     |

fix: 修复序号对齐问题， close #1412

---

packages/s2-core/__tests__/bugs/issue-565-spec.ts
packages/s2-core/__tests__/unit/utils/export/export-spec.ts
packages/s2-core/src/facet/pivot-facet.ts
packages/s2-core/src/utils/export/index.ts

✨ Feature
feat: 可以导出 Corner 中的行头名称了
🎨 Enhance
🐛 Bugfix
树状结构下，子节点全部折叠，导出内容错误
🔧 Chore
|   ![image](https://user-images.githubusercontent.com/20497176/173523025-a6ffab0f-31c1-44f0-b8c5-db44547432c1.png) |   ![image](https://gw.alipayobjects.com/zos/antfincdn/AU83KF1Sq/6fb3f3e6-0064-4ef8-a5c3-b1333fb59adf.png)   |
|![image](https://user-images.githubusercontent.com/20497176/173523423-eef16d9d-3354-4451-8877-b154bcae58d9.png) | ![image](https://user-images.githubusercontent.com/20497176/173523688-59827bba-ff81-4436-9833-f1011e432b30.png)|

fix: 树状结构下，子节点全部折叠，导出内容错误

---

packages/s2-core/__tests__/unit/sheet-type/pivot-sheet-spec.ts
packages/s2-core/__tests__/unit/utils/export/export-spec.ts
packages/s2-core/src/common/interface/basic.ts
packages/s2-core/src/common/interface/s2Options.ts
packages/s2-core/src/sheet-type/pivot-sheet.ts
packages/s2-react/__tests__/spreadsheet/data-accuracy-one-measure-spec.tsx
packages/s2-react/__tests__/spreadsheet/layout-hooks-spec.tsx
packages/s2-react/__tests__/spreadsheet/multiple-values-cell-spec.tsx
packages/s2-react/playground/config.ts
packages/s2-react/playground/index.tsx
packages/s2-vue/playground/App.vue
s2-site/docs/api/general/S2Options.zh.md
s2-site/docs/common/style.zh.md

refactor: S2Options.hierarchyCollapse => S2Options.style.hierarchyCollapse

---

packages/s2-core/__tests__/unit/utils/merge-spec.ts
packages/s2-core/src/utils/merge.ts

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore

fix: 修复相同配置字段导致程序出错, close #1427

---

.github/workflows/mirror.yml

chore: 更新国内镜像同步账号信息

---

.github/PULL_REQUEST_TEMPLATE.md
packages/s2-react/__tests__/spreadsheet/adaptive-spec.tsx
packages/s2-react/__tests__/unit/hooks/useResize-spec.ts
packages/s2-shared/src/utils/resize.ts
s2-site/docs/manual/advanced/custom/cell-size.zh.md

🔧 Chore
补充 https://github.com/antvis/S2/pull/1425 缺失的单测
ref https://github.com/antvis/S2/pull/1425

test: 补充自适应在父容器有缩放的情况下宽高获取错误的测试

---

s2-site/examples/case/data-preview/demo/excel.tsx
s2-site/examples/case/data-preview/demo/meta.json

✨ Feature
- [] New feature
🎨 Enhance
🐛 Bugfix
🔧 Chore
添加编辑场景的demo

feat: 添加编辑场景文档

---

packages/s2-shared/package.json

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore
看到现在 PR 合并 Git Action 不会运行 s2-shared 的单测

chore: 将 s2-shared 的单测检测添加到 CI 运行中

---

packages/s2-core/__tests__/unit/utils/text-spec.ts
packages/s2-core/src/common/constant/basic.ts
packages/s2-core/src/common/interface/s2DataConfig.ts
packages/s2-core/src/common/interface/theme.ts
packages/s2-core/src/facet/table-facet.ts
packages/s2-core/src/theme/index.ts
packages/s2-core/src/utils/g-mini-charts.ts
packages/s2-core/src/utils/g-renders.ts
packages/s2-core/src/utils/index.ts
packages/s2-core/src/utils/text.ts
packages/s2-react/__tests__/data/strategy-data.ts
packages/s2-react/playground/config.ts
packages/s2-react/playground/index.tsx
packages/s2-react/src/components/sheets/strategy-sheet/custom-tooltip/kpi-columns/custom-bullet-tooltip.tsx
packages/s2-react/src/components/sheets/strategy-sheet/index.tsx

✨ Feature
🎨 Enhance
* 支持 mini 折线图
* 将子弹图收敛至 `renderChart` 统一绘制

feat: 支持绘制 mini 折线图

---

packages/s2-core/src/interaction/base-interaction/click/data-cell-click.ts
packages/s2-react/playground/config.ts

feat: 明细表趋势图透出点击透出整行数据

---

packages/s2-core/src/interaction/root.ts

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore
兼容node可能为null的场景

fix: node 可能为null

---

packages/s2-core/package.json
packages/s2-react/package.json
packages/s2-vue/package.json

chore(release): 🔖@antv/s2@1.22.0 @antv/s2-react@1.19.1  @antv/s2-vue@1.1.0

---

packages/s2-core/src/cell/col-cell.ts
packages/s2-core/src/cell/corner-cell.ts
packages/s2-core/src/cell/data-cell.ts
packages/s2-core/src/cell/row-cell.ts

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore

refactor: 将cell中所有的private改为protected，便于继承定制

---

s2-site/docs/api/general/S2DataConfig.zh.md

🔧 Chore
API 文档中《基础配置项-S2DataConfig》totalData 类型笔误修复.

docs: totalData 类型文案修正

---

.github/workflows/sync-site-lock-changelog-with-pr.yml

🔧 Chore
之前 CI 自动合并时会携带 latest 分支的所有 commit, 不太美观, 虽然合并 pr 的时候会 sequash, 但是 commit 本身还有相关信息

chore(ci): 合并 changelog 时加上 --squash 将 commit 合并成一个

---

packages/s2-core/CHANGELOG.md
packages/s2-core/package.json
packages/s2-react/CHANGELOG.md
packages/s2-react/package.json
packages/s2-vue/CHANGELOG.md
packages/s2-vue/package.json

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore

chore: 更新 lock 和 changelog 文件

---

.github/workflows/lint.yml
.github/workflows/test.yml
packages/s2-core/__tests__/spreadsheet/scroll-spec.ts

🔧 Chore
对 lint 和 test 两个比较耗时的 job 进行优化, 每次 push 代码取消上一次正在跑的 job, 避免排队

chore(ci): 每次 push 代码时取消上一次未执行完的 CI, 避免排队

---

packages/s2-core/src/interaction/base-interaction/click/data-cell-click.ts

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore

fix: 修复 pivot 无法获取整行数据，而报错的问题

---

s2-site/examples/case/data-preview/demo/excel.tsx

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore

docs: 编辑场景 超出容器 编辑框消失

---

.github/workflows/mirror.yml

chore: 更新 gitee 账号信息

---

s2-site/examples/analysis/sort/demo/advanced.tsx
s2-site/examples/analysis/sort/demo/custom-totals.ts
s2-site/examples/analysis/sort/demo/group-sort.tsx
s2-site/examples/analysis/totals/demo/basic.ts
s2-site/examples/analysis/totals/demo/multiple-values.ts
s2-site/examples/analysis/totals/demo/tree.ts
s2-site/examples/interaction/custom/demo/double-click-hide-columns.ts
s2-site/examples/react-component/switcher/demo/pivot-header.tsx
s2-site/examples/react-component/switcher/demo/pivot-with-children.tsx
s2-site/examples/react-component/switcher/demo/pivot.tsx
s2-site/examples/theme/custom/demo/custom-palette.ts
s2-site/examples/theme/custom/demo/custom-schema.ts
s2-site/examples/theme/default/demo/colorful.ts
s2-site/examples/theme/default/demo/default.ts
s2-site/examples/theme/default/demo/gray.ts

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore

docs: 更新线上json文件中行政区域

---

packages/s2-vue/README.md

doc: s2-vue README 示例代码保持变量名统一

---

packages/s2-core/src/common/interface/basic.ts
packages/s2-core/src/common/interface/condition.ts
packages/s2-core/src/utils/text.ts
packages/s2-react/__tests__/data/strategy-data.ts
packages/s2-react/playground/config.ts
packages/s2-react/src/components/sheets/strategy-sheet/custom-col-cell.ts
s2-site/docs/manual/basic/analysis/strategy.zh.md
s2-site/examples/react-component/sheet/demo/strategy.tsx

🎨 Enhance
* 将趋势分析表原本从 ` options.style.cellCfg.valuesCfg.conditions`  归并至 统一的 ` options.conditions` , 保持逻辑统一
* 去掉 `disabledConditions` 判断，条件格式是否生效统一在 `mapping` 里自行判断就好
* 一些变量名的变更

refactor: 重构趋势分析表条件格式解析逻辑

---

s2-site/docs/api/components/drill-down.zh.md
s2-site/docs/manual/basic/analysis/vue.zh.md

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore
docs: 添加 vue 版的下钻组件

docs: 添加 vue 版的下钻组件

---

packages/s2-core/src/utils/text.ts
packages/s2-react/playground/config.ts
packages/s2-react/src/components/sheets/strategy-sheet/custom-col-cell.ts
s2-site/examples/case/proportion/demo/group-drill-down.tsx

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore

fix: 趋势分析表 conditions 增加容错能力

---

packages/s2-core/__tests__/unit/utils/sort-action-spec.tsx
packages/s2-core/src/utils/sort-action.ts

🐛 Bugfix
`sortByMeasures` 排序时，本质会依赖 `排序参考数据`，只有数据取正确了，才能排序正确：
- 之前：使用 getMultiData 的 isTotals 参数取（数据不太对）
- 现在：使用 getMultiData 按 query 先取数据，后根据排序字段和排序模式（按汇总值或按明细值）过滤出符合的 `排序参考数据`
本次修改主要涉及 `排序参考数据` 的取数逻辑，即 `getSortByMeasureValues@sort-action.ts`
下面介绍 `sortByMeasures` 的几种情况，以及对应的正确的 `排序参考数据`
> 以普通交叉表为例
> rows：province、city
> cols：type、subType
> values：price
> 值在列头
`sortByMeasures` 排序可以分成以下两类排序
- 按明细数据排序：
- `sortByMeasure` 取 `price`
- `sortFieldId` 为维度最后一个字段（如行维度 city）
- `query` 能限定到最后一级明细数据（如含列维度 type、subType）【见示例1】
- 按汇总数据排序：
- `sortByMeasure` 取 `TOTAL_VALUE`
- `sortFieldId` 可以取任意字段（province 或 city）
- 取 province 时，`query` 可限定  type、subType 所有维值或部门维值，此时是以 province 的行小计交叉格为准【见示例2】
- 取 city 时，`query` 只可限定到部分列维度，如 type，此时以列小计交叉格数据为准【见示例3】
```
{
sortFieldId: 'city',
sortMethod: 'desc', …
```

fix: 维度按指标汇总值排序时结果错误

---

packages/s2-react/__tests__/data/strategy-data.ts
packages/s2-react/src/components/sheets/strategy-sheet/index.tsx

🐛 Bugfix
https://github.com/antvis/S2/pull/1552  手误写了一个 mock 数据

fix(strategysheet): 修复趋势分析表错误的标题

---

packages/s2-react/__tests__/unit/components/switcher/util-spec.ts
packages/s2-react/src/components/switcher/constant.ts
packages/s2-react/src/components/switcher/content/index.tsx
packages/s2-react/src/components/switcher/dimension/index.tsx
packages/s2-react/src/components/switcher/header.tsx
packages/s2-react/src/components/switcher/index.tsx
packages/s2-react/src/components/switcher/util.ts
packages/s2-vue/src/interface.ts
s2-site/docs/api/components/switcher.zh.md
s2-site/examples/react-component/switcher/demo/pivot-with-children.tsx

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore
| 开启 | 关闭 |
|    ![2022-07-13 15 36 53](https://user-images.githubusercontent.com/17964556/178677896-7c378b98-d569-4835-ad62-2a7115fe6b6f.gif)   |  ![2022-07-13 15 37 34](https://user-images.githubusercontent.com/17964556/178677910-4444b7ac-b60b-4137-88ef-24f19fc17737.gif)|

feat: 增加允许/禁用指标在行列维度中相互切换的能力

---

packages/s2-core/__tests__/unit/utils/merge-cell-spec.ts
packages/s2-core/src/cell/merged-cell.ts
packages/s2-core/src/common/interface/basic.ts
packages/s2-core/src/utils/interaction/merge-cell.ts

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore
| ![](https://user-images.githubusercontent.com/17964556/179203359-c406c45f-d046-40f9-8160-8e64de4008ed.gif )  |  ![2022-07-18 16 09 08](https://user-images.githubusercontent.com/17964556/179471462-974d93ba-ba65-4da4-94f6-fe17e4740085.gif) |

fix: 修复合并单元格临界情况被错误移除的问题

---

s2-site/examples/react-component/sheet/demo/meta.json
s2-site/examples/react-component/sheet/demo/strategy-mini-chart.tsx

docs: 增加 mini 图 demo

---

packages/s2-core/__tests__/unit/utils/sort-action-spec.tsx
packages/s2-core/src/utils/sort-action.ts

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore
fix:  修复存在 0 时，排序错误的问题
|<img width="648" alt="image" src="https://user-images.githubusercontent.com/20497176/182558056-aa3c9d06-6ca4-4d53-8131-3de92e3886ed.png">|<img width="633" alt="image" src="https://user-images.githubusercontent.com/20497176/182554403-ac28c6d7-26c5-4235-8a53-16a0f09180f8.png">|
|<img width="643" alt="image" src="https://user-images.githubusercontent.com/20497176/182558132-348e3f4a-788c-499a-9eef-e3b5d7fbda10.png"> |<img width="633" alt="image" src="https://user-images.githubusercontent.com/20497176/182554493-82cc1ab6-12be-460b-b864-4dc12e6f7c10.png">|

fix:  修复存在 0 时，数值为 number 时，排序错误的问题

---

.github/workflows/pr-auto-assign-reviewer.yml
packages/s2-core/__tests__/spreadsheet/spread-sheet-resize-spec.ts
packages/s2-core/__tests__/unit/interaction/row-column-resize-spec.ts
packages/s2-core/src/cell/col-cell.ts
packages/s2-core/src/common/interface/resize.ts
packages/s2-core/src/interaction/row-column-resize.ts
packages/s2-react/playground/index.tsx
s2-site/docs/api/components/sheet-component.zh.md
s2-site/docs/common/interaction.zh.md

✨ Feature
🎨 Enhance
🐛 Bugfix
1. resize 相关 hook 透出 `resizedWidth/resizedHeight` 参数, 保持统一 close #1634 
2. resize 相关 hook 类型定义/文档修正, `resizeInfo` => `info` close #1632 
3. 列头隐藏时, 不应该绘制列头水平热区 ref #1603 
| ![image](https://user-images.githubusercontent.com/21015895/182515428-30eec5d5-ef56-4f3e-bf88-24b18a56dba7.png) | ![image](https://user-images.githubusercontent.com/21015895/182515320-7df3cdd4-e96d-487a-8a7f-eeaee767d16e.png) |
| ![image](https://user-images.githubusercontent.com/21015895/182515745-5db257b2-a54a-4239-83b3-3bdd4376886f.png)|  ![image](https://user-images.githubusercontent.com/21015895/182515516-c19d2294-2708-4eff-86bc-d9e608c5eebe.png) |

feat(interaction): 宽高调整事件透出 resizedWidth/resizedHeight, 修复错误类型定义

---

packages/s2-vue/playground/App.vue
packages/s2-vue/src/components/sheets/pivot-sheet.vue
packages/s2-vue/src/utils/initPropAndEmits.ts

🐛 Bugfix
vue pivot模式下cell点击事件无法触发

fix: 修复pivot模式 cell点击事件无法触发BUG

---

packages/s2-core/__tests__/bugs/issue-1624-spec.ts
packages/s2-core/src/cell/base-cell.ts

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore
| ![image](https://user-images.githubusercontent.com/17964556/183334522-828d0398-87e3-4b66-85d4-956c57cd777e.png)      | ![image](https://user-images.githubusercontent.com/17964556/183334453-10e5e9dc-9729-46ee-b5ca-3a3317b2a5d0.png)  |

fix: 修复选中态的描边宽度样式问题

---

.github/workflows/pr-auto-assign-reviewer.yml

chore: update the reviewers

---

packages/s2-core/__tests__/unit/interaction/base-interaction/click/data-cell-click-spec.ts
packages/s2-core/src/interaction/base-interaction/click/data-cell-click.ts

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore

fix: 双击时不取消datacell 选中态

---

.github/workflows/lint.yml
.github/workflows/test.yml

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore

chore: 优化lint, test action，取消上一次的action运行，减少pending时间

---

.github/ISSUE_TEMPLATE/ask-for-question.md
.github/workflows/auto-release.yml
.github/workflows/release-success.yml
.github/workflows/site-build-notify.yml

chore: 优化 CI/模板 的一些文案和提示

---

packages/s2-core/__tests__/spreadsheet/spread-sheet-collapse-spec.ts
packages/s2-core/src/common/interface/basic.ts
packages/s2-core/src/facet/layout/build-row-tree-hierarchy.ts
packages/s2-core/src/sheet-type/pivot-sheet.ts
packages/s2-react/playground/index.tsx
s2-site/docs/common/style.zh.md
s2-site/examples/interaction/advanced/demo/meta.json
s2-site/examples/interaction/advanced/demo/row-expand-depth.ts

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore

feat: 在树状模式下，增加默认展开层级的配置

---

packages/s2-core/src/facet/table-facet.ts

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore

fix: tablefacet销毁时off事件

---

.husky/common.sh
.husky/pre-commit
.husky/pre-push
package.json
packages/s2-react/package.json
scripts/validate-deps.js

🔧 Chore
确保版本号一致
非发布分支
版本未修改
验证通过

chore: 增加 alpha/beta 版本发布 devDeps 校验

---

s2-site/package.json

chore: 修复官网构建不压缩问题

---

packages/s2-react/__tests__/unit/hooks/usePagination-spec.ts
packages/s2-react/playground/index.less
packages/s2-react/src/components/pagination/index.tsx
packages/s2-react/src/components/sheets/base-sheet/index.tsx
packages/s2-react/src/hooks/usePagination.ts

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore

fix: 修复 pagination 组件属性透传问题, 简化 usePagination 逻辑

---

packages/s2-core/src/ui/tooltip/index.ts
packages/s2-react/src/components/index.ts
packages/s2-vue/src/components/index.ts

feat: 导出组件层CustomTooltip类

---

packages/s2-react/src/hooks/usePagination.ts

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore
关联pr:https://github.com/antvis/S2/pull/1722

fix: 修复闭包导致的pagination被错误重置的问题

---

s2-site/docs/api/components/sheet-component.zh.md
s2-site/docs/api/general/S2Theme.zh.md

🔧 Chore
组件层 S2Options => SheetComponentOptions

docs: 修复组件 options 类型文档错误

---

README.en-US.md
README.md

feat: readme文件增加QQ交流群二维码

---

packages/s2-core/src/cell/merged-cell.ts

fix: 修复合并单元格条件格式不生效问题 close #1751

---

packages/s2-core/__tests__/unit/utils/export/copy-spec.ts
packages/s2-core/src/interaction/brush-selection/col-brush-selection.ts
packages/s2-core/src/interaction/brush-selection/row-brush-selection.ts
packages/s2-core/src/utils/export/copy.ts
s2-site/docs/manual/basic/analysis/export.zh.md
s2-site/examples/interaction/basic/demo/brush-header.ts
s2-site/examples/interaction/basic/demo/meta.json

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore
在做复制的时候，发现了圈选还存在一个问题：  #1740 
后面再修复吧。
| 复制行头 | 复制列头 |
| ![复制行头](https://gw.alipayobjects.com/zos/antfincdn/XO1VOY%26kZ/1da2946a-5396-41f1-8b59-2e482c8127a5.png)| ![复制列头](https://gw.alipayobjects.com/zos/antfincdn/j8nJMIDrj/86a234b0-ce16-4a64-b06c-e8c5e631b597.png) |

feat: 圈选复制行列头功能

---

s2-site/package.json
s2-site/yarn.lock

chore: 更新官网s2版本

---

s2-site/docs/manual/basic/analysis/drill-down.en.md
s2-site/docs/manual/basic/analysis/drill-down.zh.md

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore
docs: 使用文档补充下钻组件
#1502

docs: 使用文档补充下钻组件

---

.github/workflows/lint.yml
.github/workflows/release-success.yml
.github/workflows/test.yml

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore

chore: 只在pr时运行 lint 和 test，减少时间开销

---

s2-site/README.md

doc: 更新  s2-site Readme

---

packages/s2-core/__tests__/unit/utils/export/copy-spec.ts
packages/s2-core/src/utils/export/copy.ts

fix: table formatter with header selected

---

packages/s2-core/src/utils/export/index.ts

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore

fix: clipbardItem不存在时不报错

---

packages/s2-core/src/utils/export/index.ts

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore

fix: 将依赖检查移动到外层

---

packages/s2-core/src/cell/data-cell.ts

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore

fix: 明细表奇数行背景色不生效修复

---

packages/s2-core/__tests__/bugs/issue-1624-spec.ts
packages/s2-core/__tests__/spreadsheet/spread-sheet-totals-spec.ts
packages/s2-core/src/cell/data-cell.ts

refactor: 优化树状行小记隐藏单元格绘制逻辑

---

packages/s2-core/package.json
packages/s2-react/package.json

chore(release): bump version

---

packages/s2-core/__tests__/spreadsheet/interaction-brush-selection-scroll-spec.ts
packages/s2-core/__tests__/spreadsheet/table-sheet-spec.ts
packages/s2-core/src/cell/base-cell.ts
packages/s2-core/src/common/constant/options.ts
packages/s2-core/src/common/interface/basic.ts
packages/s2-core/src/common/interface/s2Options.ts
packages/s2-core/src/utils/is-mobile.ts
packages/s2-core/src/utils/merge.ts
packages/s2-react/src/common/constant/options.ts
packages/s2-react/src/components/sheets/mobile-sheet/index.tsx
packages/s2-react/src/components/tooltip/custom-tooltip.tsx
packages/s2-shared/__tests__/utils/options-spec.ts
packages/s2-shared/src/utils/options.ts

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore
|   <img width="408" alt="image" src="https://user-images.githubusercontent.com/20497176/196371683-8e2193f0-5c9e-4ef1-8ef4-b183abae153b.png">|   <img width="411" alt="image" src="https://user-images.githubusercontent.com/20497176/196371333-2dbe8dc8-b84b-4c72-a7b6-3e2d3df8cbf3.png">     |
|<img width="356" alt="image" src="https://user-images.githubusercontent.com/20497176/196611924-97838543-c579-484b-b1d5-fbd7db9f6208.png"> | <img width="433" alt="image" src="https://user-images.githubusercontent.com/20497176/196611684-2176dd6c-3351-4a6c-b991-175c0aa2d4f9.png">|
|<img width="361" alt="image" src="https://user-images.githubusercontent.com/20497176/196611998-65a62620-76ba-4280-b589-7ec67c87c143.png" …

feat: 添加 mobile 组件和 mobile 模式下专用的 option 配置

---

s2-site/docs/api/general/S2Theme.zh.md

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore

fix: 修复文档 SplitLine 参数错误 close #1836

---

packages/s2-core/package.json
packages/s2-react/package.json
packages/s2-vue/package.json

Revert "chore(release): 🔖@antv/s2@1.32.0 @antv/s2-react@1.29.0 @antv/s2-vue@1…"

---

s2-site/docs/manual/basic/analysis/editable-mode.en.md
s2-site/docs/manual/basic/analysis/editable-mode.zh.md
s2-site/examples/case/data-preview/demo/excel.tsx
s2-site/examples/react-component/sheet/demo/editable.tsx
s2-site/examples/react-component/sheet/demo/meta.json
s2-site/package.json
s2-site/yarn.lock

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore

docs: 编辑表文档和示例添加

---

packages/s2-react/__tests__/unit/components/sheets/mobile-sheet/__snapshots__/index-spec.tsx.snap
packages/s2-react/__tests__/unit/components/sheets/mobile-sheet/index-spec.tsx
packages/s2-react/__tests__/unit/components/sheets/strategy-sheet/custom-tooltip/__snapshots__/index-spec.tsx.snap
packages/s2-shared/__tests__/utils/options-spec.ts
packages/s2-vue/src/components/sheets/base-sheet.vue

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore

test: 修复单测错误

---

README.md

docs: 更新README.md添加洞察分析

---

.github/workflows/auto-release.yml
.github/workflows/lint.yml
.github/workflows/test.yml
packages/s2-core/__tests__/spreadsheet/theme-spec.ts
packages/s2-core/src/theme/index.ts

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore
| <img width="1512" alt="image" src="https://user-images.githubusercontent.com/20497176/199719501-43bbc267-ea1c-468d-af23-0d79c311ae1d.png"> |  <img width="1369" alt="image" src="https://user-images.githubusercontent.com/20497176/199719659-a7edcdd9-5959-4645-8b88-f5314c4402d5.png"> |
| <img width="693" alt="image" src="https://user-images.githubusercontent.com/20497176/199721417-e01d278a-a3c4-47d9-af57-3f4fd3793078.png"> | <img width="537" alt="image" src="https://user-images.githubusercontent.com/20497176/199721488-8e1b0afd-c367-4ca6-9de1-698e1e20194e.png"> |

fix: 修复 mergedCell 缺失theme 导致的报错

---

README.md

chore: 更新README

---

s2-site/examples/data/compare.json

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore

docs: 更新master分支表格性能对比数据

---

s2-site/examples/custom/custom-cell/demo/custom-specified-cell.ts
s2-site/examples/custom/custom-cell/demo/data-cell.ts
s2-site/examples/custom/custom-cell/demo/meta.json

docs: 新增自定义特定单元格示例

---

s2-site/docs/api/general/S2Event.zh.md
s2-site/docs/api/general/S2Theme.zh.md
s2-site/examples/theme/custom/demo/custom-schema.ts
s2-site/examples/theme/custom/demo/custom-transparent-background.ts
s2-site/examples/theme/custom/demo/meta.json

🔧 Chore
1. 新增透明主题配置示例
2. 修复暗黑主题示例
| ![image](https://user-images.githubusercontent.com/21015895/200526894-2bb6d4b7-b35d-4c50-a457-4d83b8bb3f73.png) |  ![image](https://user-images.githubusercontent.com/21015895/200526857-429ee849-450b-4f5c-9d6a-28e12494ce3b.png) |

docs(theme): 新增透明背景色主题配置示例

---

README.en-US.md
README.md

docs: 更新README，增加数据洞察

---

s2-site/package.json

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore

update: package.json

---

packages/s2-react/__tests__/data/mock-dataset.json
packages/s2-react/playground/config.ts
packages/s2-react/playground/index.tsx

chore: 修复明细表多列头下无数据展示

---

s2-site/docs/api/general/S2Theme.en.md
s2-site/docs/common/mini-chart.en.md
s2-site/docs/manual/basic/analysis/strategy.en.md

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore

feat: 补充英文文档

---

s2-site/.dumirc.ts

🐛 Bugfix
| ❌      |  ![image](https://user-images.githubusercontent.com/7856674/203286264-7991213b-0d31-4d1c-a347-56df820c29ca.png)   |

fix: playground not work

---

s2-site/.gitignore
s2-site/examples/react-component/sheet/demo/editable.tsx

fix: 修复编辑表格数据获取问题

---

.gitignore
s2-site/public/site.css

style: 更新官网首页样式

---

.github/workflows/issues-similarity-analysis.yml
.github/workflows/release-notify.yml
.github/workflows/release-success.yml
.github/workflows/site-build-notify.yml
.github/workflows/sync-notify.yml
.releaserc.base.js
package.json
packages/s2-core/README.en-US.md
packages/s2-core/README.md
packages/s2-core/package.json
packages/s2-react/README.md
packages/s2-react/package.json
packages/s2-react/playground/index.tsx
packages/s2-vue/README.md
packages/s2-vue/package.json
s2-site/examples/interaction/advanced/demo/scroll-loop.ts
s2-site/examples/layout/custom/demo/custom-pivot-size.ts
s2-site/examples/layout/custom/demo/custom-row-col-cell-width.ts
s2-site/examples/layout/custom/demo/custom-table-size.ts
s2-site/examples/layout/custom/demo/custom-tree-row-width.ts
s2-site/examples/theme/custom/demo/custom-transparent-background.ts
s2-site/package.json

🔧 Chore
1. 增加自动发布的 dist-tag (默认使用 name, 显示指定更容易懂)
2. 修复部分错误官网链接
3. 简化发布完成后的同步流程

chore: 优化自动发布 CI

---

packages/s2-core/CHANGELOG.md
packages/s2-core/package.json
packages/s2-react/CHANGELOG.md
packages/s2-react/package.json
packages/s2-vue/CHANGELOG.md
packages/s2-vue/package.json

🤖 由 [[🚀 After the release is successful](https://github.com/antvis/S2/blob/master/.github/workflows/release-success.yml)] action 自动创建.

chore: 🤖 更新 changelog 文件

---

packages/s2-core/src/data-set/table-data-set.ts

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore
数据兼容 rowData 可能是undefined

fix(dataset): 修复数据undefined情况

---

packages/s2-core/__tests__/spreadsheet/scroll-spec.ts
packages/s2-core/src/facet/base-facet.ts

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore
shift+按键支持横向滚动

feat: shift+按键支持横向滚动

---

s2-site/docs/common/contact-us.en.md
s2-site/docs/common/contact-us.zh.md
s2-site/docs/manual/faq.en.md
s2-site/docs/manual/faq.zh.md
s2-site/docs/manual/introduction.en.md
s2-site/docs/manual/introduction.zh.md
s2-site/package.json

docs: 替换过期二维码 & CNAME

---

s2-site/package.json

chore: 官网部署修复

---

s2-site/docs/api/general/S2DataConfig.zh.md

🔧 Chore
ColumnNode属性是key，官网上写成了name。

docs：修正ColumnNode文档属性

---

s2-site/docs/api/general/S2DataConfig.zh.md
s2-site/docs/common/conditions.zh.md
s2-site/docs/common/mini-chart.zh.md
s2-site/docs/common/sort-param.zh.md
s2-site/docs/manual/basic/analysis/strategy.zh.md
s2-site/docs/manual/faq.zh.md

docs: 修复错误 API 文档格式

---

packages/s2-core/src/cell/row-cell.ts
packages/s2-core/src/cell/table-data-cell.ts
packages/s2-core/src/common/interface/interaction.ts
packages/s2-core/src/facet/header/row.ts
packages/s2-core/src/utils/interaction/index.ts
packages/s2-core/src/utils/interaction/link-field.ts
s2-site/docs/common/interaction.zh.md

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore

feat: 增加 linkFields 参数传入类型

---

packages/s2-vue/src/hooks/useResize.ts

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore
深度观察s2Ref会有一个g-lite的错误，不知道啥原因，这里好像也不需要做深度观察

fix: 解决S2.0next版本Vue报错bug

---

packages/s2-core/package.json
yarn.lock

由于目前 s2 和 g2 打包的 g 版本不一样导致冲突，暂时的解法先保持版本一致
更多讨论见 https://github.com/antvis/G/issues/1255
✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore

fix: 暂时修复g版本冲突问题

---

s2-site/examples/interaction/advanced/demo/custom-tree-link-jump.ts
s2-site/examples/interaction/advanced/demo/meta.json

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore

docs: 官网自定义目录树链接跳转 demo

---

packages/s2-vue/package.json
packages/s2-vue/src/hooks/useResize.ts
yarn.lock

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore

chore: 更新 vue-tsc 版本，保持和 volar 一致

---

packages/s2-core/src/common/icons/gui-icon.ts

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore
Gui 异步加载完成后，可能其依附的 Parent Cell 已经destroyed, 此时再往 Parent Cell 添加 shape 会报错：

fix: gui icon 加载完成后，增加检测步骤，避免无意义的渲染 warning

---

s2-site/examples/basic/table/demo/meta.json
s2-site/examples/basic/table/demo/table-column-group.ts

docs: 更新列分组demo配图

---

packages/s2-core/src/common/constant/events/origin.ts
packages/s2-core/src/interaction/event-controller.ts
packages/s2-core/src/sheet-type/spread-sheet.ts
packages/s2-react/playground/components/Mobile.tsx
packages/s2-react/playground/config.ts
packages/s2-react/playground/index.tsx

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore
|![S2移动端-抽屉bug](https://user-images.githubusercontent.com/20497176/209076399-dc06ec44-6ecd-4f2f-91f2-5fec115f2869.gif) | ![S2移动端-抽屉right](https://user-images.githubusercontent.com/20497176/209076435-cb2bf623-f564-4bd2-b14a-876e60c44156.gif) |
- [] Add or update relevant docs.

chore: 添加移动端demo

---

packages/s2-core/src/utils/g-mini-charts.ts

✨ Feature
子弹图为空时使用placeholder占位
|    ![CleanShot 2022-12-22 at 14 32 26@2x](https://user-images.githubusercontent.com/6716092/209071983-4782ef8c-b16b-42e1-93a3-a7d1b42b563f.png)   |   ![](https://user-images.githubusercontent.com/6716092/209071873-aaa61d75-873f-445b-9c31-59e5a7be6114.png)  |

feat: 子弹图为空时使用placeholder占位

---

s2-site/.dumirc.ts

🔧 Chore
- [爬虫管理后台](https://crawler.algolia.com/admin/crawlers/364eb79c-e12b-4ec6-b9bb-ca3f0b6c9e72/configuration/edit)

docs: 替换antgroup主站

---

.github/workflows/disscustion.yml
.github/workflows/issue-opend.yml
.github/workflows/pr-auto-assign-reviewer.yml
.github/workflows/pr-auto-set-next-label.yml
s2-site/docs/api/general/S2Theme.zh.md

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore

chore: 增加 issue 格式检测 & 讨论区通知 action

---

s2-site/.dumi/pages/playground.zh.tsx
s2-site/playground/config-panel/config-component/dragger-upload/index.less
s2-site/playground/config-panel/config-component/dragger-upload/index.tsx
s2-site/playground/config-panel/config-component/radio/index.tsx
s2-site/playground/config-panel/config-component/select/index.tsx
s2-site/playground/config-panel/config-token/index.ts
s2-site/playground/layouts/index.less
s2-site/playground/sheet-component/index.less
s2-site/playground/sheet-component/index.tsx

✨ Feature
✅ playground 支持导入 JSON 数据
🎨 Enhance
🐛 Bugfix
🔧 Chore

feat: playground 支持导入 JSON 数据

---

.eslintrc.js
packages/s2-core/__tests__/bugs/issue-1668-spec.ts
packages/s2-core/__tests__/spreadsheet/custom-grid-spec.ts
packages/s2-core/__tests__/spreadsheet/custom-tree-spec.ts
packages/s2-core/__tests__/spreadsheet/spread-sheet-totals-spec.ts
packages/s2-core/__tests__/unit/data-set/pivot-data-set-row-value-spec.ts
packages/s2-core/__tests__/unit/data-set/pivot-data-set-spec.ts
packages/s2-core/__tests__/unit/data-set/pivot-data-set-total-spec.ts
packages/s2-core/__tests__/unit/dataset/table-dataset-spec.ts
packages/s2-core/__tests__/unit/utils/dataset/pivot-data-set-spec.ts
packages/s2-core/__tests__/unit/utils/text-spec.ts
packages/s2-core/src/cell/data-cell.ts
packages/s2-core/src/cell/header-cell.ts
packages/s2-core/src/common/interface/basic.ts
packages/s2-core/src/common/interface/theme.ts
packages/s2-core/src/data-set/base-data-set.ts
packages/s2-core/src/data-set/table-data-set.ts
packages/s2-core/src/facet/layout/node.ts
packages/s2-core/src/utils/export/index.ts
packages/s2-react/__tests__/data/strategy-data.ts
packages/s2-react/__tests__/spreadsheet/layout-hooks-spec.tsx
packages/s2-react/__tests__/spreadsheet/table-sheet-spec.tsx
packages/s2-react/src/components/sheets/strategy-sheet/custom-tooltip/custom-row-tooltip.tsx
packages/s2-vue/src/components/sheets/index.vue
packages/s2-vue/src/components/sheets/pivot-sheet.vue
tsconfig.base.json

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore
在 Node, 或者 Store里面都有索引属性`[key:string]:any`这样的行了，那么在属性改动后，类型判断都能通过，容易导致漏掉一些改动，通过 noPropertyAccessFromIndexSignature 能避免一些疏漏，对类型有更强的保护：https://www.typescriptlang.org/tsconfig#noPropertyAccessFromIndexSignature

chore: 开启 noPropertyAccessFromIndexSignature 配置

---

s2-site/docs/manual/faq.zh.md

close https://github.com/antvis/S2/issues/2070
✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore

docs: update FAQ link error

---

s2-site/examples/interaction/basic/demo/frozen.ts

🔧 Chore
| ❌ ![image](https://user-images.githubusercontent.com/10885578/220065902-7c37e544-46ae-4afc-9ff6-a3bc724f7cd5.png)| ✅   ![image](https://user-images.githubusercontent.com/10885578/220065649-6043841a-c77a-49e2-b2ea-4b09945e928f.png)  |

docs: 修复行列冻结demo

---

s2-site/docs/manual/basic/theme.zh.md

🐛 Bugfix
主题章节 schema key 对照表错误

docs: 更新主题章节文档

---

packages/s2-core/__tests__/unit/utils/export/copy-spec.ts
packages/s2-core/src/utils/export/copy.ts

目前复制仅支持内置的transformer格式化，PR添加自定义格式化function支持。使用方式可参考单测用例
✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore
目前复制仅支持内置的transformer格式化，PR添加自定义格式化function支持。使用方式可参考单测用例

feat: 复制支持自定义transformer

---

.github/workflows/site-build-notify.yml
.gitignore
.npmrc
.yarnrc
s2-site/.gitignore
s2-site/.npmrc
s2-site/.yarnrc
s2-site/README.md
s2-site/package.json
s2-site/public/site.css

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore
1. 官网增加 lock, 避免 dumi/umi 升级带来的一些折磨的问题
2. 统一镜像源, 老的 taobao 镜像已经废弃了 https://zhuanlan.zhihu.com/p/465424728?spm=a2c6h.24755359.0.0.6d446e51l9GMkK
3. 文档代码块和图片增加一点间距, 美观一点
| ![image](https://user-images.githubusercontent.com/21015895/221513045-3c590e0f-dfbb-4356-96d0-cdd0fada3acb.png)| ![image](https://user-images.githubusercontent.com/21015895/221513081-42704432-177a-42ce-ab39-4a203b4b8385.png) |

docs: 修复官网图表示例无法运行

---

.github/workflows/auto-add-to-project.yml

🔧 Chore
迁移 classic project 到 github 新的project, action 做相应设配：
| 看板视图| issue 归类视图|
| ---- |----|
|![image](https://user-images.githubusercontent.com/17964556/222050511-e5dbdb76-3cd7-4365-8257-24c8f51bc3e2.png)|![image](https://user-images.githubusercontent.com/17964556/222050561-47664c25-9a61-45ab-a699-f2b3445412fc.png)|

chore: 更新 project action 配置

---

packages/s2-vue/playground/App.vue

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore

fix:  修复 vue playground 启动失败

---

.github/workflows/auto-add-to-project.yml

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore

chore: 修复 typo action 错误

---

.github/workflows/disscustion.yml

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore
修复链接缺少 双引号, 导致无法推送的问题

chore: 修复 disscustion action 执行失败

---

packages/s2-core/src/common/interface/basic.ts
packages/s2-core/src/common/interface/s2Options.ts
packages/s2-core/src/utils/interaction/merge-cell.ts
s2-site/docs/api/general/S2Options.zh.md
s2-site/docs/manual/advanced/interaction/merge-cell.en.md
s2-site/docs/manual/advanced/interaction/merge-cell.zh.md
s2-site/examples/custom/custom-cell/demo/custom-merged-cell.ts
s2-site/examples/custom/custom-cell/demo/meta.json

✨ Feature
`merged-cell` 继承于 `data-cell`，但之前未开放自定义。
目前开放配置项供开发者自定义，使用方法类似其他自定义单元格。
自定义背景色为红色
close #2110

feat: 增加自定义合并单元格能力

---

.github/workflows/auto-release.yml
.github/workflows/prerelease-notify.yml
.github/workflows/release-notify.yml
.github/workflows/release-success.yml
.github/workflows/site-build-notify.yml
.github/workflows/sync-notify.yml
.npmrc

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore
1. 本地的 .npmrc 修改为官方源, 避免 npm publish 的时候 401
2. pre release 通知到内部群
3. 调整一些文案和图片

chore: 修复镜像源问题导致自动发布失败

---

.github/workflows/issue-labeled.yml

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore

chore: 修改 reject label 为 won't support

---

.github/workflows/issue-labeled.yml

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore

chore: update issue-labeled.yml

---

packages/s2-react/src/components/switcher/index.less

✨ Feature
移除 important 关键词，开放自定义
> 无变化
|    ![CleanShot 2023-03-30 at 10 36 12@2x](https://user-images.githubusercontent.com/6716092/228713641-244ba570-7a94-4b1e-918b-edbbccce3326.png)      |  ![CleanShot 2023-03-30 at 10 35 10@2x](https://user-images.githubusercontent.com/6716092/228713521-d3b28cff-0b5d-4f19-b4b3-b84e468bfed8.png)     |

feat: 移除switcher按钮important样式

---

s2-site/docs/manual/advanced/get-cell-data.zh.md

docs: 增加角头和明细表数据获取文档 close #2141

---

s2-site/docs/api/basic-class/interaction.zh.md

获取当前单元格的所以子节点 -》获取当前单元格的所有子节点
✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore

docs: fix doc text typo bug close #2182

---

packages/s2-core/__tests__/spreadsheet/__snapshots__/custom-grid-spec.ts.snap
packages/s2-core/__tests__/spreadsheet/custom-grid-spec.ts
packages/s2-core/src/facet/base-facet.ts
packages/s2-core/src/facet/pivot-facet.ts
packages/s2-core/src/facet/table-facet.ts
packages/s2-react/playground/components/CustomGrid.tsx

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore
布局采样的节点都是第一列的, 如果自定义列头第一列节点数量小于其他列时, 会导致单元格高度计算错误, 从而影响角头的显示
> 预期是 红色数字, 实际是绿色数字
| ![image](https://user-images.githubusercontent.com/21015895/233956565-a099a728-346a-4cd2-bd23-1990d08958ec.png) | ![image](https://user-images.githubusercontent.com/21015895/233956501-99212058-a004-4df5-a1b2-2e2227033f0b.png) |

fix(layout): 修复自定义列头采样错误导致行角头不显示 close #2117

---

packages/s2-core/__tests__/bugs/issue-1781-spec.ts
packages/s2-core/src/cell/data-cell.ts

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore
| ![image](https://user-images.githubusercontent.com/17964556/234242956-8eeaf934-fe9d-4672-ad7e-d9c3c8e57948.png)      | ![2023-04-25 17 47 51](https://user-images.githubusercontent.com/17964556/234240080-2ddc91ef-7ed0-4bbe-a85c-dd9a769a2f2a.gif)    |

fix: 修复 meta name 同名时，hoverFocus 出错的问题

---

.github/workflows/test.yml
s2-site/examples/custom/custom-cell/demo/data-cell.ts

docs: 更新自定义datacell示例

---

packages/s2-core/__tests__/unit/cell/header-cell-spec.ts
packages/s2-core/src/cell/header-cell.ts

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore
行列头维度存在 formatter 时，不应该对总计小计的单元格做处理
| ![image](https://github.com/antvis/S2/assets/17964556/6c0c2f7c-71f5-4f52-bd76-55674caffaf0)      | ![image](https://github.com/antvis/S2/assets/17964556/d6a94c20-b1ce-422d-a680-c199d654d98b)     |

fix: 修复总计小计被意外 format 的问题

---

packages/s2-core/__tests__/spreadsheet/scroll-spec.ts
packages/s2-core/src/facet/base-facet.ts

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore
only do compatibility of shit + scroll on Windows

fix(core): only do compatibility of shift + scroll on Windows

---

packages/s2-core/__tests__/spreadsheet/data-link-spec.ts
packages/s2-core/src/cell/data-cell.ts

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore
在 https://github.com/antvis/S2/pull/2219 中顺带修改了 interactiveBorder 顺序，但是该图层本身不应该捕获事件：

fix: 修复 dataCell linkField 不能点击的问题

---

s2-site/docs/api/general/S2Theme.en.md
s2-site/docs/api/general/S2Theme.zh.md

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore

docs: type InteractionStateTheme

---

packages/s2-core/__tests__/unit/utils/export/export-spec.ts
packages/s2-core/src/utils/export/copy/pivot-data-cell-copy.ts
packages/s2-core/src/utils/export/copy/table-copy.ts

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore
|<img width="481" alt="image" src="https://github.com/antvis/S2/assets/20497176/9fb0da35-fbd6-4ebc-937c-188d5c03218b"> | <img width="536" alt="image" src="https://github.com/antvis/S2/assets/20497176/f6fc5fd5-a534-435a-a9bf-4a0fdb02bfeb">|
非常感谢  @xiaochong44  这位同学，发现问题，并提出相应的解决方案

fix: 修复导出数据分隔符有误的问题

---

s2-site/docs/api/general/S2Event.en.md
s2-site/docs/api/general/S2Event.zh.md

🔧 Chore
Missing docs completion
close #2246

docs: update DATA_CELL_SELECT_MOVE event

---

s2-site/docs/manual/advanced/interaction/basic.zh.md
s2-site/docs/manual/faq.zh.md
s2-site/examples/interaction/basic/demo/hover.ts
s2-site/examples/react-component/tooltip/demo/custom-click-show-tooltip.tsx
s2-site/examples/react-component/tooltip/demo/custom-content.tsx

🔧 Chore
增加交互和 tooltip 的文档示例和 FAQ

docs: 更新 FAQ 和 文档示例

---

packages/s2-react/src/components/sheets/editable-sheet/drag-copy/drag-copy-mask.tsx
packages/s2-react/src/components/sheets/editable-sheet/drag-copy/index.tsx
packages/s2-react/src/components/sheets/editable-sheet/edit-cell/index.tsx
packages/s2-react/src/components/sheets/editable-sheet/index.tsx

🎨 Enhance
Prevent unnecessary react re-render based on [react-re-render-guide](https://www.developerway.com/posts/react-re-renders-guide).

perf(react): 防止不必要的重新渲染

---

packages/s2-core/__tests__/unit/utils/export/copy-spec.ts
packages/s2-core/src/utils/export/copy.ts

🐛 Bugfix
🔧 Chore
当点击行头cell复制时，使用了Object.keys(data)来取值导致复制出的顺序与展示顺序不一致。

fix: 修复复制整行时错位

---

packages/s2-core/src/common/interface/condition.ts

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore
[https://s2.antv.antgroup.com/api/general/s2-options#conditions](https://s2.antv.antgroup.com/api/general/s2-options#conditions)文档中mapping支持返回undefined与null表示当前字段不现实字段标记样式
无改动，仅修改类型

fix: condition.mapping 返回值与文档不符合，允许返回undefined与null

---

packages/s2-core/__tests__/spreadsheet/scroll-spec.ts
packages/s2-core/src/facet/base-facet.ts

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore
scrollWithAnimation 增加 try catch，在运行报错时依然可以结束 timer 防止死循环
| ❌    | ✅     |
|<img width="1728" alt="截屏2023-08-30 21 14 58" src="https://github.com/antvis/S2/assets/48037246/04de738a-a882-416c-9aad-c9cd2b234a4f"> | <img width="1728" alt="截屏2023-08-30 21 23 48" src="https://github.com/antvis/S2/assets/48037246/aaf6bfdb-c163-44c5-951b-4445a519a402">

fix(scroll): 修复调用 scrollWithAnimation 后 unmount 表格导致频繁报错

---

packages/s2-core/__tests__/unit/utils/text-spec.ts
packages/s2-core/src/utils/text.ts
packages/s2-react/src/components/sheets/strategy-sheet/custom-tooltip/custom-data-tooltip.tsx

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore
feat: 趋势分析表无波动的字体不用红绿色显示
| ❌  ![image](https://github.com/antvis/S2/assets/9548248/356f2502-da23-4f0b-90ec-1b9f1eb7bafc)    | ✅ ![image](https://github.com/antvis/S2/assets/9548248/ba3a347f-13bb-4228-99c3-3c0a5daa213d)    |

feat: 趋势分析表无波动的字体不用红绿色显示

---

packages/s2-core/src/data-set/table-data-set.ts

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore
将每个filterParam的过滤复杂度从 O(n*len(filteredValues)) 下降为 O(n)
#2324

fix: 优化 handleDimensionValueFilter 复杂度

---

packages/s2-core/__tests__/unit/cell/row-cell-spec.ts
packages/s2-core/src/cell/base-cell.ts
packages/s2-core/src/cell/data-cell.ts
packages/s2-core/src/cell/header-cell.ts
packages/s2-core/src/cell/row-cell.ts

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore
交叉表行头叶子节点支持斑马纹风格
| ❌ ![image](https://github.com/antvis/S2/assets/9548248/d2e2c142-4378-4df7-9912-befba7ca57bd)  | ✅ ![image](https://github.com/antvis/S2/assets/9548248/4b5086d4-d361-4549-8838-6e93d80dcdf9)   |

feat: 交叉表行头叶子节点支持斑马纹风格

---

packages/s2-core/src/facet/header/series-number.ts
packages/s2-core/src/facet/layout/node.ts

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore
|  ![iShot_2023-11-14_15 23 47](https://github-production-user-asset-6210df.s3.amazonaws.com/8447716/282694826-e40e9171-fac2-45ac-aee5-2a7c6855ad2a.gif)  |   ![iShot_2023-11-14_15 26 21](https://github.com/antvis/S2/assets/8447716/62972346-2f2c-44ae-9097-421cd9e68ae1)    |

fix: 修复交叉模式下 行序号位置不正确&总计行未添加行序号

---

s2-site/.dumirc.ts
s2-site/package.json

chore: update dumi-theme-antv 0.4.0

---

.github/workflows/pr-auto-assign-reviewer.yml
s2-site/package.json

docs: 更新官网主题

---

LICENSE
s2-site/.dumirc.ts
s2-site/package.json

docs: 更新官网新闻公告

---

packages/s2-core/__tests__/spreadsheet/miss-dimension-values-spec.ts
packages/s2-core/src/utils/layout/get-dims-condition-by-node.ts

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore
ref: #2436

fix: 修复缺失维度所生成的 query 多了 empty extra value 字段

---

packages/s2-react/__tests__/unit/components/sheets/strategy-sheet/custom-tooltip/__snapshots__/index-spec.tsx.snap
packages/s2-react/__tests__/unit/components/sheets/strategy-sheet/custom-tooltip/index-spec.tsx
packages/s2-react/__tests__/util/helpers.ts
packages/s2-react/src/components/sheets/strategy-sheet/custom-tooltip/custom-data-tooltip.tsx
packages/s2-react/src/components/sheets/strategy-sheet/custom-tooltip/custom-row-tooltip.tsx
packages/s2-react/src/components/sheets/strategy-sheet/custom-tooltip/index.less

🐛 Bugfix
| ![image](https://github.com/antvis/S2/assets/21015895/e5e30a81-d675-4c3a-8f38-1a0653f2e8e9)| ![image](https://github.com/antvis/S2/assets/21015895/d1b5c68e-d3a2-4230-9209-5616b824f0f4)|

fix(tooltip): 修复字段描述为英文时展示不全

---

packages/s2-core/src/interaction/base-interaction/hover.ts

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore
|    ![2023-12-13 11 23 50](https://github.com/antvis/S2/assets/17964556/61eb9a38-fead-4c17-8e78-60c78926c984)   |   ![2023-12-13 11 23 34](https://github.com/antvis/S2/assets/17964556/6e81121b-2dd3-420a-a60f-008c40f0946e) |

fix: 去除 data cell hover 的 ellipsisTooltip 展示逻辑

---

packages/s2-core/src/facet/utils.ts

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore
|   ![image](https://github.com/antvis/S2/assets/8447716/dfea5f75-5653-4ab5-8b1c-e790b52928cd)     |

fix: 修复初始化渲染未完成时headNode NPE问题

---

packages/s2-core/__tests__/unit/data-set/pivot-data-set-row-value-spec.ts
packages/s2-core/src/data-set/pivot-data-set.ts
packages/s2-core/src/utils/dataset/pivot-data-set.ts

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore
在传入的 query 是不存在的时:

fix: 处理 getMultiData 在找不到数据时的报错信息

---

.github/workflows/release-success.yml
LEGAL.md
pnpm-lock.yaml
s2-site/LEGAL.md
s2-site/package.json

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore

docs: 修复 https://s2.antv.vision 老官网自动部署失败

---

s2-site/.dumi/global.less
s2-site/.dumi/global.ts

| ![image](https://github.com/antvis/S2/assets/21015895/3ebd242d-e2d2-4012-9943-385160184c1b) | ![image](https://github.com/antvis/S2/assets/21015895/ea547c75-6019-4ac2-bd9d-f7a34d3db696) |

docs: 修复官网导航栏样式异常

---

packages/s2-core/src/data-set/base-data-set.ts
packages/s2-react/src/components/sheets/editable-sheet/drag-copy/drag-copy-mask.tsx
packages/s2-react/src/components/sheets/editable-sheet/drag-copy/index.tsx
packages/s2-react/src/components/sheets/editable-sheet/edit-cell/index.tsx

🐛 Bugfix
表格排序后, 编辑更新数据还是用的原始数据进行更新, 导致会更新到其他行的数据, 拖拽批量替换也有类似的问题.
| ![Kapture 2024-02-05 at 19 07 55](https://github.com/antvis/S2/assets/21015895/11993f09-bac0-40e8-a232-371dc3b8ce5f) | ![Kapture 2024-02-05 at 19 10 06](https://github.com/antvis/S2/assets/21015895/b9905439-1f9b-44aa-a74a-cd737265b9e0) |

fix: 修复表格排序后, 编辑单元格后数据更新错误 close #2573

---

.github/workflows/issue-labeled.yml
.github/workflows/pr-labeled.yml
packages/s2-core/__tests__/bugs/issue-2582-spec.ts
packages/s2-core/src/facet/pivot-facet.ts
packages/s2-react/playground/config.ts
packages/s2-react/playground/index.tsx

🐛 Bugfix
|  ![image](https://github.com/antvis/S2/assets/21015895/e125c54e-878b-4ca7-9653-050533a940ef) | ![image](https://github.com/antvis/S2/assets/21015895/ae745328-30d2-4431-95f0-975c2572350b) |

fix: 修复树状模式下开启分页, 行头展开收起后表格渲染异常 close #2582

---

s2-site/docs/manual/basic/tooltip.zh.md
s2-site/examples/react-component/drill-down/demo/for-pivot.tsx

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore

docs: 修正 tooltip 和下钻demo 文档

---

s2-site/docs/manual/advanced/interaction/resize.zh.md
s2-site/examples/interaction/basic/demo/event.ts
s2-site/examples/interaction/basic/demo/resize.ts

🔧 Chore
https://github.com/antvis/S2/issues/2635#issuecomment-2022562731

docs: 补充宽高调整文档

---

packages/s2-react/package.json
packages/s2-vue/package.json

🐛 Bugfix
1. "@antv/s2": ">=1.0.0" 调整为 "@antv/s2": "^2.0.0-next.1", 以匹配 `2.0.0-next.x` 预览版本
2. "ant-design-vue": ">=3.2.0" 调整为 "ant-design-vue": "^3.2.0", 以避免匹配到 `4.x` 的版本 (最新版本是 4.2, API 有 break change)

fix: 调整 peerDependencies 命中规则

---

packages/s2-core/__tests__/unit/facet/pivot-facet-spec.ts
packages/s2-core/src/data-set/pivot-data-set.ts
packages/s2-core/src/utils/dataset/pivot-data-set.ts

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore
| ![image](https://github.com/antvis/S2/assets/17964556/e7762fc6-70b7-44f8-962f-5076b4cb68b2)| ![image](https://github.com/antvis/S2/assets/17964556/043cd902-e3cc-4609-a7c9-5836d261f4b3)     |

perf: 优化 getDimensionValues 在大量 flatten 情况下的性能

---

README.md
packages/s2-core/README.md
s2-site/docs/manual/introduction.zh.md

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore

docs: 移除答疑群二维码, 任何问题请提交 issue

---

packages/s2-core/__tests__/bugs/issue-2385-spec.ts
packages/s2-core/__tests__/data/data-issue-2385.json
packages/s2-core/src/cell/data-cell.ts
packages/s2-core/src/utils/cell/cell.ts

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore

fix: 修复紧凑模式下数值单元格maxWidth计算错误的问题

---

packages/s2-core/__tests__/bugs/issue-2385-spec.ts
packages/s2-core/__tests__/data/data-issue-2385.json
packages/s2-core/src/cell/data-cell.ts
packages/s2-core/src/utils/cell/cell.ts

This reverts commit c6bc0b845e2ff4434db4770ea62e351b866c3a6f.
✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore
实现还有点问题, 先 Revert

Revert "fix: 修复紧凑模式下数值单元格maxWidth计算错误的问题 (#2668)"

---

packages/s2-core/__tests__/unit/utils/export/export-pivot-spec.ts
packages/s2-core/__tests__/unit/utils/export/export-table-spec.ts
packages/s2-core/__tests__/util/index.ts
packages/s2-core/src/utils/export/copy/base-data-cell-copy.ts
packages/s2-core/src/utils/export/copy/pivot-data-cell-copy.ts
packages/s2-core/src/utils/export/copy/table-copy.ts

🐛 Bugfix
当复制/导出数据大于1w条时，会出现重复数据：
| <img width="618" alt="image" src="https://github.com/antvis/S2/assets/11677125/f4fbc6d5-b625-4d50-b0fc-1c210d2ba37a">      |  <img width="615" alt="image" src="https://github.com/antvis/S2/assets/11677125/a784dccb-6486-4a01-952f-6f79e8bb8e0f"> |
close #2718

fix: 修复下载数据重复 close #2718

---

packages/s2-core/src/interaction/row-column-resize.ts

✨ Feature
🎨 Enhance
🐛 Bugfix
chrome 版本在 125 以上，mousemove事件有改动, 需要在 mousedown preventDefault, 防止被上层 dragstart 捕获
🔧 Chore

fix: 在 resize 时加上 preventDefault 事件，兼容 chrome 125 事件更新的处理

---

s2-site/docs/common/style.zh.md
s2-site/docs/manual/advanced/custom/cell-size.zh.md
s2-site/examples/custom/custom-shape-and-chart/demo/custom-g-shape.ts
s2-site/examples/custom/custom-shape-and-chart/demo/meta.json
s2-site/examples/layout/custom/demo/custom-pivot-size.ts
s2-site/examples/layout/custom/demo/custom-table-size.ts

docs: 完善自定义单元格的优先级说明和自定义绘制图标的示例 close #2736

---

packages/s2-core/__tests__/unit/utils/color-spec.ts
packages/s2-core/src/cell/data-cell.ts
packages/s2-core/src/utils/color.ts
s2-site/docs/manual/basic/conditions.en.md
s2-site/docs/manual/basic/conditions.zh.md

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore
| ![image](https://github.com/antvis/S2/assets/48509562/19b83560-4407-4bcc-b451-4392e9fe56a8)   | ![image](https://github.com/antvis/S2/assets/48509562/76a0aa0e-3fff-4d65-ade2-df01e03c37c0)  |

fix: 修复字段标记背景色透明度优先级低于主题背景色透明度的问题

---

packages/s2-core/__tests__/spreadsheet/scroll-spec.ts
packages/s2-core/src/common/icons/gui-icon.ts
packages/s2-core/src/common/interface/basic.ts
packages/s2-core/src/facet/header/corner.ts
packages/s2-react/playground/config.tsx
s2-site/docs/manual/advanced/chart-in-cell.zh.md
s2-site/docs/manual/faq.zh.md
s2-site/examples/case/art/demo/lost-text.tsx
s2-site/examples/case/art/demo/time-spend-abstract.tsx
s2-site/examples/custom/custom-cell/demo/col-cell.ts
s2-site/examples/custom/custom-cell/demo/corner-cell.ts
s2-site/examples/custom/custom-cell/demo/corner-header.ts
s2-site/examples/custom/custom-cell/demo/custom-specified-cell.ts
s2-site/examples/custom/custom-cell/demo/data-cell.ts
s2-site/examples/custom/custom-cell/demo/row-cell.ts
s2-site/examples/custom/custom-shape-and-chart/demo/custom-g-shape.ts

🔧 Chore
1. 简化文档自定义图片的写法, 直接传入 url
2. 增加自定义图片使用缓存避免重复加载的 FAQ 和示例
ref #1499

docs: 增加如何避免表格滚动时图片重复加载的文档和示例 #2737

---

packages/s2-react/src/components/sheets/editable-sheet/drag-copy/drag-copy-mask.tsx
packages/s2-react/src/components/sheets/editable-sheet/drag-copy/index.tsx

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore

fix: 修复 react 层对 frozen 的处理

---

packages/s2-core/src/cell/col-cell.ts
packages/s2-core/src/common/interface/export.ts

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore

refactor: 修复部分 circular deps

---

packages/s2-react-components/README.md
packages/s2-react-components/package.json
packages/s2-react-components/playground/config.tsx
packages/s2-react-components/playground/index.tsx
packages/s2-react-components/src/components/config/theme-panel/interface.ts
packages/s2-react-components/tsconfig.json

🔧 Chore
1. 去除 s2-react 的类型依赖
2. 兼容 1.x 和 2.x

chore: 更新 react-componnents 依赖配置和说明文档

---

s2-site/docs/api/components/sheet-component.zh.md

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore
- [x ] Docs / demos update
文档错位修正
|

docs: 文档错位修正

---

s2-site/docs/api/basic-class/interaction.zh.md
s2-site/docs/api/basic-class/spreadsheet.zh.md
s2-site/docs/api/components/sheet-component.zh.md

docs: 优化 contextmenu API 文档 close #2882

---

s2-site/docs/manual/basic/tooltip.en.md
s2-site/docs/manual/basic/tooltip.zh.md

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore
文档 vue demo 修复

docs: 修复文档 vue demo

---

s2-site/docs/api/general/S2DataConfig.zh.md

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore
- [x ] Docs / demos update

#docs: 修复文档必选错位

---

packages/s2-core/src/interaction/event-controller.ts

🐛 Bugfix
G 5.0 的判断方式不同, 从 1.x cherry-pick 过来时忘记修改了 https://github.com/antvis/S2/commit/010ed050214568ea1902e4a426d6638afd3ae2f9

fix: 修复开启 supportsCSSTransform 后 hover 在表格上时报错

---

packages/s2-core/__tests__/spreadsheet/__snapshots__/multi-line-text-spec.ts.snap
packages/s2-core/__tests__/spreadsheet/corner-spec.ts
packages/s2-core/src/cell/corner-cell.ts

🎨 Enhance
```ts
s2.setOptions({
hierarchyType: 'tree',
});
s2.setTheme({
cornerCell: {
bolderText: {
textAlign: 'left',
},
},
});
```
| ![image](https://github.com/user-attachments/assets/61379686-7c43-4da4-bd13-ef8de5c83382) | ![image](https://github.com/user-attachments/assets/be2781f6-b7e8-4f78-a725-6c6106564460) |

fix: 修复文本设为左对齐时, 角头文本没有垂直对齐的问题

---

s2-site/docs/api/basic-class/spreadsheet.zh.md
s2-site/docs/api/general/S2Theme.zh.md
s2-site/examples/custom/custom-icon/demo/custom-header-action-icon.ts

🔧 Chore
1. 补充缺失的 API
2. 修改错误的说明

docs: 优化 spreadsheet class api 文档

---

packages/s2-core/src/facet/base-facet.ts

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore

fix: 修复表格卸载时 G 图形实例未销毁的问题

---

packages/s2-core/src/cell/row-cell.ts

🐛 Bugfix
多行文本兼容行头的文本滚动吸附算法
```ts
style: {
rowCell: {
height: 80,
maxLines: 10,
},
},
```
| ![image](https://github.com/user-attachments/assets/03e032f7-ad25-4079-8217-b2c1c2430fb2) | ![image](https://github.com/user-attachments/assets/0e416550-fab1-4c3f-a8ad-c353a6b5ee28) |

fix: 修复行头底部存在多行文本, 初始化和滚动时文本展示溢出的问题

---

packages/s2-core/__tests__/unit/interaction/base-interaction/click/corner-cell-click-spec.ts
packages/s2-core/__tests__/unit/interaction/base-interaction/hover-spec.ts
packages/s2-core/src/interaction/base-event.ts
packages/s2-core/src/interaction/base-interaction/click/corner-cell-click.ts
packages/s2-core/src/interaction/base-interaction/click/data-cell-click.ts
packages/s2-core/src/interaction/base-interaction/click/row-column-click.ts
packages/s2-core/src/interaction/base-interaction/hover.ts
packages/s2-react/playground/config.tsx

🐛 Bugfix
```tsx
items: [
{
key: 'custom-a',
label: '操作1',
icon: 'Trend',
visible: (cell) => {
return cell instanceof DataCell;
}
},
]
```
| ![image](https://github.com/user-attachments/assets/131fc192-1551-447e-8529-a90d1f0aa77a) | ![image](https://github.com/user-attachments/assets/fd2d21d4-6a75-4726-bc29-80b0ae1e02e2) |
|![image](https://github.com/user-attachments/assets/60a89767-5bf2-46ad-a06c-84de2feba9c6) | ![image](https://github.com/user-attachments/assets/e824647f-691c-4d38-a2ab-fbf97dc4d966) |

fix(tooltip): 修复操作按钮的 visible 对角头和文本溢出场景不生效

---

packages/s2-core/__tests__/spreadsheet/table-sheet-spec.ts
packages/s2-core/src/facet/base-facet.ts
packages/s2-core/src/facet/frozen-facet.ts
packages/s2-core/src/facet/table-facet.ts

fix: 明细表未指定 dataCfg.fields 配置时不应该渲染空数据占位

---

.github/workflows/issue-labeled.yml

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore

chore: 更新 next issue label ci 脚本
