packages/s2-core/rollup.config.js

🔧 Chore
- 更新 rollup 的 external 配置，用正则匹配 antd，避免 antd/lib 和 antd 的 locale 文件被一起打包进去，会造成如下报错

chore(build): update external using regex

---

s2-site/package.json

🔧 Chore
Currently, `gatsby-plugin-manifest` has dependency `sharp@0.27.0`, But sharp supports Apple M1 since `@0.29.0`

chore: upgrade sharp version to support M1

---

packages/s2-core/src/facet/base-facet.ts

🐛 Bugfix
1.修复透视表行头有滚动条时, 在数值单元格区域无法滚动的问题
2.修复透视表行头滚动抖动
close #374 #361

fix(povit-table): resolve scroll shake issue close #374 #361

---

packages/s2-core/src/common/constant/theme.ts
packages/s2-core/src/components/sheets/tabular-sheet/tabular-theme.ts
packages/s2-core/src/ui/tooltip/index.less
s2-site/docs/api/general/S2Theme.zh.md

🐛 Bugfix
修复在ios15上, 渲染表格文字时, 浏览器崩溃卡死
https://juejin.cn/post/7012161541378146334

fix(pivot-table): fix render apply font crash on ios15

---

packages/s2-core/src/facet/base-facet.ts
packages/s2-core/src/facet/table-facet.ts

修复 https://github.com/antvis/S2/commit/014d683a8cc251f0f4cddb28662b45b7b96d4edb 这个 commit 引入的 table 模式渲染异常问题：
把 cornerBBox 的计算逻辑放到了 table-facet 子类中覆盖了原来的方法。这样后面好维护一些。

fix(table): table mode corner width err

---

packages/s2-core/__tests__/unit/interaction/base-interaction/click/row-column-click-spec.ts
packages/s2-core/__tests__/unit/interaction/event-controller-spec.ts
packages/s2-core/__tests__/util/helpers.ts
packages/s2-core/src/components/index.tsx
packages/s2-core/src/interaction/event-controller.ts

🐛 Bugfix
**1. 优化点击空白处重置交互的处理逻辑**: 对于数据量很小的表格, 虽然看起来是空白处, 但其实还处于 canvas 区域, 这时候点击 **[空白处]** 并不能达到用户的预期, 可能会对用户产生迷惑性
|----|----|
|  ![Kapture 2021-10-12 at 19 24 30](https://user-images.githubusercontent.com/21015895/136947286-f66b7cc6-c146-4e8f-ab01-24ba10e9c6d2.gif) |  ![Kapture 2021-10-12 at 19 18 41](https://user-images.githubusercontent.com/21015895/136946707-9945bb29-e63f-444d-95f4-ab45fc5bec55.gif) |

fix(interaction): optimize reset state logic

---

packages/s2-core/src/cell/table-col-cell.ts
packages/s2-core/src/facet/table-facet.ts
packages/s2-core/src/sheet-type/table-sheet.ts

修复：明细表行列冻结在滚动后重新调 render 的时候，scrollY 设置不正确，导致渲染异常 的问题。

fix(table): scroll position issue when re-render 

---

packages/s2-core/__tests__/util/sheet-entry.tsx
packages/s2-core/src/facet/base-facet.ts
packages/s2-core/src/utils/interaction/merge-cells.ts

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore
1. 修复合并单元格，排序后失效问题。
2. 修复合并单元格，修改行列宽度后失效问题。
3. 修复对明细表冻结功能的影响。
| ![合并单元格无法保存](https://user-images.githubusercontent.com/20497176/137659830-df4ed6ca-7ca9-4dc4-9217-feb4cca98aa3.gif) | ![合并单元格修复2](https://user-images.githubusercontent.com/20497176/137659843-2ef7fe8e-f318-488d-b64f-ed544ca7cca2.gif) |

fix: fix merged cells can't be sorted and dragged

---

packages/s2-core/src/cell/table-col-cell.ts

…onIcons for detail table mode
🐛 Bugfix
| ![image](https://user-images.githubusercontent.com/10885578/137702950-0a8ecd4f-d890-40a0-98c5-5d21734632c3.png) |![image](https://user-images.githubusercontent.com/10885578/137703023-2970ccbf-9ef2-4316-bf0d-5de134cfb3c3.png)|

fix: :bug: correct the wrong condition to show the default headerActionIcons for the detail table

---

packages/s2-core/__tests__/unit/dataset/pivot-dataset-spec.ts
packages/s2-core/src/cell/header-cell.ts
packages/s2-core/src/common/constant/basic.ts
packages/s2-core/src/components/sheets/base-sheet/index.tsx
packages/s2-core/src/data-set/pivot-data-set.ts
packages/s2-core/src/interaction/base-interaction/click/row-column-click.ts
packages/s2-core/src/interaction/event-controller.ts
packages/s2-core/src/utils/drill-down.ts

…nIcon
🐛 Bugfix
- Reset the interaction after drill-down or clear the drill-down which is needed to hide the tooltip.
- Clear the interaction state after clicking the HeaderActionIcon.
- Prevent the cell click event when clicking the HeaderActionIcon.
| ![image](https://user-images.githubusercontent.com/10885578/137826218-af045583-5c02-47c9-9a6d-8846ec3e78d3.png)| ![image](https://user-images.githubusercontent.com/10885578/137826235-44095357-72c4-4ca0-9039-4cf532651c1d.png)|

fix: :bug: prevent the cell click event when clicking the HeaderActionIcon and close #409 #452

---

packages/s2-core/__tests__/unit/facet/pivot-facet-spec.ts
packages/s2-core/__tests__/unit/interaction/row-column-resize-spec.ts
packages/s2-core/__tests__/unit/utils/interaction/resize-spec.ts
packages/s2-core/__tests__/unit/utils/interaction/state-controller-spec.ts
packages/s2-core/__tests__/util/sheet-entry.tsx
packages/s2-core/src/cell/base-cell.ts
packages/s2-core/src/cell/col-cell.ts
packages/s2-core/src/cell/corner-cell.ts
packages/s2-core/src/cell/row-cell.ts
packages/s2-core/src/cell/table-col-cell.ts
packages/s2-core/src/common/constant/resize.ts
packages/s2-core/src/common/interface/resize.ts
packages/s2-core/src/common/interface/store.ts
packages/s2-core/src/common/interface/theme.ts
packages/s2-core/src/data-set/pivot-data-set.ts
packages/s2-core/src/facet/base-facet.ts
packages/s2-core/src/facet/header/corner.ts
packages/s2-core/src/interaction/row-column-resize.ts
packages/s2-core/src/theme/index.ts
packages/s2-core/src/utils/interaction/resize.ts
s2-site/docs/api/general/S2Theme.zh.md

🐛 Bugfix
🔧 Chore
修复 **冻结行头** 行头有滚动条场景下一些 resize bugs
1. 修复 resize 热区渲染错误
2. 修复 角头文字 未居中
3. 修复 实际渲染的宽度 与 resize 提示线的距离 不符
4. 优化 resize appendInfo 的添加方式
5. 统一 foregroundGroup 添加 热区的方式
6. 修复 鼠标移出 图表区域 resize 事件无法结束
| ![Kapture 2021-11-01 at 19 40 45](https://user-images.githubusercontent.com/21015895/139666154-93452926-50e2-45bc-9e5e-a8e0ada72127.gif) | ![Kapture 2021-11-01 at 19 42 18](https://user-images.githubusercontent.com/21015895/139666401-e3d63b10-ad83-406d-8740-568dee46a0e1.gif) |
close #578

fix(resize): fix corner resize blank

---

packages/s2-core/__tests__/unit/interaction/base-interaction/hover-spec.ts
packages/s2-core/__tests__/unit/interaction/row-column-resize-spec.ts
packages/s2-core/__tests__/util/helpers.ts
packages/s2-core/__tests__/util/sheet-entry.tsx
packages/s2-core/src/interaction/base-interaction/hover.ts
packages/s2-core/src/interaction/row-column-resize.ts
packages/s2-core/src/ui/tooltip/index.tsx

🐛 Bugfix
1. 修复 data cell timer 未取消, 导致鼠标在 行/列头 时, 任然显示 data cell 的 tooltip
> 鼠标悬停在 数值单元格时 => 然后鼠标移动到 行/列 头
2. 修复 tooltip 打开后, 鼠标移动到 resize 热区 tooltip 会关闭的问题
> 之前关闭tooltip 是为了防止tooltip 对拖拽造成干扰, 现在还是改为 拖拽时 让 tooltip 光标失效 (避免拖拽过程中鼠标在tooltip上无法继续拖动)
close #601 
close #602

fix(interaction): cancel data cell hover focus timer when row or col mousemove

---

.github/workflows/auto-release.yml
.github/workflows/issue-labeled.yml

🔧 Chore
支持 预发布版本 的 钉钉通知
1. 给 dingtalk-release-notify 提了一个 [PR](https://github.com/visiky/dingtalk-release-notify/pull/5), 经过测试, 暂无问题
- beta 和 alpha 分支 发布 pre release npm 包 采用 pre release  通知
- master 分支 发布 正式版 npm 包  使用 正式的 release 通知
2. 增加需求被采纳的 label

chore(ci): support prerelease notify

---

packages/s2-core/src/common/interface/theme.ts
packages/s2-core/src/facet/header/frame.ts
packages/s2-core/src/facet/table-facet.ts
packages/s2-core/src/theme/index.ts
s2-site/docs/api/general/S2Theme.zh.md

明细表行列冻结时添加阴影。把之前主题配置中的 showRightShadow 改为了 showShadow。统一控制交叉表和明细表的 shadow 展示。

feat(table): add shadow for frozen line

---

packages/s2-core/__tests__/bugs/issue-609-spec.tsx
packages/s2-core/src/components/sheets/hooks.ts

🐛 Bugfix
1. 修复 开启 `adaptive` 后, 首次渲染并没有按照容器宽度渲染
原因: 先走第一个 `useEffect` 渲染为 容器宽度, 然后又走了第二个 `useEffect` 又重置为 s2Options 配置的宽度, 实际渲染了两次
| ![image](https://user-images.githubusercontent.com/21015895/140313433-45abb756-8861-436b-8da0-b3d60386cecc.png) | ![image](https://user-images.githubusercontent.com/21015895/140313407-fa27712b-e4dc-4569-b802-76d9fae58c13.png) |
close #609

fix(component): fix not use container width when enable adaptive and first rendered

---

packages/s2-core/src/common/constant/interaction.ts
packages/s2-core/src/ui/scrollbar/index.ts

1. 修复选中态的一个问题，当 DataCell 选中态的背景色为透明时，因为 SHAPE_ATTRS_MAP 中存在 backgroundShape: ['backgroundOpacity'] 的多余映射，DataCell 选中时，背景色（backgroundShape）的透明度也会被改变，就会发现点击一个格子之后背景颜色就彻底变了。复现只需要设置 theme.dataCell.cell.interactionState.selected.backgroundOpacity 小于1 即可。
2. 横向滚动条，主要用鼠标的用户会比较常用，直接拖动横向滚动条。目前 mousemove 的事件绑定在 container 上，如果用户鼠标往下移动一点就出了范围，滚动就会中断，体验不太好。放到 body 上就可以解决这个问题。

fix(scroll): set scroll move event target to body

---

packages/s2-core/__tests__/unit/interaction/event-controller-spec.ts
packages/s2-core/__tests__/unit/utils/merge.spec.ts
packages/s2-core/__tests__/util/sheet-entry.tsx
packages/s2-core/src/common/constant/events/origin.ts
packages/s2-core/src/common/constant/options.ts
packages/s2-core/src/common/constant/tooltip.ts
packages/s2-core/src/interaction/event-controller.ts
s2-site/docs/common/interaction.zh.md
s2-site/docs/manual/advanced/interaction/basic.zh.md

🐛 Bugfix
1. 修复鼠标移出单元格, 或者表格区域时, `tooltip` 未关闭, 未取消单元格高亮
2. 增大 `tooltip` 和光标的距离
3. 修复移出单元格, 依然显示 tooltip 的问题
4. 选中聚光灯改为默认关闭
| ![Kapture 2021-11-05 at 15 36 16](https://user-images.githubusercontent.com/21015895/140474800-4e31efef-a8b5-4e98-a201-ae84e200cd14.gif) | ![Kapture 2021-11-05 at 15 33 24](https://user-images.githubusercontent.com/21015895/140474422-35267e6b-2c11-4b14-8c34-13e1e6468651.gif)|

fix(interaction): hide tooltip and clear hover highlight if mouseleave the cell

---

packages/s2-core/__tests__/unit/interaction/event-controller-spec.ts
packages/s2-core/__tests__/util/sheet-entry.tsx
packages/s2-core/src/common/constant/events/origin.ts
packages/s2-core/src/interaction/event-controller.ts

🐛 Bugfix
修复组内排序tooltip 和 自定义tooltip 打开时鼠标从单元格移开 tooltip 会关闭的问题
| ![Kapture 2021-11-08 at 11 27 39](https://user-images.githubusercontent.com/21015895/140679772-7c4cfa80-8a63-4a68-a9c0-8bc7d89109dd.gif) | ![Kapture 2021-11-08 at 11 26 51](https://user-images.githubusercontent.com/21015895/140679706-99a4b013-5b90-4e4e-8113-d9ac63949eb3.gif)|

fix(interaction): wrong hidden action tooltip when mouse outside the cell

---

packages/s2-core/__tests__/unit/dataset/pivot-dataset-row-value-spec.ts
packages/s2-core/__tests__/unit/dataset/pivot-dataset-spec.ts
packages/s2-core/__tests__/unit/dataset/pivot-dataset-total-spec.ts
packages/s2-core/__tests__/unit/facet/pivot-facet-spec.ts
packages/s2-core/__tests__/unit/facet/util.ts
packages/s2-core/__tests__/unit/utils/data-set-operate-spec.tsx
packages/s2-core/__tests__/unit/utils/dataset/pivot-dataset-spec.ts
packages/s2-core/src/data-set/interface.ts
packages/s2-core/src/data-set/pivot-data-set.ts
packages/s2-core/src/facet/layout/build-row-tree-hierarchy.ts
packages/s2-core/src/utils/data-set-operate.ts
packages/s2-core/src/utils/dataset/pivot-data-set.ts

… object for saving repeat value
🎨 Enhance
🔧 Chore
refactor: optimize sortedDimensionValues's structure by change map to object for saving repeat value and modify test

refactor: optimize sortedDimensionValues's structure by change map to object for saving repeat value and modify test

---

packages/s2-core/package.json

Unfix react versions that other projects react that version > 16 can run 'npm i' successfully.
✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore

chore: unfix peerDep versions

---

packages/s2-core/src/common/constant/interaction.ts
packages/s2-core/src/common/interface/theme.ts

🐛 Bugfix
```js 
// theme 
{
dataCell: {
cell: {
padding: {},
interactionState: {
selected: {
backgroundColor: '#2a83fa',
borderColor: '#2a83fa',
backgroundOpacity: 0.1,
borderWidth: 2,
borderOpacity: 1,
},
},
},
},
};
```
| ❌       ![image](https://user-images.githubusercontent.com/9219215/141071073-ce30650f-0992-432b-bfd6-5c80ebbc9eb0.png) | ✅                  ![image](https://user-images.githubusercontent.com/9219215/141070572-859a445a-72bc-44d6-8659-3b1393124cdd.png)           |

feat: 🎸 修复interactionState的borderWidth和borderColor不生效问题

---

packages/s2-core/__tests__/bugs/issue-609-spec.tsx
packages/s2-core/__tests__/spreadsheet/table-sheet-spec.tsx
packages/s2-core/__tests__/unit/interaction/base-interaction/click/row-column-click-spec.ts
packages/s2-core/__tests__/unit/utils/hide-columns.spec.ts
packages/s2-core/src/cell/base-cell.ts
packages/s2-core/src/cell/row-cell.ts
packages/s2-core/src/cell/table-col-cell.ts
packages/s2-core/src/common/interface/store.ts
packages/s2-core/src/common/interface/theme.ts
packages/s2-core/src/components/sheets/grid-analysis-sheet/grid-analysis-theme.ts
packages/s2-core/src/components/sheets/grid-analysis-sheet/index.tsx
packages/s2-core/src/interaction/base-interaction/click/row-column-click.ts
packages/s2-core/src/interaction/event-controller.ts
packages/s2-core/src/theme/index.ts
packages/s2-core/src/utils/hide-columns.ts
packages/s2-core/src/utils/text.ts
s2-site/docs/manual/advanced/interaction/basic.zh.md

🐛 Bugfix
1. 修复 展开隐藏列图标 **遮挡**列头文本和排序图标的问题
2. 修复 明细表 列头文本 和 排序图标 **没有 margin** 的问题
3. 修改 隐藏列头的 回调, 增加 prev node
4. 修复 主题 类型定义
| ![image](https://user-images.githubusercontent.com/21015895/141268369-3e8573b7-7ca0-4995-a1d9-803f41ac21ce.png) | ![image](https://user-images.githubusercontent.com/21015895/141268048-60f15ff4-4132-40d1-88aa-9dec46e2d466.png) |
| ![image](https://user-images.githubusercontent.com/21015895/141268329-b40f5349-d6b1-4657-8a8f-83290a469708.png)  | ![image](https://user-images.githubusercontent.com/21015895/141268241-b97fb58b-5bdf-4b39-8283-495a52829c4e.png)|

fix(table): fix expand column icon cover text and sort icon

---

packages/s2-core/src/facet/base-facet.ts

fix(facet): render v scrollbar close #681

---

packages/s2-core/src/facet/base-facet.ts
packages/s2-core/src/facet/bbox/cornerBBox.ts
packages/s2-core/src/facet/bbox/panelBBox.ts
packages/s2-core/src/facet/header/col.ts

🐛 Bugfix
1. 修复行头和数值区域都是滚动条时, 滚动边界判断错误 导致无法滚动的问题 close #561 问题2
2. 增加拖拽后 panel BBox 为负数的场景 (非常规) 的容错 close #693

fix(scroll): fix cannot scroll by mouse or touch tablet

---

packages/s2-core/src/common/interface/theme.ts
packages/s2-core/src/theme/index.ts

🐛 Bugfix
* The textOpacity is necessary.

fix: :bug: solve the issue that the selectedCellsSpotlight does not work

---

packages/s2-core/__tests__/unit/ui/hd-adapter/index-spec.ts
packages/s2-core/src/ui/hd-adapter/index.ts
packages/s2-core/src/utils/is-mobile.ts

🐛 Bugfix
> 高清适配应该只改变 canvas.width 和 canvas.height , 而不是 canvas.style.width canvas.style.height
1. 修复开启高清适配后 触控板放大后 图表宽度异常
这个bug 的原始是 更新 `g` 的 DPR 后, 宽高不应该设置放大的宽高, 不然实际是 width * DPR * 2, 放大了4倍
2. 该问题还会导致列头裁剪异常 ref #561 问题1
| ![image](https://user-images.githubusercontent.com/21015895/141739569-3b21502a-d570-4595-8210-da603aad10e8.png) | ![image](https://user-images.githubusercontent.com/21015895/141739499-fb0bb498-55f2-46e7-8b7f-98612befd5a6.png)|
ref #561

fix(hd-adapter): fix wrong container style when zoom scale changed

---

packages/s2-core/src/components/sheets/table-sheet/index.tsx
packages/s2-core/src/facet/base-facet.ts

调整 Scroll Offset 的时候，在分页的时候，应该用分页之后实际渲染的高度作为调整 Scroll Offset 的边界
不然在不分页的时候滚动到底部，然后开启分页，就会越界导致渲染异常。

fix(facet): adjustXY in pagination

---

packages/s2-core/__tests__/spreadsheet/switcher-spec.tsx
packages/s2-core/__tests__/unit/ui/hd-adapter/index-spec.ts
packages/s2-core/src/components/switcher/index.tsx
s2-site/docs/api/components/switcher.zh.md
s2-site/docs/manual/basic/analysis/switcher.zh.md
s2-site/examples/react-component/switcher/demo/table.tsx

✨ Feature
🐛 Bugfix
1. 修复 `<Switcher/>` 滚动不跟随的问题
2. 支持透传 antd `popover` 配置, 满足更多自定义需求
3. 修复维度切换组件 文档示例不生效
默认还是挂载在 `body` 下, 如解决滚动不跟随问题, 使用者自行透传 getPopupContainer 即可
```tsx
<Switcher
popover={{
getPopupContainer: (trigger) => trigger.parentElement,
}}
/>
```
ref: 
https://ant.design/docs/react/faq-cn#Select-Dropdown-DatePicker-TimePicker-Popover-Popconfirm-%E4%BC%9A%E8%B7%9F%E9%9A%8F%E6%BB%9A%E5%8A%A8%E6%9D%A1%E4%B8%8A%E4%B8%8B%E7%A7%BB%E5%8A%A8%EF%BC%9F
| ![Kapture 2021-11-16 at 15 29 35](https://user-images.githubusercontent.com/21015895/141940482-f3b917e8-6fb8-4a29-9009-dae229106ca4.gif) |

fix(components): switcher support receive antd popover props for resolve scroling with the page

---

packages/s2-core/__tests__/spreadsheet/spread-sheet-spec.tsx
packages/s2-core/src/facet/base-facet.ts

🐛 Bugfix
1. 角头宽度改变后, 同步行头滚动条偏移:
> 背景: 拖拽调整宽高后, 之前是粗暴的将 行头滚动条重置为0, 如果用户滚动条不是起始位置的话, 每次拖拽都重置, 体验很不好
2. 重构坐标偏移代码
| ![Kapture 2021-11-16 at 20 15 07](https://user-images.githubusercontent.com/21015895/141983632-651bc675-b401-413e-9361-bcac58611618.gif) | 
close #717

fix(scroll): sync row scroll offset when corner cell resized

---

packages/s2-core/__tests__/unit/ui/hd-adapter/index-spec.ts
packages/s2-core/src/facet/base-facet.ts

🎨 Enhance
🐛 Bugfix
由于滚动是监听 canvas 的 onWheel 事件 没有行/列/角头的概念, 以下情况未很好的处理分区
1. 修复: 非冻结行头时, 滚动边界判断错误
2. 修复: 冻结行头时, 行头有滚动条, 数值区域有滚动条 场景, 在任意区域滚动, 行头和数值区域都会滚动 (#707 碰伤了)
3. 修复: 透视/明细 表, 光标在列头区域, 依然会触发滚动
4. 修复: 移动端滚动条只显示一次
5. 修复: 在角头和列头滚动时, 会和父容器滚动冲突 (参考 https://ant.design/components/table-cn/#components-table-demo-grouping-columns,光标在列头时, 不触发表格滚动, 体验较好)
| ![Kapture 2021-11-17 at 15 52 21](https://user-images.githubusercontent.com/21015895/142158451-652fd0aa-764c-4d0d-b2a7-e24bd5358655.gif) | ![Kapture 2021-11-17 at 15 48 41](https://user-images.githubusercontent.com/21015895/142158042-b186f3f8-5ea0-465b-befe-a10effd3f30e.gif) |
close #718 
ref …

fix(scroll): scroll by group

---

packages/s2-core/__tests__/bugs/issue-720-spec.tsx
packages/s2-core/__tests__/unit/ui/hd-adapter-spec.ts
packages/s2-core/__tests__/unit/ui/hd-adapter/index-spec.ts
packages/s2-core/__tests__/util/helpers.ts
packages/s2-core/src/data-set/pivot-data-set.ts
packages/s2-core/src/ui/hd-adapter/index.ts

🔧 Chore
补上 #717 行头有滚动条时, 拖拽后滚动条会重置 的测试
ref #717

test: add reset row scroll when corner cell resized test

---

package.json
yarn.lock

🔧 Chore
jest-less-loader在`0.1.1`时不支持less文件中包含`@import`语法，给老王提了一个[PR](https://github.com/hustcc/jest-less-loader/pull/2)，现在可以愉快的使用公共变量和mixin了

chore: update less loader

---

packages/s2-core/__tests__/unit/interaction/event-controller-spec.ts
packages/s2-core/src/cell/merged-cell.ts
packages/s2-core/src/common/constant/interaction.ts
packages/s2-core/src/interaction/base-interaction/click/merged-cells-click.ts
packages/s2-core/src/interaction/event-controller.ts
packages/s2-core/src/utils/interaction/merge-cells.ts
s2-site/docs/api/basic-class/spreadsheet.zh.md
s2-site/docs/manual/advanced/interaction/merge-cell.zh.md
s2-site/examples/interaction/advanced/demo/merge-cells.tsx

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore
1. 调整button 样式，保持风格统一
2. 修复点击合并单元格后 tooltip 难以选中
3. 将 MERGED_CELLS 调整为 MERGE_CELL ，保持名称一致。
|![image](https://user-images.githubusercontent.com/20497176/142192624-5df476ee-477f-4619-a76c-898149af4271.png)|![image](https://user-images.githubusercontent.com/20497176/142192941-52a83ba8-53f5-4768-b6a4-1d8c3d6178d7.png)|
|![merged-cell的tooltip无法点击到](https://user-images.githubusercontent.com/20497176/142193868-c0f5dc5c-8767-4f28-8f83-72c014bc35a9.gif)|![merged-cell的tooltip可以保持](https://user-images.githubusercontent.com/20497176/142193905-fe73b974-c3c1-4037-9c13- …

fix: difficult to select the tooltip after click then merged cell

---

packages/s2-core/src/cell/base-cell.ts
packages/s2-core/src/theme/index.ts

🐛 Bugfix
🔧 Chore
原有逻辑interactionBorderShape不会根据lineWidth自适应更改大小，导致border绘制到cell外并被Clip，影响视觉效果。
interactorBorder宽度自适应
| ❌          ![image](https://user-images.githubusercontent.com/9219215/141739520-83abe439-9c68-4524-8644-257aef94957a.png)     | ✅      ![image](https://user-images.githubusercontent.com/9219215/141739247-08e792ea-745b-441a-9457-796701570c73.png)            |

fix: 🐛 interactorBorder宽度自适应

---

packages/s2-core/src/cell/base-cell.ts

🐛 Bugfix
| ❌            
|
画奇数宽的线条整个画在cell内部会导致法线两侧长度不一（1px是最小显示单位）   因此加上Math.Ceil 同时长宽上减去1的buffer，确保整个边框不被rowGroup和colGroup clip

fix: 🐛 修复1px边框错位的问题

---

packages/s2-core/__tests__/spreadsheet/interaction-tooltip-spec.ts
packages/s2-core/__tests__/unit/interaction/base-interaction/click/data-cell-click-spec.ts
packages/s2-core/__tests__/unit/interaction/data-cell-multi-selection-spec.ts
packages/s2-core/__tests__/unit/interaction/shift-multi-selection-spec.ts
packages/s2-core/__tests__/util/helpers.ts
packages/s2-core/src/common/constant/interaction.ts
packages/s2-core/src/common/interface/store.ts
packages/s2-core/src/interaction/root.ts
packages/s2-core/src/interaction/shift-multi-selection.ts
packages/s2-core/src/sheet-type/pivot-sheet.ts

🐛 Bugfix
1. 修复点击数值单元格 不显示 tooltip
原因是 https://github.com/antvis/S2/pull/732 加入 shift 多选后, 和 单选冲突
shift 的第一次点击本质上就是单选, 所以直接用 单选的逻辑即可

fix(tooltip): tooltip don't show

---

packages/s2-core/__tests__/spreadsheet/table-sheet-spec.tsx
packages/s2-core/src/cell/col-cell.ts
packages/s2-core/src/cell/table-col-cell.ts
packages/s2-core/src/common/constant/tooltip.ts
packages/s2-core/src/common/interface/tooltip.ts
packages/s2-core/src/sheet-type/pivot-sheet.ts
packages/s2-core/src/sheet-type/spread-sheet.ts
packages/s2-core/src/sheet-type/table-sheet.ts
packages/s2-core/src/theme/index.ts

+ 修复明细表排序问题。之前使用公共的 handleGroupSort。后面发现交叉表和明细表排序实现有些不同点。所以还是恢复之前的各自继承实现。
+ 明细表排序的文本修正。
+ s2-core 中新增明细表的测试 live 文件

fix(table): table sheet sort

---

.github/workflows/compressed-size.yml
.github/workflows/lint.yml
.github/workflows/test.yml
package.json

🔧 Chore
在CI中，`s2-react`只依赖于`s2-core`的`esm`模块，所以无需build其他部分，减少CI执行时间

chore: only build s2-core esm for s2-react

---

packages/s2-core/__tests__/unit/interaction/root-spec.ts
packages/s2-core/src/cell/merged-cell.ts
packages/s2-core/src/interaction/root.ts
packages/s2-core/src/sheet-type/spread-sheet.ts
packages/s2-react/src/components/sheets/table-sheet/index.tsx
s2-site/docs/api/basic-class/interaction.zh.md
s2-site/docs/api/basic-class/spreadsheet.zh.md
s2-site/docs/manual/advanced/interaction/custom.zh.md
s2-site/docs/manual/advanced/interaction/merge-cell.zh.md
s2-site/examples/interaction/custom/demo/double-click-hide-columns.ts

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore
1. 迁移示例方法 s2.hideColumns 到  s2.interaction.hideColumns 和其他方法保持统一
2. 修改相应错误文档

fix(interaction): move hideColumns method to interaction scope

---

packages/s2-core/src/ui/tooltip/index.ts
s2-site/docs/manual/advanced/interaction/merge-cell.zh.md
s2-site/examples/case/proportion/demo/single-population-proportion.tsx
s2-site/examples/interaction/advanced/demo/merge-cells.tsx

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore
1. 随 s2 和 tooltip 操作更新，更新使用方式。
2.  统一 merge-cell  的文档风格。
3. 调整了 customComponent 的优先级。
-  tooltipComponent 一般在用户配置options 的时候就会固定，如果想再次更新就需要重新渲染表格，成本很高。而在 
```js
s2.tooltip.show({
position: { x: event.clientX, y: event.clientY },
element: mergedCellsTooltip(cell), 
});
```
用户可控制其何时展示，展示几次。容易配置，且成本较低。
- 如果用户同时配置了tooltipComponent || element， element 不会生效。

docs: tweak tooltips in merge-cells

---

packages/s2-react/package.json

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore
当定义了 "exports" 字段，所有子路径都会被封闭，不再对使用者开放，为了灵活只能使用`./*: ./*`，但就失去了封闭的意义，所以这里直接删除掉该配置
close #790

fix: remove exports config close #790

---

packages/s2-core/src/facet/base-facet.ts

🐛 Bugfix
修复 getAdjustedScrollY 在数据为空时，scrollY 为 负数 的问题。

fix(facet): getAdjustedScrollY add negative check

---

s2-site/docs/api/components/header.en.md
s2-site/docs/manual/advanced/adaptive.en.md
s2-site/docs/manual/advanced/interaction/merge-cell.en.md
s2-site/docs/manual/advanced/layout/pivot.en.md
s2-site/docs/manual/advanced/layout/table.en.md
s2-site/docs/manual/basic/analysis/export.en.md
s2-site/docs/manual/basic/analysis/switcher.en.md
s2-site/docs/manual/basic/totals.en.md
s2-site/examples/interaction/advanced/demo/merge-cells.tsx

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore
1. tooltip 按钮重复问题修复
2. 修复英文文档缺失和部分目录为中文的问题。（感觉是移了目录，没有同时去更新
|![image](https://user-images.githubusercontent.com/20497176/143243142-7cf11e9f-d419-48b5-ad6c-88e33f601e36.png)| ![image](https://user-images.githubusercontent.com/20497176/143243211-3f04068d-fcf0-4843-bb32-571681fe8374.png)|
|![image](https://user-images.githubusercontent.com/20497176/143244375-7bc3d204-c59c-46de-9d4e-138ac94938d7.png) | ![image](https://user-images.githubusercontent.com/20497176/143249591-892900d6-2053-4bc6-8dbd-00641c177f55.png)|

docs: markdown link not work

---

packages/s2-core/__tests__/unit/dataset/pivot-dataset-spec.ts
packages/s2-core/src/common/interface/basic.ts
packages/s2-core/src/data-set/pivot-data-set.ts
s2-site/docs/api/general/S2DataConfig.zh.md

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore
1. 添加自定义指标维度组在行列头中的位置顺序 功能
2. 添加自定义指标维度组在行列头中的位置顺序  测试和文档
|![image](https://user-images.githubusercontent.com/20497176/143864844-7bf507fc-5af9-45fd-8390-195a5cf94545.png) | ![image](https://user-images.githubusercontent.com/20497176/143864789-a393095a-2e6e-4ff0-a8fe-3487dd28ecb5.png)|

feat: the order of the measure values in rows or cols, only works for PivotSheet (customValueOrder)

---

packages/s2-core/src/ui/tooltip/index.ts
packages/s2-react/src/components/sheets/base-sheet/index.tsx
packages/s2-react/src/components/sheets/table-sheet/index.tsx

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore
修复 react 组件层 未使用 合并后的 options, 导致 tooltip 报错的问题

fix: invalid react tooltip config

---

packages/s2-core/__tests__/bugs/issue-840-spec.ts
packages/s2-core/__tests__/data/simple-data.json
packages/s2-core/src/cell/base-cell.ts
packages/s2-core/src/cell/col-cell.ts
packages/s2-core/src/cell/table-col-cell.ts
packages/s2-core/src/facet/table-facet.ts

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore
修复 `明细表` 配置字段格式化, 会错误的格式列头的问题
```
const s2DataConfig = {
fields: {
columns: ['type', 'sub_type', 'area', 'province', 'city', 'price', 'cost'],
rows: [],
values: [],
valuesInCols: false
},
meta: [
{
field: 'price',
name: '价格',
formatter: (v) => `123`
},
{
field: 'city',
name: '城市',
formatter: (v) => `123`
},
]
}
```
| ![image](https://user-images.githubusercontent.com/21015895/144038853-ac837fa8-7d72-4229-807c-b35e617cd9c4.png) | ![image](https://user-images.githubusercontent.com/21015895/144038915-a3a3b17d-fa3f-47e8-8dc7-a6ccd571d614.png) |
close #840

fix(table): column should not be formatted

---

packages/s2-core/__tests__/bugs/issue-860-spec.ts
packages/s2-core/__tests__/data/data-issue-860.json
packages/s2-core/__tests__/unit/sheet-type/pivot-sheet-spec.ts
packages/s2-core/src/facet/layout/build-gird-hierarchy.ts

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore
close #860

fix: only omit undefined row cell

---

packages/s2-core/src/common/interface/frame.ts
packages/s2-core/src/facet/base-facet.ts
packages/s2-core/src/facet/header/frame.ts

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore
参考 ant-design table 的 [锁列阴影逻辑](https://ant.design/components/table-cn/#components-table-demo-fixed-columns-header)
1. 修复原有视窗左侧阴影错误逻辑
2. 新增视窗右侧阴影线
3. 移除废弃的 showCornerRightShadow 相关代码
|  ![before](https://gw.alipayobjects.com/zos/antfincdn/vmBV13FdC/before.gif)    |  ![after](https://gw.alipayobjects.com/zos/antfincdn/IpPBjBuHXn/after.gif) |

fix(frame): incorrect viewport splitline shadow

---

packages/s2-core/__tests__/unit/interaction/root-spec.ts
packages/s2-core/__tests__/unit/utils/merge-spec.ts
packages/s2-core/src/common/constant/options.ts
packages/s2-core/src/common/interface/s2Options.ts
packages/s2-core/src/interaction/index.ts
packages/s2-core/src/interaction/root.ts
packages/s2-core/src/interaction/row-column-resize.ts
packages/s2-react/__tests__/unit/utils/options-spec.ts
packages/s2-react/playground/index.tsx
packages/s2-react/src/components/sheets/strategy-sheet/index.tsx
s2-site/docs/common/interaction.zh.md
s2-site/docs/manual/advanced/interaction/custom.zh.md
s2-site/docs/manual/faq.zh.md

✨ Feature
1. 刷选功能支持配置是否开启 `interaction.brushSelection: boolean`
2. 趋势分析表关闭刷选功能
3. 优化注册交互的方式, 移动端关闭 `hover` 交互
4. 修复交互文档 demo 不显示的问题

feat(interaction): 支持禁用刷选功能

---

.github/workflows/auto-release-notify.yml
.github/workflows/auto-release.yml
.github/workflows/manual-release-notify.yml
.github/workflows/sync-site-lock-changelog-with-pr.yml

🔧 Chore
1. 将 自动发布 和 通知 分开, 方便管理和直接在 github 上 禁用通知
2. 修改发布通知策略, 调整为只有正式版发布时再发布通知
3. 修复发布成功后, 自动创建pr失败的问题

ci: 修复发布成功后自动创建pr失败, 以及调整推送策略

---

packages/s2-core/__tests__/unit/interaction/base-interaction/hover-spec.ts
packages/s2-core/src/cell/base-cell.ts
packages/s2-core/src/interaction/base-interaction/hover.ts

🐛 Bugfix
只有单元格文本被省略行列头才展示 tooltip

fix: :bug: 修复指标列头 hover 行为和维值列头不一致问题

---

packages/s2-core/__tests__/spreadsheet/scroll-spec.ts
packages/s2-core/__tests__/unit/interaction/event-controller-spec.ts
packages/s2-core/src/facet/base-facet.ts

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore
RT
| ![Kapture 2021-12-18 at 15 03 02](https://user-images.githubusercontent.com/21015895/146632635-3fc9dd62-5a58-4987-bfe7-875fac99515a.gif)| ![Kapture 2021-12-18 at 15 01 18](https://user-images.githubusercontent.com/21015895/146632603-d6bd4e3d-207f-4472-b32a-6fa00d829e55.gif)|

fix(scroll): 修复滚动表格后, 鼠标移动会重置已选中单元格 close #904

---

packages/s2-core/src/common/interface/s2DataConfig.ts
packages/s2-core/src/facet/layout/node.ts
packages/s2-react/playground/config.ts
packages/s2-react/playground/index.tsx
packages/s2-react/src/components/sheets/strategy-sheet/custom-col-cell.ts
packages/s2-react/src/components/sheets/strategy-sheet/custom-tooltip/custom-data-tooltip.tsx
packages/s2-react/src/components/sheets/strategy-sheet/index.tsx

🎨 Enhance
列头的文字 之前的处理是直接写死的 margin, 现在改为根据 当前列对应的 data cell 的 text 的坐标来做渲染 (即: 列头标题和数值对齐)

fix(startegysheet): 趋势分析表列头文字根据数值坐标动态计算

---

.github/workflows/test.yml
packages/s2-core/__tests__/spreadsheet/scroll-spec.ts
packages/s2-react/__tests__/spreadsheet/adaptive-spec.tsx
packages/s2-react/__tests__/spreadsheet/spread-sheet-spec.tsx
packages/s2-react/src/components/sheets/base-sheet/index.less

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore
canvas 的父容器 `container` 有 overflow: hidden, 导致没有出现滚动条, 无法滚动
| ![image](https://user-images.githubusercontent.com/21015895/147053661-3ae1f514-52d1-4956-9e65-f8a9865f13f7.png)| ![image](https://user-images.githubusercontent.com/21015895/147053830-e62fa6ab-6ac5-496d-af30-9cf48d080203.png) |

fix(components): 修复配置的宽度超过浏览器可视窗口宽度无法滚动的问题 close #889

---

packages/s2-react/src/components/sheets/strategy-sheet/custom-col-cell.ts

fix: 修复未配置 label时, hover 数值单元格报错, 并且列头文字上移的问题

---

packages/s2-core/__tests__/unit/dataset/table-dataset-spec.ts
packages/s2-core/__tests__/unit/facet/table-facet-spec.ts
packages/s2-core/src/data-set/table-data-set.ts
packages/s2-core/src/facet/base-facet.ts
packages/s2-core/src/facet/bbox/panelBBox.ts
packages/s2-core/src/facet/table-facet.ts
packages/s2-react/__tests__/spreadsheet/spread-sheet-spec.tsx

明细表数据为空时，滚动坐标、计算 index、dataset 的逻辑添加兜底。防止报错。

fix(table): 明细表数据为空时添加兜底

---

packages/s2-core/src/data-set/base-data-set.ts
packages/s2-core/src/sheet-type/pivot-sheet.ts
packages/s2-core/src/sheet-type/spread-sheet.ts
packages/s2-react/playground/index.tsx
packages/s2-react/src/components/sheets/strategy-sheet/index.tsx
packages/s2-react/src/hooks/useSpreadSheet.ts

🐛 Bugfix
* 当 `hierarchyType` 切换为 `customTree`， 需要重新构建 CustomTreePivotDataSet 和训练数据
* 移除 `SpreadSheet` 的 `dom` 属性

fix: 自定义目录树切换优化

---

packages/s2-core/src/common/interface/condition.ts
packages/s2-core/src/data-set/custom-tree-pivot-data-set.ts
packages/s2-core/src/facet/layout/build-row-custom-tree-hierarchy.ts
packages/s2-core/src/facet/pivot-facet.ts

🐛 Bugfix
* 自定义目录树情况下，默认为 hideMeasure 模式，由于走了统一的补query的逻辑，导致取数异常

fix: 修复自定义树取值路径错误问题

---

packages/s2-core/src/utils/export/index.ts

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore
当前s2中的复制功能是基于原生document.execCommand 实现的，由于它是同步操作，如果复制/粘贴大量数据，页面会出现卡顿。当前业务中，200万单元格的场景下，复制操作后页面直接崩溃。同时，document.execCommand  本身官方已经不推荐使用了，见：https://stackoverflow.com/questions/60217202/copy-text-to-clipboard-now-that-execcommandcopy-is-obsolete
改造方案采用了navigator.clipboard 的方案。Clipboard API 是下一代的剪贴板操作方法，比传统的document.execCommand()方法更强大、更合理。它的所有操作都是异步的，返回 Promise 对象，不会造成页面卡顿。而且，它可以将任意内容（比如图片）放入剪贴板。

fix: 优化复制功能，解决大数据量复制导致的页面崩溃问题

---

packages/s2-core/src/facet/base-facet.ts
packages/s2-core/src/facet/bbox/panelBBox.ts

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore
BUG 触发条件
- frozenRowHeader=false
- canvas 宽度不足
|   ![CleanShot 2022-01-07 at 16 17 03](https://user-images.githubusercontent.com/6716092/148513488-a2432bda-6aa5-4adb-8d3d-53181c6015fc.gif)   |   ![CleanShot 2022-01-07 at 16 15 18](https://user-images.githubusercontent.com/6716092/148513280-3f65c04c-9b9e-4817-9060-11271acf9f51.gif)   |

fix(facet): frozenRowHeader=false滚动时列头展示不全

---

packages/s2-core/src/facet/base-facet.ts
packages/s2-core/src/facet/header/col.ts

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore
在解决锁行列头展示不全的问题时，原有解决方法 https://github.com/antvis/S2/pull/975 是通过扩大列头宽度达到效果。
实际更好的是使用 header/col.ts 内部 clip 计算来解决
参考 https://github.com/antvis/S2/pull/975

refactor(facet): 在锁行时使用列头内部的clip实现列头滚动

---

packages/s2-core/__tests__/unit/interaction/root-spec.ts
packages/s2-core/__tests__/unit/utils/interaction/state-controller-spec.ts
packages/s2-core/__tests__/util/helpers.ts
packages/s2-core/src/interaction/shift-multi-selection.ts

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore
修复明细表中 序列号shift多选失效的问题

fix(interaction): shift区间多选在明细表序列号上失效

---

packages/s2-core/__tests__/unit/facet/bbox/panelBBox-spec.ts
packages/s2-core/src/cell/col-cell.ts
packages/s2-core/src/facet/base-facet.ts
packages/s2-core/src/facet/bbox/baseBBox.ts
packages/s2-core/src/facet/bbox/panelBBox.ts
packages/s2-core/src/facet/table-facet.ts

🐛 Bugfix
当表格的数据不足以撑满 Canvas 的宽高时，依然有一些场景，比如行列冻结，需要把行列放到 Canvas 的边缘。因此 panelBBox 的绘制范围必须包括整个 Canvas。之前 panelBBox 在数据不足时，是按数据实际的宽高去绘制的，就导致无法实现 #980 这样的效果。
改动点：
+ panelBBox 新增 viewportHeight 和 viewportWidth，内容区域如果不撑满 Canvas 时，可用用这两个属性来获取内容区的宽高。原来的 width 和 height 固定为按 Canvas 计算的最大可用宽高。
+ Frozen SplitLine 的渲染逻辑做修改和梳理
+ 修改之前 base facet 中引用的 panelBBox viewport 宽高为 viewportHeight 和 viewportWidth
+ 修正 getAdjustedScrollX 的逻辑，防止返回负值。
本次改动对交叉表无影响。
| ❌   ![image](https://user-images.githubusercontent.com/10339692/148877152-be63bf29-1182-46bb-a47d-d8c64b3cb312.png)| ✅  ![image](https://user-images.githubusercontent.com/10339692/148877104-d5c805cc-2ae4-4b5e-9217-4928100e31c9.png) |
close #980

fix(facet): 数据量较少时，维持 panelBBox 宽高

---

packages/s2-core/src/cell/corner-cell.ts
packages/s2-core/src/facet/pivot-facet.ts

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore
主要修复点
- 计算节点预估宽度时使用了值字段的 field 而非 meta.name，场景：
- 值在列头且为叶子节点
- 值在行头
- 计算节点预估宽度时，未考虑默认的 actionIcon 宽
- 优化 calculateRowNodesCoordinate 宽度计算
- grid 模式下，行头的每一列的宽度是一致的，直接取用 sampleNodeByLevel(node.width)
- calculateRowLeafNodesWidth 移除 tree 模式的宽度调用，且按功能更名为 calculateGridRowNodesWidth
- 值 field 设置了一个超长字符串
- 以下 gif 在 showDefaultHeaderActionIcon、valueInCols 反复切换录制
|   ![CleanShot 2022-01-07 at 14 12 29](https://user-images.githubusercontent.com/6716092/148500388-7542d89f-0441-44ac-b23b-b3678a8f5c06.gif) |   ![CleanShot 2022-01-07 at 14 07 46](https://user-images.githubusercontent.com/6716092/148499962-70cadfeb-1b4a-4f6f-8a4d-5f6cb39815c0.gif) |

fix(facet): 交叉表 compact 模式下行/列头宽度计算错误

---

packages/s2-core/src/facet/base-facet.ts

手机端滑动问题修改
✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore

fix：修复手机端部分区域不能滑动问题

---

packages/s2-react/package.json
packages/s2-react/src/components/sheets/pivot-sheet/index.tsx
yarn.lock

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore
点击下钻后，表组件 [drillFields](https://github.com/antvis/S2/blob/alpha/packages/s2-react/src/components/sheets/pivot-sheet/index.tsx#L17) 不再为空。
此时若表组件任意 props 变化，将陷入加载死循环。
1. PivotSheet.updateDrillDownOptions [依赖了 props]( https://github.com/antvis/S2/blob/alpha/packages/s2-react/src/components/sheets/pivot-sheet/index.tsx#L63)
2. 数据加载 effect [依赖 updateDrillDownOptions](https://github.com/antvis/S2/blob/alpha/packages/s2-react/src/components/sheets/pivot-sheet/index.tsx#L99)
3. fetchData 函数由父组件传入，其中若有 setState 等触发 props 更新操作，则死循环
updateDrillDownOptions 仅使用了 props 作为默认参数，作为 dep 驱动 hook 执行的必要性不大。
故改用 [useLatest](https://ahooks.js.org/zh-CN/hooks/use-latest) 保存最新的 props 供下游使用

fix: 加载下钻数据引起render死循环

---

packages/s2-react/__tests__/unit/utils/drill-down-spec.ts
packages/s2-react/src/components/sheets/pivot-sheet/index.tsx
packages/s2-react/src/utils/drill-down.ts

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore
修复下钻参数变更后交互未正确重置，主要改动点：
- `pivot-sheet/index.tsx ` 
- 去掉 useCallback，并把作为参数的外部变量改用 useLatest，规避层层闭包带来的错误引用。
- 精简 hooks deps，消除不相关 deps 变动带来的 effects
- `utils/drill-down.ts`
- 添加 icon 时，避免 stringify 开销，改用 ref 记录 icon 增减
截图中 playground 增加了一个 switch 开关的，用于切换下钻维度个数。
维度切换后，可见的问题有：
- 【杭州】左侧下钻 icon 仍然是展开态
- 点击下钻 icon 后，维度仍是选中态
- 点击下钻维度后，发现数据有重复（上一次的未清除）
|  ![CleanShot 2022-01-18 at 17 52 56](https://user-images.githubusercontent.com/6716092/149913811-b2657718-2990-4cef-8e12-6618666dbff8.gif)      |  ![CleanShot 2022-01-18 at 17 51 30](https://user-images.githubusercontent.com/6716092/149913554-69097fc4-5878-402e-9e23-46283a4683cf.gif)     |

fix: 下钻参数变更后未正确重置

---

packages/s2-core/src/utils/dataset/pivot-data-set.ts
packages/s2-react/src/components/sheets/pivot-sheet/index.tsx
s2-site/docs/api/components/drill-down.zh.md

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore
因为组件 memo，外界想 re-render 必须传入新的 props.partDrillDown，而修改 `props.partDrillDown.clearDrillDown` 并不需要重渲，所以修改 deps 数组以更精细地控制重渲。
当 rowPivot 中存在 `杭州 -> 西湖区 -> 男` 时，想删除 nodeId=`root[&]杭州[&]技工[&]男` 的下钻数据。
此时 path 解析为 `['root', '杭州', '技工', '男']`，原逻辑会意外跳过不存在的 meta 节点，如本例的 `技工`。
|  ![CleanShot 2022-01-19 at 17 43 38](https://user-images.githubusercontent.com/6716092/150105332-e9ad13dc-2796-45b2-877f-f07697a71a13.gif)  |  ![CleanShot 2022-01-19 at 17 41 44](https://user-images.githubusercontent.com/6716092/150104960-7ceca985-8365-418d-bdee-151496dbad4a.gif) |

fix(drilldown): 修复clearDrillDown下钻清除错误及重渲逻辑

---

packages/s2-core/src/facet/base-facet.ts
packages/s2-core/src/facet/table-facet.ts
packages/s2-react/src/components/sheets/base-sheet/index.tsx
packages/s2-react/src/components/sheets/table-sheet/index.tsx

修复 https://github.com/antvis/S2/issues/1017 中 setOptions 时 scrollSpeedRatio 取值不正确的问题。
修复 https://github.com/antvis/S2/issues/1016 中 React 组件未读取 pagination.total 的问题
close https://github.com/antvis/S2/issues/1017
close https://github.com/antvis/S2/issues/1016

fix(facet): scroll speed options & pagination totals

---

packages/s2-core/__tests__/spreadsheet/spread-sheet-spec.ts
packages/s2-core/__tests__/unit/sheet-type/pivot-sheet-spec.ts
packages/s2-core/src/sheet-type/spread-sheet.ts

🐛 Bugfix
`destroy` 方法没有销毁 g 生成的 `canvas` 节点, 如果公用一个 container 会导致销毁后再创建新表格时, 页面上会出现两个表格
```ts
const pivotSheet = new PivotSheet(container, mockDataConfig, s2options);
pivotSheet.render();
pivotSheet.destroy();
const tableSheet = new TableSheet(container, mockDataConfig, s2options);
tableSheet.render();
```

fix(s2-core): 修复延迟销毁表格时没有移除canvas节点的问题 close #1011

---

packages/s2-core/src/ui/tooltip/index.less
packages/s2-react/src/components/tooltip/components/simple-tips.tsx
packages/s2-react/src/components/tooltip/components/summary.tsx
packages/s2-react/src/components/tooltip/index.less

🎨 Enhance
🐛 Bugfix
1. 修复单元格内容过长tooltip显示不全
2. 简化一些样式
3. 兼容其他可能存在的过长的场景
| ![image](https://user-images.githubusercontent.com/21015895/150480644-01bcd280-4960-418f-bdff-1995928c7c0b.png) | ![image](https://user-images.githubusercontent.com/21015895/150480856-6fba6ff0-a2a7-4007-894d-32a468106e38.png) |

fix(tooltip): 修复单元格文字过长时 tooltip 显示被截断 close #1028

---

packages/s2-core/__tests__/unit/interaction/base-interaction/hover-spec.ts
packages/s2-core/__tests__/util/helpers.ts
packages/s2-core/src/common/interface/tooltip.ts
packages/s2-core/src/interaction/base-interaction/hover.ts
packages/s2-core/src/sheet-type/spread-sheet.ts
packages/s2-core/src/utils/tooltip.ts
packages/s2-react/playground/config.ts
packages/s2-react/playground/index.tsx

🐛 Bugfix
RT.
```ts
meta: [
{
field: 'number',
name: '数量数量数量数量数量数量数量数量数量数量数量数量数量数量数量数量',
formatter: (v) => {
return `${v} 元`;
},
},
]
```
| ![image](https://user-images.githubusercontent.com/21015895/150498023-cb0b985a-8b00-4cf0-a1ce-b2b7417a22ba.png) | ![image](https://user-images.githubusercontent.com/21015895/150498006-44ff9f6c-0ef2-44b2-b6cf-2504cbd5f4ca.png) |

fix(tooltip): 修复明细表列头的 tooltip 内容被错误的格式化 close #998

---

packages/s2-core/__tests__/unit/dataset/pivot-dataset-spec.ts
packages/s2-core/src/utils/sort-action.ts

🐛 Bugfix
🔧 Chore
fix: 透视表无序未按原顺序展示问题
|  ![first](https://user-images.githubusercontent.com/19166133/151515548-d2ba60ec-2c80-4d9e-aca6-3e2645a01ef7.gif)     | ![after](https://user-images.githubusercontent.com/19166133/151515638-a51d7a30-586e-4504-a2db-953e8f5af009.gif)     |

fix: 透视表无序未按原顺序展示问题

---

packages/s2-core/__tests__/unit/utils/merge-spec.ts
packages/s2-core/__tests__/unit/utils/text-spec.ts
packages/s2-core/src/common/constant/options.ts
packages/s2-core/src/common/constant/tooltip.ts
packages/s2-core/src/common/interface/tooltip.ts
packages/s2-core/src/data-set/pivot-data-set.ts
packages/s2-core/src/interaction/base-interaction/click/data-cell-click.ts
packages/s2-core/src/interaction/base-interaction/click/row-column-click.ts
packages/s2-core/src/sheet-type/pivot-sheet.ts
packages/s2-core/src/sheet-type/table-sheet.ts
packages/s2-react/__tests__/unit/utils/options-spec.ts
packages/s2-react/src/common/constant/options.ts
packages/s2-react/src/common/icons/html-icon.less
packages/s2-react/src/components/sheets/strategy-sheet/index.tsx
packages/s2-react/src/components/tooltip/components/operator/index.tsx
packages/s2-react/src/components/tooltip/index.tsx
s2-site/docs/common/custom-tooltip.zh.md
s2-site/docs/common/tooltip.zh.md
s2-site/docs/manual/basic/tooltip.zh.md
s2-site/examples/react-component/tooltip/demo/custom-operation.tsx
s2-site/examples/react-component/tooltip/demo/custom-show-tooltip.tsx
s2-site/examples/react-component/tooltip/demo/meta.json

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore
1. 支持自定义tooltip操作项
2. 菜单的 id 改名为 `key`, 保持和 antd 的 Menu 组件概念统一
3. tooltip 操作项配置 新增 `menus` 属性用于自定义菜单
```diff
tooltip: {
operation: {
hiddenColumns: true,
+     menus: [{}]
},
},
};
```
3. 优化操作项点击事件处理逻辑, 之前只能在最外层监听 onClick, 根据 key 来做判断, 不是很方便
```tsx
const operation = {
onClick({ key } ){
if(key === '1') ...
if(key === '2') ...
},
menus: [{ key: '1' }, { key: '1' }]
}
```
现在 `s2.showTooltip({ operation })` 和 `s2Options.tooltip.operation` 都可以对单个菜单直接监听点击事件, 更方便
```tsx
const operation = {
onClick() {
console.log('任意操作点击')
},
menus: [
{
key: 'custom-a',
text: '操作1',
icon: 'Trend',
onClick: () => {
console.log('操作1点击');
},
},
{
key: 'custom-b',
text: '操作2',
icon: 'EyeOutlined',
onClick: () => {
console.log('操作2点击');
},
},
],
}
```
4. …

feat(tooltip): 支持自定义 tooltip 操作项

---

packages/s2-core/__tests__/unit/utils/tooltip-spec.ts
packages/s2-core/src/facet/base-facet.ts
packages/s2-core/src/utils/tooltip.ts

🐛 Bugfix
修复配置不同类型单元格 tooltip 配置时, 没有 merge 父级配置, 造成配置丢失的问题
由于使用的是 {...}, 当有相同 key 时, 配置会被覆盖掉而不是继承

fix(tooltip): 修复不同类型的单元格配置合并问题

---

packages/s2-core/__tests__/unit/interaction/root-spec.ts
packages/s2-core/src/cell/data-cell.ts
packages/s2-core/src/interaction/brush-selection.ts
packages/s2-core/src/interaction/root.ts
packages/s2-core/src/utils/interaction/state-controller.ts
packages/s2-react/playground/index.tsx

🐛 Bugfix
修复 https://github.com/antvis/S2/pull/944
https://github.com/antvis/S2/pull/944/files#diff-d947b89145acaac6eced6156a5a5aad0e6837759768fd083643405b5044bcb69L338 导致的刷选不显示预选框, 行列多选功能异常等交互问题
| ![image](https://user-images.githubusercontent.com/21015895/153127238-c72e2d3d-ec1d-4236-a278-2a549f68501f.png) | ![image](https://user-images.githubusercontent.com/21015895/153127138-de4cc186-e941-471e-8012-751a6537a3bb.png) |
| ![image](https://user-images.githubusercontent.com/21015895/153127264-79f6a5d5-3e82-4252-a4f7-837de3153212.png) |  ![image](https://user-images.githubusercontent.com/21015895/153127180-2fb5e3be-d5af-4c2b-8ac3-c620b1724647.png) |
ref #944

fix(interaction): 修复刷选不显示预选框, 行列多选功能异常等交互问题

---

packages/s2-core/__tests__/unit/utils/tooltip-spec.ts
packages/s2-core/src/common/interface/tooltip.ts
packages/s2-core/src/interaction/base-interaction/click/data-cell-click.ts
packages/s2-core/src/interaction/base-interaction/click/row-column-click.ts
packages/s2-core/src/utils/tooltip.ts
packages/s2-react/src/components/sheets/strategy-sheet/index.tsx
s2-site/docs/common/custom-tooltip.zh.md
s2-site/docs/manual/basic/tooltip.zh.md
s2-site/examples/react-component/tooltip/demo/custom-operation.tsx

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore
tooltip 自定义操作项新增 `visible: boolean | (cell) => boolean` 属性, 支持嵌套, 用于根据单元格信息动态显示的场景
```ts
tooltip: {
operation: {
menus: [
{
key: 'custom-a',
text: '操作 1',
icon: 'Trend',
visible: false,
},
{
key: 'custom-b',
text: '操作 2',
icon: 'EyeOutlined',
visible: (cell) => {
// 叶子节点不显示
const meta = cell.getMeta()
return meta.isLeaf
},
},
],
},
},
};
```

feat(tooltip): tooltip 操作项支持动态显示

---

packages/s2-core/__tests__/unit/utils/sort-action-spec.tsx
packages/s2-core/src/utils/sort-action.ts
packages/s2-react/src/components/advanced-sort/index.tsx

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore
见 bug 描述
| 见 bug 描述|请等待下方 gif 加载，可点击查看更流畅~|
[![uw7xj-kcgl8.gif](https://i.postimg.cc/Nfkf2qMf/uw7xj-kcgl8.gif)](https://postimg.cc/bsdj45kK)
https://github.com/antvis/S2/issues/1065

fix: 当不同父节点下存在相同子节点时高级排序出错 close #1065

---

packages/s2-core/src/common/constant/events/basic.ts
packages/s2-core/src/common/interface/emitter.ts
packages/s2-core/src/facet/table-facet.ts
packages/s2-core/src/sheet-type/pivot-sheet.ts
packages/s2-core/src/sheet-type/spread-sheet.ts
packages/s2-react/src/components/sheets/interface.ts
packages/s2-react/src/hooks/useEvents.ts
packages/s2-react/src/utils/drill-down.ts
s2-site/docs/api/components/sheet-component.zh.md

✨ Feature
feat(pivot): 新增组内排序时触发回调事件 [onSortChange 事件]
[feat: pivot 添加 S2Event.RANGE_SORT 和 S2Event.RANGE_SORTED 事件](https://github.com/antvis/S2/commit/f9ebdd116ed187c71a6db003ccc15ad0746b9680)
[fix: 删除从 store 中获取 params，历史遗留](https://github.com/antvis/S2/commit/fcf2086a0705a6d87e2e6cf9227045ec9fe967aa)
提交说明：
1. 以前向外抛出的 onListSort（排序回调，用于做自定义排序） 事件没有生效，因为 [sortParams. sortFunc](https://s2.antv.vision/zh/docs/api/general/S2DataConfig#sortfuncparam) 具有相同功能，估不重复定义。现向外抛出  onSortChange（组内排序时触发回调事件） 事件，用户可拿到每次排序的规则。
2. 待明细表参数统一后抛出 onSortChange。
🎨 Enhance
🐛 Bugfix
🔧 Chore

feat(pivot): 新增组内排序时触发回调事件

---

.github/workflows/issue-close-require.yml
.github/workflows/issue-labeled.yml
.github/workflows/site-build-notify.yml
.github/workflows/sync-site-lock-changelog-with-pr.yml

🔧 Chore
1. 增加 github pages 部署通知
2. 修复一些自动回复的文案和错误描述
3. 修复自动同步changelog 机器人无法触发 lint 和 test ci 的问题

ci: 新增官网部署通知

---

packages/s2-core/src/utils/layout/add-totals.ts

✨ Feature
当用户配置了小计后，无论小计维度有几个子维度值，始终展示小计项。
字段配置
```
fields: {
rows: ['province', 'city', 'area'],
columns: ['type', 'subType'],
values: ['count'],
}
```
总、小计配置
```
totals: {
row: {
reverseLayout: true,
reverseSubLayout: true,
showGrandTotals: true,
showSubTotals: true,
subTotalsDimensions: ['province', 'city'],
},
col: {
reverseLayout: true,
reverseSubLayout: true,
showGrandTotals: true,
showSubTotals: true,
subTotalsDimensions: ['type'],
},
}
```
- row: `四川` 下只有 `成都` 一个子维度
- col: `休闲` 下只有 `公园` 一个子维度
|  <img width="600" alt="CleanShot 2022-02-14 at 14 48 03@2x" src="https://user-images.githubusercontent.com/6716092/153813826-2296aa16-79dc-40c7-b8fa-de7310f85fbc.png">     |  <img width="604" alt="CleanShot 2022-02-14 at 14 46 48@2x" …

feat: 全量展示小计项

---

packages/s2-core/__tests__/unit/cell/data-cell.spec.ts
packages/s2-core/src/cell/data-cell.ts
packages/s2-core/src/cell/row-cell.ts
packages/s2-core/src/common/interface/basic.ts
packages/s2-core/src/utils/export/index.ts
packages/s2-core/src/utils/tooltip.ts
s2-site/docs/api/general/S2DataConfig.zh.md

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore
close #994

feat: Meta内formatter增加入参提供完整数据 close #994

---

packages/s2-react/src/hooks/usePagination.ts

🐛 Bugfix
使用表格 react 组件时，当异步获取数据更新 props.dataCfg 后，pagination 组件 total 未更新，导致分页功能 BUG。
- 初始化无数据，点击 get data 后会载入 3 条数据
- 明细表也进行了同种测试
|   ![CleanShot 2022-02-15 at 11 30 11](https://user-images.githubusercontent.com/6716092/153987396-dee36b24-3a76-4800-b6a8-b5ca1ffdb7a7.gif)      |  ![CleanShot 2022-02-15 at 11 29 19](https://user-images.githubusercontent.com/6716092/153987328-b3c5774f-fdb7-449f-9d6c-e4633860b630.gif)    |

fix: 初始化后更新dataCfg不触发分页total变化

---

packages/s2-core/src/common/interface/tooltip.ts
packages/s2-react/src/components/tooltip/components/operator/index.tsx
packages/s2-react/src/components/tooltip/custom-tooltip.tsx
packages/s2-react/src/components/tooltip/index.tsx
packages/s2-react/src/components/tooltip/interface.ts
s2-site/docs/common/custom-tooltip.zh.md
s2-site/docs/manual/basic/tooltip.zh.md
s2-site/examples/react-component/tooltip/demo/custom-operation.tsx

✨ Feature
menu 的 onClick 事件增加 cell 参数, 方便拿到当前 tooltip 对应的单元格信息
```ts
tooltip: {
operation: {
menus: [
{
key: '操作1',
text: '操作1',
onClick(cell) {
console.log(cell);
},
children: [
{
key: '操作2',
text: '操作2',
onClick(cell) {
console.log(cell);
},
},
],
},
],
},
},
```
close #1106

feat(tooltip): tooltip 自定义操作项点击事件透出 cell 信息 close #1106

---

packages/s2-core/__tests__/bugs/issue-1014-spec.ts
packages/s2-core/src/cell/col-cell.ts
packages/s2-core/src/cell/corner-cell.ts
packages/s2-core/src/cell/header-cell.ts
packages/s2-core/src/cell/row-cell.ts
packages/s2-core/src/cell/table-col-cell.ts
packages/s2-core/src/facet/base-facet.ts
packages/s2-core/src/facet/header/col.ts
packages/s2-core/src/facet/table-facet.ts

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore
```js
meta: [
{
field: 'number',
name: '数量',
},
{
field: 'province',
name: '省份',
formatter: () => 'province',
},
{
field: 'city',
name: '城市',
formatter: () => 'city',
},
{
field: 'type',
name: '类别',
formatter: () => 'type',
},
{
field: 'sub_type',
name: '子类别',
},
],
```
| ![image](https://user-images.githubusercontent.com/17964556/155101431-a6e978d8-dbee-469a-a707-067e3ab8e139.png)    | ![image](https://user-images.githubusercontent.com/17964556/155101302-71269786-c5e6-4a15-aedf-b8d7c8e36bbf.png)   |
close #1014

fix: 修复头部cell错误使用meta中formatter的问题，close #1014

---

packages/s2-core/src/common/constant/basic.ts
packages/s2-core/src/facet/table-facet.ts

修复明细表阴影逻辑，与交叉表一致 #898 遵循 ant-design 阴影逻辑。并将单次 render 分割线，改为滚动后 render，便于重绘。
```
{
frozenRowCount: 1,
frozenTrailingRowCount: 1,
frozenColCount: 1,
frozenTrailingColCount: 1,
}
```
|     ![CleanShot 2022-02-22 at 21 11 51](https://user-images.githubusercontent.com/6716092/155139225-fa066f9c-57ee-4d3e-86b9-632da3d5b0a6.gif)   |    ![CleanShot 2022-02-22 at 21 09 48](https://user-images.githubusercontent.com/6716092/155138947-64a3f5be-f655-4e02-b7f7-187353dc3464.gif)   |

fix: 明细表锁行/列时分割线阴影显隐逻辑

---

packages/s2-core/src/cell/corner-cell.ts

🐛 Bugfix
fix: corner 事件监听失效 (S2Event.CORNER_CELL_CLICK)
没有填充 fill 的时候， 只有点击 Corner cell 的Text 才能触发 S2Event.CORNER_CELL_CLICK 事件。
|![corner事件触发-error](https://user-images.githubusercontent.com/20497176/155467663-99eeae58-3095-41b9-9156-93e21a024835.gif)|![corner事件触发-right](https://user-images.githubusercontent.com/20497176/155467674-14e212f8-a1ce-4d0a-a83a-14f771360181.gif)|

fix: corner 事件监听失效

---

packages/s2-core/__tests__/unit/interaction/event-controller-spec.ts
packages/s2-core/src/interaction/event-controller.ts
packages/s2-react/playground/index.tsx
s2-site/examples/case/data-preview/demo/index.tsx
s2-site/examples/case/data-preview/index.zh.md

🐛 Bugfix
只在焦点在表格区域时才触发 keydown 和 keyup 事件
1. 修复复制表格外任意文字, 依然触发表格复制事件, 导致无法复制文字的问题
| ![Kapture 2022-02-24 at 15 40 15](https://user-images.githubusercontent.com/21015895/155479792-70f679b0-b290-4979-a0ab-c169a896b544.gif) | ![Kapture 2022-02-24 at 15 38 11](https://user-images.githubusercontent.com/21015895/155479483-c6586b0e-c60b-4352-b8e1-4d81fbdfb0fa.gif) |

fix(interaction): 修复开启复制后, 无法复制表格外的文字

---

packages/s2-core/__tests__/unit/facet/layout/row-node-width-spec.ts
packages/s2-core/src/common/constant/options.ts
packages/s2-core/src/facet/pivot-facet.ts

✨ Feature
* 允许用户自定义平铺模式下当的行头单元格宽度（`layoutWithType` 为 `adaptive` 时除外）
* 补充单测
close #1093

feat: :sparkles: 允许用户自定义行头单元格宽度

---

packages/s2-react/src/components/switcher/dimension/index.tsx
packages/s2-react/src/components/switcher/interface.ts
packages/s2-react/src/components/switcher/item/index.less
packages/s2-react/src/components/switcher/item/index.tsx
s2-site/docs/api/components/switcher.zh.md
s2-site/docs/manual/basic/analysis/switcher.zh.md
s2-site/examples/react-component/switcher/demo/pure-switcher.tsx

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore
通过`allowEmpty`控制当前维度最后一个子项拖拽行为：
```js
const switcherFields = {
rows: {
items: [{ id: 'province' }, { id: 'city' }],
allowEmpty: false // 行头不能为空
},
columns: {
items: [{ id: 'type' }],
allowEmpty: true  // 行头可以为空
},
values: {
selectable: true,
items: [{ id: 'price' }, { id: 'cost' }],
},
};
```

feat: 维度切换组件增加allowEmpty配置 close #533

---

packages/s2-core/__tests__/spreadsheet/scroll-spec.ts
packages/s2-core/__tests__/unit/sheet-type/pivot-sheet-spec.ts
packages/s2-core/src/facet/base-facet.ts
packages/s2-core/src/sheet-type/spread-sheet.ts
packages/s2-react/__tests__/unit/hooks/useResize-spec.ts
packages/s2-react/src/components/sheets/base-sheet/index.less
packages/s2-react/src/components/sheets/base-sheet/index.tsx
packages/s2-react/src/hooks/useResize.ts
packages/s2-react/src/hooks/useSpreadSheet.ts
s2-site/docs/api/basic-class/spreadsheet.zh.md
s2-site/docs/manual/advanced/adaptive.zh.md
s2-site/docs/manual/advanced/hd-adapter.zh.md
s2-site/docs/manual/faq.zh.md

🐛 Bugfix
1.  原本 adaptive 以下配置时，sheetComponent 自适应不包含 header 和 page， 现将 header 和 page 包含其中。
```js
adaptive = {true} 
adaptive={{
width: true,
height: false,
getContainer: () => adaptiveRef.current // 或者使用 document.getElementById(containerId)
}
```
2. 将 changeSize 更改为 changeSheetSize。因为 G 的 container 和 S 的 container 上都存在 changeSize 方法，在调用时，IDE会错误识别，跑单测时，引用方法出现错误的问题。（但这样是不是 break change 了 👀
|<img width="1336" alt="image" src="https://user-images.githubusercontent.com/20497176/155474195-ec205e96-710e-4a23-b261-1d4adf7af556.png"> | <img width="1388" alt="image" src="https://user-images.githubusercontent.com/20497176/155473358-16af1ccb-a2c9-427d-aefc-1cd28be40688.png">|
close #1133

feat: adaptive 的 container 自适应包含 header 和 page

---

packages/s2-core/__tests__/spreadsheet/interaction-tooltip-spec.ts
packages/s2-core/__tests__/spreadsheet/tooltip-spec.ts
packages/s2-core/__tests__/unit/sheet-type/pivot-sheet-spec.ts
packages/s2-core/__tests__/util/helpers.ts
packages/s2-core/src/common/interface/tooltip.ts
packages/s2-core/src/sheet-type/spread-sheet.ts
packages/s2-core/src/ui/tooltip/index.ts
packages/s2-react/__tests__/spreadsheet/tooltip-spec.tsx
s2-site/docs/common/tooltip.zh.md
s2-site/docs/manual/basic/tooltip.zh.md

✨ Feature
1. tooltip 支持自定义挂载节点
```html
<div class="container" />
```
```ts
tooltip: {
getContainer: () => document.querySelector('.container')
}
}
```
2. 修复未开启 tooltip `showTooltip: false` 时, 还是会渲染节点的问题
| ![image](https://user-images.githubusercontent.com/21015895/155691511-37bd90c0-11fd-45c6-88c4-c606254880b0.png)| ![image](https://user-images.githubusercontent.com/21015895/155691481-e5fcea80-37e8-4180-9cae-5b2bf5db0bbc.png) |

feat(tooltip): 支持自定义挂载节点

---

packages/s2-react/__tests__/unit/hooks/useResize-spec.ts
packages/s2-react/__tests__/unit/hooks/useSpreadSheet-spec.ts
packages/s2-react/src/hooks/useResize.ts

🎨 Enhance
options 改变时在 useSpreadSheet 中已经 render 过一次了，useResize 里不需要重复 render
| ❌  ![image](https://user-images.githubusercontent.com/10885578/157438106-d4aa1692-dcf4-4f17-a69b-7b52793e56fd.png) | ✅  ![image](https://user-images.githubusercontent.com/10885578/157438135-51638d36-c06a-481a-a765-5244a6439164.png)|

perf(useResize): :zap: 减少当 adaptive 为false时宽高改变引发的重复渲染

---

packages/s2-core/__tests__/unit/utils/cell/cell-spec.ts
packages/s2-core/src/cell/col-cell.ts
packages/s2-core/src/utils/cell/cell.ts
s2-site/docs/manual/advanced/custom/cell-align.zh.md

✨ Feature
- 列头值维度 textStyle
- before：取数据格 dataCell 的 textStyle
- after：取列头 colCell 的 textStyle
- 列头非叶子节点支持滚动情况下始终居中
- before：只支持 center 居中
- after：新支持 left 和 right
- colCell.textAlign 不支持 left、right 
- dataCell.textAlign 会影响 colCell 指标 align
| 表格紧凑不滚动时效果 | 表格宽松滚动时效果 |
|    ![CleanShot 2022-03-02 at 17 47 30](https://user-images.githubusercontent.com/6716092/156337178-8cbdda78-0968-4157-ba50-a0c4d1873cb6.gif)    | ![CleanShot 2022-03-02 at 17 46 07](https://user-images.githubusercontent.com/6716092/156336969-3c19f065-a24e-4c98-a8a6-478b44768c0d.gif)   |
为方便对比效果，colCell.cell.padding 设置为 `left=10`、`right: 30`
| 表格紧凑不滚动时效果 | 表格宽松滚动时效果（textAlign 各取 left、center、right） |
|  ![CleanShot 2022-03-03 at 15 58 …

feat: 列头滚动场景下非维度文字支持左/右对齐

---

packages/s2-react/__tests__/unit/hooks/useResize-spec.ts
packages/s2-react/src/hooks/useResize.ts
packages/s2-react/src/hooks/useSpreadSheet.ts
s2-site/docs/manual/advanced/adaptive.zh.md

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore

fix: 开启 adaptive 时，options 更改后, 宽高不跟随 wrapperRef 的宽高改变

---

packages/s2-core/__tests__/unit/interaction/data-cell-multi-selection-spec.ts
packages/s2-core/__tests__/unit/interaction/event-controller-spec.ts
packages/s2-core/src/common/constant/interaction.ts
packages/s2-core/src/interaction/brush-selection.ts
packages/s2-core/src/interaction/data-cell-multi-selection.ts
packages/s2-core/src/interaction/event-controller.ts

支持 Ctrl 键触发多选 Cell。
对之前的 Keydown 和 Keyup 事件焦点触发的逻辑做了一下改动。如果只在点击后才能监听。那只能点击一下画布才能按键多选。但用户一般会先按键然后点击画布。体验并不好。所以这里改成针对复制和 Esc 键操作才判断是否有焦点。

fix: 支持 Ctrl 键触发多选 Cell

---

packages/s2-core/__tests__/unit/interaction/event-controller-spec.ts
packages/s2-core/__tests__/unit/interaction/selected-cell-move-spec.ts
packages/s2-core/__tests__/unit/utils/interaction/state-controller-spec.ts
packages/s2-core/src/interaction/range-selection.ts
packages/s2-core/src/interaction/selected-cell-move.ts
packages/s2-core/src/utils/interaction/select-event.ts
packages/s2-core/src/utils/interaction/state-controller.ts

✨ Feature
需要支持的快捷键类型
以下使用META键替代WINDOWS下的CTRL和MacOS下的COMMAND
1. META + A
全选表格内容（已支持）
2. 方向键
按照上下左右方向键移动选中光标（已支持）
2. META + SHIFT + 方向键
上： 选中当前单元格所在列的包括当前单元格以及以上的所有单元格。
下： 选中当前单元格所在列的包括当前单元格以及以下的所有单元格。
左： 选中当前单元格所在行的包括当前单元格以及以左的所有单元格。
右： 选中当前单元格所在行的包括当前单元格以及以右的所有单元格。
单元格区块操作：多（行/列）复用以上逻辑。
3. META + 方向键
上： 移动选中当前单元格所在列的最上方单元格。
下： 移动选中当前单元格所在列的最下方单元格。
左： 移动选中当前单元格所在行的最左方单元格。
右： 移动选中当前单元格所在行的最右方单元格。
单元格区块操作：将以第一个选中的单元格为基础。
4. SHIFT + 方向键
上： 增量选中当前单元格所在列的上方一个单元格。
下： 增量选中当前单元格所在列的下方一个单元格。
左： 增量选中当前单元格所在行的左方一个单元格。
右： 增量选中当前单元格所在行的右方一个单元格。
单元格区块操作：多（行/列）复用以上逻辑。

feat(derection): 方向键加快捷键操作

---

packages/s2-core/__tests__/bugs/issue-1191-spec.ts
packages/s2-core/src/cell/base-cell.ts

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore
之前的`linkTextFill`是按照pc和mobile端处理处理的，其中：
* pc 只添加下划线
* mobile 才应用 `linkTextFill`配置
对用户来说极具迷惑性，现在pc和mobile都统一应用`linkTextFill`，唯一区别仅有：pc端添加下划线
主题配置：
```js
{ 
theme: {
rowCell: {
text: {
linkTextFill: 'red',
},
bolderText: {
linkTextFill: 'red',
},
}
}
```
|   ![image](https://user-images.githubusercontent.com/17964556/158771961-dfdb97d3-6319-4f74-94db-8fea8a5df8af.png)   | ![image](https://user-images.githubusercontent.com/17964556/158771700-239c1f1f-b884-4928-a4fc-a49e954159c2.png)   |

fix: 修复linkTextFill不生效的问题, close #1191

---

packages/s2-core/__tests__/unit/utils/facet-spec.ts
packages/s2-core/src/utils/facet.ts

getIndexRangeWithOffsets 添加了对不合法输入的判断。

fix: 有自定义行高，但表格高度为 0 时卡死的问题

---

packages/s2-core/__tests__/unit/sheet-type/pivot-sheet-spec.ts
packages/s2-core/src/sheet-type/spread-sheet.ts
packages/s2-react/__tests__/unit/hooks/useSpreadSheet-spec.ts
packages/s2-react/playground/index.tsx
packages/s2-react/src/hooks/useResize.ts
packages/s2-react/src/hooks/useSpreadSheet.ts

🐛 Bugfix
原因是因为 s2Options 的宽高修改了, 但是没有修改 `g-canvas` 生成的 `canvas` dom 节点的宽高
| ![Kapture 2022-03-18 at 15 43 42](https://user-images.githubusercontent.com/21015895/158958130-cabd9182-2d52-4ad4-a880-f99bdd36579d.gif) | ![Kapture 2022-03-18 at 15 07 55](https://user-images.githubusercontent.com/21015895/158953480-e907a4ed-a4a4-45ee-b03f-01f7b804cb36.gif) |
close #1159

fix(react): 修复宽高改变后未重新渲染表格的问题 close #1193

---

packages/s2-react/playground/index.tsx
packages/s2-react/src/hooks/useResize.ts

🐛 Bugfix
Safari 上不支持 borderBoxSize 属性, 导致 Math floor 的宽度为 `NaN`, 导致渲染异常
| ![image](https://user-images.githubusercontent.com/21015895/158965117-2a42a86e-6fd1-42ac-a57b-516341494321.png) | ![image](https://user-images.githubusercontent.com/21015895/158965029-465b6c4e-bbd1-452e-a928-b3b644f7c644.png) |

fix(adaptive): 修复开启自适应后 组件在  Safari 上无法渲染的问题 close #1164

---

packages/s2-core/__tests__/spreadsheet/spread-sheet-spec.ts
packages/s2-core/src/ui/hd-adapter/index.ts
packages/s2-react/playground/index.tsx

🐛 Bugfix
window.visualViewport 的 `resize` 事件在浏览器窗口大小改变时也能触发, 会产生一次额外的渲染
优化: 在 pixelRatio 改变后才重新渲染
| ![image](https://user-images.githubusercontent.com/21015895/159221073-71326d75-232f-49eb-a126-6f561d15962a.png) |  ![Kapture 2022-03-21 at 15 44 23](https://user-images.githubusercontent.com/21015895/159221242-4dd84d46-ac9c-4850-8648-4e170531ad6f.gif) |

fix: 未开启自适应, 改变浏览器窗口大小, 会导致表格重新渲染 close #1197

---

packages/s2-core/__tests__/unit/facet/table-facet-spec.ts
packages/s2-core/__tests__/unit/sheet-type/table-sheet-spec.ts
packages/s2-core/__tests__/unit/utils/interaction/select-event-spec.ts
packages/s2-core/src/facet/table-facet.ts
packages/s2-core/src/interaction/base-interaction/click/row-column-click.ts
packages/s2-core/src/interaction/data-cell-multi-selection.ts
packages/s2-core/src/sheet-type/table-sheet.ts
packages/s2-core/src/utils/interaction/select-event.ts

+ 行列头多选支持 Ctrl 键
+ 明细表排序增加单元测试 && 简单重构

fix: 行列头多选支持 Ctrl 键

---

packages/s2-core/__tests__/unit/facet/table-facet-spec.ts
packages/s2-core/src/facet/table-facet.ts

🐛 Bugfix
修复row高度大于canvas高度后导致的index计算错误

fix(table-facet): 修复row高度大于canvas高度后导致的index计算错误

---

packages/s2-core/__tests__/unit/utils/export/copy-spec.ts
packages/s2-core/src/utils/export/copy.ts

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore
单元格内存在"字符会导致行内换行不生效 所以把"转成'再复制

fix: 单元格内换行存在"字符

---

packages/s2-core/__tests__/unit/utils/facet-spec.ts
packages/s2-core/src/utils/facet.ts

…min and max height
🐛 Bugfix
当minHeight等于maxHeight和某个heights节点时，yMax会因为findIndex的startIndex设置问题导致找不到当前节点所在index。

fix(facet): 修复getIndexRangeWithOffsets在minHeight和maxHeight相等的情况下返回错误的情况

---

packages/s2-react/__tests__/spreadsheet/drill-down-spec.tsx
packages/s2-react/src/components/sheets/pivot-sheet/index.tsx

🐛 Bugfix
说明：当表格 react 组件渲染完成后，再次更新 `props.options.headerActionIcons`，会导致下钻 icon 缺失不展示。
原因：
drillDownIcon 是由 react 组件层塞入到底表 headerActionIcons 中的
外部 `props.options.headerActionIcons` 更新会导致跳过上述的插入逻辑，并覆盖改底表的 headerActionIcons 数组

fix: headerActionIcons更新覆盖了下钻icon展示

---

.gitignore
packages/s2-core/__tests__/unit/sheet-type/pivot-sheet-spec.ts
packages/s2-core/__tests__/unit/utils/merge-spec.ts
packages/s2-core/src/cell/corner-cell.ts
packages/s2-core/src/common/constant/options.ts
packages/s2-core/src/common/interface/s2Options.ts
packages/s2-core/src/data-set/pivot-data-set.ts
packages/s2-react/__tests__/unit/utils/options-spec.ts
packages/s2-react/playground/config.ts
s2-site/docs/api/general/S2Options.zh.md

✨ Feature
数值挂行头时有效
这里有个特殊点就是如果这个 options 更改, 对应 react 是 `s2.render(false)` 即不重新加载数据, 但是这里文本其实对应 dataCfg 一部分, 需要 `s2.render(true)` 才行, 但考虑到这个文本应该不会有变更的场景 (cornerText. 也有这个问题), 所以暂时未做处理 : 
```ts
React.useEffect(() => {
const reloadData = prevText !== text
s2.render(reloadData)
},[s2Options])
```
close #1212

feat: 支持自定义角头的虚拟数值字段文本 close #1212

---

packages/s2-core/__tests__/unit/utils/export/copy-spec.ts
packages/s2-core/src/utils/export/copy.ts

🐛 Bugfix
场景：复制功能报错
原因：获取当前单元格的rowHeader和colHeader时，因为header内自带了‘-’字符串，导致id切分识别错误
修复：通过meta中的rowIndex和colIndex获取到headerCell

fix(copy): 修复因为header的key内带有‘-’字符串导致的row和col id识别错误

---

packages/s2-core/__tests__/spreadsheet/interaction-brush-selection-scroll-spec.ts

把两个测试，两次创建 S2 DOM 节点合并到一个 case 里。避免 DOM 节点创建时候可能有一些 race 的情况。

chore: 修复刷选测试用例稳定性问题

---

packages/s2-core/__tests__/unit/cell/header-cell-spec.ts
packages/s2-core/src/cell/header-cell.ts

fix(s2): 如果是 table mode，列头不需要被格式化
🐛 Bugfix
🔧 Chore
| <img width="906" alt="image" src="https://user-images.githubusercontent.com/20497176/162740541-e5a9781b-db13-4621-9af0-7fe7802da085.png"> |<img width="880" alt="image" src="https://user-images.githubusercontent.com/20497176/162740239-02d5e0eb-ef7f-4948-8200-ccae149239cf.png">|

fix(s2): 如果是 table mode，列头不需要被格式化

---

.releaserc.base.js

🔧 Chore
解决 semantic-release 只会提交 changelog, 不包含 package.json 的 version 修改问题
原因: @semantic-release/npm 需要在 @semantic-release/git 插件后, 应该是先发包, 再提交

chore(ci): 修复自动发布后不能自动更新版本号的问题

---

packages/s2-react/__tests__/spreadsheet/drill-down-spec.tsx
packages/s2-react/src/components/sheets/pivot-sheet/index.tsx

🐛 Bugfix
🔧 Chore
在 #1222 中，修复了 headerActionIcons 变化时没有重新 render 的问题，但是默认的 `render()` 调用，会清除下钻数据 `clearDrillDownData@packages/s2-core/src/sheet-type/pivot-sheet.ts`。
考虑 deps 中 diff 的是 headerActionIcons 引用，业务层如何使用不可预知，所以变化时需调用 `render(false)`， 即仅更新 UI可。

fix: headerActionIcons更新不应清除上一次下钻数据

---

packages/s2-core/__tests__/spreadsheet/interaction-tooltip-spec.ts
packages/s2-core/__tests__/spreadsheet/spread-sheet-spec.ts
packages/s2-core/__tests__/unit/interaction/base-interaction/click/row-column-click-spec.ts
packages/s2-core/__tests__/unit/interaction/range-selection-spec.ts
packages/s2-core/__tests__/unit/interaction/root-spec.ts
packages/s2-core/__tests__/util/helpers.ts
packages/s2-core/src/common/interface/interaction.ts
packages/s2-core/src/facet/layout/node.ts
packages/s2-core/src/interaction/base-interaction/click/row-column-click.ts
packages/s2-core/src/interaction/range-selection.ts
packages/s2-core/src/interaction/root.ts
s2-site/docs/api/basic-class/interaction.zh.md
s2-site/docs/manual/advanced/interaction/basic.zh.md

✨ Feature
- 支持行头和列头 偶数次点击时 取消选中
- 支持行头和列头 多选时, 按住 ctrl / Command 再次点击选中行/列, 进行反选
- 修复区间多选, 不显示 tooltip 的问题
| ![Kapture 2022-04-14 at 19 03 36](https://user-images.githubusercontent.com/21015895/163378707-57096911-e4ab-447a-b085-f0d9181cbab0.gif)| ![Kapture 2022-04-14 at 19 02 05](https://user-images.githubusercontent.com/21015895/163378533-e6a3dd3f-92bd-4f10-883d-bb33ea3e8dcd.gif) |
close #1243

feat(interaction): 支持行列头反选

---

packages/s2-core/__tests__/unit/utils/facet-spec.ts
packages/s2-core/src/utils/facet.ts
packages/s2-react/src/hooks/usePagination.ts

🐛 Bugfix
🔧 Chore
最初这个问题在 #1037 修改了，见 https://github.com/antvis/S2/pull/1037/files#diff-c0e3de302ea541a5e2183682d30e86a39bc28b07e8f1aa2ba567c4446076f97aL35
主要是 `getIndexRangeWithOffsets` 在处理可视范围与单元格边界重合时，意外返回了大于边界的index
最近在 #1218 重新引入了该 BUG
分页条件变更时，之前使用的是 setOptions，实际应用 updatePagination

fix: 修复交叉表分页问题

---

packages/s2-core/__tests__/bugs/issue-368-spec.ts
packages/s2-core/src/facet/pivot-facet.ts

当小计展示在上方时， sample 没有被初始化导致。
单测放在 issue 378 中，因为都是校验小计展示。
✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore
| <img width="563" alt="image" src="https://user-images.githubusercontent.com/20497176/163788855-694283af-d3b5-4850-a637-e306bb38176b.png"> | <img width="506" alt="image" src="https://user-images.githubusercontent.com/20497176/163788836-b483a2c5-38a6-4c51-8813-646660089e62.png"> |

fix: 添加当多个数值在行头显示时，小计展示被遮挡的问题

---

packages/s2-core/src/interaction/root.ts

changeState 时清除全选状态，不然全选后再做交互，每个格子的选中 interaction shape 的样式还是在。

fix(interaction): 修复全选后无法清除选中状态

---

packages/s2-core/__tests__/spreadsheet/theme-spec.ts
packages/s2-core/src/theme/index.ts

🐛 Bugfix
行头/单元格之前 icon.fill 错误的配置为了角头/列头的值（如果是彩色主题，即白色）。
但因为 icon 渲染时，一直取的是 text.fill，所以问题没有暴露，直到 #1261 修复了这个 BUG。
|  ![CleanShot 2022-04-20 at 18 11 20@2x](https://user-images.githubusercontent.com/6716092/164205567-b2985493-efad-46db-ad9e-ce4117bc8f92.png)    |   <img width="318" alt="CleanShot 2022-04-20 at 18 10 04@2x" src="https://user-images.githubusercontent.com/6716092/164205299-9ca49713-4d9f-4c31-8543-7a4217b71012.png">   |

fix: 行头/单元格icon颜色应默认与字体色一致

---

packages/s2-core/__tests__/unit/utils/facet-spec.ts
packages/s2-core/src/facet/base-facet.ts
packages/s2-core/src/utils/facet.ts

修复 scrollY 未判断最大值的越界问题。之前判断的是 
```
scrollY  >= (rendererHeight - panelHeight) &&  rendererHeight > panelHeight
```
但其实 rendererHeight > panelHeight 这个判断是多余的。rendererHeight < panelHeight 时上一次 render 的 scrollY 未被调整到合法范围内。
同时对 getScrollOffset 系列函数做一个重构，添加单测。

fix(facet): 修复 scrollY 越界问题

---

packages/s2-core/__tests__/unit/interaction/event-controller-spec.ts
packages/s2-core/src/interaction/event-controller.ts

在做边框单独渲染的时候，会触发这样的问题：
闪烁的原因是，从 A Shape 移动到 B Shape 的时候，会触发 mouseout 事件，把交互重置了，造成鼠标经过边框 Shape 的时候会闪一下。
autoreset 我记得是在鼠标移动到 Canvas 外时 reset 交互样式。目前则是在任意 mouseout 触发的时候 reset。只要从 A Shape 移动到 B Shape 就会触发。看了一下测试用例。Tooltip 的自动隐藏其实在 ChangeState 的时候就已经做了。不需要单独在 CanvasMouseOut 里面做。
改动了一下 CanvasMouseOut 的判断逻辑，只有在鼠标移动到 Canvas 外时才会触发。

fix: 修正auto reset 的 canvas 外判断逻辑

---

packages/s2-core/__tests__/unit/interaction/base-interaction/click/data-cell-click-spec.ts
packages/s2-core/__tests__/unit/interaction/base-interaction/hover-spec.ts
packages/s2-core/__tests__/unit/interaction/root-spec.ts
packages/s2-core/__tests__/unit/utils/interaction/state-controller-spec.ts
packages/s2-core/src/interaction/base-interaction/hover.ts
packages/s2-core/src/utils/interaction/state-controller.ts

明细表之前有如下问题，Hover 事件有时候会不生效：
经过排查，是因为 clearState 中判断条件：
```
if (!isEmpty(allInteractedCells) && !isEmpty(cellMetas)) {
```
应该改成
```
if (!isEmpty(allInteractedCells) || !isEmpty(cellMetas)) {
```
两者有一个不为空就需要触发 Clear 逻辑。
顺便还给 DATA_CELL_HOVER 事件添加了重复触发的判断逻辑，在一个 Cell 中不断移动鼠标 Hover 只会触发一次。和修复了 DataCell Click 的测试中重复 bindEvents 导致测试失败的问题。

fix(interaction): 连续 Hover 失效问题修复

---

packages/s2-core/src/cell/base-cell.ts
packages/s2-core/src/cell/col-cell.ts
packages/s2-core/src/cell/data-cell.ts
packages/s2-core/src/cell/row-cell.ts
packages/s2-core/src/utils/g-renders.ts

在 Cell 的初始状态，一般是没有交互状态的，比如首次渲染，或者滚动时新渲染的格子。把 stateShape 的 visible 位置为 false 来替换设置透明的背景和边框，可以让 g 在一开始不渲染这个 Shape，从而提升一些性能。
优化前：
优化后：
从 PanelGroup 的绘制时间和 Shape 的绘制调用次数来看，都有 30% 左右的提升。

fix(interaction): 设置 stateShape 的 visible 默认为 false 来减少绘制调用

---

packages/s2-core/__tests__/spreadsheet/interaction-multi-selection-spec.ts
packages/s2-core/__tests__/unit/interaction/root-spec.ts
packages/s2-core/src/interaction/base-interaction/click/row-column-click.ts
packages/s2-core/src/interaction/root.ts

🐛 Bugfix
1. 列头联动高亮未考虑 树状列头非叶子节点的情况, 这次补上, 兼容多选 
2. 同时可以解决趋势分析表 粒度切换高亮, 无法高亮整列的问题
TODO: 
| ![Kapture 2022-04-28 at 18 58 01](https://user-images.githubusercontent.com/21015895/165737853-c5f96c9d-8d02-44a3-8660-698327851c56.gif) | ![Kapture 2022-04-28 at 18 55 31](https://user-images.githubusercontent.com/21015895/165737605-5bbfc041-a568-474a-9974-b8da810c6d4b.gif)  |

fix(interaction): 树状模式列头非叶子节点选中无法高亮当前列

---

packages/s2-core/__tests__/spreadsheet/interaction-brush-selection-scroll-spec.ts
packages/s2-core/src/interaction/brush-selection.ts

🐛 Bugfix
layerX layerY Chrome / Webkit 已经移除了，咱就是说先别用了 = =
https://developer.mozilla.org/en-US/docs/Web/API/UIEvent/layerX

fix: 修复容器设置transform样式后框选背景框错位问题

---

packages/s2-core/__tests__/spreadsheet/spread-sheet-spec.ts
packages/s2-core/__tests__/spreadsheet/spread-sheet-tree-mode-spec.ts
packages/s2-core/src/facet/pivot-facet.ts

🐛 Bugfix
树状模式下，当表格首次渲染后，会缓存计算的行头宽度（rowCfg.treeRowsWidth）。
当 dataCfg 改变，如 meta[].name 变更，即各维度的名称长度会变化，导致整体行头宽度变化。
此时再使用缓存的宽度不合适，需要重新计算。
- rowCfg.treeRowsWidth 本来用作记录用户的拖拽宽度，不应用作缓存
- 不再缓存计算的宽度，每次 render 重新计算。但仍优先取 rowCfg.treeRowsWidth（用户拖拽优先级最高）

fix: dataCfg变化时未重新计算treeRow宽度

---

packages/s2-core/__tests__/unit/utils/export/index-spec.ts
packages/s2-core/src/utils/export/index.ts

🐛 Bugfix
去掉 Element.focus() 默认滚动行为
https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/focus#focus_with_focusoption
| ![Kapture 2022-05-10 at 13 59 11](https://user-images.githubusercontent.com/21015895/167558424-06f5a914-6b0a-4f18-8736-1b3ca498e968.gif) | ![Kapture 2022-05-10 at 13 56 58](https://user-images.githubusercontent.com/21015895/167558156-d4897b63-5251-4ce8-a694-ab1e433a62fc.gif) |

fix(copy): 修复同步复制时会触发页面滚动的问题 close #1317

---

s2-site/docs/manual/basic/tooltip.zh.md
s2-site/docs/manual/faq.zh.md
s2-site/docs/manual/getting-started.zh.md
s2-site/examples/react-component/tooltip/demo/custom-tooltip.tsx
s2-site/package.json
s2-site/yarn.lock

🔧 Chore
1. 完善 Tooltip 相关文档
2. 增加 Vue3 自定义 tooltip demo 和文档 https://codesandbox.io/s/antv-s2-vue3-tooltip-demo-hpm3rf?file=/src/main.js
3. 修复 React 自定义 tooltip demo 白屏的问题

docs: 增加如何在 Vue 中自定义 Tooltip 的文档

---

packages/s2-core/__tests__/unit/interaction/base-interaction/click/corner-cell-click-spec.ts
packages/s2-core/__tests__/unit/interaction/root-spec.ts
packages/s2-core/__tests__/unit/ui/tooltip/index-spec.ts
packages/s2-core/src/common/constant/interaction.ts
packages/s2-core/src/interaction/base-interaction/click/corner-cell-click.ts
packages/s2-core/src/interaction/base-interaction/click/data-cell-click.ts
packages/s2-core/src/interaction/base-interaction/click/index.ts
packages/s2-core/src/interaction/base-interaction/click/merged-cell-click.ts
packages/s2-core/src/interaction/root.ts
packages/s2-core/src/ui/tooltip/index.ts
packages/s2-react/playground/index.tsx
s2-site/docs/api/basic-class/base-data-set.zh.md
s2-site/docs/api/basic-class/base-tooltip.zh.md
s2-site/docs/api/basic-class/interaction.zh.md
s2-site/docs/api/basic-class/spreadsheet.zh.md
s2-site/docs/api/basic-class/store.zh.md
s2-site/docs/api/general/S2Options.zh.md
s2-site/docs/common/custom-tooltip.zh.md
s2-site/docs/manual/basic/tooltip.zh.md

🐛 Bugfix
🔧 Chore
1. 增加角头交互, 兼容点击角头显示 自定义 tooltip 的场景, 角头由于没有选中和悬停的状态, 需要额外处理
2. tooltip 增加 `visible` 属性, 便捷的获取当前显示状态
3. 增加 `BaseTooltip` 基础类文档
| ![Kapture 2022-05-10 at 16 27 50](https://user-images.githubusercontent.com/21015895/167584421-0f60663f-004a-400a-8ccb-ccfc5b605711.gif) | ![Kapture 2022-05-10 at 16 25 31](https://user-images.githubusercontent.com/21015895/167584076-d688be13-67a0-407a-8723-8df1e5e8bbb3.gif) |

fix(interaction): 角头单元格增加对自定义tooltip的适配

---

packages/s2-core/__tests__/spreadsheet/spread-sheet-totals-spec.ts
packages/s2-core/src/common/interface/basic.ts
packages/s2-core/src/sheet-type/spread-sheet.ts
packages/s2-core/src/utils/layout/add-totals.ts
s2-site/docs/common/totals.zh.md
s2-site/docs/manual/basic/totals.zh.md

✨ Feature
在 #1086 里，全量放开了小计的展示，不在根据子维度个数做判断 `size(fieldValues) > 1`。
实际场景中，还是有少量用户需要控制做更简洁的展示。
|  ![CleanShot 2022-05-11 at 16 47 03@2x](https://user-images.githubusercontent.com/6716092/167809164-7cb8910a-a721-450e-9495-637b3559490e.png)      |    ![CleanShot 2022-05-11 at 16 47 50@2x](https://user-images.githubusercontent.com/6716092/167809305-c832bb4c-7196-4fbc-94c5-2ef3126685f2.png)   |

feat: 当子维度不足2个时可隐藏小计节点

---

packages/s2-core/__tests__/unit/utils/export/copy-spec.ts
packages/s2-core/src/utils/export/copy.ts

🐛 Bugfix
🔧 Chore
带总/小计的交叉表
- 点选总/小计单元格，`cmd+c` 报错
- 点选总/小计所在的行列，`cmd+c` 报错 或数据复制不全
|  ![CleanShot 2022-05-12 at 23 09 00](https://user-images.githubusercontent.com/6716092/168107837-1776dc47-e638-45c0-9987-d0c802af04d5.gif)    |  ![CleanShot 2022-05-12 at 23 09 44](https://user-images.githubusercontent.com/6716092/168108036-607d0255-8f21-4787-82ae-0649c8654149.gif)   |

fix: 带总/小计的交叉表复制报错

---

packages/s2-core/__tests__/bugs/issue-1337-spec.ts
packages/s2-core/src/sheet-type/spread-sheet.ts

🐛 Bugfix
🔧 Chore
当 fields 按如下配置（无行头，所有数值充当 row）
```
{
columns: ["type"],
values: ["price", "cost"],
valueInCols: false
}
```
且开启 col 的总计时
```
{
totals: {
col: {
showGrandTotals: true
}
}
}
```
row 的总计也渲染了，期望的是只展示 col 的总计
|  <img width="628" alt="CleanShot 2022-05-16 at 09 54 38@2x" src="https://user-images.githubusercontent.com/6716092/168507031-effb6e1a-c5da-4cab-a5c2-a7471e2fab3e.png">      |   <img width="626" alt="CleanShot 2022-05-16 at 09 55 34@2x" src="https://user-images.githubusercontent.com/6716092/168507094-bffbe339-0618-4789-aea7-b9d935624610.png">  |

fix: 仅配置列头总计时却渲染了行/列头所有总计

---

.github/ISSUE_TEMPLATE/ask-for-question.md
.github/ISSUE_TEMPLATE/bug-report.md
packages/s2-core/__tests__/spreadsheet/hidden-columns-spec.ts
packages/s2-core/__tests__/unit/sheet-type/pivot-sheet-spec.ts
packages/s2-core/__tests__/unit/utils/hide-columns-spec.ts
packages/s2-core/__tests__/unit/utils/text-spec.ts
packages/s2-core/src/common/interface/s2Options.ts
packages/s2-core/src/interaction/base-interaction/click/row-column-click.ts
packages/s2-core/src/interaction/root.ts
packages/s2-core/src/sheet-type/spread-sheet.ts
packages/s2-core/src/utils/hide-columns.ts
packages/s2-react/playground/index.tsx
packages/s2-react/src/components/sheets/base-sheet/index.tsx
packages/s2-react/src/components/sheets/pivot-sheet/index.tsx
packages/s2-react/src/components/sheets/table-sheet/index.tsx
packages/s2-react/src/components/switcher/header.tsx
packages/s2-react/src/hooks/useSpreadSheet.ts
s2-site/docs/api/basic-class/interaction.zh.md
s2-site/docs/api/basic-class/spreadsheet.zh.md
s2-site/docs/manual/advanced/interaction/hide-columns.zh.md
s2-site/docs/manual/basic/sheet-type/table-mode.zh.md

🐛 Bugfix
比如: 先隐藏 `A`, 再展开 `A`, `hiddenColumnFields` 为空时也应该重新渲染, 清空上一次渲染的展开icon 和 详情信息
```ts
sheet.setOptions({
interaction: {
hiddenColumnFields: ['A']
}
})
sheet.setOptions({
interaction: {
hiddenColumnFields: []
}
})
```
其他:
1. 去除 React 层多余的一次更新
2. 去掉 `Switcher` 组件的 `JSON.stringify` 比较
| ![Kapture 2022-05-18 at 17 51 44](https://user-images.githubusercontent.com/21015895/169011805-63a3fef6-d843-4bf3-8d03-c50f9dc57fa8.gif) | ![Kapture 2022-05-18 at 17 48 33](https://user-images.githubusercontent.com/21015895/169011116-7a613567-d348-4d19-b705-0b6bc0abf9e8.gif) |

fix(interaction): 修复默认隐藏列的配置更新为空数组时, 未触发表格更新

---

packages/s2-core/__tests__/unit/facet/layout/build-row-tree-hierarchy-spec.ts
packages/s2-core/src/facet/layout/build-row-tree-hierarchy.ts
packages/s2-react/__tests__/data/mock-drill-down-dataset.json
packages/s2-react/__tests__/unit/utils/drill-down-spec.ts
packages/s2-react/src/components/sheets/pivot-sheet/index.tsx
s2-site/docs/api/components/drill-down.zh.md
s2-site/examples/custom/custom-cell/demo/col-cell.ts
s2-site/examples/custom/custom-cell/demo/row-cell.ts

✨ Feature
🎨 Enhance
🐛 Bugfix
[1. fix: clearDrillDown 无法全量清空的问题。 - 用户传入 clearDrillDown = {} 无法全量清空下钻](https://github.com/antvis/S2/commit/48baee30c8f4bef0a8841a1256e20884096b6e8a)
[2. fix: 树状结构下多层级排序失效的问题](https://github.com/antvis/S2/commit/834c99b388683ddb8269ae172c1286f41e6f7641)
🔧 Chore
|<img width="580" alt="image" src="https://user-images.githubusercontent.com/20497176/169036062-cfecc605-b090-4f57-b1b3-61a1760a869c.png"> | <img width="456" alt="image" src="https://user-images.githubusercontent.com/20497176/169036359-3e7c437c-7a86-45f4-bd81-b187befc0933.png">|

fix: 下钻数据没有按照用户数据展示

---

packages/s2-core/__tests__/unit/interaction/event-controller-spec.ts
packages/s2-core/src/interaction/event-controller.ts
packages/s2-core/src/utils/tooltip.ts
packages/s2-react/playground/index.tsx

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore
当前场景：tooltip模块关闭逻辑，只会通过鼠标位置进行验证。
不满足的场景：**tooltip包含弹出层的场景**。比如：日期选择器这种类型，在操作日期选择器模块的时候，因为鼠标并不能保证一定会在tooltip区域，所以就会触发关闭逻辑。
增强：在`tooltip.visible`为`true`且事件元素为`Node`为的情况下，进行节点匹配，只要是tooltip模块下的元素都不会触发tooltip关闭逻辑

feat: 丰富tooltip关闭的验证逻辑

---

packages/s2-core/__tests__/spreadsheet/theme-spec.ts
packages/s2-core/src/cell/base-cell.ts
packages/s2-core/src/cell/col-cell.ts
packages/s2-core/src/cell/header-cell.ts
packages/s2-core/src/cell/row-cell.ts
packages/s2-core/src/common/interface/theme.ts
packages/s2-core/src/sheet-type/spread-sheet.ts
packages/s2-core/src/theme/index.ts
packages/s2-core/src/utils/cell/cell.ts
packages/s2-react/playground/config.ts
packages/s2-react/playground/index.tsx
s2-site/docs/api/basic-class/spreadsheet.zh.md
s2-site/docs/api/general/S2Theme.zh.md

✨ Feature
🐛 Bugfix
1. 新增 measureText 度量值的文字主题配置, 由于有数值置于行头/列头, rowCell, colCell 都需要适配, 列头数值默认和 dataCell 对齐
> 之前是根据 `isLeaf` 和 `hideMeasureColumns`, 来判断
现在改为配置, 更加灵活, 而不是代码写死
```ts
colCell: {
measureText: {
textAlign: s2.theme.dataCell.text.textAlign,
},
},
```
3. 去除 colCell 写死的配置
4. 修复小计/总计 主题配置不生效的问题
5. 修改 列头和数值对齐方式

feat(theme): 新增度量值的主题配置, 修复小计总计主题配置不生效 close #1357

---

packages/s2-core/__tests__/unit/interaction/event-controller-spec.ts
packages/s2-core/__tests__/unit/interaction/row-column-resize-spec.ts
packages/s2-core/src/common/icons/gui-icon.ts
packages/s2-core/src/interaction/event-controller.ts
packages/s2-core/src/interaction/row-column-resize.ts
packages/s2-react/playground/config.ts
packages/s2-react/playground/index.tsx

🐛 Bugfix
event controller 事件分发的时候, 会对图表自己的 action icon 做判断, 如果是, 则不触发单元格的点击事件, 判断方式是 根据当前 target 的 type 是不是 `image`
如果是自定义单元格添加了背景图 也是 `image` shape 的场景就会判断错误, 导致单元格事件无法正常触发
修改为实例化 GuiIcon 的时候增加一个标识, 根据这个标识来判断更准确一点
https://codesandbox.io/s/vigilant-bell-iwre10?file=/index.tsx:210-537
```ts
class CustomRowCell extends RowCell {
// 覆盖背景绘制，可覆盖或者增加绘制方法
drawBackgroundShape() {
this.backgroundShape = this.addShape("image", {
attrs: {
...this.getCellArea(),
img:
"https://gw.alipayobjects.com/zos/antfincdn/og1XQOMyyj/1e3a8de1-3b42-405d-9f82-f92cb1c10413.png"
}
});
}
}
```
| ![Kapture 2022-05-24 at 11 48 41](https://user-images.githubusercontent.com/21015895/169944986-adbb50ea-2828-41cf-b9c6-60dc5f5b9571.gif) | ![Kapture 2022-05-24 at 11 47 …

fix(interaction): 修复自定义单元格有自定义图片时无法触发点击 close #1360

---

packages/s2-core/__tests__/unit/cell/data-cell-spec.ts
packages/s2-core/src/cell/data-cell.ts

🐛 Bugfix
当配置的 `condition. interval` mapping 未提供范围时，s2 会从数据集找到数值字段的 max、min。
计算百分比前，fieldValue 被 parseNumberWithPrecision 格式化了，但 max、min 没有。
如 fieldValue 取 `27.334666666666667`，经格式化成 `27.33466666666667`，少了一个 6。
导致 `fieldValue < minValue || fieldValue > maxValue` 为 true
进而无法绘制图案。
统一格式化

fix: fieldValue精度过高时intervalShape未绘制

---

packages/s2-core/__tests__/spreadsheet/theme-spec.ts
packages/s2-core/src/cell/header-cell.ts
packages/s2-core/src/facet/base-facet.ts
packages/s2-react/__tests__/data/strategy-data.ts
packages/s2-react/playground/index.tsx
packages/s2-react/src/components/sheets/base-sheet/index.tsx
packages/s2-react/src/components/sheets/strategy-sheet/index.tsx

🐛 Bugfix
1. #1364 重构后, 列头数值配置和 dataCell 解耦, 趋势分析表的虚拟数值列头命中了 `textAlign: 'center'`, 由于 `drawObjectText` 这个方法使用 dataCell 的 textAlign 做的坐标计算, 一个是 `right`, 一个是 `center` 导致坐标计算错误
2. 未兼容趋势分析表, 虚拟数值列头也应该命中 `measureText` 主题配置
| ![image](https://user-images.githubusercontent.com/21015895/170411541-4fb9380e-5712-4d37-ab31-3efa3f48f04b.png) | ![image](https://user-images.githubusercontent.com/21015895/170411186-290a721d-2dbd-4020-8ca2-b1237253efab.png) |

fix(strategysheet): 修复趋势分析表多列头时叶子节点未和数值单元格对齐

---

packages/s2-core/__tests__/unit/interaction/range-selection-spec.ts
packages/s2-core/src/interaction/range-selection.ts

🐛 Bugfix
明细表下 rowLeafNodes，range-selection 交互从中取 id 会报错。

fix: 明细表下range-selection报错

---

s2-site/docs/manual/advanced/adaptive.zh.md

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore

docs: 增加 vue 自适应文档

---

packages/s2-core/__tests__/unit/utils/sort-action-spec.tsx
packages/s2-core/src/utils/sort-action.ts
s2-site/docs/manual/basic/sort/custom.zh.md
s2-site/examples/analysis/sort/demo/custom-sort-func.ts

✨ Feature
当用户使用 sortFunc 排序时，若回传的排序数组，没有携带 `[&]` 连接符，目前表格无法正常渲染
如交叉表的行维度=[province, city]，当前排序字段 sortFieldId=city
若 sortResult 返回的为 ['成都', '杭州']，则表格无法渲染
期望的返回为 ['浙江[&]杭州', '四川[&]成都']
让用户手动拼接每个维度，不太友好。故使用 sortResult 按照手动排序进行兜底处理。
| <img width="621" alt="CleanShot 2022-05-26 at 16 42 44@2x" src="https://user-images.githubusercontent.com/6716092/170452506-a82a5278-b0c8-46c8-8127-386300b2f656.png">    |  <img width="615" alt="CleanShot 2022-05-26 at 16 42 57@2x" src="https://user-images.githubusercontent.com/6716092/170452535-eb4a2318-3862-4c9a-ab4b-b2cc4dc632a7.png">    |

feat: sortFunc 支持使用手动排序兜底

---

packages/s2-vue/README.md
packages/s2-vue/playground/App.vue
packages/s2-vue/src/components/index.ts
s2-site/docs/manual/advanced/adaptive.zh.md
s2-site/docs/manual/advanced/get-instance.zh.md
s2-site/docs/manual/getting-started.zh.md

🐛 Bugfix
🔧 Chore
Vue 表组件重命名  Sheet => SheetComponent

fix(vue): 统一表组件变量名保持和 react 版本一致 Sheet => SheetComponent

---

packages/s2-core/__tests__/spreadsheet/spread-sheet-spec.ts
packages/s2-core/__tests__/unit/facet/pivot-facet-spec.ts
packages/s2-core/__tests__/unit/facet/table-facet-spec.ts
packages/s2-core/__tests__/util/helpers.ts
packages/s2-core/src/facet/base-facet.ts
packages/s2-core/src/interaction/event-controller.ts
packages/s2-core/src/sheet-type/spread-sheet.ts
packages/s2-core/src/ui/hd-adapter/index.ts
packages/s2-core/src/utils/tooltip.ts
packages/s2-react/playground/index.tsx
s2-site/docs/api/basic-class/spreadsheet.zh.md

🐛 Bugfix
目前表格卸载后 `s2.destroy()`, 调用 `s2.render()` 或 `s2.changeSheetSize()` 会有不同的报错 (g 导致的), 解决办法是添加容错处理, 当找不到 `canvas` 后不执行相关逻辑
> changeSheetSize
这个错误原因是 卸载后 `canvas` 节点已经被移除了, g 内部的 `setDOMSize` 方法没有做容错, 所以只有我们来处理
> render
这个错误原因是 卸载后 所有的 Group 节点被移除, 再次调用 `render` => `buildFacet`
> node_modules/@antv/g-base/lib/abstract/container.js
close #1349

fix: 修复表格卸载后调用实例方法报错的问题 close #1349

---

packages/s2-core/__tests__/unit/ui/tooltip/index-spec.ts
packages/s2-core/__tests__/unit/utils/tooltip-spec.ts
packages/s2-core/src/ui/tooltip/index.less
packages/s2-core/src/ui/tooltip/index.ts
packages/s2-core/src/utils/tooltip.ts
packages/s2-react/playground/index.less
s2-site/docs/manual/getting-started.zh.md
s2-site/docs/manual/introduction.zh.md

🎨 Enhance
tooltip 在调用 `show` 或 `hide` 方法时才创建 container, 而对应的 `getContainer` 会导致一直更新容器的 classname 造成重绘
| ![Kapture 2022-06-07 at 19 35 32](https://user-images.githubusercontent.com/21015895/172370009-a4e7f396-579a-4b66-bdd3-d17ea8869b16.gif) | ![Kapture 2022-06-07 at 19 37 33](https://user-images.githubusercontent.com/21015895/172370321-8f80e8a6-584d-4dab-bb80-f87dc50a3e4a.gif) |

fix(tooltip): 减少 tooltip 框重绘

---

.github/workflows/issue-check-inactive.yml
.github/workflows/issue-remove-inactive.yml
packages/s2-core/__tests__/unit/sheet-type/pivot-sheet-spec.ts
packages/s2-core/__tests__/unit/sheet-type/table-sheet-spec.ts
packages/s2-core/src/cell/table-col-cell.ts
packages/s2-core/src/sheet-type/pivot-sheet.ts
packages/s2-core/src/sheet-type/table-sheet.ts

🐛 Bugfix
在 https://github.com/antvis/S2/pull/1397 的修复中, 不小心把明细表/透视表的排序文案写反了
| ![image](https://user-images.githubusercontent.com/21015895/172798885-72574c92-43bf-4e54-afd7-211f167c63d3.png) | ![image](https://user-images.githubusercontent.com/21015895/172798723-82b11c00-3a67-428c-b664-64b5ce05e9bd.png) |
| ![image](https://user-images.githubusercontent.com/21015895/172798838-145ae8e7-8ee5-49c5-8709-d8002abb3b89.png) | ![image](https://user-images.githubusercontent.com/21015895/172798772-9466b3be-4951-46c2-9fe2-7c66216f463d.png) |
ref https://github.com/antvis/S2/pull/1397 https://github.com/antvis/S2/issues/1394

fix(sort): 透视表/明细表 排序菜单文案显示错误

---

packages/s2-core/__tests__/unit/interaction/selected-cell-move-spec.ts
packages/s2-core/src/interaction/event-controller.ts
packages/s2-core/src/interaction/selected-cell-move.ts

feat: canvas 未聚焦时不触发选中格子的键盘 move 行为

---

packages/s2-core/__tests__/unit/utils/export/copy-spec.ts
packages/s2-core/src/utils/export/copy.ts

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore
原来用split('-')去判断ID，有误判的情况，修改成用colIndex去获取当前的colKey

fix(copy): 修复字段名带有-导致复制失败的问题

---

packages/s2-core/src/utils/tooltip.ts

当文档的高度未被  body 元素完全占满的时候，tooltip 显示以后点击“外部空白区域”触发 click 事件的 event.target 可能是 html 元素，执行到该函数会抛出错误  Cannot read properties of null (reading 'parentElement')
✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore

fix: 出现 tooltip 后点击画布外面的空白区域可能抛出错误

---

.github/PULL_REQUEST_TEMPLATE.md
packages/s2-core/__tests__/spreadsheet/interaction-multi-selection-spec.ts
packages/s2-core/__tests__/unit/interaction/root-spec.ts
packages/s2-core/__tests__/util/helpers.ts
packages/s2-core/src/interaction/event-controller.ts
packages/s2-core/src/interaction/root.ts
packages/s2-react/__tests__/data/mock-dataset.json
packages/s2-react/playground/index.tsx
packages/s2-react/src/components/tooltip/components/summary.tsx
s2-site/docs/api/basic-class/interaction.zh.md
s2-site/docs/manual/basic/tooltip.zh.md

🐛 Bugfix
当行/列层级 >=3 时, 在单选/多选行头时, 统计的已选中个数和汇总数据是错误的, 原因是当前所有的子节点参与了计算, 预期应该是当前点击的单元格对应的叶子节点
- 参与计算: 所有叶子节点
- 高亮: 当前节点 + 所有子节点
| ![image](https://user-images.githubusercontent.com/21015895/173789963-59eaa48c-41de-401f-a816-264a603d2ce6.png) | ![image](https://user-images.githubusercontent.com/21015895/173789845-ed6aa9fe-e162-486a-9c88-f6e825df9bb1.png) | 
close #1419

fix(tooltip): 修复行/列层级超过2级时选中数据统计错误

---

packages/s2-shared/src/utils/resize.ts

getBoundingClientRect()获取到的是缩放后的实际大小，去掉这个直接取dom元素大小
🐛 Bugfix

fix: 解决父元素缩放时,自适应无法充满父元素bug

---

packages/s2-core/__tests__/unit/facet/pivot-facet-spec.ts
packages/s2-core/__tests__/unit/interaction/base-interaction/click/row-column-click-spec.ts
packages/s2-core/src/common/interface/s2Options.ts
packages/s2-core/src/facet/base-facet.ts
packages/s2-core/src/interaction/base-interaction/click/row-column-click.ts
packages/s2-core/src/sheet-type/spread-sheet.ts
packages/s2-react/playground/config.ts
s2-site/docs/common/interaction.zh.md

🐛 Bugfix
1. 修复关闭多选配置后, 行列点击时未读取该配置, 导致依然可以进行多选的问题 (尤其对于趋势分析表, 多选没有任何意义)
```ts
interaction: {
multiSelection: false
}
}
```
2. 对 `facet.updateScrollOffset` 的内部两个方法进行兜底, `scrollWithAnimation` 和 `scrollImmediately`
避免只传递 `offsetX: {}` 和 `offsetY: {}` 报错的情况
```ts
```
| ![Kapture 2022-06-20 at 17 06 37](https://user-images.githubusercontent.com/21015895/174566986-3b4221dc-a4bf-497d-8a7c-e428ba2729e9.gif) | ![Kapture 2022-06-20 at 17 03 53](https://user-images.githubusercontent.com/21015895/174566383-35dff868-b197-4f81-b5f6-9661711c71e7.gif) |

fix(interaction): 修复禁用多选后, 未对行/列头生效

---

packages/s2-core/__tests__/unit/utils/data-set-operate-spec.tsx
packages/s2-core/src/utils/data-set-operate.ts

🐛 Bugfix
#1430 引入的 BUG，当 `'undefined' in item` 未考虑 item 可能为空

fix: 自定义 flatten 函数未考虑空值情况

---

packages/s2-core/__tests__/unit/facet/layout/build-row-tree-hierarchy-spec.ts
packages/s2-core/src/facet/layout/build-row-tree-hierarchy.ts

🐛 Bugfix
#1430  引入的 BUG，当树状模式开启总计时，总计节点的循环里，pivotMetaValue 是 `null`

fix: 构造含总计的 tree 行头布局时报错

---

packages/s2-core/__tests__/unit/interaction/selected-cell-move-spec.ts
packages/s2-core/src/common/constant/events/basic.ts
packages/s2-core/src/common/interface/emitter.ts
packages/s2-core/src/interaction/selected-cell-move.ts
packages/s2-react/__tests__/unit/hooks/useEvents-spec.ts
packages/s2-react/src/hooks/useEvents.ts
packages/s2-shared/__tests__/utils/options-spec.ts
packages/s2-shared/src/interface.ts
packages/s2-vue/src/hooks/useEvents.ts
packages/s2-vue/src/utils/initPropAndEmits.ts
s2-site/docs/api/components/sheet-component.zh.md

添加 onDataCellSelectMove 事件。在 selectMove 交互（键盘上下左右选择选中格子）触发时，抛出事件。用于需要外部 UI 和 selectMove 联动的场景。

feat(interaction): 添加 onDataCellSelectMove 事件

---

packages/s2-core/__tests__/unit/sheet-type/pivot-sheet-spec.ts
packages/s2-core/src/common/store/index.ts
packages/s2-core/src/sheet-type/spread-sheet.ts
packages/s2-react/__tests__/unit/hooks/useSpreadSheet-spec.ts
packages/s2-react/src/hooks/useSpreadSheet.ts
packages/s2-vue/src/hooks/useSheetUpdate.ts
s2-site/docs/api/basic-class/spreadsheet.zh.md

🐛 Bugfix
对于 React 和 Vue 版本 的 `SheetComponent`, dataCfg.fields.columns 切换为单列头后, 未清空保存在 store 中的叶子节点, 导致点击隐藏列头后还是拿到上一次的叶子节点, 隐藏失效
| ![Kapture 2022-06-21 at 11 14 44](https://user-images.githubusercontent.com/21015895/174708811-9e9a363d-47ca-4ebe-87a8-b0d3d5821391.gif) | ![Kapture 2022-06-21 at 11 13 35](https://user-images.githubusercontent.com/21015895/174708697-3f7f4c31-3411-4636-b3fa-b83ab50c1043.gif) |

fix(strategysheet): 修复趋势分析表多列头切换为单列头后, 隐藏列头功能失效

---

packages/s2-core/src/ui/tooltip/index.less

✨ Feature
🎨 Enhance
默认是允许用户复制 tooltip 信息的，底表样式增加一个，防止不必要的样式覆盖

fix: 增加tooltip允许复制的样式防止被外部覆盖

---

packages/s2-core/__tests__/unit/ui/tooltip/index-spec.ts
packages/s2-core/__tests__/unit/utils/tooltip-spec.ts
packages/s2-core/src/common/constant/tooltip.ts
packages/s2-core/src/common/interface/tooltip.ts
packages/s2-core/src/ui/tooltip/index.less
packages/s2-core/src/ui/tooltip/index.ts
packages/s2-core/src/utils/tooltip.ts
packages/s2-react/playground/config.ts
packages/s2-react/playground/index.tsx
s2-site/docs/common/tooltip.zh.md
s2-site/docs/manual/basic/tooltip.zh.md

🐛 Bugfix
1. 当tooltip内容很多超过屏幕时, 显示不全, 也无法滚动, 加上最大高度限制, 并运行滚动
2. 同时增加 containerStyle 和 containerClassName, 允许挂载自定义类名
| ![image](https://user-images.githubusercontent.com/21015895/174975890-09bdbe2b-e6ae-443e-9593-21173528033c.png) | ![image](https://user-images.githubusercontent.com/21015895/174975490-6e641e27-b937-4792-8115-ad0a92747016.png)  |

feat(tooltip): 支持额外的样式和类名 & 修复内容过长 tooltip 展示不全的问题

---

packages/s2-core/src/utils/text.ts
packages/s2-react/package.json

🐛 Bugfix
趋势表使用 `drawObjectText` 绘制数值列头时：
- 之前：通过 `const dataCellStyle = cell.getStyle(CellTypes.DATA_CELL)` 使用的数据单元格文字样式
- 现在：改为使用列头主题样式。
改动：
- 新增 `getDrawStyle` 函数，判断是否列头数值字段，选用不同的 cell 主题样式和 textStyle
- `getTextStyle` 更名 `getCurrentTextStyle`，复用 `getDrawStyle`  返回的 textStyle
|    <img width="479" alt="CleanShot 2022-06-22 at 20 32 19@2x" src="https://user-images.githubusercontent.com/6716092/175029705-63d63d2a-8e09-4951-b07e-71614cfc1a9d.png">    |   <img width="494" alt="CleanShot 2022-06-22 at 20 29 57@2x" src="https://user-images.githubusercontent.com/6716092/175029273-c61003ab-8456-4cdc-941d-88681a8decb2.png">     |

fix: 趋势表自定义列头数值误用数据单元格样式

---

packages/s2-core/__tests__/unit/data-set/table-data-set-spec.ts
packages/s2-core/src/data-set/table-data-set.ts
packages/s2-core/src/interaction/base-interaction/click/data-cell-click.ts
packages/s2-react/playground/index.tsx

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore
feat: 明细表的 getCellData 可获取单行数据
fix: 明细模式下返回值 对齐 聚合模式，添加 rowIndex

feat: 明细表的 getCellData 可获取单行数据

---

s2-site/docs/manual/basic/sheet-type/pivot-mode.zh.md

🐛 基础教程中的表形态透视表的 React组件方式中，dataCfg  对象内少了一个 `,` 会导致报错

docs: 修改透视表文档

---

packages/s2-core/__tests__/unit/interaction/data-cell-multi-selection-spec.ts
packages/s2-core/__tests__/unit/interaction/range-selection-spec.ts
packages/s2-core/__tests__/unit/interaction/root-spec.ts
packages/s2-core/src/interaction/base-event.ts
packages/s2-core/src/interaction/data-cell-multi-selection.ts
packages/s2-core/src/interaction/range-selection.ts
packages/s2-core/src/interaction/root.ts

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore
复现场景
在使用meta键或者shift键进行单元格多选的时候，如果通过触控板切换桌面，会导致快捷键的状态没有取消，之后再切换回当前页面的时候还是处于多选状态中
场景预期
切换会桌面的时候，多选状态会被清除，重新点击变成单选。
解决方案
监听window的visibilitychange事件，change之后将DataCellMultiSelection和 RangeSelection的状态reset（只有这两个交互设计到键盘事件和鼠标事件叠加状态）

fix(interaction): 修复按下快捷选中按钮之后通过触摸板切换页面，快捷键状态没有reset的问题

---

packages/s2-core/__tests__/unit/interaction/base-interaction/click/data-cell-click-spec.ts
packages/s2-core/__tests__/unit/interaction/base-interaction/click/row-column-click-spec.ts
packages/s2-core/__tests__/unit/interaction/base-interaction/click/row-text-click-spec.ts
packages/s2-core/src/cell/base-cell.ts
packages/s2-core/src/cell/row-cell.ts
packages/s2-core/src/common/interface/basic.ts
packages/s2-core/src/interaction/base-event.ts
packages/s2-core/src/interaction/base-interaction/click/data-cell-click.ts
packages/s2-core/src/interaction/base-interaction/click/row-column-click.ts
packages/s2-core/src/interaction/base-interaction/click/row-text-click.ts
packages/s2-core/src/interaction/base-interaction/hover.ts
packages/s2-core/src/interaction/row-column-resize.ts
packages/s2-core/src/utils/interaction/formatter.ts
packages/s2-react/playground/index.tsx

🐛 Bugfix
1. 点击 rowCell 和 dataCell 的链接文字时, 会触发相应自身的交互, 如单选, 显示 tooltip 等, 应该过滤
2. `isRowHeaderText` 重命名为 `isLinkFieldText`
| ![image](https://user-images.githubusercontent.com/21015895/175915710-52aa33db-df87-40f9-a4ac-293aca041933.png) | ![image](https://user-images.githubusercontent.com/21015895/175915644-e5c530aa-58d1-4ae9-bf6b-ca21824047d7.png) |

fix(interaction): 修复链接跳转会触发单选和 Tooltip 显示的问题

---

packages/s2-core/__tests__/spreadsheet/theme-spec.ts
packages/s2-core/__tests__/unit/cell/col-cell-spec.ts
packages/s2-core/__tests__/unit/utils/text-spec.ts
packages/s2-core/src/cell/col-cell.ts
packages/s2-core/src/sheet-type/spread-sheet.ts
packages/s2-core/src/theme/index.ts
packages/s2-core/src/utils/canvas.ts
packages/s2-core/src/utils/cell/cell.ts
packages/s2-core/src/utils/text.ts

🐛 Bugfix
列头文字&icon 无法正确对齐，主要原因有：
- `measureText` 中 canvas 没有渲染到 dom 数，无法继承 body 上的 css 样式，导致估计值与实际值有差距
- 最早的列头 col.ts 绘制文字时，只有 center 样式，即提供给 `g` 文字中心点位置即可。后支持了 `left`、`right` 绘制，但是 `getTextPosition` 等依旧计算的是中心点，导致有偏移效果。
以 `textAlign=right` 为例，以下 demo 分别为不带 icon 和带 icon
| ![CleanShot 2022-07-04 at 11 11 17](https://user-images.githubusercontent.com/6716092/177075028-5dd5f7fb-d9b2-45a4-9012-86bb6d616496.gif) | ![CleanShot 2022-07-04 at 11 08 32](https://user-images.githubusercontent.com/6716092/177074754-13fc5963-cd9b-4575-b665-baf1001be69a.gif) |
| ![CleanShot 2022-07-04 at 11 12 27](https://user-images.githubusercontent.com/6716092/177075142-3d811223-5a5d-45d5-9dd8-0185e66747ad.gif)      |   ![CleanShot 2022-07-04 at 11 07 …

fix: 列头文字&icon无法正确对齐

---

packages/s2-react/__tests__/unit/components/sheets/index-spec.tsx
packages/s2-react/playground/config.ts
packages/s2-react/playground/index.tsx
packages/s2-react/src/components/sheets/strategy-sheet/custom-tooltip/custom-data-tooltip.tsx
packages/s2-react/src/components/sheets/strategy-sheet/index.tsx

🐛 Bugfix
趋势分析表本身就是对 s2-core 的 tooltip 自定义, 但是业务侧还需要对趋势分析表的 Tooltip 再次进行自定义, 所以需要暴露一个口子

fix(strategysheet): 修复趋势分析表无法自定义 Tooltip

---

packages/s2-core/src/utils/data-set-operate.ts

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore
之前的`flatten`计算对于内存和性能消耗都很大，如果表格数据量特别大时，并且遇到单元格刚好是行总计和列总计的交叉单元格，s2会将所有的数据拿到然后再进行`flatten`，会直接卡死
在64w条数据的情况下，`flatten`性能消耗：
| ❌   卡死   |  ![image](https://user-images.githubusercontent.com/17964556/177682577-aae0072c-2502-441b-98ee-cac04e05d011.png) |

fix: 修复大量数据下，行列总计单元格计算时耗时和内存问题

---

packages/s2-react/__tests__/unit/components/sheets/index-spec.tsx
packages/s2-react/__tests__/unit/components/sheets/strategy-sheet/custom-tooltip/index-spec.tsx
packages/s2-react/src/components/index.ts
packages/s2-react/src/components/sheets/strategy-sheet/custom-tooltip/custom-col-tooltip.tsx
packages/s2-react/src/components/sheets/strategy-sheet/custom-tooltip/custom-data-tooltip.tsx
packages/s2-react/src/components/sheets/strategy-sheet/custom-tooltip/custom-row-tooltip.tsx
packages/s2-react/src/components/sheets/strategy-sheet/custom-tooltip/index.ts
packages/s2-react/src/components/sheets/strategy-sheet/custom-tooltip/interface.ts
packages/s2-react/src/components/sheets/strategy-sheet/index.tsx

✨ Feature
1. 将趋势分析表自定义的三个 Tooltip 透出, 业务层可对其进行引用, 而不用完全自定义
2. 增加 label 属性, 允许自定义标题
```tsx
<StrategySheetDataTooltip cell={cell} label={'指标A (求和)'} />
```

feat(strategysheet): 趋势分析表 Tooltip 增加 label 属性用于自定义标题

---

packages/s2-core/__tests__/unit/sheet-type/pivot-sheet-spec.ts
packages/s2-core/src/cell/header-cell.ts
packages/s2-react/__tests__/data/mock-dataset.json
packages/s2-react/__tests__/spreadsheet/drill-down-spec.tsx
packages/s2-react/playground/index.tsx
packages/s2-shared/src/utils/drill-down.ts

🐛 Bugfix
🔧 Chore
1. values 配置为空时未显示下钻 icon
当 fields.values 为空时, 由于布局限制, 会将 valueInCols 为空
https://github.com/antvis/S2/blob/a92a4b717f48dd12040ce1d3fac02bdc8aea157a/packages/s2-core/src/utils/merge.ts#L50
而下钻需要置为列头, 导致影响了显示下钻icon的判断
2. 默认的 sort icon 加上 values 不为空的限制
| ![image](https://user-images.githubusercontent.com/21015895/177697173-555fa084-cc26-4391-aafe-ab74d625647b.png) |  ![image](https://user-images.githubusercontent.com/21015895/177697011-aec300be-292e-40a7-b835-3c86f671c811.png) |
close #1514

fix(drill-down): values 配置为空时未显示下钻 icon

---

packages/s2-core/__tests__/unit/utils/g-mini-charts-spec.ts
packages/s2-core/src/utils/g-mini-charts.ts
packages/s2-react/__tests__/data/strategy-data.ts

🐛 Bugfix
* 修复趋势相同、为负等多种情况下折线图柱状图绘制不正确问题

fix: 优化 mini 图坐标计算逻辑

---

packages/s2-core/__tests__/spreadsheet/theme-spec.ts
packages/s2-core/__tests__/unit/interaction/row-column-resize-spec.ts
packages/s2-core/src/interaction/row-column-resize.ts
packages/s2-core/src/sheet-type/spread-sheet.ts
packages/s2-core/src/theme/index.ts
packages/s2-react/playground/config.ts
packages/s2-react/playground/index.tsx
packages/s2-react/src/components/sheets/base-sheet/index.tsx
s2-site/docs/api/basic-class/spreadsheet.zh.md
s2-site/docs/manual/basic/theme.zh.md
s2-site/docs/manual/faq.zh.md

🐛 Bugfix
序号列的宽度属于 `rowCell.seriesNumberWidth` 主题配置, 在序号列拖拽后会通过改变它进行宽度更新
此时 `palette` 为空, 导致 `palette` 被覆盖, 解法是新增 `setTheme` 方法只负责更新主题, 和 `setThemeCfg` 方法分开
| ![Kapture 2022-07-08 at 17 08 58](https://user-images.githubusercontent.com/21015895/177958718-71b839fa-5b66-4169-9874-517089686ec7.gif) | ![Kapture 2022-07-08 at 17 07 24](https://user-images.githubusercontent.com/21015895/177958442-d63c149e-b25a-4a17-a68e-6204bdaf2c9a.gif) |

fix(theme): 修复调整序号列后色板丢失 close #1538

---

.github/workflows/sync-site-lock-changelog-with-pr.yml
packages/s2-core/__tests__/unit/sheet-type/pivot-sheet-spec.ts
packages/s2-core/__tests__/unit/ui/tooltip/index-spec.ts
packages/s2-core/src/common/interface/tooltip.ts
packages/s2-core/src/ui/tooltip/index.ts
packages/s2-react/__tests__/util/helpers.ts

✨ Feature
🐛 Bugfix
- feat: options.tooltip.className 支持数组形式以设置多个类名
- fix: BaseTooltip destroy 后 this.container 变量未重置

feat(tooltip): 支持设置多个class类名

---

packages/s2-core/src/facet/base-facet.ts

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore
在移动端中，event中prevent方法存在于`originalEvent`中：
| ![2022-07-11 13 03 44](https://user-images.githubusercontent.com/17964556/178192424-3d01087b-12bc-4398-ac27-d8078ea3aa73.gif)      |  ![2022-07-11 13 03 05](https://user-images.githubusercontent.com/17964556/178192418-6af55ca7-7d10-46fe-8f0f-c26733784cd1.gif)    |

fix: 修复移动端滚动没有prevent问题

---

packages/s2-react/__tests__/unit/components/sheets/index-spec.tsx
packages/s2-react/__tests__/unit/components/sheets/strategy-sheet/custom-tooltip/__snapshots__/index-spec.tsx.snap
packages/s2-react/__tests__/unit/components/sheets/strategy-sheet/custom-tooltip/index-spec.tsx
packages/s2-react/__tests__/util/helpers.ts
packages/s2-react/src/components/sheets/strategy-sheet/custom-tooltip/custom-data-tooltip.tsx
packages/s2-react/src/components/sheets/strategy-sheet/custom-tooltip/custom-row-tooltip.tsx
packages/s2-react/src/components/sheets/strategy-sheet/index.tsx
packages/s2-react/src/components/sheets/strategy-sheet/utils/index.ts
s2-site/docs/manual/basic/analysis/strategy.zh.md

✨ Feature
🔧 Chore
```ts
tooltip: {
content: (cell) => <StrategySheetRowTooltip cell={cell} label={(cell, defaultLabel) => `${defaultLabel}（自定义标题`} />
}
}
```
满足业务侧, 需要对 行头和列头再次自定义 Tooltip 的场景
ref https://github.com/antvis/S2/pull/1523

feat(strategysheet): 趋势分析表允许对行头和列头的 tooltip 做自定义

---

.eslintrc.js
packages/s2-core/__tests__/unit/utils/cell/cell-spec.ts
packages/s2-core/src/utils/cell/cell.ts
packages/s2-core/src/utils/export/index.ts
packages/s2-react/__tests__/data/strategy-data.ts
packages/s2-react/__tests__/spreadsheet/strategy-sheet-spec.tsx
packages/s2-react/playground/config.ts
packages/s2-react/playground/index.tsx
packages/s2-react/src/components/sheets/strategy-sheet/custom-data-set.ts

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore
趋势分析表即使有多个层级的行头，`rows`配置也只有`extra`，此时，角头部分需要增加占位来对齐行头的单元格，以下图为例：
| ![image](https://user-images.githubusercontent.com/17964556/178293768-abb11d96-5a53-4d73-8d51-1f166fa957f7.png) | ![image](https://user-images.githubusercontent.com/17964556/178293454-a0f678d4-dd4e-4cb3-b89e-67fe61a58816.png)     |

fix: 修复趋势分析表导出问题

---

packages/s2-core/src/facet/layout/build-row-tree-hierarchy.ts
packages/s2-react/__tests__/unit/utils/drill-down-spec.ts
packages/s2-shared/src/utils/drill-down.ts

🐛 Bugfix
s2 通过 drillItemsNum 来约束下钻维度展示的个数，但是没有特殊判断 -1、0 等。
实际只有 drillItemsNum > 0 时，限制才会有意义。
> 附：清空下钻数据时，s2 也会把下钻个数重置为 -1 `clearDrillDownData@pivot-data-set.ts`，导致问题

fix: 下钻个数为-1时应展示全部下钻数据

---

packages/s2-vue/src/components/tooltip/components/operator/index.vue
packages/s2-vue/src/components/tooltip/components/operator/menu.vue

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore
表面上是排序交互不起作用，实质上是s2-vue在生成菜单时有一种边界情况没有处理：
P.s：这个bug是我昨天报告的，由于项目现在需要这个功能，所以给你们提个PR，希望能尽快处理🙃
| ![before](https://user-images.githubusercontent.com/17797002/178448607-2a6d4dd6-94a8-4c14-be4e-9a4651fd9098.gif) |  ![Kapture 2022-07-13 at 16 20 34](https://user-images.githubusercontent.com/17797002/178686194-53341ae7-ab66-4ca3-9b98-f8a82f566566.gif) |
https://github.com/antvis/S2/issues/1554

fix(s2-vue): 修复表头排序交互不起作用的问题

---

packages/s2-core/__tests__/bugs/issue-1539-spec.ts
packages/s2-core/src/facet/layout/build-table-hierarchy.ts
packages/s2-core/src/facet/table-facet.ts
packages/s2-core/src/group/grid-group.ts

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore
明细表使用 grid 进行边框绘制时，对左侧边框是否绘制判断逻辑有问题，同时会导致行列冻结时，clip区域有错误，明细表绘制左边边框的场景有两种：
1. 存在行头冻结，需要为冻结的行头组添加边框
2. 不存在行头冻结，需要为默认的 Grid 组添加边框
| ![2022-07-14 12 01 12](https://user-images.githubusercontent.com/17964556/178895851-6e03fe12-5a1d-4d0c-aa69-aa6bb60b2513.gif) ![2022-07-14 12 01 49](https://user-images.githubusercontent.com/17964556/178895882-fc3e84e0-b182-4afa-ac33-ac54ff968eb4.gif)     |    ![2022-07-14 12 00 36](https://user-images.githubusercontent.com/17964556/178895763-5ae12675-7c89-4f73-a6ea-ad58d4a2e148.gif)  ![2022-07-14 12 00 13](https://user-images.githubusercontent.com/17964556/178895746-4980c46a-1831-4d31-af51-b7ced6889af0.gif) |

fix: 修复明细表最左侧边框绘制问题

---

packages/s2-core/__tests__/unit/utils/merge-cell-spec.ts
packages/s2-core/src/common/constant/basic.ts
packages/s2-core/src/facet/base-facet.ts
packages/s2-core/src/sheet-type/spread-sheet.ts
packages/s2-core/src/utils/interaction/merge-cell.ts

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore
原因：gridGroup用于绘制边框，绘制完成后会`toFront`，导致它被放在最上面的，把合并单元格给盖住了。
现在将所有的合并单元格收敛到`mergedCellsGroup`中统一管理，并且在`drawGrid`后，将`mergedCellsGroup` toFront，保证其不会被覆盖
| ![2022-07-15 18 07 58](https://user-images.githubusercontent.com/17964556/179202560-583146ee-56bf-4191-970b-faf61081a300.gif)      | ![2022-07-15 18 07 37](https://user-images.githubusercontent.com/17964556/179202552-65083c7e-c71b-4fc4-b14a-47597d4e6c13.gif)     |

fix: 修复合并单元格被grid边框覆盖的问题

---

packages/s2-core/__tests__/bugs/issue-1539-spec.ts
packages/s2-core/__tests__/bugs/issue-1561-spec.ts
packages/s2-core/src/common/constant/basic.ts
packages/s2-core/src/group/grid-group.ts

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore
grid line 在绘制时，包围盒计算有点问题，会代入lineWidth
比如传入的 x1=0, x2=10, lineWidth=20
最后line得出来的包围盒 minX=-10, maxX=20，会将lineWidth/2纳入计算中
最后就会导致更新过程中，GridGroup的包围盒不断被放大，并且只会出现在 lineWidth >=2时（猜测是 lineWith=1 时，lineWidth/2会向下取整为0了，当好负负得正）
因此在传入时，将这部分坐标减去，并结合lineCap将这部分绘制出来，达到内容区域绘制不变，包围盒计算正确的目的
| ![2022-07-15 14 30 21](https://user-images.githubusercontent.com/17964556/179164982-455ab170-3586-45e4-b140-0df0d4e2bd96.gif)![2022-07-15 14 30 33](https://user-images.githubusercontent.com/17964556/179164986-6c419cac-499e-4217-bd92-8c2694ac24aa.gif)      | ![2022-07-15 14 30 48](https://user-images.githubusercontent.com/17964556/179164993-75bc556a-568d-429d-a622-72d3c8627283.gif) ![2022-07-15 14 31 …

fix: 修复 line 包围盒问题

---

packages/s2-vue/src/components/tooltip/components/summary.vue

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore
s2-vue 明细表圈选多个 dataCell 不应该显示总和

fix: s2-vue 保持和react组件一致的tooltip summary渲染逻辑

---

.github/workflows/lint.yml
.github/workflows/test.yml
packages/s2-core/src/theme/index.ts
packages/s2-core/src/utils/g-mini-charts.ts
packages/s2-core/src/utils/text.ts
packages/s2-react/__tests__/data/strategy-data.ts
packages/s2-react/__tests__/unit/components/sheets/index-spec.tsx
packages/s2-react/playground/config.ts

🐛 Bugfix
1. 绘制字段图指标时, 由于浮点数精度为 0, 导致低于 1% 的数值显示错误, 修改为 toFixed(2)
2. 子弹图绘制预留额外的宽度, 以便于完整的显示 `0%` => `0.22%`, 解决文本部分越界的问题
3. 兼容目标为负数的场景, 按照进度为 `0` 处理  (KPI 目标 和普通的双向柱状图, 负数左, 正数右不同)
| ![image](https://user-images.githubusercontent.com/21015895/178920235-c3d8fb1b-4e0d-4566-a770-0feb50614718.png) | ![image](https://user-images.githubusercontent.com/21015895/178920297-8ef22def-fc1d-4e97-930c-563bb378b5d0.png) |

fix(strategysheet): 修复子弹图进度小于 1% 时显示错误的问题

---

packages/s2-core/__tests__/unit/facet/pivot-facet-spec.ts
packages/s2-core/__tests__/unit/utils/merge-cell-spec.ts
packages/s2-core/src/facet/base-facet.ts
packages/s2-core/src/facet/table-facet.ts
packages/s2-core/src/group/grid-group.ts
packages/s2-core/src/group/panel-scroll-group.ts
packages/s2-core/src/sheet-type/spread-sheet.ts
packages/s2-core/src/utils/interaction/merge-cell.ts

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore
`mergedCellsGroup`作为`panelScrollGroup`的子节点，在每次`panelScrollGroup`清空时，需要重建父子关系，否则就会出现多次初始后不成功。
原本的`mergedCellsGroup`是作为`sheet`的属性存在，又被挂在了`panelScrollGroup`上，逻辑不够收敛。所以本次改动直接将所有`mergedCellsGroup`收敛到`PanelScrollGroup`中，降低代码耦合性，对于gridGroup和mergedGroup的层级控制也更直接
| 表格初始化Before | 表格初始化After |
| ![image](https://user-images.githubusercontent.com/17964556/179668563-8bab122b-bddf-47d1-91ec-17c9ab44e7d5.png)      | ![image](https://user-images.githubusercontent.com/17964556/179668469-651f5789-976f-40f8-b41b-1c781763ea5a.png)     |

fix: 修复初始化时, border不见的问题

---

packages/s2-core/src/utils/g-mini-charts.ts
packages/s2-react/__tests__/data/strategy-data.ts
packages/s2-react/__tests__/unit/components/sheets/index-spec.tsx

🐛 Bugfix
1. 修复当百分比过大, 且列宽过小时, 子弹图宽度计算为负数, 同时 G 又支持 负数绘制, 出现了如下图的效果...
同时需要配合 https://github.com/antvis/S2/pull/1583 对子弹图列做限制, 不允许拖拽缩小宽度
2. 修复百分比为负数时，数值错误的显示为 `0%`，应该是进度为0，但是数值还是为 `-xx%`
| ![image](https://user-images.githubusercontent.com/21015895/179733452-cb9f4252-77da-49dc-9a40-df52e21dbf41.png) | ![image](https://user-images.githubusercontent.com/21015895/179733198-366fcced-f4c3-4dd1-a765-405eb679e590.png)  |

fix(strategysheet): 修复单元格宽度拖拽变小后子弹图宽度计算错误

---

packages/s2-core/__tests__/spreadsheet/scroll-spec.ts
packages/s2-core/__tests__/unit/facet/pivot-facet-spec.ts
packages/s2-core/__tests__/unit/facet/table-facet-spec.ts
packages/s2-core/src/common/interface/basic.ts
packages/s2-core/src/facet/base-facet.ts
packages/s2-core/src/facet/pivot-facet.ts
packages/s2-core/src/facet/table-facet.ts
packages/s2-react/playground/config.ts
s2-site/docs/common/style.zh.md
s2-site/docs/manual/advanced/custom/cell-size.zh.md
s2-site/examples/layout/custom/demo/custom-row-col-cell-width.ts
s2-site/examples/layout/custom/demo/meta.json

✨ Feature
1. 行头/列头支持动态配置单元格宽度, 支持 `width: number | ((node: Node) => number)` 两种方式
2. 修复部分错误文档
```ts
style: {
rowCfg: {
// 固定配置: 行头单元格 100px
// width: 100,
// 动态配置: 叶子节点 300px, 非叶子节点 200px
width: (row) => {
console.log('row: ', row);
return row.isLeaf ? 300 : 200;
},
},
colCfg: {
// 固定配置: 每列 100px
// width: 100,
// 动态配置: 偶数列 100px, 奇数列 200px
width: (col) => {
console.log('col: ', col);
return col.colIndex % 2 === 0 ? 100 : 200;
},
},
},
};
```
为什么不能用 `widthByFieldValue` ?
`widthByFieldValue` 最初的设计是服务于 表格拖拽 resize 的场景, 所以会发现没有 `colCfg.width` 这种配置, 如果作为预设宽度的场景需要提前支持**具体的维值或 id**, 且无法拿到单元格节点信息, 不是很方便, 且不太灵活, 两种配置服务不同的场景
- `colCfg.widthByFieldValue`: 适用于内部拖拽数据存储, 或者每一列都需要预设的场景
- `colCfg.width`: 适用于依赖节点信息, 动态调整某列的宽度的场景
close #1585

feat(layout): 支持自定义行/列单元格宽度 close #1585

---

packages/s2-core/src/common/icons/gui-icon.ts
packages/s2-react/src/components/sheets/strategy-sheet/custom-tooltip/index.less

🐛 Bugfix
1. 之前只对 SVG 中的 `#` 转义, 之前有 `.replace(/#/g, '%23');` 的处理, 未转义完整, 改为 `encodeURIComponent`
2. 为什么只有 `Plus` 和 `Minus` 这两个 icon 加载失败? 原因是有 `\t` (感谢 VSCode)
| ![image](https://user-images.githubusercontent.com/21015895/180415160-d52e029c-e307-469b-b064-a4f38fed391b.png)  | ![image](https://user-images.githubusercontent.com/21015895/180415056-f1b64742-8e43-4350-9868-259b97b4701c.png)  |

fix(layout): 修复 Firefox 浏览器部分 icon 渲染失败 close #1571

---

packages/s2-core/__tests__/spreadsheet/hidden-columns-spec.ts
packages/s2-core/__tests__/spreadsheet/table-sheet-spec.ts
packages/s2-core/src/cell/table-col-cell.ts

✨ Feature
🎨 Enhance
🐛 Bugfix
| ❌  
| ✅   
|

fix: 有冻结行且有垂直 scrollWidth 时冻结行无法 resize

---

packages/s2-core/__tests__/unit/utils/sort-action-spec.tsx
packages/s2-core/src/utils/sort-action.ts

🐛 Bugfix
> 原 issue 描述有偏差，以实际修复说明为准
如下图所示，使用 sortByFunc 按 mesure 排序时，用户自定义的 sortFunc 会接受通过 query 查询出的数据 sortData。
当某些数据格数据缺失时（如 `湖南` 的城市），返回 sortData 也会对应缺失。
在这种情况下，用户使用缺失的数据，经过 sortFunc 返回给 s2 也是缺失的维度数据。
```
 ['四川[&]成都', '四川[&]绵阳', '浙江[&]杭州', '浙江[&]丽水']
```
而缺失的数据会直接存到 `sortedDimensionValues` 里，进而影响后续的 layout 结果。
> 湖南下属城市消失了
|  <img width="808" alt="CleanShot 2022-07-23 at 17 19 14@2x" src="https://user-images.githubusercontent.com/6716092/180598972-060cbbc1-0e0d-4b21-aaf8-f518ef5d0b22.png">      |  <img width="805" alt="CleanShot 2022-07-23 at 17 18 49@2x" src="https://user-images.githubusercontent.com/6716092/180598959-93977f4e-ab1b-4b94-874d-6bf1c4bfbbcb.png">    |

fix: sortByFunc 排序后行列维度节点丢失

---

packages/s2-core/__tests__/unit/interaction/selected-cell-move-spec.ts
packages/s2-core/src/interaction/selected-cell-move.ts

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore
场景：方向键向左移动之后选中了移动后的Cell（仅最左侧Cell有影响），但是ScrollX没有跟随着滚动过去。
原因：ScrollX比较的是移动后Cell的X和frozenColBBox.width, 这里会出现一种场景，冻结行的分割线是用冻结行右侧X作为中心往两边划的，计算frozenColBBox.width的时候会把verticalBorderWidth / 2 的宽度加上，和cell.x比较会有出入,导致无法正常向左滚动。
解决方案：使用frozenColGroup.getBBox().width - splitLineStyle.verticalBorderWidth / 2来获得真实的冻结行的宽度。

fix(interaction): 向左移动到不完全可见cell的时候，没有滚动过去

---

packages/s2-core/__tests__/unit/utils/export/export-spec.ts
packages/s2-core/src/utils/export/index.ts

🐛 Bugfix
复制明细表数据时，`header ` 不应再被 formatter。
因为明细表中，colLeafNodes 各个 node 的 field 就是 fields.column 配置的 field，
表头如果按该 field 取 formatter，而该 formatter 应格式化的是整列的数据，而不是表头 label。
表头 label 直接取 name 即可。
> console 打印了 `copyData` 的数据，注意表头
|    ![CleanShot 2022-07-26 at 10 01 52](https://user-images.githubusercontent.com/6716092/180906447-a5cd472e-5629-4bef-a4e5-b174072d11d4.png)    |  ![CleanShot 2022-07-26 at 10 00 12](https://user-images.githubusercontent.com/6716092/180906281-9fad90b1-fb53-4713-8a35-dd0b251f36e7.png)    |

fix: 明细表复制时无需使用formatter格式化列头label

---

packages/s2-core/__tests__/spreadsheet/table-sheet-spec.ts
packages/s2-core/package.json
packages/s2-core/src/interaction/event-controller.ts
yarn.lock

✨ Feature
🐛 Bugfix
🔧 Chore
原有逻辑对于最右侧column无法resize，因为事件挂载在canvas上，改为mousedown后监听window上的mousemove事件，并在mouseup时销毁

feat: 支持resize最右侧column

---

packages/s2-core/__tests__/unit/cell/col-cell-spec.ts
packages/s2-core/__tests__/unit/cell/data-cell-spec.ts
packages/s2-core/src/cell/data-cell.ts
packages/s2-core/src/cell/header-cell.ts
packages/s2-core/src/cell/table-col-cell.ts
packages/s2-core/src/common/interface/basic.ts
packages/s2-react/__tests__/data/strategy-data.ts
packages/s2-react/__tests__/spreadsheet/strategy-sheet-spec.tsx
packages/s2-react/__tests__/unit/components/sheets/index-spec.tsx
packages/s2-react/playground/config.ts
packages/s2-react/playground/index.tsx
packages/s2-react/src/components/sheets/strategy-sheet/custom-col-cell.ts
s2-site/docs/api/general/S2DataConfig.zh.md

🐛 Bugfix
1. 趋势分析表是自定义列头, 渲染文本没有适配 `meta.formatter`
```ts
meta: [
{
field: 'date',
name: '日期',
},
{
field: EXTRA_COLUMN_FIELD,
formatter: (value, data, meta) => {
return meta.colIndex === 0 ? 'test' : value;
},
},
],
```
2. formmater 增加第三个参数 `meta`, 用于根据当前单元格信息进行格式化
| ![image](https://user-images.githubusercontent.com/21015895/180984980-7d0176dd-9c2a-4e8e-8e8f-17227c18633e.png) | ![image](https://user-images.githubusercontent.com/21015895/180984925-c5690be7-89cd-444f-9ea4-789c59609299.png) |

fix(strategysheet): 修复趋势分析表列头格式化不生效

---

packages/s2-core/__tests__/bugs/issue-1587-spec.ts
packages/s2-core/src/common/constant/index.ts
packages/s2-core/src/common/constant/pagination.ts
packages/s2-core/src/facet/base-facet.ts
packages/s2-core/src/facet/utils.ts
packages/s2-core/src/interaction/event-controller.ts
packages/s2-react/playground/index.tsx
packages/s2-shared/src/utils/resize.ts
s2-site/docs/common/pagination.zh.md
s2-site/docs/manual/basic/analysis/pagination.zh.md
s2-site/docs/manual/basic/theme.zh.md
s2-site/docs/manual/getting-started.zh.md
s2-site/examples/theme/custom/demo/custom-schema.ts

🐛 Bugfix
1. 增加分页逻辑兜底, 当 current 未传, facet 计算 scrollY `getPaginationScrollY` 会为 `undefined`, 导致表格渲染空白
2. 修正一些错误文档
| ![image](https://user-images.githubusercontent.com/21015895/182324754-811400d3-74cc-4079-83a4-b0a5f89dd2d4.png)  | ![image](https://user-images.githubusercontent.com/21015895/182324650-33e8b45c-a92f-438e-8482-93e12b14e93b.png) |

fix(pagination): 分页配置未传 current 参数时表格渲染空白

---

.github/workflows/release-success.yml

chore: 发布成功后自动部署官网

---

packages/s2-core/__tests__/unit/facet/pivot-facet-spec.ts
packages/s2-core/__tests__/unit/interaction/row-column-resize-spec.ts
packages/s2-core/src/common/constant/options.ts
packages/s2-core/src/common/interface/basic.ts
packages/s2-core/src/facet/pivot-facet.ts
packages/s2-core/src/interaction/row-column-resize.ts
packages/s2-react/playground/config.ts
s2-site/docs/common/style.zh.md

🐛 Bugfix
由于历史原因, 同时存在两个 `treeRowsWidth`
```ts
const s2Option = {
hierarchyType: 'tree',
style: {
rowCfg: {
width: 50,
treeRowsWidth: 500
},
treeRowsWidth: 100,  // 以这个为准
},
};
```
1. style.rowCfg.treeRowsWidth : 宽高 resize 的时候使用
2. style.treeRowsWidth: 自定义宽高/预设场景
问题: 当同时存在 `style.rowCfg.width` 和 `style.treeRowsWidth` 时, 后者未生效
解法:
1. 废弃 `style.rowCfg.treeRowsWidth` 因为这两个属性其实是同一个含义
2. resize 的时候, 同时设置 `style.rowCfg.treeRowsWidth` 和 `style.treeRowsWidth` 保持兼容
| ![image](https://user-images.githubusercontent.com/21015895/182586427-bf26c0fa-5a2b-4383-b08b-188a99281a8a.png) | ![image](https://user-images.githubusercontent.com/21015895/182586310-834a0704-21fc-440d-8a74-b5d9dcbdcba7.png) |

fix(layout): 修复 treeRowsWidth 配置不生效 close #1622

---

packages/s2-core/CHANGELOG.md
packages/s2-core/package.json
packages/s2-react/CHANGELOG.md
packages/s2-react/package.json
packages/s2-vue/CHANGELOG.md
packages/s2-vue/package.json
yarn.lock

🤖 由 [[Sync Site S2 Lock And Changelog With PR](https://github.com/antvis/S2/blob/master/.github/workflows/sync-site-lock-changelog-with-pr.yml)] action 自动创建.

chore: 🤖 更新 lock 和 changelog 文件

---

packages/s2-core/__tests__/unit/facet/pivot-facet-spec.ts
packages/s2-core/__tests__/unit/facet/table-facet-spec.ts
packages/s2-core/__tests__/unit/utils/text-spec.ts
packages/s2-core/src/cell/base-cell.ts
packages/s2-core/src/cell/corner-cell.ts
packages/s2-core/src/facet/header/series-number.ts
packages/s2-core/src/facet/pivot-facet.ts
packages/s2-core/src/facet/table-facet.ts
packages/s2-core/src/sheet-type/spread-sheet.ts
packages/s2-core/src/utils/g-mini-charts.ts
packages/s2-core/src/utils/text.ts

🎨 Enhance
🐛 Bugfix
当 spreadsheet container 被应用了特殊的文字样式后（如 `letter-spacing`）
`drawLinkFieldShape@base-cell.ts` 绘制 `链接下划线` 会超过文字实际长度
drawLinkFieldShape 绘制下划线时，使用的是 g-base (`textShape.getBBox()`) 计算出的文字宽度
而 g-base 使用的是 [离屏 canvas](https://github.com/antvis/G/blob/0.5.12/packages/g-base/src/util/offscreen.ts)，不会应用 html 中任何样式，当 [计算文字尺寸](https://github.com/antvis/G/blob/a7f058fcec85457c65500226d1aca5c4a9cce0d1/packages/g-base/src/util/text.ts#L38) 时，与实际渲染有较大差距（如宽度）
之前在修复 [列头文字&icon](https://github.com/antvis/S2/pull/1515) 时，也发现了类似的问题。
当时把 s2 内部计算文字宽度的 offscreen canvas 放置到了 body，但实际场景中，特殊的文字样式是会设置到 container 这层，仅 body 的样式是不够的。
直接使用 spreadsheet container 挂载的 canvas 作为文字宽度计算的 ctx：
- 废弃 `utils/text.ts` 中的 `measureTextWidth`、`measureTextWidthRoughly` 函数使用（有 export 暂不移除源码）
- 移动 …

fix: 链接字段高亮下划线过长

---

packages/s2-core/src/interaction/root.ts
packages/s2-core/src/utils/interaction/state-controller.ts

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore
场景：window.click每次都会触发reset操作，如果S2实例多的时候，draw的性能较差。
原因分析：主要耗时在clearState里面draw调用的requestAnimationFrame（后续还有消耗）
解决思路：clearState的时候做个判断，如果都是初始状态，不需要clear的情况，return false 然后不掉用draw方法

fix(interaction): 优化resetSheetStyle性能

---

packages/s2-core/__tests__/bugs/issue-1668-spec.ts
packages/s2-core/__tests__/data/data-issue-1668.json
packages/s2-core/src/cell/col-cell.ts

🐛 Bugfix
父节点是小/总计节点时, 没有添加 id 信息, 导致拖拽的时候无法更新宽度信息
| ![Kapture 2022-08-11 at 18 08 56](https://user-images.githubusercontent.com/21015895/184111348-8b2b10de-6037-4843-9a7e-f0074cf0dfc0.gif) |

fix(resize): 修复总计列存在子节点时无法调整宽度

---

packages/s2-core/src/facet/table-facet.ts
packages/s2-core/src/sheet-type/table-sheet.ts
packages/s2-react/playground/index.tsx

🐛 Bugfix
明细表排序后会reload data 导致 table-facet rebuild，而原来在 table-facet destroy 的时候 解绑了 RANGE_SORT 和 RANGE_FILTER，导致外部用户使用时无法监听到这两个事件。 因此将逻辑挪到 TableSheet destory 的时候进行。

fix: 修复明细表 onRaneSort 失效问题

---

packages/s2-core/src/utils/export/index.ts
packages/s2-react/__tests__/data/strategy-data.ts
packages/s2-react/__tests__/spreadsheet/strategy-sheet-spec.tsx

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore
趋势分析表每一个列头下可以包含不同的个数的同环比，而`export`时都是按照最大的同环比个数来做的日期列头后空格子补全。
一旦出现列头同环比数量不一致，就会出现复制的列头和数据对不齐的问题
| ![image](https://user-images.githubusercontent.com/17964556/184272417-7f96efda-fbc7-4b12-af4d-faca59dcde98.png)    | ![image](https://user-images.githubusercontent.com/17964556/184272541-2d980442-f87b-4310-a9ec-79ffacb60061.png)   |

fix: 修复趋势分析表对于不同个数同环比列头复制时，数据不对齐的问题

---

packages/s2-core/__tests__/spreadsheet/scroll-spec.ts
packages/s2-core/src/common/interface/scroll.ts
packages/s2-core/src/facet/base-facet.ts
packages/s2-core/src/ui/scrollbar/index.ts
packages/s2-react/playground/config.ts
packages/s2-react/playground/index.tsx
s2-site/docs/api/basic-class/base-facet.zh.md

🐛 Bugfix
背景
g 4.x 版本计算 BBox 包围盒有问题, 由于滚动条 lineCap 是 `round`, 导致实际渲染的宽度比传入的宽度大 (渲染宽度 = 给定宽度 + round 多出了那部分宽度)
解法
1. 参考以下处理方式, 修正渲染宽度, 减去 `round` 椭圆的一部分像素
https://github.com/antvis/S2/blob/77cd111ea4d01f86d29e384e564d761c0f6c0881/packages/s2-core/src/group/grid-group.ts#L52-L56
2. 修复冻结行头, 且是列紧凑模式 (数值单元格无滚动条) 情况下, 无法滚动
3. 修复横向滚动至边缘时, 表格依然在重新 render, 且 emit scroll event
| 场景 | Before | After |
|  ------ | ------ | ----- |
| 横/竖滚动条重合 | ![image](https://user-images.githubusercontent.com/21015895/184065787-6bfc7fc3-e4e7-40bb-b4f8-ddcd9eeba47c.png) | ![image](https://user-images.githubusercontent.com/21015895/184061782-6a757a7b-0f61-4237-9f1c-bf2a0a418f87.png)   |
| 行头滚动条和 dataCell 滚动条重合 |![image](https://user-images.githubusercontent.com/21015895/184065839-c46a1753-2595-4ff9-af4b-6dc4b116e996.png …

fix(scroll): 修复滚动条显示越界 & 优化滚动性能

---

packages/s2-core/__tests__/spreadsheet/table-sheet-spec.ts
packages/s2-core/__tests__/unit/interaction/brush-selection-spec.ts
packages/s2-core/src/interaction/base-interaction/click/data-cell-click.ts
packages/s2-core/src/interaction/brush-selection.ts
packages/s2-core/src/utils/interaction/select-event.ts
packages/s2-react/playground/index.tsx
s2-site/docs/manual/advanced/interaction/basic.zh.md

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore
Before：selectedHighlight仅作用于data-cell-click事件，导致刷选情况无法触发高亮行列头
将高亮对应行列头function抽离至
https://github.com/antvis/S2/blob/c5335badf47ccc89246c5a6d0575395bbb453f36/packages/s2-core/src/utils/interaction/select-event.ts
在brush-selection中调用
After: 刷选会更新所有的对应cell

feat: 刷选时支持高亮所有对应的行列头cell

---

packages/s2-core/src/facet/layout/build-gird-hierarchy.ts

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore
在DI侧，从明细模式切换到聚合模式时，如果数据量比较大，整个转换过程耗时非常久，排查原因是`uniqWith`函数耗时特别久
使用for来提前退出，减少开销

perf: 优化生成grid模式时性能问题

---

packages/s2-core/__tests__/unit/utils/cell/header-cell-spec.ts
packages/s2-core/src/cell/header-cell.ts
packages/s2-core/src/common/constant/events/basic.ts
packages/s2-core/src/common/interface/basic.ts
packages/s2-core/src/common/interface/emitter.ts
packages/s2-core/src/facet/pivot-facet.ts
packages/s2-core/src/utils/cell/header-cell.ts
packages/s2-core/src/utils/cell/table-col-cell.ts
s2-site/docs/api/components/drill-down.zh.md
s2-site/docs/common/custom/headerActionIcons.zh.md
s2-site/docs/common/header-action-icon.zh.md

✨ Feature
当前的 `options.headerActionIcons` 配置，属于同一个 config 下的图标 iconNames：
- 只能统一 `展示/隐藏`，通过 displayCondition 判断
- 只能统一设置是否 hover 展示，通过 defaultHide 判断
displayCondition、defaultHide 支持更细粒度的判断
- boolean 或判断回调函数
- 判断回调函数增加 actionName 参数
> 1. 省维度：隐藏 config 中单个 icon
> 2. 市维度：defaultHide 第二个 icon
|  ![image](https://user-images.githubusercontent.com/6716092/184634395-62ce149c-4510-4208-a920-795a2078a34e.png) | ![image](https://user-images.githubusercontent.com/6716092/184634742-b00fcd65-866e-4433-9ef7-579b2598d978.png)  |
|  ![CleanShot 2022-08-15 at 20 24 23](https://user-images.githubusercontent.com/6716092/184634582-214a1b64-f469-4eeb-b222-ea2c0c8a84dc.gif)     |   ![CleanShot 2022-08-15 at 20 31 39](https://user-images.githubusercontent.com/6716092/1846355 …

feat: actionIcons支持细粒度展示控制

---

packages/s2-core/src/common/interface/basic.ts
packages/s2-core/src/common/interface/s2Options.ts
packages/s2-react/__tests__/spreadsheet/__snapshots__/pagination-spec.tsx.snap
packages/s2-react/__tests__/spreadsheet/pagination-spec.tsx
packages/s2-react/__tests__/spreadsheet/spread-sheet-spec.tsx
packages/s2-react/playground/config.ts
packages/s2-react/src/components/pagination/index.tsx
packages/s2-react/src/components/sheets/base-sheet/index.tsx
packages/s2-react/src/components/sheets/index.tsx
packages/s2-react/src/components/sheets/interface.ts
packages/s2-react/src/utils/options.ts
packages/s2-shared/src/interface.ts
packages/s2-vue/src/interface.ts
packages/s2-vue/src/utils/initPropAndEmits.ts
s2-site/docs/manual/basic/analysis/pagination.zh.md
s2-site/examples/react-component/pagination/demo/pivot.tsx

🐛 Bugfix
1. 组件层增加 LocaleProvider 的适配, 在配置 S2 国际化的同时, 也对 antd 的组件生效
2. 透传 antd 分页组件 props
3. 补充 vue 组件的 emit 定义
| ![image](https://user-images.githubusercontent.com/21015895/185585590-3b4e7ab3-1191-4e3e-b8d1-38979a03d44d.png) | ![image](https://user-images.githubusercontent.com/21015895/185585450-a0360434-bfac-4f88-ac80-5d3b12af0206.png) |

fix(pagination): 透传组件分页参数 & 修复国际化不生效 close #1697

---

packages/s2-core/__tests__/spreadsheet/scroll-spec.ts
packages/s2-core/src/facet/base-facet.ts

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore
DP中s2会有数据比对场景，类似monaco的diffEditor，左右实例同步滚动，需要在被动滚动时防止scrollEvent的触发。
因此在facet.startsScroll添加了被动参数，如为true则不emit事件

chore: facet.startsScroll添加被动参数

---

packages/s2-core/__tests__/unit/cell/row-cell-spec.ts
packages/s2-core/src/cell/base-cell.ts

🐛 Bugfix
#1562 中修复了 link 无法对齐的问题，但未测试文字 `居中`、`居右` 的情况。
因为底层 g-base 计算文字 bbox 已经有误，所以使用它提供的 minX 作为 linkShape 的开始点并不正确
例如在居中的情况下，文字整体是在 bbox 的中间，左右两侧各有空隙。
使用 s2 自己计算的 textPosition 进行定位
|   ![CleanShot 2022-08-24 at 15 14 02](https://user-images.githubusercontent.com/6716092/186354806-40bcb309-feee-4940-bc08-0e2b360b2ad7.png)      |   ![CleanShot 2022-08-24 at 15 13 16](https://user-images.githubusercontent.com/6716092/186354640-85910bbc-01e8-4301-9669-4039c0f86e11.png)    |
|   ![CleanShot 2022-08-24 at 15 14 31](https://user-images.githubusercontent.com/6716092/186354886-692c111e-471a-4788-850c-b4a916804dd1.png)     |  ![CleanShot 2022-08-24 at 15 12 44](https://user-images.githubusercontent.com/6716092/186354544-5d8cae31-8eb9-41d4-945b-da8840d69725.pn …

fix: text居中居右时link绘制错位

---

packages/s2-core/src/common/interface/basic.ts
packages/s2-core/src/common/interface/interaction.ts
packages/s2-core/src/common/interface/s2Options.ts
packages/s2-react/__tests__/data/grid-analysis-data.ts
packages/s2-react/__tests__/data/strategy-data.ts
packages/s2-react/playground/config.ts
packages/s2-react/playground/index.tsx
packages/s2-react/playground/resize.tsx
packages/s2-react/src/components/header/index.tsx
packages/s2-react/src/components/sheets/interface.ts
packages/s2-react/src/components/sheets/pivot-sheet/index.tsx
packages/s2-react/src/components/switcher/header.tsx
packages/s2-react/src/hooks/useSpreadSheet.ts
packages/s2-react/src/utils/options.ts
packages/s2-shared/src/interface.ts
packages/s2-shared/src/utils/drill-down.ts
packages/s2-shared/src/utils/options.ts
packages/s2-vue/src/interface.ts

🎨 Enhance
在开启了严格模式的 ts 项目中使用 <SheetComponnet/>, S2Options 的第二次分页参数 (P) 默认值是 unknown, 会报错, 重构了一下相关类型
- 新增 `SheetComponentOptions`, 用于和 `S2Options` 做区分, 让 core 层 和 react/vue 层的类型提示更准确
> s2-core
```ts
type S2Options<T = Element | string, P = Pagination>
```
> s2-react
```ts
import {AntdPaginationProps} from 'antd'
export type SheetComponentOptions = S2Options<
ReactNode,
Pagination & AntdPaginationProps
>;
```
> s2-vue
```ts
import {PaginationProps} from 'antd-vue'
export type SheetComponentOptions = S2Options<
Element | string,
Pagination & PaginationProps
>;
```

fix(types): 修复严格模式下 S2Options 类型报错

---

packages/s2-core/__tests__/unit/interaction/event-controller-spec.ts
packages/s2-core/src/interaction/event-controller.ts
packages/s2-react/__tests__/data/grid-analysis-data.ts
packages/s2-react/__tests__/data/strategy-data.ts
packages/s2-react/playground/config.ts
packages/s2-react/playground/resize.tsx

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore
- fix: 修复不按类型引入，导致 `react:playground` 启动报错
- [fix: 修复tooltip 点击空白无法消失的问题](https://github.com/antvis/S2/commit/4a604fcd825cb3308eeef76ae6e6d002453e3c35)
|<img width="1735" alt="image" src="https://user-images.githubusercontent.com/20497176/188353335-cf291815-d470-492a-b3ec-05048003ee8f.png"> |<img width="1392" alt="image" src="https://user-images.githubusercontent.com/20497176/188353387-f6f3fb29-b8bc-49a3-a3f9-48da869be566.png">|
|![error-tooltip](https://user-images.githubusercontent.com/20497176/188353069-d7fc41d5-a96a-4ae0-b4b4-5da73999c9e1.gif)|![right-tooltip](https://user-images.githubusercontent.com/20497176/188353074-13bf548d-a178-4d5c-9e89-2a0427235013.gif)|

fix: 修复tooltip 点击空白无法消失的问题

---

packages/s2-core/__tests__/unit/sheet-type/pivot-sheet-spec.ts
packages/s2-core/__tests__/unit/sheet-type/table-sheet-spec.ts
packages/s2-react/__tests__/unit/hooks/useSpreadSheet-spec.ts
packages/s2-react/playground/index.tsx
packages/s2-react/src/hooks/useEvents.ts
packages/s2-react/src/hooks/useSpreadSheet.ts

🐛 Bugfix
修复 core 层 `s2.on(S2Event.LAYOUT_DESTROY)` 和 React 组件层 SheetComponent 的  `onDestroy` 都无法触发
背景:
组件 unmount 的时候会销毁表格 
https://github.com/antvis/S2/blob/3962178aae99c512315d9234e3e3d8bb9538ea36/packages/s2-react/src/hooks/useSpreadSheet.ts#L69-L75
然后会**同时销毁已注册**的事件
这就会导致 emit destroy 事件的时候, emitter 已经没有相应事件了, destroy 恰好比较特殊
https://github.com/antvis/S2/blob/3962178aae99c512315d9234e3e3d8bb9538ea36/packages/s2-core/src/sheet-type/spread-sheet.ts#L398-L401
解法:
在 off destroy 事件之前, 提前触发一次
| ![image](https://user-images.githubusercontent.com/21015895/188462833-427fdb57-e758-444c-b075-784d2b90cc06.png) | ![image](https://user-images.githubusercontent.com/21015895/188463052-600c048e-f35d-4503-8ae0-626c77125724.png) |
ref #1728

fix: 修复表格 onDestroy 卸载事件无法触发

---

packages/s2-core/src/utils/export/index.ts
packages/s2-react/__tests__/data/strategy-data.ts
packages/s2-react/__tests__/spreadsheet/strategy-sheet-spec.tsx
packages/s2-react/__tests__/unit/components/sheets/index-spec.tsx

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore
在趋势分析表多列头的情况下，如果某一个的数据为空，之前对这一列填充了一个空占位，但实际上应该按照列头的指标数量填充，否则就会出现数据偏移：
| ![image](https://user-images.githubusercontent.com/17964556/189080547-57fd789c-6a04-4093-84ac-f60fbf46aedf.png)      | ![image](https://user-images.githubusercontent.com/17964556/189080246-6a8fec73-b8a3-46ae-b0a5-a73ef3ae2e41.png)     |

fix: 修复趋势分析表多列头情况下，单元格数据为空引起的复制数据偏移问题

---

packages/s2-core/src/common/interface/theme.ts
packages/s2-core/src/theme/index.ts
packages/s2-core/src/utils/g-mini-charts.ts

🎨 Enhance
之前计算子弹图宽度时（使用 widthPercent 自定义占比），包含了 `文字`，`进度条` 宽度
而每行文字宽度不一，会导致进度条长度也不一致
现在改为 widthPercent 仅代表 `进度条` 宽度，文字使用 `总宽度` - `进度条` 的剩余空间
|   ![CleanShot 2022-09-15 at 19 51 47](https://user-images.githubusercontent.com/6716092/190396734-6176a1db-a51a-4317-a08d-5127768b8b02.png)    |   ![CleanShot 2022-09-15 at 19 51 11](https://user-images.githubusercontent.com/6716092/190396552-c02669f0-b7eb-4516-afe2-12b85a1b3378.png)     |

fix: 子弹图左侧文字未对齐

---

packages/s2-react/__tests__/unit/components/sheets/strategy-sheet/custom-tooltip/__snapshots__/index-spec.tsx.snap
packages/s2-react/__tests__/unit/components/sheets/strategy-sheet/custom-tooltip/index-spec.tsx
packages/s2-react/src/components/sheets/strategy-sheet/custom-tooltip/custom-data-tooltip.tsx
packages/s2-react/src/components/sheets/strategy-sheet/custom-tooltip/index.less
packages/s2-react/src/components/sheets/strategy-sheet/custom-tooltip/interface.ts
s2-site/docs/manual/basic/analysis/strategy.zh.md

✨ Feature
优化 https://github.com/antvis/S2/pull/1750 的方案, `<StrategySheetDataTooltip/>` 支持自定义衍生指标, 更灵活
```ts
<StrategySheetDataTooltip
cell={cell}
renderDerivedValue={(currentValue, originalValue) => (
<span>
{currentValue} ({originalValue})
</span>
)}
/>
```

feat(strategysheet): 支持自定义衍生指标

---

packages/s2-core/__tests__/unit/sheet-type/pivot-sheet-spec.ts
packages/s2-core/__tests__/unit/sheet-type/table-sheet-spec.ts
packages/s2-core/src/common/interface/store.ts
packages/s2-core/src/common/interface/tooltip.ts
packages/s2-core/src/sheet-type/pivot-sheet.ts
packages/s2-core/src/sheet-type/spread-sheet.ts
packages/s2-core/src/sheet-type/table-sheet.ts
packages/s2-react/__tests__/unit/components/tooltip/index-spec.tsx
packages/s2-react/__tests__/util/helpers.ts
packages/s2-react/src/components/tooltip/components/operator.tsx
packages/s2-react/src/components/tooltip/custom-tooltip.tsx
packages/s2-react/src/components/tooltip/index.tsx
packages/s2-shared/src/styles/tooltip/operator.less
s2-site/docs/api/basic-class/spreadsheet.zh.md
s2-site/docs/api/basic-class/store.zh.md
s2-site/docs/common/custom-tooltip.zh.md

🐛 Bugfix
目前的排序菜单是一次性操作, 不会**记住上一次选中状态** 即: 用 UI 得到当前这一次操作的 sortMethod 做排序
且 CustomTooltip 没有正确的更新 dom, 透视表和明细表, 以及业务层都有这个问题 即: 单元格1 选中了 [降序], 单元格2 还是高亮的 [降序], 因为 ui 没有更新
1. 增加 `defaultSelectedKeys` 透传给 antd menu 组件用于高亮
2. CustomTooltip 每次 render 前 `unmountComponentAtNode` 一次确保 UI 被更新
3. 增加一个 map 存储排序状态, 用于回填
4. 修复样式被覆盖, 导致排序菜单没有高亮颜色的问题
| ![Kapture 2022-09-09 at 11 45 51](https://user-images.githubusercontent.com/21015895/189331460-88f0b475-f3c5-4bef-b18e-5f9b29a26ee5.gif) | ![Kapture 2022-09-09 at 11 42 24](https://user-images.githubusercontent.com/21015895/189267278-b813f9c5-37dc-43f0-a324-c72d6d24e30d.gif)
| ![Kapture 2022-09-09 at 11 46 59](https://user-images.githubusercontent.com/21015895/189267675-0e386947-a7fb-4a5c-83b1-08fa0e084472.gif)| …

fix(sort): 修复 tooltip 中排序菜单未记住上一次选中状态 close #1716

---

packages/s2-core/__tests__/bugs/issue-1764-spec.ts
packages/s2-core/__tests__/spreadsheet/scroll-spec.ts
packages/s2-core/src/facet/base-facet.ts
packages/s2-core/src/ui/scrollbar/index.ts

🐛 Bugfix
1. 修复 点击横/纵向滚动条的滑道时, 表格渲染空白 (透视表/明细表都有问题)
2. 修复 行头有滚动条, 数值区域无滚动条, 在数值区域滚动时报错
| ![Kapture 2022-09-27 at 11 20 52](https://user-images.githubusercontent.com/21015895/192424331-37bea8b0-2824-4894-b2e8-8638a8a8c177.gif) | ![Kapture 2022-09-27 at 11 19 27](https://user-images.githubusercontent.com/21015895/192424186-70011c2c-dd36-49be-aa9f-ec7e751735f9.gif) |
close #1784 #1780 #1764

fix(scroll): 修复点击滚动条滑道区域表格渲染空白 close #1764 #1780

---

packages/s2-core/__tests__/spreadsheet/spread-sheet-totals-spec.ts
packages/s2-core/__tests__/unit/cell/data-cell-spec.ts
packages/s2-core/__tests__/unit/facet/pivot-facet-spec.ts
packages/s2-core/src/cell/data-cell.ts

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore
之前，在树状结构下，行头天然存在小计的格子，如果此时用户刚好传入了小计的数据，不过此时`totals.row.showSubtotals`是否开启，都会将其展示出来。
现在让行小计的格子数据展示也符合小计配置规则。
| ![image](https://user-images.githubusercontent.com/17964556/192933184-6bd590a1-d6f2-4b93-8f72-7e3f461c33f3.png)      | ![image](https://user-images.githubusercontent.com/17964556/192933159-459b95f3-1429-4308-ba41-1e1e738a66c9.png)     |

feat: 树状结构下, 行小计数据显示配置规则

---

packages/s2-core/src/utils/export/copy.ts

🐛 Bugfix
带行头cell复制时 rowcell对应的colIndex为0且取不到对应formatter，需要过滤
🔧 Chore

fix: 带行头复制报错修复

---

.releaserc.base.js

🔧 Chore
`@semantic-release` 默认只有三个前缀, 增加两个常用的, 避免被跳过
https://github.com/semantic-release/commit-analyzer/blob/16ea4561f48811f143bbb1cbb352f6431e94bc7f/lib/default-release-rules.js#L10-L12

chore: 自动发布 commit 触发条件 增加 refactor 和 style

---

packages/s2-core/__tests__/unit/sheet-type/pivot-sheet-spec.ts
packages/s2-core/__tests__/unit/sheet-type/table-sheet-spec.ts
packages/s2-core/src/common/interface/tooltip.ts
packages/s2-core/src/sheet-type/pivot-sheet.ts
packages/s2-core/src/sheet-type/table-sheet.ts
packages/s2-react/__tests__/spreadsheet/tooltip-spec.tsx
packages/s2-react/src/components/tooltip/custom-tooltip.tsx
s2-site/docs/common/custom-tooltip.zh.md

🐛 Bugfix
内部修改为分场景, 而不是始终销毁组件, 避免外部调用 `s2.showTooltip()` 时, tooltip 反复渲染
> 测试代码
```ts
s2.showTooltip({
position: {
x: event.clientX,
y: event.clientY,
},
content: (
<img
src="https://gw.alipayobjects.com/zos/antfincdn/xv%2685cV97/2022-09-15%25252022.43.09.gif"
width={200}
/>
),
});
```
> 注意观察 img 标签
| ![Kapture 2022-10-13 at 11 11 44](https://user-images.githubusercontent.com/21015895/195490515-65d60060-d025-4862-97b1-aaf844d211fb.gif) |

fix(tooltip): tooltip 显示时不应该强制清空 dom

---

packages/s2-core/__tests__/bugs/issue-1624-spec.ts
packages/s2-core/src/cell/data-cell.ts

🐛 Bugfix
#1802 改动中，误改变了 data-cell 中 shape 的绘制顺序，导致 interactiveBorderShape 在 text 之后被加入到画板。
即 text 被遮挡，导致无法交互（开启 linkField 时无能点击和 hover）
|   ![CleanShot 2022-10-14 at 14 05 16](https://user-images.githubusercontent.com/6716092/195774038-7967f023-2133-40ce-90a7-584483e5d07b.gif)  |   ![CleanShot 2022-10-14 at 14 03 58](https://user-images.githubusercontent.com/6716092/195773867-ac1b9a34-fc6f-400b-b92c-cf9f97389560.gif)    |

fix: data-cell文字无法交互

---

packages/s2-core/__tests__/unit/utils/layout/generate-id.spec.ts
packages/s2-core/src/common/constant/basic.ts
packages/s2-core/src/utils/layout/generate-id.ts
packages/s2-core/src/utils/layout/index.ts

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore
在生成 id 时，对`undefined`, `null`做区分，并抛出`resolveId`方法，方便外部产品对id进行解析，可以处理内部平台产品中趋势图id对`null`和`'null'`混淆的问题

feat: 在生成 id 时，对 undefined, null 做区分

---

packages/s2-react/__tests__/bugs/issue-1736-spec.tsx
packages/s2-react/src/components/export/index.tsx
s2-site/docs/api/components/export.zh.md

✨ Feature
```diff
export interface ExportCfgProps {
open: boolean;
className?: string;
icon?: React.ReactNode;
copyOriginalText?: string;
copyFormatText?: string;
downloadOriginalText?: string;
downloadFormatText?: string;
successText?: string;
errorText?: string;
fileName?: string;
syncCopy?: boolean;
+ // ref: https://ant.design/components/dropdown-cn/#API
+ dropdown?: DropDownProps;
}
```
🐛 Bugfix
react SheetComponent 导出界面异常🐛 #1736

fix: 修复open属性冲突的问题 close #1736

---

packages/s2-core/__tests__/unit/facet/layout/col-node-width-spec.ts
packages/s2-core/src/facet/pivot-facet.ts

🐛 Bugfix
紧凑模式下，计算列头根节点时，未考虑 formatter 情况，导致宽度计算错误
如数据为：`123456789`，meta.formatter 后为 `123百万`
但估算时，还是使用的 `123456789`，而非后者，导致单元格宽度过宽
> 下图中，原始值 ratio 为 `3.321312312312`，formatter 为保留两位小数
|    ![CleanShot 2022-10-19 at 18 07 23@2x](https://user-images.githubusercontent.com/6716092/196662395-a4446afb-8512-4439-8bea-ab34078cccda.png)    |   ![CleanShot 2022-10-19 at 18 05 28@2x](https://user-images.githubusercontent.com/6716092/196662026-39542bb6-0fca-4f61-9bfd-7418927a5750.png)     |

fix: 紧凑模式下节点宽度计算错误

---

packages/s2-core/__tests__/unit/facet/layout/col-node-width-spec.ts
packages/s2-core/src/facet/pivot-facet.ts

🐛 Bugfix
🔧 Chore
自适应模式下，未考虑开启 `序号列` 的情况，始终使用了 canvas 总宽度作为总可用宽度计算。
实际应该使用 `canvas 宽度` 减去 `序号列宽度`，余下的空间用于所有节点均分。
|   ![CleanShot 2022-10-20 at 18 17 22](https://user-images.githubusercontent.com/6716092/196922648-83d1b593-b7e4-4e94-a345-bc4f22b31bc8.gif)      |   <img width="1008" alt="CleanShot 2022-10-20 at 18 17 55@2x" src="https://user-images.githubusercontent.com/6716092/196922794-649b269d-e0ae-467b-ba40-6422b4985c84.png"> |

fix: 自适应模式节点宽度计算错误

---

packages/s2-react/__tests__/unit/components/sheets/index-spec.tsx
packages/s2-react/playground/index.tsx
packages/s2-react/src/components/sheets/base-sheet/index.tsx
packages/s2-react/src/components/sheets/index.tsx

🐛 Bugfix
在 https://github.com/antvis/S2/pull/1830 修改后, 漏掉了 `base-sheet/index.tsx` 中的映射, 导致没使用 `getSpreadSheet` 控制台也会有 warning, 现修正, 并增加单测覆盖
packages/s2-react/src/components/sheets/base-sheet/index.tsx
ref: https://github.com/antvis/S2/pull/1830

fix: 修复 SheetComponent 未使用 getSpreadSheet 也会报 warning 的问题

---

packages/s2-core/__tests__/spreadsheet/scroll-spec.ts
packages/s2-core/__tests__/spreadsheet/spread-sheet-tree-mode-spec.ts
packages/s2-core/__tests__/spreadsheet/theme-spec.ts
packages/s2-core/__tests__/unit/facet/layout/col-node-width-spec.ts
packages/s2-core/src/theme/index.ts

🐛 Bugfix
据 [font-weight 定义](https://developer.mozilla.org/en-US/docs/Web/CSS/font-weight) ，`bold` 应对应 `700` 数字字重。
之前的 500 在 MacOS Chrome 下有粗体效果，但在 Safari 下没有。
|    ![CleanShot 2022-10-21 at 14 58 34@2x](https://user-images.githubusercontent.com/6716092/197132767-ce39e13f-2835-4324-b672-3bb53a9a5d27.png)    |   ![CleanShot 2022-10-21 at 14 56 09@2x](https://user-images.githubusercontent.com/6716092/197132385-3303e97c-0417-4fea-8c03-3f3793f2b922.png)     |
|  ![CleanShot 2022-10-21 at 14 58 10@2x](https://user-images.githubusercontent.com/6716092/197132708-b20d26fd-bc90-4ca2-ad84-ae6cc4d7c100.png) |  ![CleanShot 2022-10-21 at 14 56 49@2x](https://user-images.githubusercontent.com/6716092/197132468-a4062b90-adc9-47c6-8cfc-2245d31cba29.png) |

fix: bold字体对应数字字重不正确

---

packages/s2-core/__tests__/unit/utils/color-spec.ts
packages/s2-core/src/utils/color.ts

🐛 Bugfix
增加 `generateStandardColors` 的容错, 避免 `brandColor` 为空时 `toUpperCase` 报错

fix(theme): 获取标准色时增加容错和兜底

---

packages/s2-core/__tests__/unit/cell/data-cell-spec.ts
packages/s2-core/src/cell/data-cell.ts
packages/s2-core/src/common/constant/condition.ts
packages/s2-core/src/common/interface/condition.ts
packages/s2-core/src/utils/color.ts
s2-site/docs/common/conditions.zh.md
s2-site/docs/manual/basic/conditions.zh.md
s2-site/examples/analysis/conditions/demo/intelligent-background.ts
s2-site/examples/analysis/conditions/demo/meta.json

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore
通过显示指定 `background` 字段标记中的 `mapping` 函数返回值  `intelligentReverseTextColor` 属性值为 `true`。
当标记背景颜色较暗时，文本颜色将变为白色。当标记背景颜色明亮时，文本颜色默认为黑色。
优先级： `background condition` 的 `intelligentReverseTextColor` < `text condition` 的 `fill`
| <img width="567" alt="image" src="https://user-images.githubusercontent.com/20497176/197137662-ba48220b-35a3-441b-85c7-39f0b9abd79f.png"> |<img width="568" alt="image" src="https://user-images.githubusercontent.com/20497176/197137550-e9f0f543-23aa-42c7-968a-dda5913babff.png"> |

feat: 在背景字段标记中添加 文本智能反色

---

packages/s2-core/package.json
packages/s2-core/src/facet/base-facet.ts
packages/s2-core/src/facet/header/col.ts
packages/s2-core/src/facet/header/corner.ts
packages/s2-core/src/facet/header/row.ts
packages/s2-core/src/facet/header/series-number.ts
packages/s2-core/src/facet/table-facet.ts
yarn.lock

🐛 Bugfix
g更新见：https://github.com/antvis/G/releases/tag/%40antv%2Fg%405.12.1
测试范围包括
* 透视表
* 行头冻结/不冻结
* 有序号/无序号
* 行高列宽调整
* 明细表
TODO：
* 行列冻结明细表暂未测试
| ❌ ![image](https://user-images.githubusercontent.com/10885578/197989873-175f1849-693c-4a4e-bc86-19aec93d9d19.png) | ✅ ![image](https://user-images.githubusercontent.com/10885578/197989656-4d5881c7-2c30-4600-8f7b-1e52a7699c56.png)|

fix: 修复新版g5.0clipPath计算规则改变导致的裁剪错位问题

---

packages/s2-core/__tests__/spreadsheet/spread-sheet-spec.ts
packages/s2-core/src/sheet-type/spread-sheet.ts
packages/s2-core/src/utils/merge.ts
s2-site/docs/api/basic-class/base-data-set.zh.md
s2-site/docs/api/basic-class/spreadsheet.zh.md
s2-site/docs/manual/faq.zh.md

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore
现在 setDataCfg 和  setOptions 都只有更新配置的功能，现在很多用户需要直接重置掉之前的配置，传入全新的配置。

feat : 给 setDataCfg 和 setOptions 添加重置字段

---

packages/s2-core/__tests__/unit/utils/number-calculate-spec.ts
packages/s2-core/src/utils/number-calculate.ts

当数值中存在如 '2022-10-31' 或者 '1\n2\n3\n' 这种非数字字符串时， `isNotNumber` 判断错误
✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore

当数值存在非数字时页面白屏问题

---

packages/s2-core/__tests__/spreadsheet/spread-sheet-spec.ts
packages/s2-core/src/sheet-type/spread-sheet.ts
s2-site/docs/api/basic-class/spreadsheet.zh.md

✨ Feature
https://developer.mozilla.org/zh-CN/docs/Web/API/TextMetrics
1. 实例增加 `measureTextHeight`
2. 原有 `measureTextWidth` 拆分成 `measureText` 和 `measureTextWidth` 方法
3. 补充缺失文档

feat: 新增 measureTextHeight 用于测量文字高度

---

packages/s2-core/__tests__/spreadsheet/sort-by-order-spec.ts
packages/s2-core/src/data-set/pivot-data-set.ts

在手动排序，调用`getDimensionValues`时，对`sortedDimensionValues`采用的是`includes`而不是`startsWith`，会导致过滤的信息和预期不符合，比如想获取**小程序访问**的所有子维度用于排序：
最终导致排序不正确
| ![image](https://user-images.githubusercontent.com/17964556/201853991-99b918be-74a1-4d6b-8ab2-e5ca1c846486.png)      | ![image](https://user-images.githubusercontent.com/17964556/201854021-667760f4-2123-43e9-bcc4-e7e6093564cd.png)     |

fix: 修复sortedDimensionValues过滤不正确而导致的排序错乱的问题

---

packages/s2-core/__tests__/unit/facet/pivot-facet-spec.ts
packages/s2-core/src/facet/header/corner.ts

🐛 Bugfix
角头中，序号列对应的 cell.meta 没有 spreadsheet 实例变量

fix: 角头序号单元格meta无spreadsheet实例

---

packages/s2-core/__tests__/spreadsheet/table-sheet-spec.ts
packages/s2-core/src/facet/table-facet.ts

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore
layoutCoordinate这个layout hook函数需要在 
```
colsHierarchy.width += currentNode.width;
```
之前执行。
如果之后执行的话，就会导致node的width和实际layout的width不对等。。
|   ![image](https://user-images.githubusercontent.com/16497201/204224783-c1e159d2-5805-41df-b1fd-6f6456473b1e.png) | ![image](https://user-images.githubusercontent.com/16497201/204224696-cb218907-aa09-4542-8d32-54a78c0a6d20.png)   |

fix(facet): 调整 layoutCoordinate 执行顺序

---

package.json
scripts/latest-bump-version.js
scripts/util.js
scripts/validate-deps.js

✨ Feature
在 latest 分支进行部署时，为了创建`chore(release)`的触发 commit，需要我们在 `package.json` 里面做版本修改，而版本号的修改最终会被工具覆盖点，其实没有意义，现在直接通过脚本创建空的 commit。
在 latest 发布步骤：
1. 合并 master
2. 执行 `yarn release:bump-latest`
3. 推送代码
> 提供分支检测，脚本只在 latest 生效，其他预览版分支照旧

chore: 添加 latest 分支生成 release commit 脚本

---

packages/s2-core/__tests__/unit/utils/export/copy-spec.ts
packages/s2-core/src/utils/export/copy.ts

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore
兼容 hideMeasureColumn 方案：hideMeasureColumn 的隐藏实现是通过截取掉度量(measure)数据，但是又只截取了 Node 中的，像 pivotMeta 中的又是完整的。导致复制时，无法通过 Node 找出正确路径。
所以，被 hideMeasureColumn 隐藏的 度量(measure) 值，手动添加上。
|![Dec-08-2022 16-30-45](https://user-images.githubusercontent.com/20497176/206398070-d82e7591-982f-4cc7-8eca-f10cd38b5c4a.gif) |![复制-隐藏-正常展示](https://user-images.githubusercontent.com/20497176/206398099-ee1af72f-ae3e-47d7-baaa-f656b28b8cd8.gif)|

fix: 修复 enableCopy 和 hideMeasureColumn 都开启为 true 时，复制报错问题

---

packages/s2-core/__tests__/unit/utils/export/copy-spec.ts
packages/s2-core/src/utils/export/copy.ts

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore
feat: 实现树状模式下可复制
[fix: 修复存在空数据时复制错误的问题](https://github.com/antvis/S2/commit/d1068fbd0725f73b22b6185e66a0a88b5011521a)
| ![树状模式下无法复制](https://user-images.githubusercontent.com/20497176/206612306-327d20d2-adb6-4ed0-8ac6-393895344c29.gif) | ![树状模式下可复制](https://user-images.githubusercontent.com/20497176/206612323-35afd21c-c029-4e9a-97b1-f39a00ea0561.gif) | 
|  <img width="1224" alt="image" src="https://user-images.githubusercontent.com/20497176/206612725-6ff40631-8f58-41d8-bd5a-d9370c76fe3c.png"> |<img width="1234" alt="image" src="https://user-images.githubusercontent.com/20497176/206612707-64e4f198-b097-40e7-92ce-9550e86d2962.png"> |

feat: 实现树状模式下可复制

---

packages/s2-core/__tests__/spreadsheet/row-link-spec.ts
packages/s2-core/__tests__/unit/interaction/base-interaction/click/data-cell-click-spec.ts
packages/s2-core/src/cell/row-cell.ts
packages/s2-core/src/common/interface/emitter.ts
packages/s2-core/src/interaction/base-interaction/click/data-cell-click.ts
packages/s2-core/src/interaction/base-interaction/click/row-text-click.ts
s2-site/docs/api/components/sheet-component.zh.md

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore

feat: 适配链接跳转的判断方式

---

packages/s2-core/__tests__/unit/facet/layout/col-node-width-spec.ts
packages/s2-core/__tests__/unit/facet/table-facet-spec.ts
packages/s2-core/src/facet/table-facet.ts

🐛 Bugfix
紧凑模式 `layoutWidthType=compact` 下计算列宽度时，没有使用格式化后的数据
导致计算结果与实际渲染不一致
如原始数据为 `1.23456`，但 formatter 后为 `1.2`
应使用 `1.2` 来 measureWidth
- `成本` 列，原始数据 `1.23456789`，formatter 截取两位
|   <img width="356" alt="CleanShot 2022-12-19 at 11 31 48@2x" src="https://user-images.githubusercontent.com/6716092/208342147-2cdd6dc5-6c64-42f4-87ae-343b8d86821a.png">      |    <img width="306" alt="CleanShot 2022-12-19 at 11 32 23@2x" src="https://user-images.githubusercontent.com/6716092/208342199-79c44313-4345-456a-9360-6253a96ba26c.png">   |

fix: 明细表紧凑模式宽度计算错误

---

packages/s2-core/__tests__/spreadsheet/table-sheet-spec.ts
packages/s2-core/src/utils/interaction/link-field.ts

🐛 Bugfix
#1992 误引入的问题，导致明细表的 linkField 判断失效

fix: 明细表linkField失效

---

packages/s2-core/src/utils/g-mini-charts.ts

🐛 Bugfix
垂直方向绘制起点始终是 0， 导致绘制错误，实际应取 cell.y
|  ![CleanShot 2022-12-26 at 14 55 43@2x](https://user-images.githubusercontent.com/6716092/209514683-4c357c5f-b1a5-4d62-a8d8-2c0decf56d6b.png)      |    ![CleanShot 2022-12-26 at 14 56 17@2x](https://user-images.githubusercontent.com/6716092/209514738-7aad5016-876f-46b6-b1a9-de8342e7c443.png)    |

fix: bullet占位符绘制错误

---

packages/s2-core/__tests__/unit/cell/data-cell-spec.ts
packages/s2-core/src/cell/data-cell.ts
packages/s2-core/src/cell/header-cell.ts
packages/s2-core/src/utils/cell/data-cell.ts
s2-site/docs/common/interaction.zh.md
s2-site/docs/manual/advanced/interaction/basic.zh.md

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore
合并了外部用户提的PR后，导致了一些问题，此PR 修复发现的问题。
|![行列头高亮失效](https://user-images.githubusercontent.com/20497176/209933369-ba5c96da-0903-4526-a7fa-7b1b440e58fc.gif) | ![Large GIF (764x526)](https://user-images.githubusercontent.com/20497176/209933450-b0119446-d25f-4b93-b3e3-f04347e841cb.gif) |
issue link

fix : 修复点击行列头无法整行高亮的问题

---

packages/s2-core/CHANGELOG.md
packages/s2-core/package.json
packages/s2-react/CHANGELOG.md
packages/s2-react/package.json

🤖 由 [[🚀 After the release is successful](https://github.com/antvis/S2/blob/master/.github/workflows/release-success.yml)] action 自动创建.

chore: 🤖 更新 changelog 文件

---

packages/s2-core/__tests__/unit/utils/tooltip-spec.ts
packages/s2-core/src/common/interface/tooltip.ts
packages/s2-core/src/utils/tooltip.ts
packages/s2-react/src/components/tooltip/components/summary.tsx

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore
1. 添加原始数据的返回
2. 当 name 为空时，不显示总和。
|  <img width="1448" alt="image" src="https://user-images.githubusercontent.com/20497176/211767298-589c377c-0bd2-4e88-a644-09d09c4f6d4a.png"> | <img width="1237" alt="image" src="https://user-images.githubusercontent.com/20497176/211767182-19e8cce3-c458-4408-bedb-127dc2968005.png"> |

feat: tooltip summaries 返回原始数据

---

packages/s2-core/__tests__/bugs/issue-1715-spec.ts
packages/s2-core/src/facet/pivot-facet.ts
packages/s2-react/__tests__/data/mock-dataset.json
packages/s2-react/playground/config.ts

🐛 Bugfix
| ![image](https://user-images.githubusercontent.com/21015895/212289645-991b3bdd-3f2f-4be5-8336-3730cf0ac09f.png) | ![image](https://user-images.githubusercontent.com/21015895/212289558-3df5577d-b01b-4b6a-93b1-b0c8ff9c6dfa.png) |
close #1715 
close #2049

fix(layout): 修复存在多列头多数值且数值置于行头时,列总计单元格高度不对 close #1715 #2049

---

packages/s2-core/__tests__/spreadsheet/row-link-spec.ts
packages/s2-core/__tests__/spreadsheet/table-sheet-spec.ts
packages/s2-core/__tests__/unit/cell/data-cell-spec.ts
packages/s2-core/__tests__/unit/interaction/row-column-resize-spec.ts
packages/s2-core/src/cell/base-cell.ts
packages/s2-core/src/cell/corner-cell.ts
packages/s2-core/src/cell/merged-cell.ts
packages/s2-core/src/cell/row-cell.ts
packages/s2-core/src/common/interface/emitter.ts
packages/s2-core/src/engine/CustomText.ts
packages/s2-core/src/facet/base-facet.ts
packages/s2-core/src/facet/header/base.ts
packages/s2-core/src/facet/header/frame.ts
packages/s2-core/src/facet/table-facet.ts
packages/s2-core/src/facet/utils.ts
packages/s2-core/src/interaction/base-interaction/click/data-cell-click.ts
packages/s2-core/src/interaction/event-controller.ts
packages/s2-core/src/interaction/root.ts
packages/s2-core/src/interaction/row-column-resize.ts
packages/s2-core/src/sheet-type/spread-sheet.ts
packages/s2-core/src/ui/scrollbar/index.ts
packages/s2-core/src/utils/g-mini-charts.ts
packages/s2-core/src/utils/g-renders.ts
packages/s2-core/src/utils/interaction/common.ts
packages/s2-core/src/utils/text.ts

🎨 Enhance
主要解决迁移 g5.0 后的 todo 项目
- 清除过时的 todo
- 固定 `base-cell` 图形的类型
- 对含有 appendInfo 的 text 迁移到自定义类 `CustomText`（类似 CustomRect，不再使用 `.attr()` 语法）
- 整理 resize 事件，统一使用 PointerEvent

refactor: 移除 g5.0 todo 项

---

packages/s2-core/__tests__/spreadsheet/table-sheet-spec.ts
packages/s2-core/__tests__/unit/interaction/base-interaction/click/data-cell-click-spec.ts
packages/s2-core/__tests__/unit/utils/export/copy-spec.ts
packages/s2-core/src/interaction/base-interaction/click/data-cell-click.ts
packages/s2-core/src/interaction/brush-selection/data-cell-brush-selection.ts
packages/s2-core/src/interaction/data-cell-multi-selection.ts
packages/s2-core/src/utils/export/copy.ts

✨ Feature
🎨 Enhance
🐛 Bugfix
fix: 选择datacell不连带选中column cell（会导致选中单个单元格copy时copy整列）
fix: 复制带双引号不再改变原始值
fix: 复制不规则单元格不再报错
🔧 Chore

复制相关bugfix

---

.github/workflows/pr-auto-assign-reviewer.yml
packages/s2-core/__tests__/bugs/issue-720-spec.ts
packages/s2-core/__tests__/spreadsheet/interaction-brush-selection-scroll-spec.ts
packages/s2-core/__tests__/spreadsheet/scroll-spec.ts
packages/s2-core/__tests__/spreadsheet/spread-sheet-spec.ts
packages/s2-core/__tests__/spreadsheet/table-sheet-spec.ts
packages/s2-core/__tests__/unit/interaction/brush-selection/base-brush-selection-spec.ts
packages/s2-core/__tests__/unit/interaction/brush-selection/row-brush-selection-spec.ts
packages/s2-core/src/cell/row-cell.ts
packages/s2-core/src/common/interface/basic.ts
packages/s2-core/src/common/interface/scroll.ts
packages/s2-core/src/common/interface/store.ts
packages/s2-core/src/facet/base-facet.ts
packages/s2-core/src/facet/header/base.ts
packages/s2-core/src/interaction/brush-selection/base-brush-selection.ts
packages/s2-core/src/interaction/brush-selection/col-brush-selection.ts
packages/s2-core/src/interaction/brush-selection/data-cell-brush-selection.ts
packages/s2-core/src/interaction/brush-selection/row-brush-selection.ts
packages/s2-core/src/sheet-type/spread-sheet.ts
packages/s2-core/src/utils/facet.ts
packages/s2-core/src/utils/interaction/select-event.ts
packages/s2-react/playground/config.ts
packages/s2-react/playground/index.tsx
s2-site/docs/api/basic-class/base-facet.en.md
s2-site/docs/api/basic-class/base-facet.zh.md
s2-site/docs/api/basic-class/spreadsheet.zh.md
s2-site/docs/api/basic-class/store.en.md
s2-site/docs/api/basic-class/store.zh.md
s2-site/docs/manual/advanced/interaction/basic.zh.md
s2-site/examples/interaction/advanced/demo/scroll-to-cell.ts

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore
- 行头增加刷选时自动滚动, 支持 **水平滚动** 和 **垂直滚动**, 可以用于统计单元格个数, 复制
- 增加行头区域的滚动方法, 原本 `updateScrollOffset` 只支持数值区域的滚动 (即 `offsetX` 和 `offsetY`), 现在行头滚动需要增强其能力, `rowHeaderOffsetX`
```ts
s2.updateScrollOffset({
rowHeaderOffsetX: {
value: 50,
animate: true,
},
});
```
TODO:
| ![Kapture 2023-02-21 at 17 14 42](https://user-images.githubusercontent.com/21015895/220302089-f5db8cc9-5c24-4e32-a350-3f1c1b88ef68.gif) | ![Kapture 2023-02-21 at 17 12 17](https://user-images.githubusercontent.com/21015895/220300656-daf50950-358a-40c7-9748-72c8555504f0.gif) |
close #2075

feat(interaction): 行头支持滚动刷选

---

packages/s2-core/src/sheet-type/spread-sheet.ts

🎨 Enhance
g5的supportCSSTransform改名为supportsCSSTransform了，S2同步做修改

fix: 重命名supportCSSTransform为supportsCSSTransform

---

packages/s2-core/src/utils/g-renders.ts
packages/s2-core/src/utils/text.ts

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore
对于趋势分析表，当文本超过省略后，无法获取原始数据。
通过 viewMeta：{ value: "[\"数值\",\"环比环比环比环比环比环比环比环比环比环比环比环比环比\"]" }
会 存在一个问题： value: "[\"cutomizedelta\",\"cutomizeContrast ratio\",\"cutomizeComparison value\"]" 时， 都展示为 cutomize... ，所以添加了 originText 字段
| <img width="1470" alt="image" src="https://user-images.githubusercontent.com/20497176/223372864-ae993c57-e7d9-4faa-9f95-e6d264eafee5.png">|<img width="1423" alt="image" src="https://user-images.githubusercontent.com/20497176/223372249-706b5e6b-9d4a-4a95-b3ae-09bf00ed13d2.png"> |

feat: 在 shape 中添加文本的原始值

---

packages/s2-core/__tests__/bugs/issue-2164-spec.ts
packages/s2-core/src/facet/pivot-facet.ts

🐛 Bugfix
多个数值放行头时，总计节点没有调整节点宽度。
|   <img width="293" alt="CleanShot 2023-04-17 at 12 15 47@2x" src="https://user-images.githubusercontent.com/6716092/232376562-de9ebf8b-aea0-45ce-8704-7096f821c0c2.png">     |  <img width="299" alt="CleanShot 2023-04-17 at 12 15 23@2x" src="https://user-images.githubusercontent.com/6716092/232376527-5450e6c8-aeb7-4178-90ba-7ec41e5e407b.png">    |

fix: 多指标行头总计节点宽度计算错误

---

packages/s2-core/__tests__/bugs/issue-2140-spec.ts
packages/s2-core/src/facet/base-facet.ts

🐛 Bugfix
行头过宽时（通过拖拽，或者 style 配置），滚动条会渲染的比整个 canvas 宽。
导致无法滚动到头，即 panel 会有部分遮挡，渲染不全。
配置
- canvas 设置 400 宽度
- province、city 各配置 300 宽度
|  ![CleanShot 2023-04-23 at 17 08 46](https://user-images.githubusercontent.com/6716092/233830559-7ac5215b-8667-4d94-9942-599a105e7888.gif)    |  ![CleanShot 2023-04-23 at 17 07 37](https://user-images.githubusercontent.com/6716092/233830505-75ba9945-afa6-4e01-952e-83af618a3ae5.gif)     |

fix: 行头过宽且不冻结时滚动条渲染错误

---

packages/s2-core/__tests__/unit/interaction/event-controller-spec.ts
packages/s2-core/__tests__/util/helpers.ts
packages/s2-core/src/interaction/event-controller.ts

🐛 Bugfix
`canvas mouse out` 时应该清除交互样式，现在没有清除，原因是在 g5.0 的迁移中，判断条件替换错了。
```diff
private onCanvasMouseout = (event: CanvasEvent) => {
-    if (!this.isAutoResetSheetStyle || event?.shape) {
+    if (!this.isAutoResetSheetStyle || event?.target instanceof DisplayObject) {
```
以前 canvas 内部有事件触发时
- 如果由图形触发事件，则 event.shape 指向该图形
- 如果在 cavas 内，但没 hit 任何图形，则 event.shape 为 null
需要注意的是，上面的事件中 event.target 都是 HTMLCanvas 对象
在 g5.0 中，所有画布、图形、事件都被抽象了
- event.target 指向的图形都是 DisplayObject 对象
|  ![CleanShot 2023-04-27 at 09 29 03](https://user-images.githubusercontent.com/6716092/234736750-cf42d23d-d8d9-41eb-86ea-798cf0ae736c.gif)     |  ![CleanShot 2023-04-27 at 09 27 04](https://user-images.githubusercontent.com/6716092/234736453-76361571-0659-4d8a-ab90-67ba34a13591.g …

fix: canvas mouseout 判断错误

---

packages/s2-core/__tests__/unit/interaction/base-interaction/click/row-column-click-spec.ts
packages/s2-core/__tests__/unit/interaction/data-cell-multi-selection-spec.ts
packages/s2-core/__tests__/unit/interaction/range-selection-spec.ts
packages/s2-core/src/interaction/base-interaction/click/row-column-click.ts
packages/s2-core/src/interaction/data-cell-multi-selection.ts
packages/s2-core/src/interaction/range-selection.ts
packages/s2-core/src/utils/interaction/select-event.ts

🐛 Bugfix
以 `range-selection` 为例，该交互通过监听 `shift` 的 keyup/keydown 事件，来置标志位。
当 shift 按下，标志位置为 true，用户可以进行多选。
但如果不松 shfit，继续按下 shift+cmd+4 组合进行截图，之后即使松开组合键，也无法获取到 keydown 事件，进而导致多选交互异常。
类似的问题还存在于 `行列头多个点选`、`单元格多个点选`，都是类似的 pattern。
监听 mouseMove 事件，查看对应的修饰键是否还在被按压，补充调用 reset 一下状态。
为什么还要保留 keydown 的 reset？因为用户可能不移动鼠标，直接点选单元格。
> 以 dataCell cmd 点选多选为例
|  ![CleanShot 2023-05-06 at 16 30 16](https://user-images.githubusercontent.com/6716092/236612982-5b57d8a3-88f5-465b-b0d7-ea0d9679c8a5.gif)     |   ![CleanShot 2023-05-06 at 16 29 03](https://user-images.githubusercontent.com/6716092/236612886-4a37ea77-77a5-4311-a999-f621c2ae505e.gif)    |

fix: 系统拦截快捷键后多选交互异常

---

packages/s2-core/__tests__/bugs/issue-1624-spec.ts
packages/s2-core/__tests__/unit/cell/header-cell-spec.ts
packages/s2-core/src/cell/data-cell.ts
packages/s2-core/src/cell/header-cell.ts

✨ Feature
🎨 Enhance
🐛 Bugfix
修复上一个PR没考虑到的树状结构的问题：https://github.com/antvis/S2/pull/2209/
🔧 Chore

fix: 修复树状模式下，总计小计格式化问题

---

packages/s2-core/src/utils/export/copy.ts

🐛 Bugfix
use actualText replace value label in copy
只有指标维度在复制的时候有问题，用实际文本替换指标维度的标签

fix: use actualText replace value label in copy

---

packages/s2-core/__tests__/spreadsheet/table-sheet-spec.ts
packages/s2-core/__tests__/unit/interaction/row-column-resize-spec.ts
packages/s2-core/src/common/interface/resize.ts
packages/s2-core/src/interaction/row-column-resize.ts

🐛 Bugfix
当 Sheet 周围存在其它元素时，因为原本的计算方式使用 `offsetX` 来计算，当鼠标移到其它元素上时，`offsetX` 又重新从 0 开始累增，其实这的意思是 Sheet 的 `offsetX` 和鼠标 Target 的 `offsetX` 已经不是同一个元素了，需要更改为适应性更强的 `clientX` 来计算
保留原本的属性和类型，防止造成 break change
|![Screen Recording 2023-06-28 at 23 26 56](https://github.com/antvis/S2/assets/56076317/7d7e20d8-7eaa-47fe-9a2f-68fdc8e21006)|![Screen Recording 2023-06-28 at 23 25 09](https://github.com/antvis/S2/assets/56076317/eb5010ea-6fd0-4038-9c17-b9f23074f96a)|

fix(core): 使用客户端的位置来计算调整大小的偏移量

---

packages/s2-core/src/interaction/range-selection.ts

🐛 Bugfix
🔧 Chore
背景请看 #2260 
在点击列头的时候会触发两次 GLOBAL_SELECTED，一次是正常的，另一次是 range-selection 的，range-selection 目前无论如何都会添加一个 hover 的拦截器，需要在不是 range-selection 的情况下把这个拦截器给清除掉！

fix(core): 删除范围选择中的错误拦截器

---

s2-site/docs/manual/basic/tooltip.zh.md
s2-site/docs/manual/faq.zh.md
s2-site/examples/react-component/tooltip/demo/custom-click-show-tooltip.tsx
s2-site/examples/react-component/tooltip/demo/custom-hover-show-tooltip.tsx

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore

docs: 完善 tooltip 文档

---

packages/s2-core/__tests__/unit/sheet-type/table-sheet-spec.ts
packages/s2-core/src/facet/base-facet.ts
packages/s2-core/src/facet/pivot-facet.ts
packages/s2-core/src/facet/table-facet.ts
packages/s2-core/src/sheet-type/pivot-sheet.ts

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore
上层业务有使用 `getContentHeight()` 明细表没有适配这个 api, 导致获取到错误的高度了
| ![image](https://github.com/antvis/S2/assets/21015895/293adf0e-6bf6-445e-979e-9de18d083bc7) | ![image](https://github.com/antvis/S2/assets/21015895/088a8d55-38e9-4914-9aa2-566d7d478645) |
close #2289

fix(table): 修复明细表获取到错误的实际渲染内容高度

---

packages/s2-core/__tests__/unit/interaction/base-interaction/click/row-column-click-spec.ts
packages/s2-core/__tests__/unit/interaction/range-selection-spec.ts
packages/s2-core/src/interaction/range-selection.ts

🐛 Bugfix
为了处理列头反选后，hover 不生效的问题，#2263 里 range-selection 暴力去除了 hover 拦截。
导致列头在选中状态下，hover 拦截始终失效（range-selection 和 row-column-click 两个交互的冲突了）
如点击列头后，用户将鼠标移动到 data-cell 区，列头的 tooltip 会被销毁。
|    ![CleanShot 2023-07-18 at 18 11 17](https://github.com/antvis/S2/assets/6716092/80954735-dd39-48bd-a2a3-177a6a7577c3)    |   ![CleanShot 2023-07-18 at 18 10 32](https://github.com/antvis/S2/assets/6716092/49ce0e2c-7831-4417-b2a1-66a40e012a1b)     |

fix: 点击列头后hover拦截消失

---

packages/s2-react/src/components/sheets/base-sheet/index.tsx
packages/s2-react/src/components/sheets/editable-sheet/drag-copy/index.tsx
packages/s2-react/src/components/sheets/editable-sheet/edit-cell/index.tsx
packages/s2-react/src/components/sheets/editable-sheet/index.tsx

🎨 Enhance
Prevent unnecessary react re-render based on [react-re-render-guide](https://www.developerway.com/posts/react-re-renders-guide).

perf(react): 防止不必要的重新渲染

---

packages/s2-core/__tests__/spreadsheet/header-action-icons-spec.ts
packages/s2-core/src/cell/base-cell.ts
packages/s2-core/src/cell/data-cell.ts
packages/s2-core/src/cell/header-cell.ts
packages/s2-core/src/common/interface/basic.ts
packages/s2-core/src/common/interface/theme.ts
packages/s2-core/src/utils/cell/header-cell.ts
packages/s2-react/__tests__/unit/components/drill-down/__snapshots__/index-spec.tsx.snap
packages/s2-react/__tests__/unit/components/sheets/mobile-sheet/index-spec.tsx
packages/s2-react/__tests__/unit/components/sheets/mobile-sheet/mobile-tooltip-spec.tsx
packages/s2-react/__tests__/unit/components/tooltip/index-spec.tsx
packages/s2-react/playground/config.ts
packages/s2-react/playground/index.tsx
packages/s2-react/src/components/drill-down/index.tsx
packages/s2-react/src/components/sheets/base-sheet/index.tsx
packages/s2-react/src/components/sheets/chart-sheet/index.tsx
packages/s2-react/src/components/sheets/editable-sheet/drag-copy/drag-copy-mask.tsx
packages/s2-react/src/components/sheets/editable-sheet/drag-copy/index.tsx
packages/s2-react/src/components/sheets/editable-sheet/edit-cell/index.tsx
packages/s2-react/src/components/sheets/grid-analysis-sheet/index.tsx
packages/s2-react/src/components/sheets/index.tsx
packages/s2-react/src/components/sheets/mobile-sheet/index.tsx
packages/s2-react/src/components/sheets/pivot-sheet/index.tsx
packages/s2-react/src/components/sheets/strategy-sheet/index.tsx
packages/s2-react/src/components/sheets/table-sheet/index.tsx
packages/s2-react/src/context/SpreadSheetContext.tsx
packages/s2-shared/src/interface.ts
packages/s2-shared/src/styles/drill-down.less
packages/s2-shared/src/utils/drill-down.ts
s2-site/examples/custom/custom-icon/demo/custom-header-action-icon.tsx

✨ Feature
🐛 Bugfix
当同一个单元格配置了多个 icon 时, 为了区分是哪个 icon , 第二参数传入了 iconName, 那么在 icon 很多的场景
尤其是配置了 `defaultHide`, `displayConditions`, `onClick` 之类的动态展示场景,写法比较繁琐.
```ts
const headerActionIcons = {
icons: ['iconA', 'iconB', 'iconC'],
defaultHide: (meta, iconName) => {
if(iconName === 'iconA') {
}
if(iconName === 'iconB') {
}
if(iconName === 'iconC') {
}
},
displayConditions: (meta, iconName) => {
if(iconName === 'iconA') {
}
if(iconName === 'iconB') {
}
if(iconName === 'iconC') {
}
},
onClick: (meta, iconName) => {
if(iconName === 'iconA') {
}
if(iconName === 'iconB') {
}
if(iconName === 'iconC') {
}
}
}
```
现在修改为, 支持单个 icon 粒度的 hook
单个 icon 粒度的hook 优先级 > 所有 icon 的 hook, 这样可以满足对所有 icon 统一控制 和单独控制的场景诉求
```ts
const headerActionIcons = [
{
icons: [
{
name: 'iconA',
displayCondition: (meta) => {}, …
```

feat: headerActionIcons 支持细粒度配置 & 修复异步渲染导致无法获取实例的问题

---

packages/s2-core/__tests__/bugs/issue-2322-spec.ts
packages/s2-core/__tests__/data/data-issue-2322.json
packages/s2-core/src/facet/table-facet.ts

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore
原过滤逻辑在先后过滤A列和B列后，取消A列过滤时，会清空B列过滤，因为调用 `oldConfig.splice()` 方法时没有传入 deleteCount 参数，默认删除了从 `oldIndex` 开始的后续全部内容

fix(table-facet): 修复过滤多列时，删除一列过滤将同时清空后续过滤列

---

s2-site/docs/api/components/sheet-component.zh.md
s2-site/docs/api/general/S2Event.zh.md
s2-site/docs/api/general/S2Theme.zh.md
s2-site/docs/common/interaction.zh.md
s2-site/docs/manual/advanced/interaction/basic.zh.md
s2-site/docs/manual/basic/theme.zh.md
s2-site/docs/manual/faq.zh.md
s2-site/examples/interaction/basic/demo/hover.ts
s2-site/examples/interaction/basic/demo/meta.json
s2-site/examples/interaction/basic/demo/state-theme.ts

🔧 Chore
1. 补充如何配置交互相关的主题文档和示例, 这一块文档只有 API 定义, 而且还是错的, 减少同类问题的答疑
2. 去除列头刷选 `仅支持透视表` 的错误描述

docs: 完善交互主题配置

---

packages/s2-core/__tests__/unit/utils/text-spec.ts
packages/s2-core/src/utils/text.ts
packages/s2-react/src/components/sheets/strategy-sheet/custom-tooltip/custom-data-tooltip.tsx

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore
feat: 对比值无波动时也显示灰色
| ![image](https://github.com/antvis/S2/assets/9548248/748cb194-becf-4c30-bcb7-792f973b5908)     |   ![image](https://github.com/antvis/S2/assets/9548248/9184c69d-60a1-494b-b82f-1bb814ccbe59)   |

feat: 对比值无波动时也显示灰色

---

packages/s2-core/src/cell/header-cell.ts

🐛 Bugfix
fix: 修复树状模式下总计节点的指标节点没有被格式化数据
| ![Uploading image.png…]()      | ![image](https://github.com/antvis/S2/assets/56724970/969a7300-69d1-4737-a7a0-7b875324e7a5)     |

fix: 修复树状模式下总计节点的指标节点没有被格式化数据

---

packages/s2-core/__tests__/spreadsheet/hidden-columns-spec.ts
packages/s2-core/src/facet/layout/node.ts
packages/s2-core/src/facet/pivot-facet.ts
packages/s2-core/src/utils/layout/generate-header-nodes.ts

🐛 Bugfix
Solve the issue and close #2355 
解决隐藏结点时对父节点的布局错误
| ![image](https://github.com/antvis/S2/assets/56724970/2af12475-bcba-4624-b930-b8271e89bb84)      | ![image](https://github.com/antvis/S2/assets/56724970/7f91435d-d5c4-4045-83d5-c782b8c3f31a)    |

fix(layout): 修复隐藏结点时对父节点的布局计算错误 close #2355

---

packages/s2-core/__tests__/bugs/issue-2359-spec.ts
packages/s2-core/src/utils/text.ts

🐛 Bugfix
使用 `drawObjectText` 绘制多列文本时, 根据当前单元格类型的样式绘制, 而不是写死 `dataCell`
```ts
s2.setTheme({
colCell: {
measureText: {
fontSize: 12,
},
bolderText: {
fontSize: 14,
},
text: {
fontSize: 20,
fill: 'red',
},
},
dataCell: {
text: {
fontSize: 30,
fill: 'green',
},
},
});
```
> 如图, colCell 使用了 dataCell 的 theme
| ![image](https://github.com/antvis/S2/assets/21015895/87bebefa-6d87-49f6-a05c-101c24cdbe6c) | ![image](https://github.com/antvis/S2/assets/21015895/76696ac6-6c65-443e-ba59-a89da60171b0) |
close #2359

fix: 列头绘制多列文本时错误的使用了数值单元格的样式 close #2359

---

packages/s2-core/__tests__/bugs/issue-2385-spec.ts
packages/s2-core/__tests__/data/data-issue-2385.json
packages/s2-core/src/facet/pivot-facet.ts
packages/s2-react/__tests__/data/mock-dataset.json
packages/s2-react/playground/config.ts
packages/s2-react/playground/index.tsx
s2-site/docs/common/style.zh.md

🐛 Bugfix
🔧 Chore
紧凑模式下计算文本宽度时, 列头宽度用 (datalCell 采样前50条) 或 (colCell) 中最长的文本计算, 未考虑 dataCell 自定义 `fontSize` 的场景, 需要取两者 `fontSize` 最大的数值去测量文本宽度
```ts
const s2Options: S2Options = {
width: 800,
height: 600,
style: {
layoutWidthType: 'compact',
},
};
s2.setTheme({
dataCell: {
text: {
fontSize: 20,
},
},
})
```
| ![image](https://github.com/antvis/S2/assets/21015895/faae04c1-208f-4e12-b3e7-bd69285df834) | ![image](https://github.com/antvis/S2/assets/21015895/31a7deac-5792-4465-8e72-63303d451b93) |
close #2385

fix(layout): 修复在紧凑模式列头宽度未按文本自适应 close #2385

---

s2-site/docs/manual/advanced/custom/hook.zh.md
s2-site/docs/manual/basic/analysis/strategy.zh.md
s2-site/examples/case/art/demo/lost-text.tsx
s2-site/examples/case/art/demo/meta.json
s2-site/examples/custom/custom-cell/demo/corner-header.ts
s2-site/examples/custom/custom-cell/demo/custom-specified-cell.ts
s2-site/examples/custom/custom-cell/demo/custom-table-cell.ts
s2-site/examples/custom/custom-cell/demo/data-cell.ts
s2-site/examples/custom/custom-cell/demo/meta.json
s2-site/examples/custom/custom-cell/demo/mini-chart.ts
s2-site/examples/custom/custom-cell/demo/totals-cell.ts
s2-site/examples/custom/custom-layout/demo/custom-coordinate.ts
s2-site/examples/custom/custom-layout/demo/custom-data-position.ts
s2-site/examples/custom/custom-layout/demo/custom-layout-arrange.ts
s2-site/examples/custom/custom-layout/demo/custom-layout-hierarchy.ts
s2-site/examples/custom/custom-layout/demo/custom-value-order.ts
s2-site/examples/react-component/sheet/demo/strategy-mini-chart.tsx

🔧 Chore
1. 新增如何自定义明细表 列头/数值 单元格的 demo
2. 新增使用 mini 图的 demo
3. 新增之前写的一个表格交互小游戏的 demo
ref #2391

docs: 新增自定义明细表单元格 & 自定义 mini 图文档

---

packages/s2-react/__tests__/unit/components/sheets/strategy-sheet/index-spec.tsx
packages/s2-react/src/components/sheets/strategy-sheet/index.tsx

🐛 Bugfix
如果 rowCell 自定义了 tooltip, 点击 colCell 时会错误的使用 rowCell 的 tooltip, 默认值一直写错了, 最近业务侧恰好触发这个场景了

fix: 修复趋势分析表自定义列头 tooltip 后错误的使用行头的 tooltip

---

CONTRIBUTING.md
packages/s2-core/__tests__/spreadsheet/__snapshots__/theme-spec.ts.snap
packages/s2-core/src/cell/col-cell.ts
packages/s2-core/src/common/interface/theme.ts
packages/s2-core/src/facet/header/frame.ts
packages/s2-core/src/facet/table-facet.ts
packages/s2-core/src/group/grid-group.ts
packages/s2-core/src/theme/index.ts
packages/s2-core/src/utils/cell/cell.ts
s2-site/docs/api/general/S2Theme.en.md
s2-site/docs/api/general/S2Theme.zh.md

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore
支持透视表明细表单元格的虚线，以及分割线的虚线
[https://github.com/antvis/S2/issues/2400](#2400)

feat: 支持透视表明细表单元格虚线&分割线虚线(#2400)

---

packages/s2-core/src/common/interface/theme.ts
s2-site/docs/api/general/S2Theme.zh.md
s2-site/docs/api/graphic.zh.md
s2-site/examples/custom/custom-cell/demo/data-cell-placeholder.ts
s2-site/examples/custom/custom-cell/demo/meta.json

🔧 Chore
1. fontStyle 和 fontVariant 是透传给 g 的, 能力是支持的, 但是文档没写 
2. 增加 placeholder 单元格空数据占位符的 demo
ref https://github.com/antvis/S2/discussions/2384 https://github.com/antvis/S2/discussions/2406

docs: 补充缺失的 fontStyle 和 fontVariant 文档

---

packages/s2-core/__tests__/bugs/issue-2340-spec.ts
packages/s2-core/src/cell/data-cell.ts
packages/s2-core/src/cell/header-cell.ts
packages/s2-core/src/common/constant/interaction.ts
packages/s2-core/src/facet/header/col.ts
packages/s2-core/src/interaction/brush-selection/col-brush-selection.ts
packages/s2-core/src/interaction/brush-selection/data-cell-brush-selection.ts
packages/s2-core/src/interaction/brush-selection/row-brush-selection.ts
packages/s2-core/src/interaction/root.ts

🐛 Bugfix
问题: 行列头圈选后, 当前交互状态是 `selected`, 如果滑出可视范围 (单元格被销毁) 再滑动回来 (重新实例化), 会触发列头的多选, 导致数值也被选中
解法: 增加一个 `brushSelected` 状态, 以区分 `selected`
| ![Kapture 2023-11-13 at 17 29 58](https://github.com/antvis/S2/assets/21015895/480be45a-06bf-43c3-8f6c-7116a534c196) | ![Kapture 2023-11-13 at 17 31 25](https://github.com/antvis/S2/assets/21015895/c5ffa876-c262-4174-bac4-c8de81959378) |

fix(interaction): 修复行列头圈选后滑出可视范围后, 错误的选择了数值单元格 close #2340

---

packages/s2-core/__tests__/unit/utils/export/copy-spec.ts
packages/s2-core/src/utils/export/copy.ts
packages/s2-react/playground/config.ts
s2-site/docs/common/export.zh.md
s2-site/docs/manual/basic/analysis/copy-export.zh.md

🐛 Bugfix
1. 修复行列头单元格存在 `...` 省略号时, 未复制原始值的问题 (回滚 https://github.com/antvis/S2/pull/2254, 换一种方式实现)
2. 修复行列头的数值单元格复制时, 未格式化的问题 (数值置于行头/置于列头)
3. 修复开启 `copyWithHeader` 后, 复制的行列头数值未格式化的问题
| ![image](https://github.com/antvis/S2/assets/21015895/ec64ba50-c674-4e92-8926-1390c401cf91) | ![image](https://github.com/antvis/S2/assets/21015895/ee90161c-8d1e-48c3-9b71-9bee82e2439e) | | 
| ![image](https://github.com/antvis/S2/assets/21015895/f6bb4b49-550f-4958-b63a-8eddfbae36cb) | ![image](https://github.com/antvis/S2/assets/21015895/d36d20bf-2509-4152-867a-748900ff47de) |
ref https://github.com/antvis/S2/issues/2252
close #1657

fix(copy): 修复刷选复制行列头时, 数值单元格未格式化 & 存在省略号时未复制原始值

---

packages/s2-core/src/common/constant/basic.ts
packages/s2-core/src/facet/frozen-facet.ts
packages/s2-core/src/facet/header/col.ts
packages/s2-core/src/facet/header/table-col.ts
packages/s2-core/src/facet/table-facet.ts

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore
- 背景：交叉表支持冻结首行逻辑需求
- 解决：为了实现背景中提到的需求，将明细表冻结行列公共逻辑抽取成基类，交叉表复用。
- 说明：逻辑本身未修改，仅做抽取 确保能复用

refactor: 抽取明细表冻结行列逻辑，交叉表冻结首行逻辑复用

---

packages/s2-core/__tests__/spreadsheet/hidden-columns-spec.ts
packages/s2-core/src/facet/layout/layout-hooks.ts

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore
- 解决：目前仅支持隐藏列头部分，行总计和列总计ID 一致时也会被隐藏问题
- 其他说明：行头、列头实际场景不会出现同样的维度
| ![iShot_2023-11-16_14 40 39](https://github.com/antvis/S2/assets/8447716/866d3db3-017c-45d3-9080-9ccd986a7501)       |  ![iShot_2023-11-16_14 39 27](https://github.com/antvis/S2/assets/8447716/f406c441-d55a-4fc6-89e2-c71e3ccb5327)    |

fix: 修复隐藏列总计时行总计也被隐藏问题

---

package.json
packages/s2-react/__tests__/spreadsheet/spread-sheet-spec.tsx
packages/s2-react/playground/index.tsx
packages/s2-react/src/hooks/useSpreadSheet.ts

🐛 Bugfix
React 18 StrictMode 在非生产环境下会强制执行两次, 导致会挂载两个 canvas, 体验不是很好
| ![image](https://github.com/antvis/S2/assets/21015895/3fb4953d-0ff8-4e41-a532-415858d6419f) | ![image](https://github.com/antvis/S2/assets/21015895/88951183-b9df-4077-9a6a-846ae181f4c9) |
https://github.com/antvis/S2/pull/2373 遗留问题

fix: 修复 React 18 StrictMode 同时挂载两个表格的问题

---

packages/s2-core/__tests__/spreadsheet/empty-dataset-spec.ts
packages/s2-core/src/data-set/base-data-set.ts
packages/s2-core/src/facet/frozen-facet.ts

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore
ref: #2357 
明细表不需要默认的空结构，但是透视表的 Grid 模式 依旧需要，否则会出现单元格缺失
| ![image](https://github.com/antvis/S2/assets/17964556/fae6296a-011f-4ad0-9d2b-f84ffb2e4732) ![image](https://github.com/antvis/S2/assets/17964556/6978d864-d4f2-4c44-99f1-fe573ea3ced9)      | ![image](https://github.com/antvis/S2/assets/17964556/5f46ff81-fd9c-4847-ae14-71173c252f80)![image](https://github.com/antvis/S2/assets/17964556/11b8134b-0263-4e16-8574-4c4b9af99411)![image](https://github.com/antvis/S2/assets/17964556/caa044ac-d720-4ece-be36-74151a791a66)|

fix: 修复透视表数据为空时，行列交叉单元格缺失的问题

---

packages/s2-core/src/common/icons/gui-icon.ts

🐛 Bugfix
`GuiIcon load fielad` 报错的本质是要捕获图片加载错误的场景, 但会捕获到 G 绘制过程中无效的错误信息 (cell 已卸载, 此时 addShape 的容错场景), 之前 https://github.com/antvis/S2/pull/1997 已经处理过类似的问题
https://github.com/antvis/S2/blob/6490f32e426f72a808f710e4966c357d750758c9/packages/s2-core/src/common/icons/gui-icon.ts#L48-L52
1. 区分 TypeError 和加载 Error, 输出不同的提示
2. 增加容错, 如果 canvas 没有 refreshElements, 就不需要绘制图层
ref https://github.com/antvis/S2/pull/1997

fix: 区分 GuiIcon 报错类型 close #2345

---

packages/s2-core/src/facet/header/row.ts
packages/s2-core/src/facet/header/series-number.ts

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore

fix: seriesNumberHeader 不应该使用  custom row cell

---

packages/s2-core/__tests__/unit/interaction/base-interaction/hover-spec.ts
packages/s2-core/src/cell/base-cell.ts
packages/s2-core/src/interaction/base-interaction/hover.ts

🐛 Bugfix
增加获取不到 actualText 时的兼容
https://github.com/antvis/S2/pull/2457/files#diff-f1b493511b681a9bcd5be80e1866329688caaedd25541a4a4aaa01b57b0c713dL144
close https://github.com/antvis/S2/issues/2471

fix: 修复多列文本单元格 hover 时报错

---

.github/workflows/auto-release.yml
.releaserc.base.js
package.json
scripts/add-version.js
yarn.lock

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore
* 在 prepare 阶段，获取到生成的 nextVersion， 将它写入源码，然后重新 build 打包，就能将代码写入到产物中
* 然后需要将源码中新增的 nextVersion 修改revert 掉，保证其代码不会写入历史中
* release ci 中不再需要单独 build， build 被上面的 prepare build 替代
源码：
类型提示：

feat: 在自动发布前, 自动注入新版本到打包代码中

---

packages/s2-core/__tests__/spreadsheet/empty-string-values-spec.ts
packages/s2-core/src/utils/dataset/pivot-data-set.ts

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore
在做 `getDimensionValues` 查询时，意外的将空字符串作为了查全量的标志，导致查询结果有误，且命中了 flatten 逻辑，耗时较久
| ![image](https://github.com/antvis/S2/assets/17964556/11a1dacc-883a-40f9-8b16-a2e46320f91b) ![image](https://github.com/antvis/S2/assets/17964556/9059cf6d-04b1-4557-bf1d-06f2839d5a21)  | ![image](https://github.com/antvis/S2/assets/17964556/0b0740f7-1d8e-4722-94e7-680dfc87156f)![image](https://github.com/antvis/S2/assets/17964556/bb391903-d468-4364-ab68-c4674cedea0a)     |

fix: 修复行头字段为空字符串时, getDimensionValues 获取数据错误的问题

---

packages/s2-core/__tests__/unit/utils/dataset/pivot-data-set-spec.ts
packages/s2-core/src/data-set/interface.ts
packages/s2-core/src/utils/dataset/pivot-data-set.ts

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore
| ![image](https://github.com/antvis/S2/assets/17964556/6cfb82c5-470e-44e8-815e-8a515d77b516)    | ![image](https://github.com/antvis/S2/assets/17964556/85330dee-f76d-4431-a93a-a1e696a15d4d)     |

fix: 修复维度字段中包含 [&] 分隔符导致的获取数据不正确的问题

---

packages/s2-core/__tests__/spreadsheet/__snapshots__/spread-sheet-resize-spec.ts.snap
packages/s2-core/__tests__/spreadsheet/spread-sheet-resize-spec.ts
packages/s2-core/src/facet/pivot-facet.ts

🐛 Bugfix
自定义树状模式行头宽度时, 预期是数字, 如果传入一个字符串会导致布局错误, 增加一下容错
```ts
s2.setOptions({
hierarchyType: 'tree',
style: {
rowCfg: {
treeRowsWidth: '@',
},
},
});
```
| ![image](https://github.com/antvis/S2/assets/21015895/b7e8b3c6-1456-409a-8647-742d03bd868c)| ![image](https://github.com/antvis/S2/assets/21015895/8064ccf0-101a-4ee4-bd29-5f98ad14fb14) |

fix: 增加树状模式自定义宽度的容错

---

packages/s2-core/__tests__/bugs/issue-2501-spec.ts
packages/s2-core/src/facet/base-facet.ts
packages/s2-core/src/facet/frozen-facet.ts
packages/s2-core/src/facet/table-facet.ts

🐛 Bugfix
在 https://github.com/antvis/S2/pull/2416 支持冻结首行后, 抽象了 `FrozenFacet` 类, 导致继承链路改变, 执行时序有问题, 在用户配置了 `rowCfg.heightByField` 后布局错误
```ts
const s2Options: S2Options = {
style: {
rowCfg: {
heightByField: {
'0': 100,
'1': 150,
},
},
},
};
```
```diff
public init() {
-  super.init();
-  this.initRowOffsets();
+  this.initRowOffsets();
+  super.init();
}
```
| ![image](https://github.com/antvis/S2/assets/21015895/8f6ff341-d899-42d1-8865-eee34588fdb3) | ![image](https://github.com/antvis/S2/assets/21015895/73fd8e50-9b32-4e5c-ab16-afc30001c0c7) |

fix(table-sheet): 修复明细表配置自定义行高后展示异常 close #2501

---

packages/s2-core/__tests__/spreadsheet/__snapshots__/custom-dataset-spec.ts.snap
packages/s2-core/__tests__/spreadsheet/__snapshots__/custom-value-order-spec.ts.snap
packages/s2-core/__tests__/spreadsheet/custom-dataset-spec.ts
packages/s2-core/__tests__/spreadsheet/custom-value-order-spec.ts
packages/s2-core/__tests__/spreadsheet/hidden-columns-spec.ts
packages/s2-core/__tests__/unit/data-process/pivot-spec.tsx
packages/s2-core/__tests__/unit/utils/export/__snapshots__/copy-spec.ts.snap
packages/s2-core/__tests__/unit/utils/export/__snapshots__/export-spec.ts.snap
packages/s2-core/__tests__/unit/utils/export/copy-spec.ts
packages/s2-core/__tests__/unit/utils/export/export-pivot-spec.ts
packages/s2-core/__tests__/unit/utils/export/export-spec.ts
packages/s2-core/__tests__/util/fp.ts
packages/s2-core/src/utils/layout/generate-header-nodes.ts
s2-site/docs/manual/migration-v2.zh.md
s2-site/examples/interaction/advanced/demo/pivot-hide-columns.ts

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore
| ![image](https://github.com/antvis/S2/assets/17964556/9599ceb3-cba0-435c-a4c2-7184aae2ece4)      | ![image](https://github.com/antvis/S2/assets/17964556/c66af1ef-9d06-49e2-ab57-8a18e61f536a)     |

fix: 回退生成 nodeId 时对 extra 字段的格式化

---

packages/s2-core/src/facet/base-facet.ts

🐛 Bugfix
在移动端表格滚动至边缘时, `@antv/g-gesture@1.0.1` 有 bug, 向上滚动至边缘时, deltaY 有时会为负数, 导致向下滚动时然后回弹, 看起来就像表格在抖动, 需要判断滚动方向, 修正一下 deltaY
这个PR https://github.com/antvis/S2/pull/2302 只处理了报错, 没有修复抖动问题.
| ![Kapture 2024-02-22 at 14 31 59](https://github.com/antvis/S2/assets/21015895/21bcb854-32f8-44ac-8495-8aa0a0cc528a) | ![Kapture 2024-02-22 at 14 30 35](https://github.com/antvis/S2/assets/21015895/13ca8389-0dfd-419e-a2ba-4848ad13b32e) |
ref https://github.com/antvis/S2/issues/2266

fix(scroll): 修复移动端滚动至边缘时抖动

---

packages/s2-core/src/facet/header/table-col.ts

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore
| ![image](https://github.com/antvis/S2/assets/17964556/8204314c-652d-41bf-93a3-a0542862af02) ![2024-02-26 11 39 07](https://github.com/antvis/S2/assets/17964556/05a42dc0-d39d-4d7d-846b-41d55c984521)     | ![image](https://github.com/antvis/S2/assets/17964556/485621fa-13fe-44e4-86df-240f7c0a151d)![2024-02-26 11 40 08](https://github.com/antvis/S2/assets/17964556/a0c3d0c7-4f96-4855-9b18-f3f7bc67dac7)     |

perf: 优化明细表滚动性能 close #2548, #2402

---

packages/s2-core/__tests__/unit/interaction/brush-selection/base-brush-selection-spec.ts
packages/s2-core/__tests__/unit/interaction/brush-selection/col-brush-selection-spec.ts
packages/s2-core/__tests__/unit/interaction/brush-selection/data-brush-selection-spec.ts
packages/s2-core/__tests__/unit/interaction/brush-selection/row-brush-selection-spec.ts
packages/s2-core/__tests__/unit/interaction/event-controller-spec.ts
packages/s2-core/__tests__/util/helpers.ts
packages/s2-core/src/common/interface/basic.ts
packages/s2-core/src/common/interface/tooltip.ts
packages/s2-core/src/interaction/brush-selection/base-brush-selection.ts
packages/s2-core/src/interaction/brush-selection/col-brush-selection.ts
packages/s2-core/src/interaction/brush-selection/data-cell-brush-selection.ts
packages/s2-core/src/interaction/brush-selection/row-brush-selection.ts
packages/s2-core/src/interaction/event-controller.ts
packages/s2-core/src/sheet-type/spread-sheet.ts
packages/s2-react/playground/components/CustomTree.tsx
s2-site/docs/api/basic-class/interaction.zh.md
s2-site/docs/api/basic-class/spreadsheet.zh.md

🐛 Bugfix
1. 父容器存在 `transform: scale() ` 时, 刷选坐标拿的有问题, 应该使用 `offsetX/offsetY` 而不是 `clientX/clientY`, 参考 G 的 supportsCSSTransform 处理方式.
https://github.com/antvis/G/blob/a43c19a662684945d0bf9dc1876af43ac26b1243/packages/g-lite/src/plugins/EventPlugin.ts#L215-L229
2. 增加遗漏的 eventController 文档
| ![Kapture 2024-02-27 at 17 17 37](https://github.com/antvis/S2/assets/21015895/5c70847b-f709-4619-a57f-3591dc377e38) | ![Kapture 2024-02-27 at 17 13 40](https://github.com/antvis/S2/assets/21015895/22893d9c-bacc-42d5-9380-bf778575a994) |

fix: 修复父容器存在 transform 缩放时单元格刷选偏移 close #2553

---

packages/s2-core/__tests__/bugs/issue-1520-spec.ts
packages/s2-core/__tests__/bugs/issue-292-spec.ts
packages/s2-core/__tests__/bugs/issue-368-spec.ts
packages/s2-core/__tests__/bugs/issue-446-spec.ts
packages/s2-core/__tests__/bugs/issue-507-spec.ts
packages/s2-core/__tests__/bugs/issue-511-spec.ts
packages/s2-core/__tests__/bugs/issue-868-spec.ts
packages/s2-core/__tests__/unit/cell/data-cell-spec.ts
packages/s2-core/__tests__/unit/interaction/event-controller-spec.ts
packages/s2-core/__tests__/util/helpers.ts
packages/s2-core/src/common/constant/events/basic.ts
packages/s2-core/src/common/icons/gui-icon.ts
packages/s2-core/src/interaction/event-controller.ts

✨ Feature
🐛 Bugfix
默认单元格内的 icon 点击时会进行拦截, 不会触发单元格的点击事件, 避免触发选中, 但是 dataCell 没有做处理, 如果通过自定义 dataCell 的方式, 绘制自定义 icon, 这个时候应该拦截
相关 issue #2333 , 在 1.x 考虑到影响面未做修改, 2.0 中修改拦截的规则, 对所有单元格生效 (字段标记生成的 icon 除外)
| ![Kapture 2024-02-28 at 19 11 56](https://github.com/antvis/S2/assets/21015895/2c641100-70e0-46d4-8a15-ce8dd81bbe9b) | ![Kapture 2024-02-28 at 19 09 47](https://github.com/antvis/S2/assets/21015895/c3f26b83-8522-45a1-9b61-53065cfb3772) |

fix: 修复数值单元格内的自定义 icon 点击时会选中单元格的问题 close #2333

---

packages/s2-core/scripts/test-live.mjs
packages/s2-react/scripts/test-live.mjs

🔧 Chore
ref https://github.com/antvis/S2/pull/2593#issuecomment-1993884021

chore: 单测调试支持跨平台

---

packages/s2-core/__tests__/spreadsheet/__snapshots__/spread-sheet-collapse-spec.ts.snap
packages/s2-core/__tests__/spreadsheet/spread-sheet-collapse-spec.ts
packages/s2-core/src/cell/corner-cell.ts
packages/s2-core/src/facet/layout/build-row-custom-tree-hierarchy.ts
packages/s2-core/src/sheet-type/pivot-sheet.ts
packages/s2-react/playground/components/CustomTree.tsx
packages/s2-react/playground/config.tsx
s2-site/docs/manual/migration-v2.zh.md

🐛 Bugfix
🔧 Chore
1. 修复行头和角头的折叠/展开 icon 状态未同步的问题
```ts
style: {
rowCell: {
// 这种情况下等价于 collapseAll: true 但是角头 icon 状态不对
collapseFields: {
'root[&]浙江省': true,
'root[&]四川省': true,
},
},
}
```
2. 修复全部折叠的情况下, 行头节点展开异常 close #2607 
| ![image](https://github.com/antvis/S2/assets/21015895/9a899d88-496a-46c9-b767-6d4a324d28a9)  |  ![image](https://github.com/antvis/S2/assets/21015895/0666ac43-ff27-4830-bf66-f2bddc418c5d) |
| ![image](https://github.com/antvis/S2/assets/21015895/ab6a685c-2e72-4726-af7e-0a8a8718691b) | ![image](https://github.com/antvis/S2/assets/21015895/91542844-a037-4d96-bf54-f5afee8d6ab0) |

fix: 修复角头和行头折叠展开 icon 的状态未同步以及展开异常的问题 close #2607

---

packages/s2-core/__tests__/spreadsheet/__snapshots__/multi-line-text-spec.ts.snap
packages/s2-core/__tests__/spreadsheet/multi-line-text-spec.ts
packages/s2-core/__tests__/unit/facet/table-facet-spec.ts
packages/s2-core/src/common/constant/options.ts
packages/s2-core/src/facet/base-facet.ts
packages/s2-core/src/facet/pivot-facet.ts
packages/s2-core/src/facet/table-facet.ts
s2-site/docs/manual/advanced/custom/cell-size.zh.md
s2-site/docs/manual/basic/multi-line-text.zh.md
s2-site/examples/layout/custom/demo/custom-table-size.ts

🐛 Bugfix
🔧 Chore
```ts
s2.setOptions({
style: {
colCell: {
height: 70,
},
rowCell: {
heightByField: {
0: 70,
1: 100,
2: 150,
},
},
},
});
```
1. 修复开启换行时, 且不存在换行文本时自定义单元格高度失效的问题, 现在自定义单元格宽高的优先级最高.
2. 完善相关单测和文档
| ![image](https://github.com/antvis/S2/assets/21015895/e5384668-6b9a-4ef8-8b8d-fe4936d4c89f) | ![image](https://github.com/antvis/S2/assets/21015895/e5066769-b29a-426c-b615-8a1f6c1222e4) |

fix: 调整换行高度自适应和自定义高度的优先级 close #2613

---

packages/s2-vue/src/components/pagination/index.vue
packages/s2-vue/src/components/sheets/base-sheet.vue
packages/s2-vue/src/hooks/usePagination.ts

🐛 Bugfix
```tsx
const s2Options = reactive({
pagination: {
current: 1,
pageSize: 6,
size: 'default',
showQuickJumper: true,
}
})
```
| ![image](https://github.com/antvis/S2/assets/21015895/04ab10e4-9d0a-412c-85a0-c8da527bd15f) | ![image](https://github.com/antvis/S2/assets/21015895/a9db55cf-62d7-4daf-8de5-6459dda1873e) |
close #2648

fix: 修复分页配置无法透传

---

packages/s2-core/__tests__/unit/utils/export/__snapshots__/export-pivot-spec.ts.snap
packages/s2-core/__tests__/unit/utils/export/__snapshots__/export-spec.ts.snap
packages/s2-core/__tests__/unit/utils/export/__snapshots__/export-table-spec.ts.snap
packages/s2-core/__tests__/unit/utils/export/export-pivot-spec.ts
packages/s2-core/__tests__/unit/utils/export/export-table-spec.ts
packages/s2-core/src/utils/export/copy/table-copy.ts
packages/s2-react/playground/components/CustomGrid.tsx

🐛 Bugfix
🔧 Chore
1. 修复明细表默认列头复制导出时未格式化的问题
2. 修复明细表自定义列头复制导出格式错误的问题
| ![image](https://github.com/antvis/S2/assets/21015895/bc734862-e92e-43dc-9e70-e559a3d5121b) | ![image](https://github.com/antvis/S2/assets/21015895/ad365a59-b898-40be-919d-9973a7c14e3e) |
close #2664

fix: 修复明细表自定义多级列头导出格式错误 close #2664

---

packages/s2-core/__tests__/spreadsheet/scroll-spec.ts
packages/s2-core/src/facet/base-facet.ts

🐛 Bugfix
facet 渲染时跳过 scroll event 的分发, 避免无效事件触发
https://github.com/antvis/S2/blob/ea6201847b23e738bafbaaab212f274520ab75f6/packages/s2-core/src/facet/base-facet.ts#L1391-L1393

fix: 修复非滚动引起的渲染也会触发滚动事件的问题

---

packages/s2-core/__tests__/bugs/issue-446-spec.ts
packages/s2-core/__tests__/bugs/issue-565-spec.ts
packages/s2-core/__tests__/unit/data-set/pivot-data-set-spec.ts
packages/s2-core/__tests__/unit/utils/export/__snapshots__/export-pivot-spec.ts.snap
packages/s2-core/__tests__/unit/utils/export/__snapshots__/export-table-spec.ts.snap
packages/s2-core/__tests__/unit/utils/export/copy-spec.ts
packages/s2-core/__tests__/unit/utils/export/export-pivot-spec.ts
packages/s2-core/__tests__/unit/utils/export/export-table-spec.ts
packages/s2-core/__tests__/unit/utils/export/utils-spec.ts
packages/s2-core/__tests__/util/helpers.ts
packages/s2-core/src/common/constant/copy.ts
packages/s2-core/src/common/interface/export.ts
packages/s2-core/src/data-set/base-data-set.ts
packages/s2-core/src/utils/export/copy/base-data-cell-copy.ts
packages/s2-core/src/utils/export/copy/common.ts
packages/s2-core/src/utils/export/copy/pivot-data-cell-copy.ts
packages/s2-core/src/utils/export/copy/table-copy.ts
packages/s2-core/src/utils/export/utils.ts
packages/s2-react/__tests__/unit/components/sheets/strategy-sheet/__snapshots__/index-spec.tsx.snap
packages/s2-react/__tests__/unit/components/sheets/strategy-sheet/index-spec.tsx
packages/s2-react/playground/config.tsx
packages/s2-react/src/components/export/index.tsx
packages/s2-react/src/components/export/strategy-copy.ts
s2-site/docs/api/components/export.en.md
s2-site/docs/api/components/export.zh.md
s2-site/docs/common/copy-export.en.md
s2-site/docs/common/copy-export.zh.md
s2-site/docs/manual/migration-v2.zh.md

🐛 Bugfix
1. BREAKING CHANGE: Export 组件 和 asyncGetAllPlainData, copyToClipboard 的是否异步导出参数统一为 async
2. 修复普通表格导出 CSV 分隔符错误.
3. 修复趋势分析表未接受自定义分隔符导致的导出错误.
| ![image](https://github.com/antvis/S2/assets/21015895/3a4d8bf0-cb7f-489c-bd58-425e8cbbeabe) | ![image](https://github.com/antvis/S2/assets/21015895/46f9661e-cfca-4a4f-abbd-9fe0201b0a3a) |
| ![image](https://github.com/antvis/S2/assets/21015895/2586b43b-f663-4408-8485-723ea55cbe61) | ![image](https://github.com/antvis/S2/assets/21015895/97e967d4-ce48-4ae9-919e-5245545c149d) |
close #2701

fix: 修复导出 CSV 时分隔符错误导致的展示格式错误 close #2701

---

packages/s2-core/src/facet/base-facet.ts

🐛 Bugfix
滚动表格的时候，表格和父容器的滚动条会同时滚动：
`passive` 设置为 `true` 使浏览器忽略了 `preventDefault`，滚动事件会冒泡到父元素，导致父元素开始滚动。
| ![file](https://github.com/antvis/S2/assets/11677125/71ec858f-1996-451c-a5aa-daa446cd37f9)  |  ![3](https://github.com/antvis/S2/assets/11677125/4f143b19-1f8a-4383-8e58-e6453a4a0a47) |
close #2720

fix: 修复滚动边界问题 close #2720

---

packages/s2-core/src/facet/base-facet.ts
packages/s2-core/src/facet/pivot-facet.ts

🎨 Enhance
1. 未开启换行, 或开启换行且文本只有一行时, 不测量文本高度, 提升布局性能 (对齐 1.x)
2. 多行文本的场景后续优化, 还没想到好的方案
| ![Kapture 2024-05-15 at 16 56 52](https://github.com/antvis/S2/assets/21015895/55d4e71c-e559-4cdd-aaa4-e3aa145fc60e) | ![Kapture 2024-05-15 at 16 52 31](https://github.com/antvis/S2/assets/21015895/667ba27f-3fed-4fa5-8f59-df277561bd10) |
closes #2693 #2710

perf: 优化未开启多行文本时的布局性能 close #2693

---

packages/s2-core/__tests__/unit/sheet-type/pivot-sheet-spec.ts
packages/s2-core/src/sheet-type/spread-sheet.ts
packages/s2-core/src/utils/tooltip.ts

🐛 Bugfix
```ts
tooltip: {
dataCell: {
content(cell, defaultTooltipShowOptions) {
console.log(cell, defaultTooltipShowOptions);
return null;
},
},
}
}
```
| ![image](https://github.com/antvis/S2/assets/21015895/cce897dc-47b1-4a1d-a615-98da4f088e9b) | ![image](https://github.com/antvis/S2/assets/21015895/2605747f-28af-4271-8427-0f26854f691e) |

fix: 修复自定义 tooltip 时, 刷选时无法获取到单元格信息

---

packages/s2-core/__tests__/benchmark/pivot-sheet-spec.ts
packages/s2-core/__tests__/benchmark/table-sheet-spec.ts
packages/s2-core/__tests__/spreadsheet/__snapshots__/multi-line-text-spec.ts.snap
packages/s2-core/__tests__/spreadsheet/multi-line-text-spec.ts
packages/s2-core/package.json
packages/s2-core/scripts/test-live.mjs
packages/s2-core/src/cell/base-cell.ts
packages/s2-core/src/cell/col-cell.ts
packages/s2-core/src/cell/corner-cell.ts
packages/s2-core/src/cell/data-cell.ts
packages/s2-core/src/cell/header-cell.ts
packages/s2-core/src/cell/row-cell.ts
packages/s2-core/src/cell/series-number-cell.ts
packages/s2-core/src/common/interface/basic.ts
packages/s2-core/src/common/interface/s2Options.ts
packages/s2-core/src/facet/base-facet.ts
packages/s2-core/src/facet/frozen-facet.ts
packages/s2-core/src/facet/header/table-col.ts
packages/s2-core/src/facet/layout/node.ts
packages/s2-core/src/facet/pivot-facet.ts
packages/s2-core/src/facet/table-facet.ts
packages/s2-core/src/interaction/brush-selection/data-cell-brush-selection.ts
packages/s2-core/src/utils/interaction/merge-cell.ts
packages/s2-react/package.json
packages/s2-react/scripts/test-live.mjs
packages/s2-shared/package.json
packages/s2-vue/package.json
pnpm-lock.yaml

🎨 Enhance
在 https://github.com/antvis/S2/pull/2728 中优化了没有开启多行文本时的性能, 这个 PR 优化开启多行文本时的布局性能  (完成 https://github.com/antvis/S2/pull/2728#issuecomment-2117158843 中的 TODO)
1. 使用同一个 class 的示例, 动态更新 meta 的方式, 避免频繁创建实例 GC 的性能问题.
2. 对文本长度相同, 并且单元格宽度一致的情况, 增加缓存, 大幅降低多行文本高度测量的性能损耗.
3. 减少明细表频繁 `setOptions` 触发 merge 的性能损耗.
4. 明细表适配 `shallowRender` 逻辑, 减少 `initCell` 的性能损耗.
测试数据样本 (2w 条明细数据):
| 透视表 (9.8s -> 1.8s) ![image](https://github.com/antvis/S2/assets/21015895/2087bfdc-f54b-4477-b8ac-e215c09199f8) | ![image](https://github.com/antvis/S2/assets/21015895/0e598125-886d-41ef-af6a-c6271a6ae5d0) |
| 明细表 (16s -> 0.35s (有缓存) -> 5.7s (无缓存)) ![image](https://github.com/antvis/S2/assets/21015895/a24081bd-200f-42a2-8f57-a9ae569c7a1b) | …

perf: 优化开启多行文本时的布局性能

---

s2-site/docs/manual/migration-v2.zh.md
s2-site/examples/custom/custom-order/demo/custom-order.tsx

🔧 Chore
1. 增加文档, 避免小白用户不知道怎么办
2. close https://github.com/antvis/S2/discussions/2759

docs: 2.0 升级指南增加 antd 多版本共存的教程

---

packages/s2-core/__tests__/unit/facet/pivot-facet-spec.ts
packages/s2-react/__tests__/unit/components/sheets/strategy-sheet/index-spec.tsx
packages/s2-react/src/components/sheets/chart-sheet/index.tsx
packages/s2-react/src/components/sheets/grid-analysis-sheet/index.tsx
packages/s2-react/src/components/sheets/strategy-sheet/index.tsx
s2-site/docs/api/general/S2Options.zh.md
s2-site/docs/common/custom/dataCellCallback.zh.md
s2-site/docs/manual/advanced/chart-in-cell.zh.md
s2-site/docs/manual/migration-v2.zh.md
s2-site/examples/case/art/demo/time-spend-abstract.tsx
s2-site/examples/case/comparison/demo/measure-comparison.tsx
s2-site/examples/case/comparison/demo/time-spend.tsx
s2-site/examples/case/kpi-strategy/demo/basic.tsx
s2-site/examples/custom/custom-cell/demo/custom-specified-cell.ts
s2-site/examples/custom/custom-cell/demo/custom-table-cell.ts
s2-site/examples/custom/custom-cell/demo/data-cell.ts
s2-site/examples/custom/custom-cell/demo/mini-chart.ts
s2-site/examples/custom/custom-dataset/demo/custom-strategy-sheet-dataset.ts
s2-site/examples/custom/custom-shape-and-chart/demo/custom-g-shape.ts
s2-site/examples/custom/custom-shape-and-chart/demo/custom-g2-chart.ts

🐛 Bugfix
🔧 Chore
```diff
width: 600,
-  dataCell: (viewMeta) => {
-    return new CustomDataCell(viewMeta, viewMeta.spreadsheet);
-  }
+  dataCell: (viewMeta, spreadsheet) => {
+    return new CustomDataCell(viewMeta, spreadsheet);
+  }
}
```
https://github.com/antvis/S2/discussions/2747

fix: 修复自定义 dataCell 错误的传参写法

---

packages/s2-core/src/cell/header-cell.ts
packages/s2-core/src/common/interface/basic.ts
packages/s2-core/src/common/interface/events.ts
packages/s2-core/src/common/interface/export.ts
packages/s2-core/src/common/interface/interaction.ts
packages/s2-core/src/common/interface/resize.ts
packages/s2-core/src/common/interface/s2DataConfig.ts
packages/s2-core/src/common/interface/style.ts
packages/s2-core/src/common/interface/theme.ts
packages/s2-core/src/interaction/event-controller.ts
packages/s2-core/src/sheet-type/spread-sheet.ts
packages/s2-react/playground/config.tsx
s2-site/docs/api/general/S2Theme.zh.md
s2-site/docs/manual/basic/theme.zh.md

🎨 Enhance
```diff
export enum LayoutWidthType {
Adaptive = 'adaptive',
ColAdaptive = 'colAdaptive',
Compact = 'compact',
}
export interface A {
-  layoutWidthType?: LayoutWidthType
+  layoutWidthType?: `${LayoutWidthType}`
}
```
将枚举定义改成模版字符串的方式, 可以直接获得编辑器提示, 无需引入额外的枚举定义. 
**注意: 原来枚举的写法不受影响,这样是可以兼容之前的枚举写法的, 相当于多了种选择.**
> 直接写字符串也可以
> 直接写枚举也可以

feat(type): 使用 Template Literal Types 增强枚举类型的提示

---

packages/s2-core/src/sheet-type/spread-sheet.ts
packages/s2-react/__tests__/unit/components/sheets/__snapshots__/index-spec.tsx.snap
packages/s2-react/playground/index.tsx

🐛 Bugfix
| ![image](https://github.com/antvis/S2/assets/21015895/516fe367-9ccb-49c4-a3ac-0a247aa8660f) | ![image](https://github.com/antvis/S2/assets/21015895/1fbecc91-b66a-4c65-94cd-de4527ed1c50) |

fix: 取消双击表格时浏览器默认的选中文本行为 close #2798

---

packages/s2-core/src/interaction/base-interaction/click/data-cell-click.ts
packages/s2-react/__tests__/unit/utils/react-render-16-spec.tsx
packages/s2-react/__tests__/unit/utils/react-render-18-spec.tsx
packages/s2-react/playground/index.tsx
packages/s2-react/src/components/sheets/editable-sheet/custom-cell/edit-cell/index.tsx
packages/s2-react/src/components/tooltip/custom-tooltip.tsx
packages/s2-react/src/utils/invokeComponent.tsx
packages/s2-react/src/utils/reactRender.ts
s2-site/docs/manual/migration-v2.zh.md

✨ Feature
原本 Tooltip 做了 React 16/18 的兼容, 但在实际运行时 `react-dom/client` 的方式打包工具会报错
本质上 `react-dom/client` 是 `react-dom` 的一个 sub module
https://github.com/facebook/react/blob/main/packages/react-dom/package.json#L51-L59
所以参考 antd 的处理方式, 使用 `import *` 的方式全部引入, 然后做一个克隆, 跟进版本动态判断是否使用 `createRoot`
https://github.com/react-component/util/blob/677d3ac177d147572b65af63e67a7796a5104f4c/src/React/render.ts#L6-L13
```ts
import * as ReactDOM from 'react-dom';
import type { Root } from 'react-dom/client';
const ReactDOMClone = {
...ReactDOM,
} as typeof ReactDOM & {
__SECRET_INTERNALS_DO_NOT_USE_OR_YOU_WILL_BE_FIRED?: {
usingClientEntryPoint?: boolean;
};
createRoot?: CreateRoot;
};
```
其他:
React 19 已发布 [RC 版本](https://react.dev/blog/2024/04/25/react-19), 社区负面反馈较多, 后续兼容视React 19 稳定情况而定。 …

feat: 支持同时在 React 16/17/18 下运行

---

packages/s2-core/__tests__/bugs/issue-2804-spec.ts
packages/s2-core/__tests__/data/data-issue-2804.json
packages/s2-core/src/facet/layout/build-row-tree-hierarchy.ts

🐛 Bugfix
树状模式由于一级节点即是普通节点, 又是小计节点, 在当前分组下只有一条数据时, `isLeaf` 判断错误, 错误的展示了折叠展开 icon.
```ts
{
"fields": {
"rows": ["row0", "row1"],
"columns": ["col0"],
"values": ["cost"],
"valueInCols": true
},
"data": [
{
"row0": "a-1",
"col0": "b-1",
"cost": 2
},
{
"row0": "a-2",
"row1": "a-2-1",
"col0": "b-2",
"cost": 3
}
]
}
```
| ![image](https://github.com/antvis/S2/assets/21015895/faa5be08-b134-48e4-8587-a5b7d6d43839) | ![image](https://github.com/antvis/S2/assets/21015895/dd79fe17-a8e3-41eb-80b4-595eef9a281e) |

fix: 修复树状模式当一组数据只有一条数据时, 叶子节点判断错误, 也渲染了展开/收起图标 close #2804

---

s2-site/playground/config-panel/config-component/dragger-upload/index.tsx

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore
This commit addresses the issue where page navigation incorrectly overwrote the content of previously opened tabs. By changing the target attribute of the a-tag from _black to _blank, new pages will now open in a new tab, preventing the overwriting of existing tabs.

fix(typo): Change target attribute from _black to _blank

---

packages/s2-core/src/utils/g-mini-charts.ts

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore
这次改动主要是处理用使用 mini画柱状图时，在数据全为正值和全为零值时，柱状图展示异常问题。在单元格内绘制 mini 柱状图时，计算每个坐标转换的函数有点问题，如下图所示。
上图框起来的部分需要分情况分别考虑 barHeight 和 positionY：1. 数据全为正、2. 数据全为零、3. 数据全为负，修改如下图所示。
改版前后的对比图如下所示。覆盖了以下常见都没有问题了。
1. 数据全为正
2. 数据全为负
3. 数据全为零
4. 数据有正有负
5. 数据有正有负有零

fix: 处理自定义mini图显示柱状图时，全为正值&全为零值 展示异常问题

---

packages/s2-core/__tests__/unit/utils/tooltip-spec.ts
packages/s2-core/src/utils/tooltip.ts
s2-site/docs/manual/advanced/chart-in-cell.zh.md

🐛 Bugfix
明细表普通单元格点击 tooltip 展示的是自身的数值, 对于自身是图表的场景不应该渲染 tooltip, 这里是错误的把图表数据渲染在 Tooltip 的 JSX 中, 所以报错了

fix: 修复在明细表中绘制 G2 图表, 点击单元格报错 close #2843

---

packages/s2-core/__tests__/data/custom-grid-fields.ts
packages/s2-core/__tests__/unit/utils/export/__snapshots__/export-pivot-spec.ts.snap
packages/s2-core/__tests__/unit/utils/export/export-pivot-spec.ts
packages/s2-core/src/utils/export/copy/pivot-data-cell-copy.ts

🐛 Bugfix
| ![image](https://github.com/user-attachments/assets/a935713c-640f-4f25-ba05-4c141d6a3ffa) | ![image](https://github.com/user-attachments/assets/3649f06d-037e-4b6e-b3f7-5874bf38e4ac) |

fix: 修复自定义列头导出数据时, 角头文本展示错误 close #2844

---

packages/s2-core/__tests__/spreadsheet/__snapshots__/spread-sheet-collapse-spec.ts.snap
packages/s2-core/__tests__/spreadsheet/spread-sheet-collapse-spec.ts
packages/s2-core/src/common/interface/s2DataConfig.ts
packages/s2-core/src/common/interface/style.ts
packages/s2-core/src/facet/layout/build-row-custom-tree-hierarchy.ts
packages/s2-core/src/facet/layout/build-row-tree-hierarchy.ts
packages/s2-react/playground/components/CustomTree.tsx
s2-site/docs/manual/advanced/custom/custom-collapse-nodes.zh.md

🐛 Bugfix
自定义行头节点的树状模式场景未适配, 导致和普通树状模式表现不一致
```ts
style: {
rowCell: {
expandDepth: 0,
},
}
```
| ![image](https://github.com/user-attachments/assets/73b53d82-ddd7-4994-8c86-081fde7b7ab5) | ![image](https://github.com/user-attachments/assets/5232a5c1-3f87-463e-82ae-0cc99be525ab) |

fix: 修复 expandDepth 在自定义行头场景下不生效

---

packages/s2-core/__tests__/spreadsheet/spread-sheet-spec.ts
packages/s2-core/src/sheet-type/spread-sheet.ts

🐛 Bugfix
G 的 supportsPointerEvents 默认开启, 会给 canvas 设置 `touchAction: none`, 会导致移动端无法滚动
https://github.com/antvis/G/blob/910c58e9bcba48cfa7bb0585064d27d3ae0bff4c/packages/g-plugin-dom-interaction/src/DOMInteractionPlugin.ts#L134-L136

fix: 移动端关闭 supportsPointerEvents, 避免禁用 touchAction close #2857

---

packages/s2-core/__tests__/spreadsheet/__snapshots__/theme-spec.ts.snap
packages/s2-core/src/facet/header/frame.ts
packages/s2-core/src/theme/index.ts
packages/s2-react-components/__tests__/unit/components/config/theme-panel/__snapshots__/utils-spec.ts.snap
packages/s2-react/playground/config.tsx
s2-site/docs/api/general/S2Theme.zh.md
s2-site/docs/common/totals.zh.md
s2-site/docs/manual/basic/totals.zh.md
s2-site/docs/manual/migration-v2.zh.md

🎨 Enhance
🐛 Bugfix
| ![image](https://github.com/user-attachments/assets/c85e8014-bef1-4a6b-a1ae-df60c06f1e69) | ![image](https://github.com/user-attachments/assets/d9cb33c6-dd50-4018-aee3-eb0dbf7fc470) |

fix: 调整分割线的颜色绘制逻辑, 优化和单元格边框颜色不一致的问题

---

packages/s2-react/__tests__/unit/components/drill-down/__snapshots__/index-spec.tsx.snap
packages/s2-react/playground/drill-down.tsx
packages/s2-react/src/components/drill-down/index.tsx
packages/s2-shared/__tests__/unit/utils/__snapshots__/drill-down-spec.ts.snap
packages/s2-shared/src/styles/drill-down.less
packages/s2-shared/src/utils/drill-down.ts

🐛 Bugfix
| ![image](https://github.com/user-attachments/assets/57fcc8e5-adaf-470a-b686-78c1dfdfa436) | ![image](https://github.com/user-attachments/assets/d1595c15-6075-487a-bb61-facceffd003a) |

fix: 修复下钻 icon 不应该默认全部展示和标题样式问题

---

packages/s2-core/package.json
packages/s2-core/src/facet/base-facet.ts
packages/s2-core/src/interaction/base-interaction/click/data-cell-click.ts
packages/s2-core/src/interaction/brush-selection/base-brush-selection.ts
packages/s2-core/src/interaction/event-controller.ts
packages/s2-react/package.json
packages/s2-react/playground/config.tsx
pnpm-lock.yaml

fix: 增加单元格单双击的判断范围

---

packages/s2-react/__tests__/unit/components/tooltip/__snapshots__/index-spec.tsx.snap
packages/s2-react/__tests__/unit/components/tooltip/index-spec.tsx
packages/s2-react/src/components/tooltip/components/operator.tsx
packages/s2-shared/src/styles/tooltip/operator.less
packages/s2-shared/src/styles/variables.less

🐛 Bugfix
| ![image](https://github.com/user-attachments/assets/23b08ec7-1ea7-4eaa-bb7d-841651555801) | ![image](https://github.com/user-attachments/assets/a26cb6ed-7406-4442-b99e-284c0e7793dc) |
|  ![image](https://github.com/user-attachments/assets/18ce3431-6dcb-4075-9c04-b3cd7ca2e10a) |  ![image](https://github.com/user-attachments/assets/8157db9d-b282-4ca8-b9fa-2dd2e14d8740) |

fix: 修复排序菜单没有子节点时图标展示错误 & 调整默认样式

---

packages/s2-core/__tests__/unit/utils/export/__snapshots__/export-pivot-spec.ts.snap
packages/s2-core/__tests__/unit/utils/export/export-pivot-spec.ts
packages/s2-core/src/utils/export/copy/pivot-data-cell-copy.ts

🐛 Bugfix
| ![image](https://github.com/user-attachments/assets/9f39b19e-13e1-4307-86c4-0938d094d788) | ![image](https://github.com/user-attachments/assets/700f5a76-e6aa-4737-9d1d-20b34094a117) |

fix: 修复自定义计算总计时, 复制的数据不正确 close #2928

---

packages/s2-core/src/facet/pivot-facet.ts
packages/s2-core/src/facet/table-facet.ts
packages/s2-react/src/components/tooltip/components/operator.tsx

🐛 Bugfix
在 https://github.com/antvis/S2/pull/2932 修复箭头的展示后, 由于层级发生变动, 原 sub-menu 变为 menu, 会导致自定义 menu 的 hook 未触发.
| ![Kapture 2024-10-28 at 17 03 35](https://github.com/user-attachments/assets/cba308f3-5cda-4774-854a-057b256af2c2) | ![Kapture 2024-10-28 at 17 01 41](https://github.com/user-attachments/assets/e5d165f1-dfbe-41ff-bd11-00d99f3d6b6e) |

fix: 修复自定义菜单项不触发 click 事件的问题

---

packages/s2-core/src/sheet-type/spread-sheet.ts
packages/s2-core/src/ui/hd-adapter/index.ts

✨ Feature
🎨 Enhance
🐛 Bugfix
🔧 Chore
1. 项目中使用了浏览器全屏演示表格组件，并配置了缩放比例，启用了高清适配属性
2. 在退出全屏时主动销毁了表格组件，但因为退出全屏的同时触发了 `resize` 事件，而经过查看源码发现 `resize` 事件的处理器是异步执行并且使用了防抖函数，导致该事件的执行时机滞后于 `spreadsheet` 的销毁时机，进而导致后续过程的报错，浏览器控制台报错信息如下：
3. 在 hdAdapter 销毁后添加 destroyed 标识，并在 resize 事件处理器执行前检查是否已销毁，避免后续过程报错

fix: 修复表格卸载后, 高清适配逻辑还会触发的问题

---

packages/s2-core/__tests__/data/custom-table-col-fields.ts
packages/s2-core/__tests__/spreadsheet/__snapshots__/multi-line-text-spec.ts.snap
packages/s2-core/__tests__/spreadsheet/multi-line-text-spec.ts
packages/s2-core/src/facet/pivot-facet.ts
packages/s2-core/src/facet/table-facet.ts

🐛 Bugfix
在 https://github.com/antvis/S2/pull/2705 中修复明细表单列头, 单测未覆盖自定义列头的场景, 先计算宽度, 再计算高度, 确保计算多行文本时能获取到正确的最大文本宽度
```tsx
style: {
colCell: {
maxLines: 10,
},
}
}
```
| ![image](https://github.com/user-attachments/assets/6643b787-3afb-4a68-855e-52e39ab31820) | ![image](https://github.com/user-attachments/assets/baa7cce9-6eab-4f43-b79f-15da3a0459ba) |

fix: 修复明细表自定义列头时开启文本换行, 单元格高度错误的问题 close #2955

---

packages/s2-core/__tests__/unit/sheet-type/pivot-sheet-spec.ts
packages/s2-core/src/common/interface/s2Options.ts
packages/s2-core/src/sheet-type/spread-sheet.ts
packages/s2-core/src/utils/hide-columns.ts
packages/s2-react/__tests__/unit/hooks/useSpreadSheet-spec.ts
packages/s2-react/src/hooks/useSpreadSheet.ts
s2-site/docs/api/basic-class/spreadsheet.zh.md
s2-site/docs/api/components/sheet-component.zh.md
s2-site/docs/manual/migration-v2.zh.md

🐛 Bugfix
背景见 #2839 
```ts
onDataCellClick={(cell) => {
ReactDOM.unstable_batchedUpdates(() => {
setCheckedRowIndex(rowIndex);
setCheckedColIndex(colIndex);
});
}}
```

fix: 减少开启 ReactDOM.unstable_batchedUpdates 后的重渲染次数
